Repository knative/test-infra, pull requests merged in 2018-10, with the labels that each got.

#158 More fixes to test-infra
  dummy.go
  scripts/e2e-tests.sh
Labels: approved, lgtm, size/S

#163 Update prow-tests image
  images/prow-tests/Dockerfile
Labels: approved, lgtm, size/XS

#160 Explain how to build new prow-tests images
  images/prow-tests/README.md
Labels: approved, lgtm, size/S

#164 Display version of tools on presubmit
  scripts/presubmit-tests.sh
Labels: approved, lgtm, size/S

#166 Change build-pipline merge method to `rebase`
  ci/prow/config.yaml
Labels: approved, lgtm, size/XS

#165 Disable gcloud notification updates in Prow presubmit tests
  scripts/presubmit-tests.sh
Labels: approved, lgtm, size/XS

#167 Add trigger for integration tests
  ci/prow/config.yaml
Labels: approved, lgtm, size/M

#171 Create a helper for running e2e go tests
  scripts/README.md
  scripts/e2e-tests.sh
Labels: approved, lgtm, size/M

#176 Don't return non-zero when there isn't another tag.
  scripts/release.sh
Labels: approved, lgtm, size/XS

#175 Redirect stderr to /dev/null
  scripts/library.sh
Labels: approved, lgtm, size/XS

#172 Don't set timeout in go_test_e2e
  scripts/e2e-tests.sh
Labels: approved, lgtm, size/XS

#179 Add test coverage to pull requests in the build pipeline repo
  ci/prow/config.yaml
Labels: approved, lgtm, size/M

#182 Don't build resource names ending in "-"
  scripts/e2e-tests.sh
Labels: approved, lgtm, size/XS

#181 Make report_go_test parse SIGQUIT entries
  scripts/library.sh
  test/library-tests.sh
  test/presubmit-tests.sh
  test/simple_test.go
Labels: approved, lgtm, size/L

#183 Add 10 more projects to boskos pool
  ci/prow/boskos/resources.yaml
Labels: approved, lgtm, size/S

#184 Clearly state why the full test log is dumped
  scripts/library.sh
Labels: approved, lgtm, size/XS

#173 Add infrastructure for publishing named releases
  scripts/README.md
  scripts/e2e-tests.sh
  scripts/library.sh
  scripts/release.sh
  test/presubmit-tests.sh
  test/release-tests.sh
Labels: approved, lgtm, size/L

#185 Add a job for measuring Knative Build latency
  ci/prow/config.yaml
  ci/testgrid/config.yaml
Labels: approved, lgtm, size/S

#187 Set per-job data source directory for latency aggregation jobs
  ci/prow/config.yaml
Labels: approved, lgtm, size/XS

#192 Request Prow to automatically lint go code in PRs
  .github/pull-request-template.md
Labels: approved, lgtm, size/XS

#191 $(JOB_NAME) is invalid, use raw name
  ci/prow/config.yaml
Labels: approved, lgtm, size/XS

#189 Don't remove bazel stuff after parsing results
  scripts/library.sh
Labels: approved, lgtm, size/S

#193 Fix the name of source for aggregating metrics
  ci/prow/config.yaml
Labels: approved, lgtm, size/XS

#194 Install netbase with prow
  images/prow-tests/Dockerfile
Labels: approved, lgtm, size/XS

#196 Separate gcs and testgrid into its own packages
  tools/apicoverage/apicoverage.go
  tools/apicoverage/testgrid.go
  tools/gcs/gcs.go
  tools/testgrid/testgrid.go
Labels: approved, lgtm, size/L

#200 Cleanup bazel after library-tests.sh finish
  test/library-tests.sh
Labels: approved, lgtm, size/XS

#198 Allow defining custom flags for `e2e-tests.sh`
  scripts/README.md
  scripts/e2e-tests.sh
  test/e2e-tests.sh
  test/presubmit-tests.sh
Labels: approved, lgtm, size/M

#203 Prow setup for knative/eventing-sources
  ci/gubernator/config.yaml
  ci/prow/config.yaml
  ci/testgrid/config.yaml
Labels: approved, lgtm, size/L

#206 Bump hook to v20181023-ca14137 to enable review_acts_as_approve
  ci/prow/cluster.yaml
  ci/prow/plugins.yaml
Labels: approved, lgtm, size/XS

#205 Add knative/build-pipeline to Testgrid
  ci/testgrid/config.yaml
Labels: approved, lgtm, size/S

#210 Use dep-collector from within the test-infra repo.
  scripts/library.sh
Labels: approved, lgtm, size/XS

#209 Add alternate spelling of LICENSE seen in new knative/pkg dep
  tools/dep-collector/licenses.go
Labels: approved, lgtm, size/XS

#212 Install dep-collector from `./vendor/`
  scripts/library.sh
Labels: approved, lgtm, size/XS

#213 This moves the build of dep-collector into the Prow Dockerfile.
  images/prow-tests/Dockerfile
  images/prow-tests/Makefile
Labels: approved, lgtm, size/S

#208 Expose docker daemon in knative/build e2e tests
  ci/prow/config.yaml
Labels: approved, lgtm, size/XS

#199 Create a default integration test runner for presubmit
  scripts/README.md
  scripts/e2e-tests.sh
  scripts/library.sh
  scripts/presubmit-tests.sh
  test/presubmit-tests.sh
  test/unit/e2e-custom-flag-tests.sh
  test/unit/library-tests.sh
  test/unit/presubmit-full-custom-integration-tests.sh
  test/unit/presubmit-integration-tests-common.sh
  test/unit/presubmit-partial-custom-integration-tests.sh
  test/unit/release-tests.sh
Labels: approved, lgtm, size/L

#219 Readd dummy.go because dep still needs it
  dummy.go
Labels: approved, lgtm, size/S

#221 change the code coverage job to test running coverage on entire ./
  ci/prow/config.yaml
Labels: approved, lgtm, size/M

#224 Add missing coverage jobs for knative/build-pipeline
  ci/prow/config.yaml
Labels: approved, lgtm, size/M

#211 Install Istio CRDs before the rest of Istio
  scripts/library.sh
Labels: approved, lgtm, size/XS

#216 Adding a new TestGrid dashboard tab for conformance tests results
  ci/testgrid/config.yaml
Labels: approved, lgtm, size/XS

#226 Don't --track when checking out release branch
  scripts/release.sh
Labels: approved, lgtm, size/XS

#227 Add a library function to get all pods of a given app.
  scripts/library.sh
Labels: approved, lgtm, size/S

#225 Install kubetest if necessary when running E2E tests
  scripts/e2e-tests.sh
  scripts/library.sh
  scripts/release.sh
Labels: approved, lgtm, size/S

#229 Use go install for local packages, go get for remote
  scripts/library.sh
Labels: approved, lgtm, size/XS

#228 When branching a release, accept YAMLs in any directory
  scripts/release.sh
  test/presubmit-tests.sh
  test/unit/library-tests.sh
  test/unit/release-tests.sh
Labels: approved, lgtm, size/M
