Repository knative/test-infra, pull requests merged in 2018-09, with the labels that each got.

#94 Provide default (empty value) for PROW_JOB_ID if it's unset
  scripts/library.sh
Labels: approved, lgtm, size/XS

#98 Disable review_acts_as_approve
  ci/prow/plugins.yaml
Labels: approved, lgtm, size/XS

#102 Fix knative/build release job
  ci/prow/config.yaml
Labels: approved, lgtm, size/S

#100 Deal with error when checking for modified files
  scripts/presubmit-tests.sh
Labels: approved, lgtm, size/XS

#104 Add a function to lint markdown files
  images/prow-tests/Dockerfile
  scripts/library.sh
Labels: approved, lgtm, size/M

#99 Remove stray slash from list of GKE versions
  scripts/e2e-tests.sh
Labels: approved, lgtm, size/XS

#107 GOPATH can be inferred if not set
  scripts/e2e-tests.sh
Labels: approved, lgtm, size/XS

#105 Install wrk with prow
  images/prow-tests/Dockerfile
Labels: approved, lgtm, size/XS

#112 add missing paren to scripts/library.sh
  scripts/library.sh
Labels: approved, lgtm, size/XS

#114 setup prow jobs for knative/build-pipeline
  ci/gubernator/config.yaml
  ci/prow/config.yaml
Labels: approved, lgtm, size/M

#116 Add the missing step about OWNERS filers
  ci/prow/prow_setup.md
Labels: approved, lgtm, size/XS

#117 Fix Knative Robots team name
  ci/prow/prow_setup.md
Labels: approved, lgtm, size/XS

#115 Fix authentication for test clusters
  scripts/e2e-tests.sh
  scripts/library.sh
Labels: approved, lgtm, size/S

#118 Fix the go test parser
  scripts/library.sh
Labels: approved, lgtm, size/M

#109 Setup Prow jobs for knative/caching
  ci/gubernator/config.yaml
  ci/prow/config.yaml
  ci/testgrid/config.yaml
Labels: approved, lgtm, size/L

#125 Fix the directory of ci-* jobs
  ci/gubernator/config.yaml
Labels: approved, lgtm, size/XS

#124 Create a Makefile to deploy Gubernator
  ci/gubernator/Makefile
  ci/gubernator/redir_github.py
Labels: approved, lgtm, size/M

#126 Update README.md
  ci/gubernator/README.md
Labels: approved, lgtm, size/XS

#127 Missed trailing / in gubernator config
  ci/gubernator/config.yaml
Labels: approved, lgtm, size/XS

#130 Set GOPATH in library.sh if unset
  scripts/e2e-tests.sh
  scripts/library.sh
Labels: approved, lgtm, size/S

#128 Add wait for app to be routable function in library.sh
  scripts/library.sh
Labels: approved, lgtm, size/S

#119 Add e2e test
  test/e2e-tests.sh
  test/presubmit-tests.sh
Labels: approved, lgtm, size/M

#120 Use the same go test command for testing locally or on Prow
  scripts/library.sh
Labels: approved, lgtm, size/S

#135 Update typo when running go test
  scripts/library.sh
Labels: approved, lgtm, size/XS

#110 Run code coverage on the entire knative/pkg repo
  ci/prow/config.yaml
Labels: approved, lgtm, size/XS

#138 Create a smoke test for test-infra
  dummy.go
  test/presubmit-tests.sh
  test/smoke_test.go
Labels: approved, lgtm, size/M

#142 Remove SSH access to Knative repos for Prow jobs
  ci/prow/config.yaml
Labels: approved, lgtm, size/L

#151 Fix SSH keys workaround for kubetest
  scripts/e2e-tests.sh
Labels: approved, lgtm, size/XS

#152 Use https for cloning repo on go coverage jobs
  ci/prow/config.yaml
Labels: approved, lgtm, size/M

#156 Add info about gubernator to README
  README.md
Labels: approved, lgtm, size/XS

#157 Handle fatal log entries when parsing go test output
  scripts/library.sh
Labels: approved, lgtm, size/S
