Repository knative/test-infra, pull requests merged in 2018-12, with the labels that each got.

#289 Update serving continous run to every 2 hours
  ci/prow/config.yaml
Labels: approved, lgtm, size/XS

#287 add knative testgrid to README
  README.md
Labels: approved, lgtm, size/XS

#290 Deflake signal-based tests in library_test.go
  test/library_test.go
Labels: approved, lgtm, size/XS

#288 Allow setting GCR/GCS on command line for releases
  scripts/README.md
  scripts/release.sh
  test/unit/release-tests.sh
Labels: approved, lgtm, size/L

#291 Fix image build in release
  scripts/release.sh
  test/unit/release-tests.sh
Labels: approved, lgtm, size/M

#292 Remove spurious link in coverage tool test data
  tools/coverage/testgrid/cov-profile.txt/stdout.txt
Labels: approved, lgtm, size/XS

#295 Add ci-knative-build-pipeline-release back
  ci/prow/config.yaml
Labels: approved, lgtm, size/M

#297 Use regional GKE clusters
  scripts/e2e-tests.sh
  scripts/library.sh
Labels: approved, lgtm, size/S

#298 Fix wrong repo name
  ci/prow/config.yaml
Labels: approved, lgtm, size/XS

#293 Add performance wrapper on fortio
  tools/loadgenerator/loadgenerator.go
  tools/loadgenerator/loadgenerator_test.go
Labels: approved, lgtm, size/L

#299 Remove commented code missed in #297
  scripts/e2e-tests.sh
Labels: approved, lgtm, size/XS

#302 Enhance the readability of the test summary
  scripts/library.sh
  test/unit/library-tests.sh
Labels: approved, lgtm, size/M

#296 Rename release jobs to "nightly-release" for clarity
  ci/gubernator/config.yaml
  ci/prow/config.yaml
  ci/prow/prow_setup.md
  ci/testgrid/config.yaml
Labels: approved, lgtm, size/M

#303 Use separate acccounts for test and release jobs
  ci/prow/config.yaml
  ci/prow/prow_setup.md
Labels: approved, lgtm, size/L

#306 Add knative/observability to tide list
  ci/prow/config.yaml
Labels: approved, lgtm, size/XS

#307 Re-add the service-account mount for Prow jobs
  ci/prow/config.yaml
Labels: approved, lgtm, size/S

#309 When creating a test cluster on Prow, use the default service account
  scripts/e2e-tests.sh
Labels: approved, lgtm, size/XS

#305 Periodical Prow job deleting old images
  ci/prow/config.yaml
  scripts/e2e-tests.sh
  scripts/library.sh
  scripts/presubmit-tests.sh
  scripts/release.sh
  test/unit/cleanup-tests.sh
  test/unit/helper.sh
  test/unit/release-tests.sh
  tools/cleanup/README.md
  tools/cleanup/cleanup.sh
Labels: approved, lgtm, size/L

#311 Rename the service account key to service-account.js
  ci/prow/config.yaml
Labels: approved, lgtm, size/L

#312 Add --service-account flag to cleanup.sh
  ci/prow/config.yaml
  test/unit/cleanup-tests.sh
  tools/cleanup/README.md
  tools/cleanup/cleanup-functions.sh
  tools/cleanup/cleanup.sh
Labels: approved, lgtm, size/L

#314 add preset-test-account label to cleanup job
  ci/prow/config.yaml
Labels: approved, lgtm, size/XS

#310 Add support to automated "dot" releases in release.sh
  scripts/release.sh
  test/unit/release-tests.sh
Labels: approved, lgtm, size/M

#315 Add Chao to OWNERS
  OWNERS
Labels: approved, lgtm, size/XS

#316 webhook based API-Coverage tool resource tree definition
  tools/webhook-apicoverage/resourcetree/README.md
  tools/webhook-apicoverage/resourcetree/arraykindnode.go
  tools/webhook-apicoverage/resourcetree/basictypekindnode.go
  tools/webhook-apicoverage/resourcetree/node.go
  tools/webhook-apicoverage/resourcetree/otherkindnode.go
  tools/webhook-apicoverage/resourcetree/ptrkindnode.go
  tools/webhook-apicoverage/resourcetree/resourceforest.go
  tools/webhook-apicoverage/resourcetree/resourcetree.go
  tools/webhook-apicoverage/resourcetree/structkindnode.go
Labels: approved, lgtm, size/L

#320 Also log bazel version when running presubmit tests
  scripts/presubmit-tests.sh
Labels: approved, lgtm, size/XS

#327 Make cleanup job passing by adding placeholder in artifacts
  ci/prow/config.yaml
  test/unit/cleanup-tests.sh
  tools/cleanup/cleanup.sh
Labels: approved, lgtm, size/S

#321 Enable weekly "dot" releases for Knative Serving
  ci/prow/config.yaml
  ci/prow/prow_setup.md
Labels: approved, lgtm, size/M

#328 Fix cleanup job parameter
  ci/prow/config.yaml
Labels: approved, lgtm, size/XS

#333 Remove bazel settings from Prow config
  ci/prow/config.yaml
Labels: approved, lgtm, size/L

#330 Use the prow-tests image with the "stable" tag
  ci/prow/config.yaml
  images/prow-tests/README.md
Labels: approved, lgtm, size/L

#323 webhook based API-Coverage tool: type analysis
  tools/webhook-apicoverage/resourcetree/README.md
  tools/webhook-apicoverage/resourcetree/arraykindnode.go
  tools/webhook-apicoverage/resourcetree/basictypekindnode.go
  tools/webhook-apicoverage/resourcetree/buildChildNodes_test.go
  tools/webhook-apicoverage/resourcetree/node.go
  tools/webhook-apicoverage/resourcetree/otherkindnode.go
  tools/webhook-apicoverage/resourcetree/ptrkindnode.go
  tools/webhook-apicoverage/resourcetree/resourceforest.go
  tools/webhook-apicoverage/resourcetree/resourcetree.go
  tools/webhook-apicoverage/resourcetree/structkindnode.go
  tools/webhook-apicoverage/resourcetree/test_util.go
  tools/webhook-apicoverage/resourcetree/timetypenode.go
Labels: approved, lgtm, size/L

#334 Georeplicate images during release
  scripts/release.sh
Labels: approved, lgtm, size/XS

#336 Assorted fixes to the "dot" releases feature
  ci/prow/config.yaml
  scripts/e2e-tests.sh
  scripts/library.sh
  scripts/release.sh
  test/unit/cleanup-tests.sh
  test/unit/release-tests.sh
  test/unit/test-helper.sh
Labels: approved, lgtm, size/L

#319 Update WORKSPACE definitions
  WORKSPACE
  ci/prow/Makefile
Labels: approved, lgtm, size/S

#325 Properly escape $ in shell command in Makefile
  images/prow-tests/Makefile
Labels: approved, lgtm, size/XS

#313 Add job to back up artifacts
  ci/prow/config.yaml
  images/backups/Dockerfile
  images/backups/Makefile
  images/backups/README.md
  images/backups/backup.sh
Labels: approved, lgtm, size/L

#322 Also display docker version when running presubmit tests
  scripts/presubmit-tests.sh
Labels: approved, lgtm, size/XS

#338 Add missing editor required by a boskos resource
  ci/prow/prow_setup.md
Labels: approved, lgtm, size/XS

#339 Move ci-knative-backups config to a separate block
  ci/prow/config.yaml
Labels: approved, lgtm, size/S

#340 Create artifacts dir if not present when writing testgrid xml
  shared/testgrid/testgrid.go
  shared/testgrid/testgrid_test.go
Labels: approved, lgtm, size/M

#343 When installing latest Knative, show what it is
  scripts/library.sh
Labels: approved, lgtm, size/S

#344 Create a separate xml file for each test when creating testgrid output
  shared/testgrid/testgrid.go
  shared/testgrid/testgrid_test.go
  tools/apicoverage/apicoverage.go
Labels: approved, lgtm, size/M

#345 Add a convenience script to start a Prow job from command line
  ci/prow/README.md
  ci/prow/run_job.sh
Labels: approved, lgtm, size/M

#346 Allow cluster size parameters to be set by caller.
  scripts/e2e-tests.sh
Labels: approved, lgtm, size/S

#347 Don't show pods twice when they time out to come up, it's confusing
  scripts/library.sh
Labels: approved, lgtm, size/XS

#348 Handle case when covered and notCovered are both 0 when calculating apicoverage
  tools/apicoverage/apicoverage.go
Labels: approved, lgtm, size/XS

#351 Update deck to v20181228-006c641
  ci/prow/cluster.yaml
Labels: approved, lgtm, size/XS

#352 Set privileged mode for jobs using docker
  ci/prow/config.yaml
Labels: approved, lgtm, size/S

#349 Use go-junit-report for parsing go test results
  images/prow-tests/Dockerfile
  scripts/library.sh
  test/presubmit-tests.sh
  test/unit/library-tests.sh
Labels: approved, lgtm, size/L

#353 Add update-deps for updating vendor dir
  hack/update-deps.sh
Labels: approved, lgtm, size/S
