Repository knative/test-infra, pull requests merged in 2018-11, with the labels that each got.

#230 Update KO_DOCKER_REPO when not publishing a release
  scripts/release.sh
Labels: approved, lgtm, size/XS

#231 Deal with the default case of not publishing a release.
  scripts/release.sh
Labels: approved, lgtm, size/S

#232 Update OWNERS with new team members
  OWNERS
Labels: approved, lgtm, size/XS

#234 Make `go_test_e2e()` accept arbitrary tags.
  scripts/e2e-tests.sh
Labels: approved, lgtm, size/S

#240 Clearly display test failures on releases
  scripts/release.sh
  test/unit/release-tests.sh
Labels: approved, lgtm, size/M

#239 Allow specifying a GKE version for running E2E tests
  scripts/README.md
  scripts/e2e-tests.sh
Labels: approved, lgtm, size/M

#246 Fix release tagging
  scripts/release.sh
Labels: approved, lgtm, size/S

#243 Fix removal of -v flag in parameters
  scripts/library.sh
Labels: approved, lgtm, size/XS

#248 Count and report how many tests failed
  scripts/library.sh
Labels: approved, lgtm, size/XS

#250 Add more generic methods to testgrid
  tools/apicoverage/apicoverage.go
  tools/gcs/gcs.go
  tools/testgrid/testgrid.go
Labels: approved, lgtm, size/S

#251 Remove wrk from prow image
  images/prow-tests/Dockerfile
Labels: approved, lgtm, size/XS

#247 Explicitly state that E2E tests passed/failed
  scripts/e2e-tests.sh
Labels: approved, lgtm, size/XS

#254 Fix getting commit hash for tagging
  images/prow-tests/Makefile
  scripts/release.sh
Labels: approved, lgtm, size/XS

#237 Don't run presubmit when changing OWNERS_ALIASES, it's useless
  scripts/presubmit-tests.sh
Labels: approved, lgtm, size/XS

#253 Update testgrid config to include perf
  ci/testgrid/config.yaml
Labels: approved, lgtm, size/XS

#256 Allow running different e2e tests on presubmit
  scripts/library.sh
  scripts/presubmit-tests.sh
  test/unit/e2e-custom-flag-tests.sh
  test/unit/library-tests.sh
  test/unit/presubmit-full-custom-integration-tests.sh
  test/unit/presubmit-partial-custom-integration-tests.sh
Labels: approved, lgtm, size/L

#255 Allow specifying a GCP project for E2E tests using a flag
  scripts/e2e-tests.sh
Labels: approved, lgtm, size/M

#257 Set KO_DOCKER_REPO during E2E environment setup
  scripts/e2e-tests.sh
Labels: approved, lgtm, size/XS

#258 Remove dead code
  test/e2e-tests.sh
Labels: approved, lgtm, size/S

#245 Add prow config for upgrade tests
  ci/prow/config.yaml
Labels: approved, lgtm, size/M

#259 Run nightly releases on Knative 0.2 branch
  ci/prow/config.yaml
  ci/testgrid/config.yaml
Labels: approved, lgtm, size/M

#262 Don't run upgrade tests against Knative releases 0.1 and 0.2
  ci/prow/config.yaml
Labels: approved, lgtm, size/XS

#266 Dont use junit_bazel.xml as testgrid output filename
  tools/testgrid/testgrid.go
Labels: approved, lgtm, size/XS

#268 Enable dind for Knative 0.2 nightly releases
  ci/prow/config.yaml
Labels: approved, lgtm, size/XS

#269 Fix linefeed in wait_until_object_does_not_exist() when it succeeds
  scripts/library.sh
Labels: approved, lgtm, size/XS

#274 Don't run E2E tests if DOCKER_REPO_OVERRIDE is the release GCR
  scripts/e2e-tests.sh
Labels: approved, lgtm, size/XS

#271 Temporarily remove ci-knative-build-pipeline-release
  ci/prow/config.yaml
Labels: approved, lgtm, size/M

#275 Use --match instead of --exclude for git describe
  images/prow-tests/Makefile
  scripts/presubmit-tests.sh
  scripts/release.sh
Labels: approved, lgtm, size/XS

#277 Don't delete images after an E2E test finishes
  scripts/e2e-tests.sh
Labels: approved, lgtm, size/S

#270 Reuse get_app_pods() in get_app_pod()
  scripts/library.sh
Labels: approved, lgtm, size/XS

#273 Append to the file if existing when creating testgrid output
  Gopkg.toml
  test/library_test.go
  test/presubmit-tests.sh
  test/unit/library-tests.sh
  tools/dep-collector/imports.go
  tools/testgrid/testgrid.go
  tools/testgrid/testgrid_test.go
Labels: approved, lgtm, size/M

#279 Use nightly images from knative-nightly
  scripts/e2e-tests.sh
  scripts/library.sh
Labels: approved, lgtm, size/S

#261 Send email alerts when Testgrid flows are bad
  ci/testgrid/config.yaml
Labels: approved, lgtm, size/XS

#284 Fix wait_until_object_does_not_exist()
  scripts/library.sh
Labels: approved, lgtm, size/XS

#285 Also handle "panic" log entries when parsing test output
  scripts/library.sh
  test/library_test.go
  test/unit/library-tests.sh
Labels: approved, lgtm, size/S
