Repository knative/test-infra, pull requests merged in 2019-06, with the labels that each got.

#849 enable debug logging
  ci/prow/config.yaml
  ci/prow/make_config.go
Labels: approved, lgtm, size/XS

#847 Prow version auto bumper part 1: fetching version to update
  tools/prow-auto-bumper/main.go
Labels: approved, lgtm, size/L

#854 Cluster creation retry catching GKE version not supported error
  scripts/e2e-tests.sh
Labels: approved, lgtm, size/XS

#853 Move Prow/Testgrid templates into individual yaml files
  ci/prow/make_config.go
  ci/prow/templates/prow_config_header.yaml
  ci/prow/templates/prow_periodic_custom_job.yaml
  ci/prow/templates/prow_periodic_test_job.yaml
  ci/prow/templates/prow_postsubmit_gocoverage_job.yaml
  ci/prow/templates/prow_presubmit_gocoverate_job.yaml
  ci/prow/templates/prow_presubmit_job.yaml
  ci/prow/templates/testgrid_config_header.yaml
  ci/prow/templates/testgrid_dashboardgroup.yaml
  ci/prow/templates/testgrid_dashboardtab.yaml
  ci/prow/templates/testgrid_testgroup.yaml
Labels: approved, lgtm, size/XL

#852 Use defaults for coverage job flags
  ci/prow/config.yaml
  ci/prow/config_knative.yaml
  ci/prow/make_config.go
  ci/prow/templates/prow_postsubmit_gocoverage_job.yaml
  ci/prow/templates/prow_presubmit_gocoverate_job.yaml
  tools/coverage/main.go
Labels: approved, lgtm, size/L

#837 [monitoring] update db record after parsing config yaml and build log
  tools/monitoring/config/config.go
  tools/monitoring/config/config_test.go
  tools/monitoring/config/sample.yaml
  tools/monitoring/log_parser/log_parser.go
  tools/monitoring/log_parser/log_parser_test.go
  tools/monitoring/main.go
  tools/monitoring/mysql/db_mysql.go
Labels: approved, lgtm, size/L

#735 Update the pull-request-template file to show more detailed informati…
  .github/pull-request-template.md
Labels: approved, lgtm, ok-to-test, size/S

#851 Allow standard install of a custom Knative Serving
  scripts/library.sh
Labels: approved, lgtm, size/S

#858 Update prow_setup.md
  ci/prow_setup.md
Labels: approved, lgtm, size/XS

#861 Adding CloudRunEvents to tide.
  ci/prow/config.yaml
  ci/prow/templates/prow_config_header.yaml
Labels: approved, lgtm, size/XS

#860 Prow version auto bumper part 2: Unit tests
  shared/ghutil/fakeghutil/fakeghutil.go
  tools/prow-auto-bumper/getversion_test.go
  tools/prow-auto-bumper/main.go
Labels: approved, lgtm, size/L

#864 add knative-metrics-robot to coverage tool & config
  tools/coverage/main.go
Labels: approved, lgtm, size/XS

#870 Fix knative-serving/conformance-tests TestGrid tab
  ci/prow/make_config.go
  ci/testgrid/config.yaml
Labels: approved, lgtm, size/XS

#872 update boskos images
  ci/prow/boskos/config.yaml
Labels: approved, lgtm, size/XS

#865 Send a test email from monitoring
  images/monitoring/Makefile
  tools/monitoring/gke_deployment/monitoring_service.yaml
  tools/monitoring/mail/mail.go
  tools/monitoring/mail/mail_test.go
  tools/monitoring/main.go
Labels: approved, lgtm, size/L

#873 Update CI to use istio 1.1.7 instead of 1.1.2
  ci/prow/config.yaml
  ci/prow/config_knative.yaml
  ci/prow/make_config.go
  ci/testgrid/config.yaml
Labels: approved, lgtm, size/M

#874 Setup Prow plugins for GoogleCloudPlatform/cloud-run-events
  ci/prow/plugins.yaml
Labels: approved, lgtm, size/S

#877 Fix typo in long && line in e2e-tests.sh
  scripts/e2e-tests.sh
Labels: approved, lgtm, size/XS

#859 Adding CloudRunEvents to prow.
  ci/prow/config.yaml
  ci/prow/config_knative.yaml
  ci/testgrid/config.yaml
Labels: approved, lgtm, size/L

#881 Fix CamelCased org/repo names in Prow/Testgrid configs
  ci/prow/config.yaml
  ci/prow/config_knative.yaml
  ci/prow/make_config.go
  ci/testgrid/config.yaml
Labels: approved, lgtm, size/M

#879 eventing-sources to eventing-contrib
  ci/gubernator/config.yaml
  ci/prow/config.yaml
  ci/prow/config_knative.yaml
  ci/prow/templates/prow_config_header.yaml
  ci/testgrid/config.yaml
Labels: approved, lgtm, size/L

#868 Update instructions on setting Prow for a new org
  ci/prow_setup.md
Labels: approved, lgtm, size/S

#885 Move mysql client to shared from monitoring
  shared/mysql/client.go
  tools/monitoring/gke_deployment/monitoring_service.yaml
  tools/monitoring/main.go
  tools/monitoring/mysql/operations.go
  tools/monitoring/mysql/schema.sql
Labels: approved, lgtm, size/L

#886 Set 12 Janitor instances so that Boskos recycles faster
  ci/prow/boskos/config.yaml
Labels: approved, lgtm, size/XS

#882 Simplify tab names in TestGrid
  ci/prow/make_config.go
  ci/testgrid/config.yaml
Labels: approved, lgtm, size/M

#878 Prow version auto bumper part 3: Update Prow versions and create PullRequest
  shared/ghutil/client.go
  shared/ghutil/fakeghutil/fakeghutil.go
  shared/ghutil/pullrequest.go
  tools/prow-auto-bumper/config.go
  tools/prow-auto-bumper/file.go
  tools/prow-auto-bumper/getversion_test.go
  tools/prow-auto-bumper/main.go
  tools/prow-auto-bumper/parser.go
  tools/prow-auto-bumper/pullrequest.go
  tools/prow-auto-bumper/run.go
Labels: approved, lgtm, size/XXL

#826 added the monitoring tool README
  tools/monitoring/README.md
  tools/monitoring/mysql/README.md
Labels: approved, lgtm, size/M

#891 Prow version auto bumper part 4: README and images
  images/prow-auto-bumper/Dockerfile
  images/prow-auto-bumper/Makefile
  images/prow-auto-bumper/README.md
  tools/prow-auto-bumper/README.md
  tools/prow-auto-bumper/config.go
  tools/prow-auto-bumper/file.go
  tools/prow-auto-bumper/parser.go
  tools/prow-auto-bumper/pullrequest.go
Labels: approved, lgtm, size/L

#892 Add common performance metrics methods
  shared/loadgenerator/loadgenerator.go
  shared/mysql/client.go
  shared/performance/performance.go
  tools/monitoring/main.go
  tools/monitoring/mysql/operations.go
Labels: approved, lgtm, size/L

#901 clean up Prow auto bumper
  tools/prow-auto-bumper/pullrequest.go
Labels: approved, lgtm, size/S

#898 Add mysql db creds to perf jobs
  ci/prow/config.yaml
  ci/prow/make_config.go
Labels: approved, lgtm, size/S

#903 Delete the job for updating Knative Playground
  ci/gubernator/config.yaml
  ci/prow/config.yaml
  ci/prow/config_knative.yaml
  ci/prow/make_config.go
  ci/testgrid/config.yaml
Labels: approved, lgtm, size/M

#884 [monitoring] query db and checks if error condition is met
  tools/monitoring/mysql/operations.go
Labels: approved, lgtm, size/S

#906 use tab instead of whitespace for indentation
  tools/monitoring/mysql/schema.sql
Labels: approved, lgtm, size/S

#905 Support cluster version as [major].[minor] or [major] in e2e tests
  scripts/e2e-tests.sh
Labels: approved, lgtm, size/S

#908 Setup presubmit smoke E2E tests for serving
  ci/prow/config.yaml
  ci/prow/config_knative.yaml
Labels: approved, lgtm, size/M

#888 Add rbac permission for plank on prowjobs
  ci/prow/config_start.yaml
Labels: approved, lgtm, size/XS

#909 Check $PROJECT_ID only when setting up test cluster
  scripts/e2e-tests.sh
Labels: approved, lgtm, size/XS

#910 No need to skip tests for branches without CI
  ci/prow/config.yaml
  ci/prow/config_knative.yaml
Labels: approved, lgtm, size/S

#907 convert Time in golang to sql timestamp format
  tools/monitoring/mysql/operations.go
Labels: approved, lgtm, size/XS

#911 Rename conformance-tests tab to conformance
  ci/prow/make_config.go
  ci/testgrid/config.yaml
Labels: approved, lgtm, size/XS

#902 Add a configurable release number as a parameter to launch Knative serving
  scripts/library.sh
Labels: approved, lgtm, size/XS

#914 Fix README for prow-auto-bumper
  tools/prow-auto-bumper/README.md
Labels: approved, lgtm, size/XS

#913 update plugins to remove usage of deprecated keys
  ci/prow/plugins.yaml
Labels: approved, lgtm, size/XS

#915 Store metrics in db when creating the testgrid metrics row
  shared/performance/performance.go
Labels: approved, lgtm, size/S

#883 Added pubsub integration to monitoring app
  Gopkg.lock
  images/monitoring/Dockerfile
  tools/monitoring/Makefile
  tools/monitoring/gke_deployment/monitoring_service.yaml
  tools/monitoring/main.go
  tools/monitoring/subscriber/subscriber.go
  tools/monitoring/subscriber/subscriber_test.go
  vendor/cloud.google.com/go/pubsub/apiv1/doc.go
  vendor/cloud.google.com/go/pubsub/apiv1/iam.go
  vendor/cloud.google.com/go/pubsub/apiv1/path_funcs.go
  vendor/cloud.google.com/go/pubsub/apiv1/publisher_client.go
  vendor/cloud.google.com/go/pubsub/apiv1/subscriber_client.go
  vendor/cloud.google.com/go/pubsub/debug.go
  vendor/cloud.google.com/go/pubsub/doc.go
  vendor/cloud.google.com/go/pubsub/flow_controller.go
  vendor/cloud.google.com/go/pubsub/internal/distribution/distribution.go
  vendor/cloud.google.com/go/pubsub/iterator.go
  vendor/cloud.google.com/go/pubsub/message.go
  vendor/cloud.google.com/go/pubsub/nodebug.go
  vendor/cloud.google.com/go/pubsub/pubsub.go
  vendor/cloud.google.com/go/pubsub/pullstream.go
  vendor/cloud.google.com/go/pubsub/service.go
  vendor/cloud.google.com/go/pubsub/snapshot.go
  vendor/cloud.google.com/go/pubsub/subscription.go
  vendor/cloud.google.com/go/pubsub/topic.go
  vendor/cloud.google.com/go/pubsub/trace.go
  vendor/github.com/golang/protobuf/ptypes/empty/empty.pb.go
  vendor/go.opencensus.io/plugin/ocgrpc/client.go
  vendor/go.opencensus.io/plugin/ocgrpc/client_metrics.go
  vendor/go.opencensus.io/plugin/ocgrpc/client_stats_handler.go
  vendor/go.opencensus.io/plugin/ocgrpc/doc.go
  vendor/go.opencensus.io/plugin/ocgrpc/server.go
  vendor/go.opencensus.io/plugin/ocgrpc/server_metrics.go
  vendor/go.opencensus.io/plugin/ocgrpc/server_stats_handler.go
  vendor/go.opencensus.io/plugin/ocgrpc/stats_common.go
  vendor/go.opencensus.io/plugin/ocgrpc/trace_common.go
  vendor/golang.org/x/sync/AUTHORS
  vendor/golang.org/x/sync/CONTRIBUTORS
  vendor/golang.org/x/sync/LICENSE
  vendor/golang.org/x/sync/PATENTS
  vendor/golang.org/x/sync/errgroup/errgroup.go
  vendor/golang.org/x/sync/semaphore/semaphore.go
  vendor/google.golang.org/api/support/bundler/bundler.go
  vendor/google.golang.org/api/transport/dial.go
  vendor/google.golang.org/api/transport/go19.go
  vendor/google.golang.org/api/transport/grpc/dial.go
  vendor/google.golang.org/api/transport/grpc/dial_appengine.go
  vendor/google.golang.org/api/transport/not_go19.go
  vendor/google.golang.org/appengine/internal/socket/socket_service.pb.go
  vendor/google.golang.org/appengine/socket/doc.go
  vendor/google.golang.org/appengine/socket/socket_classic.go
  vendor/google.golang.org/appengine/socket/socket_vm.go
  vendor/google.golang.org/genproto/googleapis/pubsub/v1/pubsub.pb.go
  vendor/google.golang.org/genproto/protobuf/field_mask/field_mask.pb.go
  vendor/google.golang.org/grpc/credentials/oauth/oauth.go
Labels: approved, lgtm, size/XXL

#921 Remove delete_leaked_network_resources since it's not happening anymore
  scripts/e2e-tests.sh
Labels: approved, lgtm, size/S

#917 add pubsub labels to continuous prow job
  ci/prow/config.yaml
  ci/prow/make_config.go
  ci/prow/templates/prow_periodic_custom_job.yaml
  ci/prow/templates/prow_periodic_test_job.yaml
  ci/prow/templates/prow_postsubmit_gocoverage_job.yaml
  ci/prow/templates/prow_presubmit_gocoverate_job.yaml
  ci/prow/templates/prow_presubmit_job.yaml
Labels: approved, lgtm, size/M

#920 Do fail coverage job on errors
  tools/coverage/githubUtil/github.go
  tools/coverage/logUtil/logUtil.go
  tools/coverage/main.go
Labels: approved, lgtm, size/S

#927 add new repo sample-controller
  ci/gubernator/config.yaml
  ci/prow/config.yaml
  ci/prow/config_knative.yaml
  ci/prow/templates/prow_config_header.yaml
  ci/testgrid/config.yaml
Labels: approved, lgtm, size/L

#928 Prow job generation: allow full-command override for better reading
  ci/prow/config_knative.yaml
  ci/prow/make_config.go
Labels: approved, lgtm, size/M

#930 Increase timeout for eventing periodic jobs
  ci/prow/config.yaml
  ci/prow/config_knative.yaml
Labels: approved, lgtm, size/XS

#925 flaky-test-reporter: fix a few small issues introduced recently
  shared/testgrid/testgrid.go
  tools/flaky-test-reporter/config.go
  tools/flaky-test-reporter/main.go
  tools/flaky-test-reporter/result.go
Labels: approved, lgtm, ok-to-test, size/S

#935 golang format tools
  ci/prow/make_config.go
  shared/testgrid/testgrid.go
  tools/coverage/artifacts/profiling.go
  tools/flaky-test-reporter/config.go
  tools/monitoring/config/config.go
  tools/prow-auto-bumper/getversion_test.go
  tools/webhook-apicoverage/coveragecalculator/ignorefields.go
Labels: approved, lgtm, ok-to-test, size/M

#933 Increase boskos janitor count to match number of boskos projects.
  ci/prow/boskos/config.yaml
Labels: approved, lgtm, size/XS

#938 fix broken link
  tools/webhook-apicoverage/webhook/README.md
Labels: approved, lgtm, size/XS

#931 Create test cluster without downloading kubernetes
  scripts/e2e-tests.sh
Labels: approved, lgtm, size/M

#918 update alerts table and send alert email conditionally
  shared/mysql/client.go
  tools/monitoring/config/config.go
  tools/monitoring/mysql/alert.go
  tools/monitoring/mysql/error_logger.go
Labels: approved, lgtm, size/L

#934 Format markdown
  CONTRIBUTING.md
  README.md
  ci/README.md
  ci/gubernator/README.md
  ci/prow/README.md
  ci/prow/boskos/README.md
  ci/prow_setup.md
  ci/release.md
  ci/testgrid/README.md
  devstats/INSTALL.md
  devstats/README.md
  devstats/grafana/README.md
  images/apicoverage/README.md
  images/backups/README.md
  images/prow-tests/README.md
  scripts/README.md
  tools/cleanup/README.md
  tools/dep-collector/README.md
  tools/flaky-test-reporter/README.md
  tools/monitoring/README.md
  tools/monitoring/mysql/README.md
  tools/prow-auto-bumper/README.md
  tools/webhook-apicoverage/coveragecalculator/README.md
  tools/webhook-apicoverage/resourcetree/README.md
  tools/webhook-apicoverage/tools/README.md
  tools/webhook-apicoverage/view/README.md
  tools/webhook-apicoverage/webhook/README.md
Labels: approved, lgtm, ok-to-test, size/XL

#939 golang format tools
  tools/monitoring/mysql/error_logger.go
Labels: approved, lgtm, ok-to-test, size/XS

#941 Format markdown
  tools/webhook-apicoverage/webhook/README.md
Labels: approved, lgtm, ok-to-test, size/XS

#943 moved prowapi structs to a separate package
  tools/monitoring/main.go
  tools/monitoring/prowapi/types.go
  tools/monitoring/subscriber/subscriber.go
  tools/monitoring/subscriber/subscriber_test.go
Labels: approved, lgtm, size/L

#940 Fix spelling errors
  tools/coverage/githubUtil/githubPr/githubRepo.go
  tools/flaky-test-reporter/main.go
  tools/latency/main.go
  tools/webhook-apicoverage/tools/tools.go
Labels: approved, lgtm, ok-to-test, size/S

#944 update kubekins-e2e to use latest
  images/prow-tests/Dockerfile
Labels: approved, lgtm, size/XS

#929 auto generate cron string for period job
  ci/prow/config.yaml
  ci/prow/config_knative.yaml
  ci/prow/make_config.go
Labels: approved, lgtm, size/L

#947 Allow setting REPO_ROOT_DIR externally.
  scripts/library.sh
Labels: approved, lgtm, size/XS

#923 Surface build errors on Gubernator
  scripts/presubmit-tests.sh
Labels: approved, lgtm, size/S

#950 Generate cron strings deterministically
  ci/prow/config.yaml
  ci/prow/make_config.go
Labels: approved, lgtm, size/L

#959 Update list of permissions required for boskos
  ci/prow/boskos/permissions.sh
Labels: approved, lgtm, size/XS

#899 Add Prow auto bumper job
  ci/prow/config.yaml
  ci/prow/make_config.go
Labels: approved, lgtm, size/L

#951 Do not store perf metrics in sql
  shared/performance/performance.go
Labels: approved, lgtm, size/M

#955 [coverage] fix testgrid redness on passed tests
  tools/coverage/testgrid/testsuiteXmlWriter.go
Labels: approved, lgtm, size/S

#963 Add continuous flow for test-infra
  ci/prow/config.yaml
  ci/prow/config_knative.yaml
  ci/testgrid/config.yaml
Labels: approved, lgtm, size/M

#962 Prow auto bumper: add missing Makefile
  ci/prow/config.yaml
  ci/prow/make_config.go
  tools/prow-auto-bumper/Makefile
Labels: approved, lgtm, size/S

#966 mock check_links_in_markdown so unit test doesn't really run markdown…
  test/unit/presubmit-tests.sh
Labels: approved, lgtm, size/XS

#967 Boskos resources update - Increased by 10 GCP project
  ci/prow/boskos/permissions.sh
  ci/prow/boskos/resources.yaml
Labels: approved, lgtm, size/S

#969 mock default_build_test_runner so unit test doesn't run build test again
  test/unit/presubmit-tests.sh
Labels: approved, lgtm, size/XS

#970 Fix fortio package dependency
  Gopkg.lock
  shared/loadgenerator/loadgenerator.go
  vendor/fortio.org/fortio/LICENSE
  vendor/fortio.org/fortio/debian/copyright
  vendor/fortio.org/fortio/fhttp/http_client.go
  vendor/fortio.org/fortio/fhttp/http_server.go
  vendor/fortio.org/fortio/fhttp/http_utils.go
  vendor/fortio.org/fortio/fhttp/httprunner.go
  vendor/fortio.org/fortio/fnet/network.go
  vendor/fortio.org/fortio/log/logger.go
  vendor/fortio.org/fortio/periodic/periodic.go
  vendor/fortio.org/fortio/stats/stats.go
  vendor/fortio.org/fortio/version/version.go
  vendor/istio.io/fortio/fhttp/http.go
  vendor/istio.io/fortio/fnet/network.go
Labels: approved, lgtm, size/XXL

#942 read build log from gcs
  shared/gcs/gcs.go
  shared/gcs/gcs_test.go
Labels: approved, lgtm, size/M

#979 Reverting kubekins-e2e image
  images/prow-tests/Dockerfile
Labels: approved, lgtm, size/XS

#980 Update gubernator config for serving 0.X logs
  ci/gubernator/config.yaml
Labels: approved, lgtm, size/XS

#953 Add jobs testing different k8s versions
  ci/prow/config.yaml
  ci/prow/config_knative.yaml
  ci/prow/make_config.go
  ci/testgrid/config.yaml
Labels: approved, lgtm, size/L

#989 deprecating bootstrap, use podutil
  ci/prow/config.yaml
  ci/prow/templates/prow_periodic_test_job.yaml
  ci/prow/templates/prow_presubmit_job.yaml
Labels: approved, lgtm, size/XXL

#952 Complete all required content for alert email
  tools/monitoring/alert/alert.go
  tools/monitoring/alert/report.go
  tools/monitoring/log_parser/database.go
  tools/monitoring/log_parser/log_parser.go
Labels: approved, lgtm, size/L

#904 add endpoint test for alert condition check
  tools/monitoring/main.go
Labels: approved, lgtm, size/S

#994 Fix GKE version parsing
  scripts/e2e-tests.sh
Labels: approved, lgtm, size/XS

#982 Add perf testing job for eventing
  ci/prow/config.yaml
  ci/prow/config_knative.yaml
  ci/testgrid/config.yaml
Labels: approved, lgtm, size/M

#991 Enable Spyglass on Prow
  ci/prow/cluster.yaml
  ci/prow/config.yaml
  ci/prow/templates/prow_config_header.yaml
  ci/prow/templates/testgrid_config_header.yaml
  ci/testgrid/config.yaml
Labels: approved, lgtm, size/M

#997 Update job url with Spyglass URL in Prow config
  ci/prow/config.yaml
  ci/prow/templates/prow_config_header.yaml
Labels: approved, lgtm, size/XS

#998 Update WORKSPACE
  WORKSPACE
Labels: approved, lgtm, size/XS

#999 Add a timestamp to banners.
  scripts/library.sh
Labels: approved, lgtm, size/XS

#1001 Update prow_setup with updated prow config template
  ci/prow_setup.md
Labels: approved, lgtm, size/S

#1000 Cache bazel version in prow-images
  images/prow-tests/Dockerfile
  scripts/presubmit-tests.sh
Labels: approved, lgtm, size/XS

#1002 Format markdown
  ci/prow_setup.md
Labels: approved, lgtm, ok-to-test, size/XS

#993 Use path_alias for sample-controller repo
  ci/prow/config.yaml
  ci/prow/config_knative.yaml
  ci/prow/make_config.go
  ci/prow/templates/prow_postsubmit_gocoverage_job.yaml
  ci/prow/templates/prow_presubmit_gocoverate_job.yaml
  ci/prow/templates/prow_presubmit_job.yaml
Labels: approved, lgtm, size/L

#973 Add the support of new repository of serving-operator
  ci/gubernator/config.yaml
  ci/prow/config.yaml
  ci/prow/config_knative.yaml
  ci/prow/templates/prow_config_header.yaml
  ci/testgrid/config.yaml
Labels: approved, lgtm, size/L

#1004 Adding resource limits to test-pods namespace
  ci/prow/config_start.yaml
Labels: approved, lgtm, size/S

#978 Fix database connection problem
  shared/mysql/client.go
  tools/monitoring/README.md
  tools/monitoring/main.go
Labels: approved, lgtm, size/S

#1005 randomize the ko docker repo
  scripts/e2e-tests.sh
Labels: approved, lgtm, size/XS

#958 Unit test against testgrid package inconsistent with testgrid config …
  shared/common/common.go
  shared/testgrid/testgrid_test.go
  shared/testgrid/yaml.go
  tools/prow-auto-bumper/file.go
Labels: approved, lgtm, size/L

#1010 Update to using go 1.12.1 in coverage job
  tools/coverage/Dockerfile
Labels: approved, lgtm, size/XS

#988 fixing continuous error
  test/e2e/flag.go
Labels: approved, lgtm, size/M

#1011 Update prow to v20190614-1bd5c9911
  ci/prow/boskos/config.yaml
  ci/prow/cluster.yaml
  ci/prow/config.yaml
  ci/prow/templates/prow_config_header.yaml
Labels: approved, lgtm, size/M

#1007 `clean` target doesn't exist anymore
  images/prow-tests/Makefile
Labels: approved, lgtm, size/XS

#1006 Remove gubernator from prow_setup since it's not needed
  ci/prow_setup.md
Labels: approved, lgtm, size/XS

#1015 Each container in test-pods request 1 CPU
  ci/prow/config_start.yaml
Labels: approved, lgtm, size/XS

#1019 Run dep-collector from latest source
  images/prow-tests/Dockerfile
  scripts/library.sh
Labels: approved, lgtm, size/XS

#1021 Format markdown
  tools/monitoring/README.md
Labels: approved, lgtm, ok-to-test, size/XS

#949 Update Prow setup for a new org
  ci/prow_setup.md
Labels: approved, lgtm, size/S

#1020 Display ko version on presubmit
  images/prow-tests/Dockerfile
  scripts/presubmit-tests.sh
Labels: approved, lgtm, size/S

#1016 Fixes for Prow configs
  ci/prow/Makefile
  ci/prow/cluster.yaml
  ci/prow/config_start.yaml
Labels: approved, lgtm, size/M

#1025 Report node/pod names in presubmit tests
  scripts/presubmit-tests.sh
Labels: approved, lgtm, size/XS

#1028 Request same memory for limit and request
  ci/prow/cluster.yaml
Labels: approved, lgtm, size/XS

#1022 golang format tools
  shared/testgrid/yaml.go
Labels: approved, lgtm, ok-to-test, size/XS

#1012 Have a single target to fully update the Prow cluster
  ci/prow/Makefile
Labels: approved, lgtm, size/XS

#1023 Use local dep-collector that's a wrapper for building it on-the-fly
  images/prow-tests/Dockerfile
  images/prow-tests/dep-collector
Labels: approved, lgtm, size/M

#1017 Display timestamp as PDT so it aligns with Prow dashboard
  scripts/library.sh
Labels: approved, lgtm, size/XS

#1030 Default memory request 4G each container
  ci/prow/cluster.yaml
Labels: approved, lgtm, size/XS

#1009 actual config yaml used for monitoring
  tools/monitoring/config/config.yaml
  tools/monitoring/config/config_test.go
Labels: approved, lgtm, size/L

#965 added the alerting workflow
  shared/gcs/gcs.go
  tools/monitoring/alert/alerting.go
  tools/monitoring/alert/report.go
  tools/monitoring/log_parser/log_parser.go
  tools/monitoring/log_parser/log_parser_test.go
  tools/monitoring/main.go
  tools/monitoring/mysql/database.go
Labels: approved, lgtm, size/L

#1034 Remove Eric and Nikhil from OWNERS_ALIASES.
  OWNERS_ALIASES
Labels: approved, lgtm, size/XS

#1035 Format markdown
  ci/prow_setup.md
Labels: approved, lgtm, ok-to-test, size/XS

#1036 Refactor make_config as it is getting unweildy
  ci/prow/Makefile
  ci/prow/README.md
  ci/prow/make_config.go
  ci/prow/periodic_config.go
  ci/prow/testgrid_config.go
  ci/release.md
Labels: approved, lgtm, size/XXL

#1038 Add Ingress object for stats site.
  devstats/Kubernetes/grafana-service.yaml
Labels: approved, lgtm, size/S

#1039 Add CI for serving release 0.7 branch
  ci/prow/config.yaml
  ci/prow/config_knative.yaml
  ci/testgrid/config.yaml
Labels: approved, lgtm, size/M

#1032 Always report build test status as a JUnit XML
  scripts/presubmit-tests.sh
Labels: approved, lgtm, size/S

#992 add shared JSON report library and client in flaky-test-reporter
  tools/flaky-test-reporter/json_reporter.go
  tools/flaky-test-reporter/jsonreport/jsonreport.go
  tools/flaky-test-reporter/main.go
Labels: approved, lgtm, ok-to-test, size/L

#1040 Enable PR status on Prow
  ci/prow/cluster.yaml
Labels: approved, lgtm, size/S

#1043 Run perf jobs every 3 hours instead of once a day
  ci/prow/config.yaml
  ci/prow/periodic_config.go
Labels: approved, lgtm, size/M

#1047 Format markdown
  ci/prow/README.md
Labels: approved, lgtm, ok-to-test, size/XS

#1033 Readd default maintainer for the milestone plugin
  ci/prow/plugins.yaml
Labels: approved, lgtm, size/XS

#1046 Fix prow-tests Dockerfile
  images/prow-tests/Dockerfile
Labels: approved, lgtm, size/XS

#1045 In Testgrid, first part of the name is testsuite
  scripts/presubmit-tests.sh
Labels: approved, lgtm, size/XS

#1053 Fetch all remotes when initializing dot release
  scripts/release.sh
Labels: approved, lgtm, size/XS

#1048 Prow jobs for pkg repo uses knative.dev alias
  ci/prow/config.yaml
  ci/prow/config_knative.yaml
  ci/prow/make_config.go
Labels: approved, lgtm, size/S

#1044 Update Prow/Testgrid config for 0.7 release
  ci/prow/config.yaml
  ci/prow/config_knative.yaml
  ci/testgrid/config.yaml
Labels: approved, lgtm, size/L

#1050 Fix versioning when specifying a different branch for dot releases
  scripts/release.sh
Labels: approved, lgtm, size/XS

#1051 Send the alert email when it meets the alerting criteria
  tools/monitoring/alert/alert.go
  tools/monitoring/alert/alerting.go
  tools/monitoring/alert/report.go
  tools/monitoring/config/config.go
  tools/monitoring/config/config_test.go
  tools/monitoring/main.go
  tools/monitoring/mysql/database.go
Labels: approved, lgtm, size/L

#1058 Fix example commands for arbitrary releases
  ci/release.md
Labels: approved, lgtm, size/XS

#1055 Prow jobs for caching repo use knative.dev alias
  ci/prow/config.yaml
  ci/prow/config_knative.yaml
Labels: approved, lgtm, size/S

#1061 golang format tools
  shared/prometheus/prometheus.go
  tools/webhook-apicoverage/webhook/apicoverage_recorder.go
  tools/webhook-apicoverage/webhook/webhook.go
Labels: approved, lgtm, ok-to-test, size/S

#1062 testing mesh with istio1.2
  ci/prow/config.yaml
  ci/prow/config_knative.yaml
  ci/prow/testgrid_config.go
  ci/testgrid/config.yaml
  shared/testgrid/testgrid.go
  tools/flaky-test-reporter/config.go
Labels: approved, lgtm, size/L

#1065 remove k8s variants
  ci/prow/config.yaml
  ci/prow/config_knative.yaml
  ci/prow/testgrid_config.go
  ci/testgrid/config.yaml
Labels: approved, lgtm, size/L

#1066 Query alerts in monitoring db
  tools/monitoring/alert/alert.go
  tools/monitoring/mysql/database.go
Labels: approved, lgtm, size/M

#1064 Unset cluster credential after manual job tests
  ci/prow/run_job.sh
Labels: approved, lgtm, size/XS

#1057 Add ssh key for prow updater job
  ci/prow/config.yaml
  ci/prow/periodic_config.go
Labels: approved, lgtm, size/XS

#1069 Fix update-full target
  ci/prow/Makefile
Labels: approved, lgtm, size/S

#1063 Update the toGcsLink to remove spyglass link prefix
  tools/monitoring/alert/alerting.go
  tools/monitoring/alert/alerting_test.go
Labels: approved, lgtm, size/M

#1072 golang format tools
  shared/testgrid/testgrid.go
Labels: approved, lgtm, ok-to-test, size/XS

#1059 Flaky test reporter uses spyglass link instead of gubernator
  tools/flaky-test-reporter/github_issue.go
Labels: approved, lgtm, size/XS
