Repository knative/test-infra, pull requests merged in 2019-03, with the labels that each got.

#543 Handling parellel request to the webhook apicoverage tool
  tools/webhook-apicoverage/resourcetree/basictypekindnode.go
  tools/webhook-apicoverage/resourcetree/resourcetree.go
  tools/webhook-apicoverage/webhook/apicoverage_recorder.go
Labels: approved, lgtm, size/M

#506 Flaky test reporting(part #4) Github issues tracking for flaky tests
  tools/flaky-test-reporter/config.go
  tools/flaky-test-reporter/error.go
  tools/flaky-test-reporter/ghutil/ghutil.go
  tools/flaky-test-reporter/github_issue.go
  tools/flaky-test-reporter/main.go
  tools/flaky-test-reporter/result.go
  tools/flaky-test-reporter/run.go
Labels: approved, lgtm, size/XL

#545 Enable the verify-owners plugin for Prow
  ci/prow/plugins.yaml
Labels: approved, lgtm, size/XS

#536 Make all github calls as receivable by github client
  tools/flaky-test-reporter/ghutil/ghutil.go
  tools/flaky-test-reporter/github_issue.go
  tools/flaky-test-reporter/main.go
Labels: approved, lgtm, size/L

#544 Use the common monitoring component for prometheus
  Gopkg.lock
  shared/prometheus/prometheus.go
  shared/prometheus/prometheus_test.go
  vendor/github.com/knative/pkg/logging/config.go
  vendor/github.com/knative/pkg/test/monitoring/doc.go
  vendor/github.com/knative/pkg/test/monitoring/monitoring.go
  vendor/github.com/knative/pkg/webhook/certs.go
Labels: approved, lgtm, size/L

#549 Fix escaping
  scripts/library.sh
Labels: approved, lgtm, size/XS

#551 Parse basic overrides after default options
  ci/prow/config.yaml
  ci/prow/make_config.go
Labels: approved, lgtm, size/M

#552 Replace custom periodic templates with the standard one
  ci/prow/config.yaml
  ci/prow/make_config.go
Labels: approved, lgtm, size/L

#554 Webhook-APICoverage: Prow job env variable fix
  ci/prow/config.yaml
  ci/prow/make_config.go
Labels: approved, lgtm, size/XS

#558 Fix typo doc
  scripts/README.md
Labels: approved, lgtm, size/XS

#560 Remove backticks from string
  scripts/release.sh
Labels: approved, lgtm, size/XS

#561 Enable auto and dot releases for eventing-sources
  ci/prow/config.yaml
  ci/prow/config_knative.yaml
Labels: approved, lgtm, size/M

#541 Flaky test reporting(part #5) Automatic Slack notification for flaky tests
  shared/testgrid/testgrid.go
  tools/flaky-test-reporter/error.go
  tools/flaky-test-reporter/github_issue.go
  tools/flaky-test-reporter/main.go
  tools/flaky-test-reporter/result.go
  tools/flaky-test-reporter/run.go
  tools/flaky-test-reporter/slack_notification.go
Labels: approved, lgtm, size/L

#562 Enable dot releases for eventing
  ci/prow/config.yaml
  ci/prow/config_knative.yaml
Labels: approved, lgtm, size/M

#564 Set knative/build dot releases and update Testgrid
  ci/prow/config.yaml
  ci/prow/config_knative.yaml
  ci/testgrid/config.yaml
Labels: approved, lgtm, size/L

#559 Fail fast in release.sh when testing (#331)
  scripts/README.md
  scripts/presubmit-tests.sh
  scripts/release.sh
  test/unit/presubmit-tests.sh
Labels: approved, lgtm, size/M

#553 flaky tests reporter: fake GithubClient for unit test
  tools/flaky-test-reporter/ghutil/fakeghutil/fakeghutil.go
  tools/flaky-test-reporter/ghutil/ghutil.go
  tools/flaky-test-reporter/github_issue.go
Labels: approved, lgtm, size/L

#565 flaky tests reporter: assorted fixes
  tools/flaky-test-reporter/config.go
  tools/flaky-test-reporter/ghutil/fakeghutil/fakeghutil.go
  tools/flaky-test-reporter/ghutil/ghutil.go
  tools/flaky-test-reporter/github_issue.go
  tools/flaky-test-reporter/main.go
Labels: approved, lgtm, size/M

#566 updating plank to v20190311
  ci/prow/cluster.yaml
  ci/prow/config.yaml
  ci/prow/make_config.go
Labels: approved, lgtm, size/S

#569 Be more verbose about a release being published
  scripts/release.sh
Labels: approved, lgtm, size/XS

#568 Flaky test reporter: add unit test for github operations
  tools/flaky-test-reporter/github_issue_test.go
Labels: approved, lgtm, size/L

#567 Update knative/pkg
  Gopkg.lock
  shared/prometheus/prometheus.go
  vendor/github.com/knative/pkg/test/monitoring/monitoring.go
Labels: approved, lgtm, size/S

#572 hard code E2E_CLUSTER_ZONE to a
  ci/prow/config.yaml
  ci/prow/make_config.go
Labels: approved, lgtm, size/M

#573 also hard code cluster zone in continuous runs
  ci/prow/config.yaml
  ci/prow/make_config.go
Labels: approved, lgtm, size/M

#574 Fail release if an empty yaml is generated
  scripts/release.sh
Labels: approved, lgtm, size/XS

#578 flaky test reporter: add new comment explaining closing/reopening reasons
  tools/flaky-test-reporter/github_issue.go
Labels: approved, lgtm, size/S

#575 webhook-apicoverage: HTML display and other fixes
  tools/webhook-apicoverage/coveragecalculator/calculator.go
  tools/webhook-apicoverage/resourcetree/arraykindnode.go
  tools/webhook-apicoverage/resourcetree/basictypekindnode.go
  tools/webhook-apicoverage/resourcetree/node.go
  tools/webhook-apicoverage/resourcetree/otherkindnode.go
  tools/webhook-apicoverage/resourcetree/ptrkindnode.go
  tools/webhook-apicoverage/resourcetree/resourcetree.go
  tools/webhook-apicoverage/resourcetree/structkindnode.go
  tools/webhook-apicoverage/resourcetree/timetypenode.go
  tools/webhook-apicoverage/tools/tools.go
  tools/webhook-apicoverage/view/README.md
  tools/webhook-apicoverage/view/coverage_display.go
  tools/webhook-apicoverage/view/html_display.go
  tools/webhook-apicoverage/view/jsontype_display.go
  tools/webhook-apicoverage/webhook/apicoverage_recorder.go
Labels: approved, lgtm, size/L

#563 Remove knative/build-pipeline from the prow configuration.
  ci/gubernator/config.yaml
  ci/prow/config.yaml
  ci/prow/config_knative.yaml
  ci/prow/make_config.go
  ci/testgrid/config.yaml
Labels: approved, lgtm, size/L

#580 Add `owners-label` to plugins.
  ci/prow/plugins.yaml
Labels: approved, lgtm, size/XS

#581 Flaky test reporter: remove label and close issue if failed creating issue
  tools/flaky-test-reporter/github_issue.go
Labels: approved, lgtm, size/M

#542 Flaky test reporting(part #6): Prow job definition for flaky tests reporting
  ci/prow/config.yaml
  ci/prow/make_config.go
  images/flaky-test-reporter/Dockerfile
  images/flaky-test-reporter/Makefile
  images/flaky-test-reporter/README.md
  tools/flaky-test-reporter/Makefile
Labels: approved, lgtm, size/L

#586 Flaky test reporter: consider test as flaky even with not enough runs
  tools/flaky-test-reporter/github_issue.go
  tools/flaky-test-reporter/result.go
Labels: approved, lgtm, size/M

#587 Update Prow setup for a new repo
  ci/prow/prow_setup.md
Labels: approved, lgtm, size/XS

#584 Flaky test reporter: fixes for Prow job config and Docker file
  ci/prow/config.yaml
  ci/prow/make_config.go
  images/flaky-test-reporter/Dockerfile
Labels: approved, lgtm, size/S

#582 Increase serving test timeouts
  ci/prow/config.yaml
  ci/prow/config_knative.yaml
Labels: approved, lgtm, size/XS

#376 A helper funcion for removing broken symlinks
  scripts/library.sh
Labels: approved, lgtm, size/S

#593 Revert Hardcoding cluster zones
  ci/prow/config.yaml
  ci/prow/make_config.go
Labels: approved, lgtm, size/L

#599 Move tests to west2 region due to stockouts
  ci/prow/config.yaml
  ci/prow/make_config.go
Labels: approved, lgtm, size/L

#600 change prow config to us-central1 region
  ci/prow/config.yaml
  ci/prow/make_config.go
Labels: approved, lgtm, size/L

#607 Flaky test reporter: don't list individual test in Slack if flaky rate too high
  tools/flaky-test-reporter/github_issue.go
  tools/flaky-test-reporter/slack_notification.go
Labels: approved, lgtm, size/S

#608 Update ko repo
  images/prow-tests/Dockerfile
Labels: approved, lgtm, size/XS

#583 Also generate testgrid config with make_config.go
  ci/prow/Makefile
  ci/prow/make_config.go
  ci/testgrid/Makefile
  ci/testgrid/config.yaml
Labels: approved, lgtm, size/XL

#601 Fix docs link
  CONTRIBUTING.md
Labels: approved, lgtm, size/XS

#614 Create presubmit jobs for knative/client
  ci/prow/config.yaml
  ci/prow/config_knative.yaml
  ci/prow/make_config.go
  ci/testgrid/config.yaml
Labels: approved, lgtm, size/L

#613 Cleanup Testgrid a bit
  ci/prow/Makefile
  ci/prow/config.yaml
  ci/prow/config_knative.yaml
  ci/prow/make_config.go
  ci/testgrid/config.yaml
Labels: approved, lgtm, size/L

#612 Allow creating major releases from existing nightly builds
  scripts/release.sh
  test/unit/release-tests.sh
Labels: approved, lgtm, size/L

#616 Add correct alert settings for Testgrid
  ci/prow/make_config.go
  ci/testgrid/config.yaml
Labels: approved, lgtm, size/M

#617 Enable dind for integration test in docs repo
  ci/prow/config.yaml
  ci/prow/config_knative.yaml
Labels: approved, lgtm, size/S

#620 More tweaks to Testgrid alerts
  ci/prow/make_config.go
  ci/testgrid/config.yaml
Labels: approved, lgtm, size/M

#622 Allow overriding the test timeout when generating a Prow config file
  ci/prow/make_config.go
Labels: approved, lgtm, size/XS

#623 Use atleast 16 nodes for perf test cluster
  ci/prow/config.yaml
  ci/prow/make_config.go
Labels: approved, lgtm, size/S

#624 Delete the continuous release-0.2 and release-0.3 integration flows
  ci/prow/config.yaml
  ci/prow/config_knative.yaml
  ci/testgrid/config.yaml
Labels: approved, lgtm, size/L

#621 Add README for flaky test reporter
  tools/flaky-test-reporter/README.md
  tools/flaky-test-reporter/flowchart.png
Labels: approved, lgtm, size/M

#570 Cleanup job also deletes stale Boskos clusters
  ci/prow/config.yaml
  ci/prow/make_config.go
  scripts/library.sh
  test/unit/cleanup-tests.sh
  tools/cleanup/README.md
  tools/cleanup/cleanup-functions.sh
  tools/cleanup/cleanup.sh
Labels: approved, lgtm, size/L

#630 Flaky test related issues moving to serving repo
  tools/flaky-test-reporter/config.go
Labels: approved, lgtm, size/S

#641 use html tag for flaky tests issue to make it look better
  tools/flaky-test-reporter/github_issue.go
Labels: approved, lgtm, size/S

#639 sending slack notification to api channel
  tools/flaky-test-reporter/slack_notification.go
Labels: approved, lgtm, size/XS

#647 update boskos version
  ci/prow/boskos/config.yaml
Labels: approved, lgtm, size/XS

#644 remove post-knative-serving-go-coverage as defaultPostSubmitJobName
  tools/coverage/main.go
Labels: approved, lgtm, size/XS
