Repository knative/test-infra, pull requests merged in 2019-09, with the labels that each got.

#1322 A few bug fixes in flaky-test-reporter
  images/flaky-test-reporter/Dockerfile
  tools/flaky-test-reporter/config/config.go
  tools/flaky-test-reporter/github_issue.go
Labels: approved, lgtm, size/S

#1327 limit flaky report issue comment length
  tools/flaky-test-reporter/github_issue.go
Labels: approved, lgtm, size/M

#1330 Build flaky-test-reporter using go1.12
  images/flaky-test-reporter/Dockerfile
Labels: approved, lgtm, size/XS

#1332 Fixing flakytestreporter identifying existing comment bug, fixing dryrun
  tools/flaky-test-reporter/github_issue.go
Labels: approved, lgtm, size/S

#1333 Extract code to function is_release_branch
  scripts/library.sh
Labels: approved, lgtm, size/S

#1334 Add note about boskos project folder settings
  ci/prow/boskos/create_projects.sh
Labels: approved, lgtm, size/XS

#1335 Hide error when gcp isn't being used
  scripts/release.sh
Labels: approved, lgtm, size/XS

#1337 Add eventing perf recycling cron jobs
  ci/prow/config.yaml
  ci/prow/make_config.go
  ci/prow/periodic_config.go
Labels: approved, lgtm, size/L

#1339 Acquire cluster admin role for only GKE
  scripts/e2e-tests.sh
Labels: approved, lgtm, size/S

#1341 tools/webhook-apicoverage: Removing webhook-apicoverage tool
  tools/webhook-apicoverage/coveragecalculator/README.md
  tools/webhook-apicoverage/coveragecalculator/calculator.go
  tools/webhook-apicoverage/coveragecalculator/coveragedata.go
  tools/webhook-apicoverage/coveragecalculator/ignorefields.go
  tools/webhook-apicoverage/resourcetree/README.md
  tools/webhook-apicoverage/resourcetree/arraykindnode.go
  tools/webhook-apicoverage/resourcetree/basictypekindnode.go
  tools/webhook-apicoverage/resourcetree/buildChildNodes_test.go
  tools/webhook-apicoverage/resourcetree/node.go
  tools/webhook-apicoverage/resourcetree/otherkindnode.go
  tools/webhook-apicoverage/resourcetree/ptrkindnode.go
  tools/webhook-apicoverage/resourcetree/resourceforest.go
  tools/webhook-apicoverage/resourcetree/resourcetree.go
  tools/webhook-apicoverage/resourcetree/rule.go
  tools/webhook-apicoverage/resourcetree/structkindnode.go
  tools/webhook-apicoverage/resourcetree/test_util.go
  tools/webhook-apicoverage/resourcetree/timetypenode.go
  tools/webhook-apicoverage/resourcetree/updateCoverage_test.go
  tools/webhook-apicoverage/tools/README.md
  tools/webhook-apicoverage/tools/tools.go
  tools/webhook-apicoverage/view/README.md
  tools/webhook-apicoverage/view/html_display.go
  tools/webhook-apicoverage/view/rule.go
  tools/webhook-apicoverage/webhook/README.md
  tools/webhook-apicoverage/webhook/apicoverage_recorder.go
  tools/webhook-apicoverage/webhook/webhook.go
Labels: approved, lgtm, size/XXL

#1342 Use string instead of ptr when defining flakyissue id
  tools/flaky-test-reporter/constants.go
  tools/flaky-test-reporter/github_issue.go
Labels: approved, lgtm, size/S

#1338 Using updated slackutil in knative/pkg
  Gopkg.lock
  tools/flaky-test-reporter/github_issue.go
  tools/flaky-test-reporter/json_reporter.go
  tools/flaky-test-reporter/main.go
  tools/flaky-test-reporter/slack_notification.go
  vendor/knative.dev/pkg/apis/condition_types.go
  vendor/knative.dev/pkg/logging/config.go
  vendor/knative.dev/pkg/metrics/config.go
  vendor/knative.dev/pkg/metrics/metricskey/constants.go
  vendor/knative.dev/pkg/metrics/metricskey/constants_eventing.go
  vendor/knative.dev/pkg/metrics/monitored_resources_eventing.go
  vendor/knative.dev/pkg/metrics/record.go
  vendor/knative.dev/pkg/metrics/stackdriver_exporter.go
  vendor/knative.dev/pkg/metrics/utils.go
  vendor/knative.dev/pkg/test/helpers/data.go
  vendor/knative.dev/pkg/test/helpers/error.go
  vendor/knative.dev/pkg/test/helpers/name.go
  vendor/knative.dev/pkg/test/helpers/run.go
  vendor/knative.dev/pkg/test/slackutil/http.go
  vendor/knative.dev/pkg/test/slackutil/message_read.go
  vendor/knative.dev/pkg/test/slackutil/message_write.go
  vendor/knative.dev/pkg/webhook/resource_admission_controller.go
  vendor/knative.dev/pkg/webhook/stats_reporter.go
  vendor/knative.dev/pkg/webhook/webhook.go
Labels: approved, lgtm, size/XL

#1346 Format markdown
  README.md
Labels: approved, lgtm, ok-to-test, size/XS

#1347 golang format tools
  tools/coverage/githubUtil/github_test.go
Labels: approved, lgtm, ok-to-test, size/XS

#1348 Convert all 'nil =='style to '== nil' style
  ci/prow/make_config.go
  shared/common/common.go
  shared/gcs/gcs.go
  shared/junit/junit.go
  shared/junit/junit_test.go
  shared/prow/prow.go
  shared/testgrid/testgrid.go
  shared/testgrid/testgrid_test.go
  shared/testgrid/yaml.go
  tools/flaky-test-reporter/config/config.go
  tools/flaky-test-reporter/github_issue.go
  tools/flaky-test-reporter/github_issue_test.go
  tools/flaky-test-reporter/json_reporter.go
  tools/flaky-test-reporter/jsonreport/jsonreport.go
  tools/flaky-test-reporter/main.go
  tools/flaky-test-reporter/result.go
  tools/flaky-test-reporter/slack_notification.go
  tools/flaky-test-retryer/github_commenter.go
  tools/flaky-test-retryer/github_commenter_test.go
  tools/flaky-test-retryer/log_parser.go
  tools/githubhelper/githubhelper.go
  tools/prow-auto-bumper/file.go
  tools/prow-auto-bumper/getversion_test.go
  tools/prow-auto-bumper/main.go
  tools/prow-auto-bumper/parser.go
  tools/prow-auto-bumper/pullrequest.go
Labels: approved, lgtm, size/L

#1350 Make test-infra more mac friendly.
  ci/prow/boskos/create_projects.sh
  ci/prow/boskos/set_permissions.sh
  ci/prow/run_job.sh
  devstats/postgre-docker-entrypoint.sh
  devstats/scripts/copy_devstats_binaries.sh
  devstats/scripts/copy_grafana_files.sh
  devstats/scripts/generate_repo_groups.sh
  devstats/scripts/import_affs.sh
  devstats/scripts/k8s_objects.sh
  devstats/scripts/setup_db.sh
  devstats/scripts/setup_mount.sh
  devstats/scripts/tags.sh
  devstats/updateConfig.sh
  images/backups/backup.sh
  scripts/e2e-tests.sh
  scripts/library.sh
  scripts/presubmit-tests.sh
  scripts/release.sh
  test/e2e-tests.sh
  test/presubmit-tests.sh
  test/unit/cleanup-tests.sh
  test/unit/e2e-custom-flag-tests.sh
  test/unit/library-tests.sh
  test/unit/presubmit-tests.sh
  test/unit/release-tests.sh
  test/unit/test-helper.sh
  tools/cleanup/cleanup-functions.sh
  tools/cleanup/cleanup.sh
  tools/monitoring/clearalerts/run_clear_alerts.sh
Labels: approved, lgtm, size/M

#1355 Remove prow jobs for Knative build
  ci/prow/config.yaml
  ci/prow/config_knative.yaml
  ci/testgrid/config.yaml
  scripts/library.sh
Labels: approved, lgtm, size/XL

#1354 Expose knative monitoring release URL
  scripts/library.sh
Labels: approved, lgtm, size/XS

#1353 Use var for regexp.mustCompile
  ci/prow/make_config.go
  ci/prow/testgrid_config.go
  tools/flaky-test-reporter/github_issue.go
  tools/flaky-test-retryer/github_commenter.go
  tools/latency/main.go
Labels: approved, lgtm, size/M

#1356 Subscribe pubsub also for unit-tests so they can get flaky-auto-retries
  ci/prow/config.yaml
  ci/prow/make_config.go
Labels: approved, lgtm, size/M

#1358 Remove some ununsed vars
  tools/monitoring/subscriber/subscriber.go
  tools/monitoring/subscriber/subscriber_test.go
Labels: approved, lgtm, size/S

#1359 Add instruction for verifying flaky-test-report locally + fix a small…
  tools/flaky-test-reporter/README.md
  tools/flaky-test-reporter/github_issue.go
  tools/flaky-test-reporter/main.go
Labels: approved, lgtm, size/M

#1360 Update flaky-test-retryer to use latest image
  tools/flaky-test-retryer/gke_deployment/retryer_service.yaml
Labels: approved, lgtm, size/XS

#1367 library.sh already sets GOPATH if necessary
  hack/update-codegen.sh
Labels: approved, lgtm, size/XS

#1365 Format markdown
  tools/flaky-test-reporter/README.md
Labels: approved, lgtm, ok-to-test, size/S

#1352 Include more information in cluster dump
  scripts/e2e-tests.sh
Labels: approved, lgtm, size/XS

#1369 Delete our copy of devstats
  devstats/Dockerfile
  devstats/Dockerfile.postgres
  devstats/INSTALL.md
  devstats/Kubernetes/batch-job-backfill.yaml
  devstats/Kubernetes/cli-home.yaml
  devstats/Kubernetes/cron-updates.yaml
  devstats/Kubernetes/env-variables.yaml
  devstats/Kubernetes/grafana-service.yaml
  devstats/Kubernetes/postgres-service.yaml
  devstats/Kubernetes/volumes.yaml
  devstats/Makefile
  devstats/README.md
  devstats/grafana/README.md
  devstats/grafana/provisioning/dashboards/dashboards.yaml
  devstats/grafana/provisioning/datasources/datasource.yaml
  devstats/pg_hba.conf
  devstats/postgre-docker-entrypoint.sh
  devstats/postgresql.conf
  devstats/projects.yaml
  devstats/scripts/copy_devstats_binaries.sh
  devstats/scripts/copy_grafana_files.sh
  devstats/scripts/generate_repo_groups.sh
  devstats/scripts/import_affs.sh
  devstats/scripts/k8s_objects.sh
  devstats/scripts/setup_db.sh
  devstats/scripts/setup_mount.sh
  devstats/scripts/tags.sh
  devstats/skip_dates.yaml
  devstats/updateConfig.sh
Labels: approved, lgtm, size/XXL

#1371 updated the monitoring config to be more lenient on test setup failures
  tools/monitoring/config/config.yaml
Labels: approved, lgtm, size/XS

#1373 Remove the dep-collector wrapper
  images/prow-tests/Dockerfile
  images/prow-tests/dep-collector
Labels: approved, lgtm, size/M

#1372 Add more debugging to githubhelper regarding the token
  tools/githubhelper/githubhelper.go
Labels: approved, lgtm, size/XS

#1370 Use authenticated API calls when listing changes on a GitHub PR
  ci/prow/config.yaml
  ci/prow/make_config.go
  scripts/presubmit-tests.sh
Labels: approved, lgtm, size/L

#1377 Sort release versions/tags properly so we can release 0.10 and beyond
  scripts/release.sh
Labels: approved, lgtm, size/XS

#1378 Add kail and update ko install in prow-tests
  images/prow-tests/Dockerfile
  scripts/presubmit-tests.sh
Labels: approved, lgtm, size/XS

#1381 Generate testgrid config for webhook API coverage jobs
  ci/prow/make_config.go
  ci/prow/testgrid_config.go
  ci/testgrid/config.yaml
Labels: approved, lgtm, size/S

#1380 Remove pointer usage when not needed
  tools/flaky-test-reporter/github_issue.go
  tools/flaky-test-reporter/github_issue_test.go
  tools/flaky-test-reporter/main.go
  tools/flaky-test-reporter/slack_notification.go
Labels: approved, lgtm, size/L

#1385 Remove the check of GOOGLE_APPLICATION_CREDENTIALS in make update-config for testgrid
  ci/testgrid/Makefile
Labels: approved, lgtm, size/XS

#1388 Amplify flaky test retryer noise, and use a fresh context every time
  tools/flaky-test-retryer/handler.go
  tools/flaky-test-retryer/log_parser.go
Labels: approved, lgtm, size/XS

#1389 More retryer logging for debugging
  tools/flaky-test-retryer/handler.go
  tools/monitoring/subscriber/subscriber.go
Labels: approved, lgtm, size/XS

#1391 Update retryer image with more verbose logging
  tools/flaky-test-retryer/gke_deployment/retryer_service.yaml
Labels: approved, lgtm, size/XS

#1392 user 5 workers for crier pubsub
  ci/prow/deployments/crier.yaml
Labels: approved, lgtm, size/XS

#1382 Add issue tracker for docs
  ci/prow/config.yaml
  ci/prow/periodic_config.go
Labels: approved, lgtm, size/L

#1387 Clean up the coverage code a bit
  tools/coverage/calc/base.go
  tools/coverage/calc/calc.go
  tools/coverage/calc/delta.go
  tools/coverage/calc/group.go
  tools/coverage/gcs/gcs.go
  tools/coverage/githubUtil/githubFiles.go
  tools/coverage/githubUtil/githubFiles_test.go
  tools/coverage/main.go
  tools/coverage/presubmit.go
Labels: approved, lgtm, size/L

#1394 update istio to 1.13 and remove 1.11
  ci/prow/config.yaml
  ci/prow/config_knative.yaml
  ci/prow/testgrid_config.go
  ci/testgrid/config.yaml
  shared/testgrid/testgrid.go
  tools/flaky-test-reporter/config/config.yaml
Labels: approved, lgtm, size/L

#1397 Fix flaky-test-reporter dryrun mode
  tools/flaky-test-reporter/github_issue.go
Labels: approved, lgtm, size/XS

#1396 Allow changing the project from CLI when deploying Gubernator
  ci/gubernator/Makefile
Labels: approved, lgtm, size/XS

#1400 Extend cleanup job timeout to 120 hours
  ci/prow/config.yaml
  ci/prow/periodic_config.go
Labels: approved, lgtm, size/XS

#1401 Make Prow config more easily configurable from CLI
  ci/prow/Makefile
Labels: approved, lgtm, size/M

#1402 some more coverage cleanup
  tools/coverage/gcs/gcs.go
  tools/coverage/gcs/gcsPostsubmit.go
  tools/coverage/gcs/gcsPostsubmit_test.go
  tools/coverage/gcs/gcsPresubmit.go
  tools/coverage/main.go
  tools/coverage/presubmit.go
  tools/coverage/presubmit_test.go
Labels: approved, lgtm, size/L

#1404 Add pubsub labels to monitor tooling jobs
  ci/prow/config.yaml
  ci/prow/issue_tracker_config.go
  ci/prow/periodic_config.go
Labels: approved, lgtm, size/L

#1390 Dump all Kubernetes resources in dedicated file
  scripts/e2e-tests.sh
Labels: approved, lgtm, size/M

#1406 Make knative-dev a viewer of Boskos projects
  ci/prow/boskos/set_permissions.sh
Labels: approved, lgtm, size/M

#1405 A few improvements of the script to create new Boskos projects
  ci/prow/boskos/create_projects.sh
Labels: approved, lgtm, size/S

#1363 Updated service account roles in boskos projects
  ci/prow/boskos/set_permissions.sh
Labels: approved, lgtm, size/S

#1276 google/knative-gcp mimics all repo level settings in knative
  ci/prow/config.yaml
  ci/prow/templates/prow_config_header.yaml
Labels: approved, lgtm, size/XS

#1408 Remove srinivahegde86 as owner
  OWNERS_ALIASES
Labels: approved, lgtm, size/XS

#1407 Update config to alert on more jobs
  tools/monitoring/config/config.yaml
Labels: approved, lgtm, size/S

#1410 Parameterize Prow host and TestGrid bucket
  ci/prow/make_config.go
  ci/prow/templates/prow_config_header.yaml
  ci/prow/templates/testgrid_config_header.yaml
  ci/prow/testgrid_config.go
Labels: approved, lgtm, size/M

#1411 Rename -webhookAPICoverageScript to keep flag names consistent
  ci/prow/make_config.go
Labels: approved, lgtm, size/XS

#1412 Auto generate repos for tide based on config
  ci/prow/config.yaml
  ci/prow/make_config.go
  ci/prow/templates/prow_config_header.yaml
Labels: approved, lgtm, size/L

#1409 Update OWNERS_ALIASES for Productivity WG
  OWNERS_ALIASES
Labels: approved, lgtm, size/XS

#1414 Fix issue tracker jobs
  ci/prow/config.yaml
  ci/prow/issue_tracker_config.go
Labels: approved, lgtm, size/M

#1415 golang format tools
  ci/prow/make_config.go
Labels: approved, lgtm, ok-to-test, size/S

#1416 Allow not generating maintenance jobs in Prow config
  ci/prow/make_config.go
Labels: approved, lgtm, size/S

#1418 Fail script if application default credentials are not set
  ci/prow/boskos/set_permissions.sh
Labels: approved, lgtm, size/XS

#1417 Fix creating boskos projects from scratch
  ci/prow/boskos/create_projects.sh
Labels: approved, lgtm, size/XS

#1419 Parameterize the Prow log bucket when creating the config
  ci/prow/Makefile
Labels: approved, lgtm, size/XS

#1420 Parameterize the registry of docker images used in Prow config
  ci/prow/Makefile
  ci/prow/make_config.go
  ci/prow/periodic_config.go
Labels: approved, lgtm, size/S
