Repository knative/test-infra, pull requests merged in 2019-07, with the labels that each got.

#1085 golang format tools
  tools/flaky-test-reporter/config/config.go
  tools/monitoring/config/config.go
Labels: approved, lgtm, ok-to-test, size/XS

#1088 Boskos project creation scripts.
  ci/prow/boskos/create_projects
  ci/prow/boskos/permissions.sh
  ci/prow/boskos/project_create
  ci/prow_setup.md
Labels: approved, lgtm, size/M

#1089 Add Boskos projects 51-70 and increase janitors to 35.
  ci/prow/boskos/config.yaml
  ci/prow/boskos/resources.yaml
Labels: approved, lgtm, size/S

#1086 Format markdown
  tools/flaky-test-reporter/README.md
Labels: approved, lgtm, ok-to-test, size/XS

#1091 add Initialize() func to jsonreport
  tools/flaky-test-reporter/jsonreport/jsonreport.go
Labels: approved, lgtm, needs-ok-to-test, size/XS

#1083 added clear-alerts image
  images/clear-test-infra-alerts/Dockerfile
  images/clear-test-infra-alerts/Makefile
  tools/monitoring/alert/alert.go
  tools/monitoring/clearalerts/Makefile
  tools/monitoring/clearalerts/main.go
  tools/monitoring/config/config.go
  tools/monitoring/mysql/database.go
Labels: approved, lgtm, size/L

#1087 Update boskos readme to include request for more cpu quota
  ci/prow_setup.md
Labels: approved, lgtm, size/XS

#1094 Set readonly permission for mounted ssh key
  ci/prow/config.yaml
  ci/prow/make_config.go
  ci/prow/periodic_config.go
Labels: approved, lgtm, size/S

#1095 Fixed the build url issue in monitoring
  shared/gcs/gcs.go
  shared/gcs/gcs_test.go
  tools/monitoring/alert/alert.go
Labels: approved, lgtm, size/M

#1092 Refactor scripts for creating new Boskos projects
  ci/prow/boskos/README.md
  ci/prow/boskos/create_projects.sh
  ci/prow/boskos/project_create
  ci/prow/boskos/set_permissions.sh
  ci/prow_setup.md
Labels: approved, lgtm, size/M

#1097 Format markdown
  ci/prow_setup.md
Labels: approved, lgtm, ok-to-test, size/S

#1096 link to the gcs console link in the test-infra monitoring email
  shared/gcs/gcs.go
  shared/gcs/gcs_test.go
  tools/monitoring/alert/report.go
  tools/monitoring/alert/report_test.go
Labels: approved, lgtm, size/L

#1098 Update section about expanding Boskos pool
  ci/prow_setup.md
Labels: approved, lgtm, size/S

#1100 Setup GitHub Pages for displaying oncall rotation
  docs/README.md
  docs/_config.yml
  test/markdown-lint-config.rc
  tools/oncall/oncall.html
Labels: approved, lgtm, size/M

#1106 Fixing release branch periodic jobs config
  ci/prow/config.yaml
  ci/prow/make_config.go
  ci/prow/periodic_config.go
Labels: approved, lgtm, size/M

#1107 Fix formatting of repo names with hyphen
  scripts/library.sh
  test/unit/library-tests.sh
Labels: approved, lgtm, size/S

#1110 GetArtifacts should return all files instead of only direct children …
  shared/prow/prow.go
Labels: approved, lgtm, size/XS

#1111 Format markdown
  ci/prow_setup.md
Labels: approved, lgtm, ok-to-test, size/S

#1109 Make restore working Prow config easier
  ci/prow/Makefile
  ci/prow/config.yaml
  ci/prow/templates/prow_config_header.yaml
Labels: approved, lgtm, size/S

#1113 Fixing coverage job path_alias to let them pass
  ci/prow/config.yaml
  ci/prow/make_config.go
  ci/prow/periodic_config.go
Labels: approved, lgtm, size/M

#1115 Remove map[config.yaml] from stored old config file
  ci/prow/Makefile
Labels: approved, lgtm, size/XS

#1114 Enhance the test-infra status page
  docs/README.md
  docs/README.txt
  docs/cors-json-file.json
  test/markdown-lint-config.rc
  test/presubmit-tests.sh
  tools/oncall/oncall.html
Labels: approved, lgtm, size/L

#1084 added the clear-alerts prow configs
  ci/prow/config.yaml
  ci/prow/make_config.go
  ci/prow/periodic_config.go
Labels: approved, lgtm, size/M

#1118 Add new method to parse default monitoring config
  tools/monitoring/alert/alert.go
  tools/monitoring/clearalerts/main.go
  tools/monitoring/config/config.go
  tools/monitoring/log_parser/log_parser.go
Labels: approved, lgtm, size/M

#1105 refactor jsonreport to better support multi-repo searching
  tools/flaky-test-reporter/jsonreport/jsonreport.go
Labels: approved, lgtm, ok-to-test, size/M

#1120 fix prow config by removing extra 'periodic' from config
  ci/prow/config.yaml
  ci/prow/periodic_config.go
Labels: approved, lgtm, size/XS

#1119 Use parsedefaultconfig method in monitoring/main.go
  tools/monitoring/main.go
Labels: approved, lgtm, size/S

#1116 Also make testgrid URL one-line
  docs/README.md
Labels: approved, lgtm, size/XS

#1121 Update protobuf dep to latest(1.3.1)
  Gopkg.lock
  vendor/github.com/golang/protobuf/proto/decode.go
  vendor/github.com/golang/protobuf/proto/deprecated.go
  vendor/github.com/golang/protobuf/proto/equal.go
  vendor/github.com/golang/protobuf/proto/extensions.go
  vendor/github.com/golang/protobuf/proto/lib.go
  vendor/github.com/golang/protobuf/proto/message_set.go
  vendor/github.com/golang/protobuf/proto/pointer_reflect.go
  vendor/github.com/golang/protobuf/proto/pointer_unsafe.go
  vendor/github.com/golang/protobuf/proto/properties.go
  vendor/github.com/golang/protobuf/proto/table_marshal.go
  vendor/github.com/golang/protobuf/proto/table_unmarshal.go
  vendor/github.com/golang/protobuf/protoc-gen-go/descriptor/descriptor.pb.go
  vendor/github.com/golang/protobuf/ptypes/any/any.pb.go
  vendor/github.com/golang/protobuf/ptypes/duration.go
  vendor/github.com/golang/protobuf/ptypes/duration/duration.pb.go
  vendor/github.com/golang/protobuf/ptypes/empty/empty.pb.go
  vendor/github.com/golang/protobuf/ptypes/timestamp.go
  vendor/github.com/golang/protobuf/ptypes/timestamp/timestamp.pb.go
Labels: approved, lgtm, size/XXL

#1103 Add flaky-test-retryer skeleton
  tools/flaky-test-retryer/github_commenter.go
  tools/flaky-test-retryer/handler.go
  tools/flaky-test-retryer/log_parser.go
  tools/flaky-test-retryer/main.go
Labels: approved, lgtm, ok-to-test, size/L

#1123 add monitoring labels to ci, presubmit jobs
  ci/prow/config.yaml
  ci/prow/make_config.go
  ci/prow/periodic_config.go
Labels: approved, lgtm, size/L

#1127 jsonreport: fix absolute/relative path discrepancy
  tools/flaky-test-reporter/jsonreport/jsonreport.go
Labels: approved, lgtm, ok-to-test, size/XS

#1125 support adding error rates as metrics in perf tests
  shared/loadgenerator/loadgenerator.go
  shared/performance/performance.go
Labels: approved, lgtm, size/M

#1126 add flaky-test-reporter's config.yaml to its image
  images/flaky-test-reporter/Dockerfile
Labels: approved, lgtm, ok-to-test, size/XS

#1128 Fix flaky test reporter by using absolute path instead of relative pa…
  images/flaky-test-reporter/Dockerfile
  tools/flaky-test-reporter/main.go
Labels: approved, lgtm, size/XS

#1124 serving works with vanity URL knative.dev
  ci/prow/config.yaml
  ci/prow/config_knative.yaml
  ci/prow/make_config.go
  ci/prow/templates/prow_periodic_custom_job.yaml
  ci/prow/templates/prow_periodic_test_job.yaml
  ci/prow/templates/prow_postsubmit_gocoverage_job.yaml
  ci/prow/templates/prow_presubmit_gocoverate_job.yaml
  ci/prow/templates/prow_presubmit_job.yaml
Labels: approved, lgtm, size/L

#1131 Add optional presubmit jobs for different ingress
  ci/prow/config.yaml
  ci/prow/config_knative.yaml
Labels: approved, lgtm, size/L

#1135 Update prow config for serving-operator to use knative.dev
  ci/prow/config.yaml
  ci/prow/config_knative.yaml
Labels: approved, lgtm, size/S

#1139 Fix mktemp in OS X
  scripts/e2e-tests.sh
Labels: approved, lgtm, size/XS

#1141 Update monitoring email to knative-productivity-dev
  tools/monitoring/main.go
Labels: approved, lgtm, size/XS

#1130 flaky-test-retryer: add all log parsing functionality
  tools/flaky-test-reporter/result.go
  tools/flaky-test-retryer/github_commenter.go
  tools/flaky-test-retryer/handler.go
  tools/flaky-test-retryer/log_parser.go
  tools/flaky-test-retryer/main.go
Labels: approved, lgtm, ok-to-test, size/L

#1142 Retry publishing to GitHub 3 times in case of error.
  scripts/release.sh
  test/unit/release-tests.sh
Labels: approved, lgtm, size/M

#1144 Prow auto updater: turn warning into more descriptive messages
  tools/prow-auto-bumper/file.go
  tools/prow-auto-bumper/main.go
  tools/prow-auto-bumper/pullrequest.go
Labels: approved, lgtm, size/M

#1140 Allow setting the org name in the release script.
  ci/prow/config.yaml
  ci/prow/config_knative.yaml
  ci/prow/make_config.go
  ci/prow/periodic_config.go
  scripts/release.sh
Labels: approved, lgtm, size/M

#1145 clean up the log
  tools/monitoring/alert/alert.go
Labels: approved, lgtm, size/XS

#1143 retryer: add log cache
  tools/flaky-test-retryer/handler.go
  tools/flaky-test-retryer/log_parser.go
Labels: approved, lgtm, ok-to-test, size/L

#1147 [monitoring] Add a failure type that happens recently.
  tools/monitoring/config/config.yaml
Labels: approved, lgtm, size/S

#1129 Move boskos to different namespace
  ci/prow/Makefile
  ci/prow/boskos/config.yaml
  ci/prow/boskos/config_start.yaml
  ci/prow/config_start.yaml
Labels: approved, lgtm, size/M

#1155 Revert "Move boskos to different namespace"
  ci/prow/Makefile
  ci/prow/boskos/config.yaml
  ci/prow/boskos/config_start.yaml
  ci/prow/config_start.yaml
Labels: approved, lgtm, size/M

#1152 updated monitoring README
  tools/monitoring/README.md
  tools/monitoring/clearalerts/run_clear_alerts.sh
  tools/monitoring/systems.png
Labels: approved, lgtm, size/M

#1153 removed redundant test and unneeded code
  tools/monitoring/Makefile
  tools/monitoring/clearalerts/main.go
  tools/monitoring/main.go
Labels: approved, lgtm, size/M

#1151 golang format tools
  tools/flaky-test-retryer/log_parser.go
Labels: approved, lgtm, ok-to-test, size/XS

#1146 Properly report other errors in build tests
  scripts/library.sh
  scripts/presubmit-tests.sh
Labels: approved, lgtm, size/M

#1157 Fix the mess in the /docs directory
  docs/README.md
  docs/README.txt
  docs/index.html
Labels: approved, lgtm, size/L

#1159 Add monitoring for DNS flakiness
  tools/monitoring/config/config.yaml
Labels: approved, lgtm, size/XS

#1162 Removing istio 1.0 related jobs
  ci/prow/config.yaml
  ci/prow/config_knative.yaml
  ci/prow/testgrid_config.go
  ci/testgrid/config.yaml
  shared/testgrid/testgrid.go
  tools/flaky-test-reporter/config.yaml
Labels: approved, lgtm, size/L

#1158 Report data races in go tests
  scripts/library.sh
  scripts/presubmit-tests.sh
Labels: approved, lgtm, size/M

#1163 Format markdown
  docs/README.md
  tools/monitoring/README.md
Labels: approved, lgtm, ok-to-test, size/M

#1156 Add instructions on how to setup automated releases for a repo
  ci/README.md
  ci/manual_release.md
  ci/release_setup.md
Labels: approved, lgtm, size/M

#1170 Dump logs from all containers inside a pod
  scripts/library.sh
Labels: approved, lgtm, size/XS

#1171 move -race option to go_test_e2e and default_unit_test_runner
  scripts/e2e-tests.sh
  scripts/library.sh
  scripts/presubmit-tests.sh
Labels: approved, lgtm, size/XS

#1172 Remove GCS URL hack
  tools/monitoring/alert/alert.go
  tools/monitoring/alert/alert_test.go
Labels: approved, lgtm, size/M

#1173 Store the build-log url instead of artifacts url
  tools/monitoring/alert/alert.go
  tools/monitoring/alert/report.go
  tools/monitoring/alert/report_test.go
Labels: approved, lgtm, size/S

#1150 add prow job for running Knative-Serving e2e against Gloo
  ci/prow/config.yaml
  ci/prow/config_knative.yaml
  ci/prow/testgrid_config.go
  ci/testgrid/config.yaml
  shared/testgrid/testgrid.go
Labels: approved, lgtm, ok-to-test, size/M

#1176 Update kubekins base image version
  images/prow-tests/Dockerfile
Labels: approved, lgtm, size/XS

#1177 Wait for Boskos instead of fail
  scripts/e2e-tests.sh
Labels: approved, lgtm, size/XS

#1174 Break down each deployment to it's own config file
  ci/prow/Makefile
  ci/prow/README.md
  ci/prow/boskos/config.yaml
  ci/prow/boskos/deployments/boskos.yaml
  ci/prow/boskos/deployments/janitor.yaml
  ci/prow/boskos/deployments/persistentvolume.yaml
  ci/prow/boskos/deployments/reaper.yaml
  ci/prow/boskos/deployments/statefulset.yaml
  ci/prow/cluster.yaml
  ci/prow/deployments/cpu_limitrange.yaml
  ci/prow/deployments/crds.yaml
  ci/prow/deployments/crier.yaml
  ci/prow/deployments/deck.yaml
  ci/prow/deployments/hook.yaml
  ci/prow/deployments/horologium.yaml
  ci/prow/deployments/ingress.yaml
  ci/prow/deployments/memory_limitrange.yaml
  ci/prow/deployments/plank.yaml
  ci/prow/deployments/sinker.yaml
  ci/prow/deployments/tide.yaml
  ci/prow_setup.md
Labels: approved, lgtm, size/XXL

#1165 flaky-test-retryer: add github integration
  shared/ghutil/client.go
  shared/ghutil/fakeghutil/fakeghutil.go
  shared/ghutil/issue.go
  tools/flaky-test-retryer/github_commenter.go
  tools/flaky-test-retryer/github_commenter_test.go
  tools/flaky-test-retryer/handler.go
  tools/flaky-test-retryer/main.go
Labels: approved, lgtm, ok-to-test, size/L

#1194 Small improvements and issue fixes
  tools/flaky-test-reporter/github_issue.go
  tools/flaky-test-reporter/github_issue_test.go
  tools/flaky-test-reporter/json_reporter.go
  tools/flaky-test-reporter/main.go
  tools/flaky-test-reporter/slack_notification.go
Labels: approved, lgtm, size/L

#1169 More documentation on (automated) releases.
  ci/manual_release.md
  ci/release_setup.md
Labels: approved, lgtm, size/L

#1197 Minor fixes to devstats documentation
  devstats/INSTALL.md
  devstats/Makefile
Labels: approved, lgtm, size/S

#1178 flaky-test-retryer: add build, deployment files
  images/flaky-test-retryer/Dockerfile
  images/flaky-test-retryer/Makefile
  images/flaky-test-retryer/README.md
  tools/flaky-test-reporter/gke_deployment/retryer_service.yaml
  tools/flaky-test-retryer/Makefile
Labels: approved, lgtm, ok-to-test, size/L

#450 document how to run pre-submit coverage diff locally
  tools/coverage/docs/local_presubmit.md
  tools/coverage/local_presubmit.sh
Labels: approved, lgtm, size/S

#1201 Format markdown
  ci/manual_release.md
  ci/prow_setup.md
  ci/release_setup.md
  images/flaky-test-retryer/README.md
  tools/coverage/docs/local_presubmit.md
Labels: approved, lgtm, ok-to-test, size/L

#1202 golang format tools
  tools/flaky-test-retryer/github_commenter.go
  tools/flaky-test-retryer/github_commenter_test.go
Labels: approved, lgtm, ok-to-test, size/XS

#1078 add doc for code coverage tool
  tools/coverage/README.md
  tools/coverage/design.md
  tools/coverage/design.svg
Labels: approved, lgtm, size/L

#1203 Warn about using an auto-scaled Prow cluster
  ci/prow_setup.md
Labels: approved, lgtm, size/XS

#1205 move retryer yaml to correct directory
  tools/flaky-test-retryer/gke_deployment/retryer_service.yaml
Labels: approved, lgtm, ok-to-test, size/XS

#1206 Escape `<` and `>` in custom junit results
  scripts/library.sh
Labels: approved, lgtm, size/XS

#1209 Format markdown
  ci/prow_setup.md
  tools/coverage/README.md
  tools/coverage/design.md
Labels: approved, lgtm, ok-to-test, size/M

#1210 golang format tools
  shared/prometheus/prometheus_test.go
  shared/testgrid/yaml.go
  tools/coverage/gcs/gcs.go
  tools/webhook-apicoverage/webhook/apicoverage_recorder.go
Labels: approved, lgtm, ok-to-test, size/S

#1211 fix temp repo path in retryer Dockerfile
  images/flaky-test-retryer/Dockerfile
Labels: approved, lgtm, needs-ok-to-test, size/XS

#1207 Avoid runtime error when Flaky test reporter failed collecting result for one job
  tools/flaky-test-reporter/main.go
Labels: approved, lgtm, size/XS

#1212 retryer: add service to YAML
  tools/flaky-test-retryer/gke_deployment/retryer_service.yaml
Labels: approved, lgtm, needs-ok-to-test, size/S

#1215 Add optional Gloo test job for serving
  ci/prow/config.yaml
  ci/prow/config_knative.yaml
Labels: approved, lgtm, size/M

#1216 retryer: update pubsub topic, apply fixes to deployment
  tools/flaky-test-retryer/gke_deployment/retryer_service.yaml
  tools/flaky-test-retryer/main.go
Labels: approved, lgtm, ok-to-test, size/XS

#1217 Move to using 4 nodes for perf tests as we are now using bigger machines
  ci/prow/config.yaml
  ci/prow/periodic_config.go
Labels: approved, lgtm, size/S

#1218 make the subscriber client reusable
  tools/flaky-test-retryer/handler.go
  tools/monitoring/alert/alert.go
  tools/monitoring/main.go
  tools/monitoring/subscriber/subscriber.go
Labels: approved, lgtm, size/M

#1219 flaky-test-retryer: use unique subscriber
  tools/flaky-test-retryer/handler.go
  tools/flaky-test-retryer/main.go
Labels: approved, lgtm, ok-to-test, size/XS
