Repository knative/test-infra, pull requests merged in 2019-10, with the labels that each got.

#1422 Format markdown
  images/prow-tests-go112/README.md
  images/prow-tests/README.md
Labels: approved, lgtm, ok-to-test, size/XS

#1423 Fix ci/prow/Makefile
  ci/prow/Makefile
  test/presubmit-tests.sh
Labels: approved, lgtm, size/XS

#1427 Parameterize the TestGrid GCS bucket in Prow config
  ci/prow/Makefile
Labels: approved, lgtm, size/XS

#1429 Update and add missing roles to sinker initial config
  ci/prow/config_start.yaml
Labels: approved, lgtm, size/M

#1426 Add missing roles to boskos initial config
  ci/prow/config_start.yaml
Labels: approved, lgtm, size/M

#1425 [cov] Remove necessity of github connection
  tools/coverage/calc/delta.go
  tools/coverage/githubUtil/githubPr/githubRepo.go
  tools/coverage/main.go
  tools/coverage/presubmit.go
  tools/coverage/presubmit_test.go
Labels: approved, lgtm, size/L

#1431 Explain the source of the Prow config
  ci/prow/config_start.yaml
Labels: approved, lgtm, size/XS

#1428 Move CI/CD Makefiles configuration to a single place
  ci/Makefile.base
  ci/prow/Makefile
  ci/testgrid/Makefile
Labels: approved, lgtm, size/L

#1430 Merge Boskos initial setup into main initial setup
  ci/prow/boskos/README.md
  ci/prow/boskos/config_start.yaml
  ci/prow/config_start.yaml
Labels: approved, lgtm, size/M

#1434 Merge Prow and Boskos deployments
  ci/Makefile.base
  ci/prow/Makefile
  ci/prow/README.md
  ci/prow/boskos/README.md
  ci/prow/boskos_resources.yaml
  ci/prow/create_boskos_projects.sh
  ci/prow/deployments/boskos.yaml
  ci/prow/deployments/boskos_janitor.yaml
  ci/prow/deployments/boskos_metrics.yaml
  ci/prow/deployments/boskos_reaper.yaml
  ci/prow/deployments/boskos_statefulset.yaml
  ci/prow/deployments/boskos_volumes.yaml
  ci/prow/set_boskos_permissions.sh
Labels: approved, lgtm, size/M

#1433 Update and add missing roles to deck initial config
  ci/prow/config_start.yaml
Labels: approved, lgtm, size/M

#1435 Update and add missing roles to plank initial config
  ci/prow/config_start.yaml
Labels: approved, lgtm, size/M

#1436 Add missing separator to config_start.yaml
  ci/prow/config_start.yaml
Labels: approved, lgtm, size/XS

#1437 Format markdown
  ci/prow/README.md
Labels: approved, lgtm, needs-ok-to-test, size/XS

#1440 Use a single statement to generate issue tracker jobs
  ci/prow/issue_tracker_config.go
Labels: approved, lgtm, size/S

#1439 Install liche with module support on
  images/prow-tests/Dockerfile
Labels: approved, lgtm, size/XS

#1441 Update Prow setup document
  ci/prow_setup.md
Labels: approved, lgtm, size/L

#1443 Fix boskos config path
  ci/prow/config.yaml
  ci/prow/periodic_config.go
  test/unit/cleanup-tests.sh
  tools/cleanup/README.md
Labels: approved, lgtm, size/S

#1444 Retire eventing perf test
  ci/prow/config.yaml
  ci/prow/config_knative.yaml
  ci/testgrid/config.yaml
Labels: approved, lgtm, size/M

#1438 Parameterize Boskos projects creation/setup
  ci/prow/create_boskos_projects.sh
  ci/prow/set_boskos_permissions.sh
Labels: approved, lgtm, size/S

#1446 added a no-cache version in image Makefile
  images/prow-tests/README.md
  shared/Makefile.simple-image
Labels: approved, lgtm, size/S

#1448 coverage tool uses existing sets rather than inventing another one
  tools/coverage/calc/group.go
  tools/coverage/githubUtil/githubFiles_test.go
  tools/coverage/test/commons.go
Labels: approved, lgtm, size/M

#1453 Explicitly pass flags to serving E2E tests
  ci/prow/config.yaml
  ci/prow/config_knative.yaml
Labels: approved, lgtm, size/S

#1455 Configure knative/website for tide
  ci/prow/config.yaml
  ci/prow/config_knative.yaml
Labels: approved, lgtm, size/XS

#1457 Revert "Pass flags as there is no default values anymore. (#1453)"
  ci/prow/config.yaml
  ci/prow/config_knative.yaml
Labels: approved, lgtm, size/S

#1458 Allow using cleanup.sh on arbitrary projects and GCR
  test/unit/cleanup-tests.sh
  tools/cleanup/README.md
  tools/cleanup/cleanup-functions.sh
  tools/cleanup/cleanup.sh
Labels: approved, lgtm, size/L

#1462 Fix push_latest for all images
  shared/Makefile.simple-image
Labels: approved, lgtm, size/XS

#1463 Add CI jobs for knative 0.9
  ci/prow/config.yaml
  ci/prow/config_knative.yaml
  ci/testgrid/config.yaml
Labels: approved, lgtm, size/L

#1466 Fix cluster deletion in cleanup-functions.sh
  tools/cleanup/cleanup-functions.sh
Labels: approved, lgtm, size/S

#1467 Fix examples in cleanup's README.md
  tools/cleanup/README.md
Labels: approved, lgtm, size/XS

#1468 Fix create_boskos_project.sh
  ci/prow/create_boskos_projects.sh
Labels: approved, lgtm, size/S

#1470 Add lenses config for spyglass
  ci/prow/config.yaml
  ci/prow/templates/prow_config_header.yaml
Labels: approved, lgtm, size/M

#1474 Remove CI flows for Knative 0.4 and 0.5
  ci/prow/config.yaml
  ci/prow/config_knative.yaml
  ci/prow/testgrid.yaml
Labels: approved, lgtm, size/L

#1473 Add regex to match boskos error to highlight on spyglass
  ci/prow/config.yaml
  ci/prow/templates/prow_config_header.yaml
Labels: approved, lgtm, size/S

#1472 Add configurations for the staging Prow cluster
  ci/prow/Makefile
  ci/prow/make_config.go
  ci/prow/staging/Makefile
  ci/prow/staging/README.md
  ci/prow/staging/boskos_resources.yaml
  ci/prow/staging/config.yaml
  ci/prow/staging/config_staging.yaml
  ci/prow/staging/plugins.yaml
  ci/prow/staging/testgrid.yaml
  ci/prow/testgrid_config.go
Labels: approved, lgtm, size/XL

#1475 Allow passing arguments to specific presubmit test
  scripts/README.md
  scripts/presubmit-tests.sh
  test/presubmit-tests.sh
Labels: approved, lgtm, size/S

#1477 Update Prow staging config
  ci/prow/staging/config.yaml
  ci/prow/staging/config_staging.yaml
Labels: approved, lgtm, size/L

#1478 Add performance-tests.sh
  Gopkg.lock
  Gopkg.toml
  scripts/README.md
  scripts/performance-tests.sh
  vendor/google.golang.org/api/container/v1beta1/container-gen.go
  vendor/knative.dev/pkg/test/gke/addon.go
  vendor/knative.dev/pkg/test/gke/client.go
  vendor/knative.dev/pkg/test/gke/location.go
  vendor/knative.dev/pkg/test/gke/request.go
  vendor/knative.dev/pkg/test/gke/wait.go
  vendor/knative.dev/pkg/test/helpers/data.go
  vendor/knative.dev/pkg/test/helpers/dryrun.go
  vendor/knative.dev/pkg/test/helpers/name.go
  vendor/knative.dev/pkg/testutils/clustermanager/perf-tests/main.go
  vendor/knative.dev/pkg/testutils/clustermanager/perf-tests/pkg/benchmark.go
  vendor/knative.dev/pkg/testutils/clustermanager/perf-tests/pkg/cluster.go
Labels: approved, lgtm, size/XXL

#1480 Fix typos in Prow bumper commit message
  tools/prow-auto-bumper/pullrequest.go
Labels: approved, lgtm, size/XS

#1483 Also use go 1.13 for serving perf jobs
  ci/prow/config.yaml
  ci/prow/periodic_config.go
Labels: approved, lgtm, size/S

#1482 Add pj-on-kind.sh script for running ProwJobs locally.
  .gitignore
  ci/prow/pj-on-kind.sh
Labels: approved, lgtm, size/M

#1485 Use Go 1.13 Prow image for serving operator
  ci/prow/config.yaml
  ci/prow/config_knative.yaml
Labels: approved, lgtm, size/L

#1486 Format markdown
  ci/prow/README.md
  ci/prow/staging/README.md
  ci/prow_setup.md
  images/prow-tests/README.md
  scripts/README.md
  tools/cleanup/README.md
Labels: approved, lgtm, ok-to-test, size/L

#1489 Fixes to performance-tests.sh
  scripts/performance-tests.sh
Labels: approved, lgtm, size/XS

#1488 Add new test job for serving operator
  ci/prow/config.yaml
  ci/prow/config_knative.yaml
  ci/prow/testgrid.yaml
  ci/prow/testgrid_config.go
Labels: approved, lgtm, size/L

#1490 Fix custom optional presubmits for Serving
  ci/prow/config.yaml
  ci/prow/config_knative.yaml
Labels: approved, lgtm, size/L

#1484 Add post submit job for performance test cluster reconciliation
  ci/prow/config.yaml
  ci/prow/config_knative.yaml
  ci/prow/make_config.go
  ci/prow/perf_config.go
  ci/prow/periodic_config.go
  ci/prow/postsubmit_config.go
  ci/prow/presubmit_config.go
  ci/prow/templates/prow_postsubmit_gocoverage_job.yaml
  ci/prow/templates/prow_postsubmit_perf_job.yaml
  ci/prow/testgrid.yaml
Labels: approved, lgtm, size/XXL

#1491 Fixes to the perf test script
  ci/prow/config.yaml
  ci/prow/perf_config.go
  scripts/performance-tests.sh
Labels: approved, lgtm, size/S

#1493 Configure knative/community for tide
  ci/prow/config.yaml
  ci/prow/config_knative.yaml
  ci/prow/plugins.yaml
Labels: approved, lgtm, size/M

#1497 Fix spelling errors
  ci/prow/perf_config.go
Labels: approved, lgtm, ok-to-test, size/XS

#1499 use the version tag for the monitoring image
  tools/monitoring/gke_deployment/monitoring_service.yaml
Labels: approved, lgtm, size/XS

#1500 Remove latency tool and related configs
  README.md
  ci/prow/config.yaml
  ci/prow/config_knative.yaml
  ci/prow/make_config.go
  ci/prow/periodic_config.go
  ci/prow/testgrid.yaml
  ci/prow/testgrid_config.go
  images/latency/Dockerfile
  images/latency/Makefile
  tools/latency/Makefile
  tools/latency/main.go
Labels: approved, lgtm, size/XL

#1481 Explicitly pass flags to serving E2E tests
  ci/prow/config.yaml
  ci/prow/config_knative.yaml
Labels: approved, lgtm, size/S

#1502 Format markdown
  README.md
Labels: approved, lgtm, ok-to-test, size/XS

#1501 [monitoring] ignore build logs of success jobs
  tools/monitoring/alert/alert.go
Labels: approved, lgtm, size/XS

#1504 Update monitoring image
  tools/monitoring/gke_deployment/monitoring_service.yaml
Labels: approved, lgtm, size/XS

#1508 retry cluster creation if nodes not fully up
  scripts/e2e-tests.sh
Labels: approved, lgtm, size/XS

#1507 Add new CI jobs for 0.10
  ci/prow/config.yaml
  ci/prow/config_knative.yaml
  ci/prow/testgrid.yaml
Labels: approved, lgtm, size/L

#1503 [monitoring] update build and deployment doc of monitoring tool
  tools/monitoring/README.md
Labels: approved, lgtm, size/S

#1510 Add new test job for eventing operator
  ci/prow/config.yaml
  ci/prow/config_knative.yaml
  ci/prow/testgrid.yaml
Labels: approved, lgtm, size/M
