Repository knative/test-infra, pull requests merged in 2019-01, with the labels that each got.

#354 Redirect stderr to stdout
  scripts/library.sh
Labels: approved, lgtm, size/XS

#356 Also update E2E test return value on failures
  scripts/e2e-tests.sh
Labels: approved, lgtm, size/M

#358 Add save as json option to load generator results
  shared/loadgenerator/loadgenerator.go
  shared/loadgenerator/loadgenerator_test.go
Labels: approved, lgtm, size/M

#360 raise coverage threshold for knative/build to 80%
  ci/prow/config.yaml
Labels: approved, lgtm, size/XS

#361 Bump kubekins to v20190103-edc7696cc-master
  images/prow-tests/Dockerfile
Labels: approved, lgtm, size/XS

#366 Ignore .gitignore, .gitattributes and AUTHORS on presubmit
  scripts/presubmit-tests.sh
Labels: approved, lgtm, size/XS

#363 Remove build from serving release
  scripts/library.sh
Labels: approved, lgtm, size/XS

#369 Drop "github.com/knative/<repo_name>" from test names
  scripts/library.sh
Labels: approved, lgtm, size/XS

#364 Update default build/unit test runners.
  scripts/README.md
  scripts/presubmit-tests.sh
  test/presubmit-tests.sh
  test/unit/presubmit-custom-runners-tests.sh
  test/unit/presubmit-full-custom-integration-tests.sh
  test/unit/presubmit-integration-tests-common.sh
  test/unit/presubmit-partial-custom-integration-tests.sh
  test/unit/presubmit-tests.sh
  test/unit/release-tests.sh
  test/unit/test-helper.sh
Labels: approved, lgtm, size/XL

#370 Don't fetch all remotes when releasing
  scripts/release.sh
Labels: approved, lgtm, size/S

#373 Don't lint markdown files in /vendor
  scripts/presubmit-tests.sh
  tools/dep-collector/README.md
Labels: approved, lgtm, size/S

#375 Properly find e2e tests to run in the default runner
  scripts/presubmit-tests.sh
Labels: approved, lgtm, size/XS

#341 webhook based API-Coverage tool: Value analysis
  tools/webhook-apicoverage/resourcetree/README.md
  tools/webhook-apicoverage/resourcetree/arraykindnode.go
  tools/webhook-apicoverage/resourcetree/basictypekindnode.go
  tools/webhook-apicoverage/resourcetree/buildChildNodes_test.go
  tools/webhook-apicoverage/resourcetree/node.go
  tools/webhook-apicoverage/resourcetree/otherkindnode.go
  tools/webhook-apicoverage/resourcetree/ptrkindnode.go
  tools/webhook-apicoverage/resourcetree/resourceforest.go
  tools/webhook-apicoverage/resourcetree/resourcetree.go
  tools/webhook-apicoverage/resourcetree/structkindnode.go
  tools/webhook-apicoverage/resourcetree/test_util.go
  tools/webhook-apicoverage/resourcetree/timetypenode.go
  tools/webhook-apicoverage/resourcetree/updateCoverage_test.go
Labels: approved, lgtm, size/L

#379 Update tide to v20190109-716fe27
  ci/prow/cluster.yaml
Labels: approved, lgtm, size/XS

#380 Fix link to tide dashboard
  ci/prow/config.yaml
Labels: approved, lgtm, size/XS

#381 Check licenses of all packages, not only `cmd`
  scripts/presubmit-tests.sh
Labels: approved, lgtm, size/XS

#386 Log where build and istio are being installed from
  scripts/library.sh
Labels: approved, lgtm, size/XS

#385 Allow setting E2E test cluster region, zone and machine type
  scripts/README.md
  scripts/e2e-tests.sh
  scripts/library.sh
  test/e2e-tests.sh
Labels: approved, lgtm, size/M

#394 increasing images cleanup job timeout to 8 hours
  ci/prow/config.yaml
Labels: approved, lgtm, size/XS

#391 Allow disabling markdown check steps in the default build test
  scripts/README.md
  scripts/presubmit-tests.sh
Labels: approved, lgtm, size/M

#396 Make --version a standalone flag
  scripts/README.md
  scripts/release.sh
  test/unit/release-tests.sh
Labels: approved, lgtm, size/M

#398 raise coverage threshold to 80% for PR in Serving
  ci/prow/config.yaml
Labels: approved, lgtm, size/XS

#392 Encapsulate the build process in a function for release.sh
  scripts/README.md
  scripts/release.sh
  test/unit/release-tests.sh
Labels: approved, lgtm, size/L

#402 Fix regexp for conformance-tests tab
  ci/testgrid/config.yaml
Labels: approved, lgtm, size/XS

#403 Save cluster metadata once it is created
  scripts/e2e-tests.sh
Labels: approved, lgtm, size/M

#401 webhook based API-Coverage tool: resourcetree traversal
  tools/webhook-apicoverage/coveragecalculator/README.md
  tools/webhook-apicoverage/coveragecalculator/coveragedata.go
  tools/webhook-apicoverage/resourcetree/README.md
  tools/webhook-apicoverage/resourcetree/arraykindnode.go
  tools/webhook-apicoverage/resourcetree/basictypekindnode.go
  tools/webhook-apicoverage/resourcetree/node.go
  tools/webhook-apicoverage/resourcetree/otherkindnode.go
  tools/webhook-apicoverage/resourcetree/ptrkindnode.go
  tools/webhook-apicoverage/resourcetree/resourceforest.go
  tools/webhook-apicoverage/resourcetree/resourcetree.go
  tools/webhook-apicoverage/resourcetree/rule.go
  tools/webhook-apicoverage/resourcetree/structkindnode.go
  tools/webhook-apicoverage/resourcetree/timetypenode.go
Labels: approved, lgtm, size/L

#405 webhook based API-Coverage tool: Export NodeData type
  tools/webhook-apicoverage/resourcetree/arraykindnode.go
  tools/webhook-apicoverage/resourcetree/basictypekindnode.go
  tools/webhook-apicoverage/resourcetree/buildChildNodes_test.go
  tools/webhook-apicoverage/resourcetree/node.go
  tools/webhook-apicoverage/resourcetree/otherkindnode.go
  tools/webhook-apicoverage/resourcetree/ptrkindnode.go
  tools/webhook-apicoverage/resourcetree/resourceforest.go
  tools/webhook-apicoverage/resourcetree/resourcetree.go
  tools/webhook-apicoverage/resourcetree/structkindnode.go
  tools/webhook-apicoverage/resourcetree/test_util.go
  tools/webhook-apicoverage/resourcetree/timetypenode.go
Labels: approved, lgtm, size/L

#407 Remove mentions to the (now unused) general service account
  ci/prow/boskos/config.yaml
  ci/prow/config.yaml
Labels: approved, lgtm, size/S

#408 Don't keep a copy of test-infra in prow-tests
  images/prow-tests/Dockerfile
  images/prow-tests/Makefile
Labels: approved, lgtm, size/XS

#409 Update boskos to v20180725-c421ed4f9
  ci/prow/boskos/config.yaml
Labels: approved, lgtm, size/XS

#411 Add a presubmit job to run perf tests
  ci/prow/config.yaml
Labels: approved, lgtm, size/S

#412 Do not lint or check links for deleted Markdown docs
  scripts/presubmit-tests.sh
Labels: approved, lgtm, size/XS

#413 Check also hostname when waiting for external address
  scripts/library.sh
Labels: approved, lgtm, size/S

#418 Allow passing extra flags for creating the test cluster
  scripts/e2e-tests.sh
Labels: approved, lgtm, size/M

#419 Allow customizing the markdown lint tool
  scripts/README.md
  scripts/library.sh
  scripts/markdown-lint-config.rc
Labels: approved, lgtm, size/S

#423 Don't show server version when displaying test setup
  scripts/presubmit-tests.sh
Labels: approved, lgtm, size/XS

#427 Assorted fixes to e2e test infra
  scripts/e2e-tests.sh
  scripts/library.sh
  test/e2e-tests.sh
Labels: approved, lgtm, size/S

#410 Assorted fixes to E2E metadata dump
  scripts/e2e-tests.sh
Labels: approved, lgtm, size/M

#429 Run all e2e tests on us-west1
  ci/prow/config.yaml
Labels: approved, lgtm, size/XS

#421 Fix hyphenated component name in published release
  scripts/release.sh
Labels: approved, lgtm, size/XS

#430 Use bot account for GitHub api
  ci/prow/config.yaml
  tools/githubhelper/README.md
  tools/githubhelper/githubhelper.go
Labels: approved, lgtm, size/M

#426 Webhooko API Coverage Tool: Coverage Calculation
  tools/webhook-apicoverage/coveragecalculator/README.md
  tools/webhook-apicoverage/coveragecalculator/calculator.go
  tools/webhook-apicoverage/coveragecalculator/coveragedata.go
  tools/webhook-apicoverage/coveragecalculator/ignorefields.go
  tools/webhook-apicoverage/resourcetree/arraykindnode.go
  tools/webhook-apicoverage/resourcetree/basictypekindnode.go
  tools/webhook-apicoverage/resourcetree/node.go
  tools/webhook-apicoverage/resourcetree/otherkindnode.go
  tools/webhook-apicoverage/resourcetree/ptrkindnode.go
  tools/webhook-apicoverage/resourcetree/resourceforest.go
  tools/webhook-apicoverage/resourcetree/resourcetree.go
  tools/webhook-apicoverage/resourcetree/rule.go
  tools/webhook-apicoverage/resourcetree/structkindnode.go
  tools/webhook-apicoverage/resourcetree/timetypenode.go
  tools/webhook-apicoverage/view/README.md
  tools/webhook-apicoverage/view/jsontype_display.go
  tools/webhook-apicoverage/view/rule.go
  tools/webhook-apicoverage/webhook/webhook.go
Labels: approved, lgtm, size/L

#431 Remove GITHUB_BOT_TOKEN from Prow config
  ci/prow/config.yaml
Labels: approved, lgtm, size/XS

#432 Also publish the generated YAMLs to the GCS bucket
  scripts/release.sh
Labels: approved, lgtm, size/XS
