Repository knative/test-infra, pull requests merged in 2019-11, with the labels that each got.

#1509 Format markdown
  tools/monitoring/README.md
Labels: approved, lgtm, ok-to-test, size/XS

#1512 set path_alias for new operator jobs
  ci/prow/config.yaml
  ci/prow/config_knative.yaml
Labels: approved, lgtm, size/XS

#1518 Fix two Prow jobs
  ci/prow/config.yaml
  ci/prow/config_knative.yaml
Labels: approved, lgtm, size/XS

#1517 Actually fail the cluster jobs for performance tests
  scripts/performance-tests.sh
Labels: approved, lgtm, size/S

#1514 Increase alert period
  tools/monitoring/config/config.yaml
Labels: approved, lgtm, size/XS

#1520 fix syntax error in cluster creation retry logic
  scripts/e2e-tests.sh
Labels: approved, lgtm, size/XS

#1515 Fix config issue that potentially caused some alert not sent
  tools/monitoring/config/config.yaml
Labels: approved, lgtm, size/XS

#1511 Get the YAML and logs for a single failed Pod, if Pods are not marked as ready/complete in time.
  scripts/library.sh
Labels: approved, lgtm, size/S

#1522 Add perf jobs for Knative GCP
  ci/prow/config.yaml
  ci/prow/config_knative.yaml
  ci/prow/perf_config.go
Labels: approved, lgtm, size/L

#1523 Run the cleanup job every 6h
  ci/prow/config.yaml
  ci/prow/periodic_config.go
Labels: approved, lgtm, size/XS

#1525 Create a job for knative/docs link check presubmit
  ci/prow/config.yaml
  ci/prow/config_knative.yaml
Labels: approved, lgtm, size/M

#1529 Increase boskos projects to 100
  ci/prow/boskos_resources.yaml
Labels: approved, lgtm, size/S

#1527 Add a new function to start_knative_monitoring
  scripts/library.sh
Labels: approved, lgtm, size/S

#1531 Increase memory resource for eventing and eventing-contrib build jobs
  ci/prow/config.yaml
  ci/prow/config_knative.yaml
Labels: approved, lgtm, size/L

#1530 Markdown link checker presubmit for knative/docs is optional
  ci/prow/config.yaml
  ci/prow/config_knative.yaml
Labels: approved, lgtm, size/XS

#1534 Cleanups
  Gopkg.lock
  ci/prow/make_config.go
  ci/prow/periodic_config.go
  hack/verify-codegen.sh
Labels: approved, lgtm, size/S

#1532 Enable running tests with https for presubmit
  ci/prow/config.yaml
  ci/prow/config_knative.yaml
Labels: approved, lgtm, size/L

#1535 Display nodes of the test cluster before running the test
  scripts/e2e-tests.sh
Labels: approved, lgtm, size/XS

#1536 Display nodes of the test cluster before running the test
  test/e2e-tests.sh
Labels: approved, lgtm, size/XS

#1538 fix malformed junit result from custom build tests
  scripts/library.sh
Labels: approved, lgtm, size/XS

#1543 Sort releases by natural sort for dot release jobs
  scripts/release.sh
Labels: approved, lgtm, size/XS

#1541 golang format tools
  ci/prow/periodic_config.go
Labels: approved, lgtm, ok-to-test

#1548 use mdl v0.5 in prow test image
  images/prow-tests/Dockerfile
Labels: approved, lgtm, size/XS

#1547 updated the monitor config to remove noise
  tools/monitoring/config/config.yaml
Labels: approved, lgtm, size/M

#1550 Modifications on Spyglass highlight regexes
  ci/prow/config.yaml
  ci/prow/templates/prow_config_header.yaml
Labels: approved, lgtm, size/S

#1551 Fix knative monitoring installation function
  scripts/library.sh
Labels: approved, lgtm, size/XS

#1555 githubhelper: Raise ListFiles responses PerPage to 300.
  tools/githubhelper/githubhelper.go
Labels: approved, lgtm, size/XS

#1559 Enable Istio 1.4 in pull-knative-serving-istio-1.4-* test grids and remove 1.2
  ci/prow/config.yaml
  ci/prow/config_knative.yaml
  ci/prow/testgrid.yaml
  shared/testgrid/testgrid.go
  tools/flaky-test-reporter/config/config.yaml
Labels: approved, lgtm, size/L
