Repository knative/test-infra, pull requests merged in 2019-08, with the labels that each got.

#1221 flaky-test-retryer: add readme
  tools/flaky-test-retryer/README.md
Labels: approved, lgtm, ok-to-test, size/M

#1198 Enable Boskos Metrics server
  ci/prow/Makefile
  ci/prow/boskos/deployments/metrics.yaml
Labels: approved, lgtm, size/M

#1226 readonly and export E2E_PROJECT_ID in separate lines
  scripts/e2e-tests.sh
Labels: approved, lgtm, size/XS

#1222 Format markdown
  tools/flaky-test-retryer/README.md
Labels: approved, lgtm, ok-to-test, size/M

#1229 Update all Boskos related images base paths
  ci/prow/boskos/deployments/janitor.yaml
  ci/prow/boskos/deployments/metrics.yaml
  ci/prow/boskos/deployments/reaper.yaml
  ci/prow/boskos/deployments/statefulset.yaml
Labels: approved, lgtm, size/XS

#1232 GCP knative components moving to google.
  ci/prow/config.yaml
  ci/prow/config_knative.yaml
  ci/prow/plugins.yaml
  ci/prow/templates/prow_config_header.yaml
  ci/testgrid/config.yaml
Labels: approved, lgtm, size/L

#1234 use ID instead of login for flaky-test-retryer
  tools/flaky-test-retryer/github_commenter.go
  tools/flaky-test-retryer/github_commenter_test.go
Labels: approved, lgtm, ok-to-test, size/XS

#1235 flaky test retryer uses verioned tag instead of latest
  tools/flaky-test-retryer/gke_deployment/retryer_service.yaml
Labels: approved, lgtm, size/XS

#1132 Eventing testing with vanity URL
  ci/prow/config.yaml
  ci/prow/config_knative.yaml
Labels: approved, lgtm, size/L

#1238 Eventing-contrib jobs using vanity URL
  ci/prow/config.yaml
  ci/prow/config_knative.yaml
Labels: approved, lgtm, size/L

#1223 Add instruction for adding new k8s resources on Prow cluster
  ci/prow_setup.md
Labels: approved, lgtm, size/S

#1220 Add issue lifecycle tracker period jobs
  ci/prow/config.yaml
  ci/prow/make_config.go
  ci/prow/periodic_config.go
  ci/prow/templates/prow_periodic_test_job.yaml
Labels: approved, lgtm, size/L

#1245 Restrict issue tracker bot to only test-infra
  ci/prow/config.yaml
  ci/prow/periodic_config.go
Labels: approved, lgtm, size/XS

#1236 add update instructions to retryer readme
  tools/flaky-test-retryer/README.md
Labels: approved, lgtm, needs-ok-to-test, size/XS

#1243 heart: Add TrevorFarrelly as an adoree
  ci/prow/plugins.yaml
Labels: approved, lgtm, ok-to-test, size/XS

#1248 Format markdown
  ci/prow_setup.md
  tools/flaky-test-retryer/README.md
Labels: approved, lgtm, ok-to-test, size/M

#1149 disable the clear-alerts prow job
  ci/prow/config.yaml
  ci/prow/make_config.go
  ci/prow/periodic_config.go
Labels: approved, lgtm, size/M

#1256 Fix issue tracker jobs
  ci/prow/config.yaml
  ci/prow/periodic_config.go
Labels: approved, lgtm, size/M

#1253 flaky test retryer: add Spyglass links, update grammar
  tools/flaky-test-retryer/github_commenter.go
  tools/flaky-test-retryer/github_commenter_test.go
  tools/flaky-test-retryer/log_parser.go
Labels: approved, lgtm, ok-to-test, size/L

#1257 Make ingress tests optional for PRs
  ci/prow/config.yaml
  ci/prow/config_knative.yaml
  ci/prow/make_config.go
  ci/prow/templates/prow_presubmit_job.yaml
Labels: approved, lgtm, size/S

#1246 More detailed instructions on releases
  ci/manual_release.md
  ci/release_setup.md
Labels: approved, lgtm, size/M

#1260 Fix update-full command in Prow's Makefile
  ci/prow/Makefile
Labels: approved, lgtm, size/XS

#1254 Enable project plugin for eventing and eventing-contrib
  ci/prow/plugins.yaml
Labels: approved, lgtm, size/S

#1261 revert postsubmit coverage job back to only run on master branch
  ci/prow/config.yaml
  ci/prow/make_config.go
  ci/prow/templates/prow_postsubmit_gocoverage_job.yaml
Labels: approved, lgtm, size/M

#1258 refactor jsonreport into client and interface
  tools/flaky-test-reporter/json_reporter.go
  tools/flaky-test-reporter/jsonreport/jsonreport.go
  tools/flaky-test-retryer/handler.go
  tools/flaky-test-retryer/log_parser.go
  tools/flaky-test-retryer/main.go
Labels: approved, lgtm, ok-to-test, size/L

#1264 Format markdown
  ci/release_setup.md
Labels: approved, lgtm, ok-to-test, size/M

#1263 flaky test retryer: add fake jsonreport lib, unit test log_parser.go
  tools/flaky-test-reporter/jsonreport/fakejsonreport/fakejsonreport.go
  tools/flaky-test-retryer/log_parser_test.go
Labels: approved, lgtm, ok-to-test, size/L

#1268 flaky-test-retryer: add more logging info for easier debugging
  tools/flaky-test-retryer/handler.go
  tools/flaky-test-retryer/log_parser.go
Labels: approved, lgtm, size/XS

#1272 Use path_alias for client repo
  ci/prow/config.yaml
  ci/prow/config_knative.yaml
Labels: approved, lgtm, size/S

#1275 golang format tools
  tools/flaky-test-reporter/jsonreport/jsonreport.go
  tools/flaky-test-retryer/github_commenter_test.go
  tools/flaky-test-retryer/log_parser_test.go
Labels: approved, lgtm, ok-to-test, size/S

#1255 Add prow jobs to update clusters running serving benchmarks
  ci/prow/config.yaml
  ci/prow/make_config.go
  ci/prow/periodic_config.go
Labels: approved, lgtm, size/L

#1277 remove dushyanthsc from productivity-reviewers
  OWNERS_ALIASES
Labels: approved, lgtm, size/XS

#1271 flaky-test-retryer: backward compatible with old comment
  tools/flaky-test-retryer/github_commenter.go
  tools/flaky-test-retryer/github_commenter_test.go
Labels: approved, lgtm, size/M

#1267 flaky test retryer uses new image
  tools/flaky-test-retryer/gke_deployment/retryer_service.yaml
Labels: approved, lgtm, size/XS

#1288 flaky-test-retryer start over counting on new commits
  tools/flaky-test-retryer/github_commenter.go
  tools/flaky-test-retryer/github_commenter_test.go
Labels: approved, lgtm, size/L

#1292 retry cluster creation when it failed due to nodes unhealthy
  scripts/e2e-tests.sh
Labels: approved, lgtm, size/XS

#1289 Scans flaky tests for test-infra so retryer can help test-infra as well
  tools/flaky-test-reporter/config.yaml
Labels: approved, lgtm, size/XS

#1280 Convenience Makefile credential rules for monitoring cluster
  tools/monitoring/Makefile
Labels: approved, lgtm, size/S

#1278 Add skip reporting mode to flaky-test-reporter, add a job runs with this mode
  ci/prow/config.yaml
  ci/prow/periodic_config.go
  tools/flaky-test-reporter/constants.go
  tools/flaky-test-reporter/main.go
  tools/flaky-test-reporter/result.go
Labels: approved, lgtm, size/L

#1293 fix a couple of bugs in flaky test retryer
  tools/flaky-test-retryer/github_commenter.go
  tools/flaky-test-retryer/github_commenter_test.go
Labels: approved, lgtm, size/XS

#1297 golang format tools
  tools/flaky-test-retryer/github_commenter_test.go
Labels: approved, lgtm, ok-to-test, size/S

#1295 Remove update-test-infra.sh since sockpuppet already does it
  hack/update-test-infra.sh
Labels: approved, lgtm, size/M

#1298 Revert "retry cluster creation when it failed due to nodes unhealthy"
  scripts/e2e-tests.sh
Labels: approved, lgtm, size/XS

#1299 remove github and slack tokens from flaky test recorder to avoid accident
  ci/prow/config.yaml
  ci/prow/periodic_config.go
Labels: approved, lgtm, size/XS

#1301 flaky test retryer uses flaky test recorder results
  tools/flaky-test-reporter/jsonreport/fakejsonreport/fakejsonreport.go
  tools/flaky-test-reporter/jsonreport/jsonreport.go
  tools/flaky-test-retryer/log_parser.go
  tools/flaky-test-retryer/main.go
Labels: approved, lgtm, size/M

#1302 update retryer image and readme
  tools/flaky-test-retryer/README.md
  tools/flaky-test-retryer/gke_deployment/retryer_service.yaml
Labels: approved, lgtm, size/XS

#1300 build-test: do not run e2e tests in presubmit.
  scripts/presubmit-tests.sh
Labels: approved, lgtm, size/S

#1303 Move slack operations to shared
  shared/slackutil/messaging.go
  tools/flaky-test-reporter/main.go
  tools/flaky-test-reporter/slack_notification.go
Labels: approved, lgtm, size/L

#1304 Format markdown
  tools/flaky-test-retryer/README.md
Labels: approved, lgtm, ok-to-test, size/XS

#1307 Add comment explaining why retryer scans latest build instead of current build
  tools/flaky-test-retryer/log_parser.go
Labels: approved, lgtm, size/XS

#1308 expanding boskos to 75
  ci/prow/boskos/resources.yaml
Labels: approved, lgtm, size/XS

#1305 Set serving build test requests/limits both to 16Gb memory
  ci/prow/config.yaml
  ci/prow/config_knative.yaml
  ci/prow/make_config.go
  ci/prow/templates/prow_periodic_test_job.yaml
  ci/prow/templates/prow_presubmit_job.yaml
Labels: approved, lgtm, size/M

#1317 Always get the latest flaky issues
  tools/flaky-test-reporter/github_issue.go
  tools/flaky-test-reporter/github_issue_test.go
  tools/flaky-test-reporter/main.go
Labels: approved, lgtm, size/L

#1320 fixing paths for config.yaml since it's moved
  images/flaky-test-reporter/Dockerfile
  tools/flaky-test-reporter/config/config.go
Labels: approved, lgtm, size/XS

#1318 Make temp files creation work across OSes
  scripts/library.sh
Labels: approved, lgtm, ok-to-test, size/S

#1321 Format markdown
  tools/coverage/README.md
Labels: approved, lgtm, ok-to-test, size/S
