Repository knative/test-infra, pull requests merged in 2019-05, with the labels that each got.

#729 Cleanup job timeout extends to 24 hours
  ci/prow/config.yaml
  ci/prow/make_config.go
Labels: approved, lgtm, size/XS

#724 Correct expression for catching stockouts in retrying cluster creation
  scripts/e2e-tests.sh
Labels: approved, lgtm, size/XS

#726 Reuse the junit lib to generate junit xml for coverage results
  shared/junit/junit.go
  tools/coverage/gcs/gcs.go
  tools/coverage/gcs/gcsPresubmit.go
  tools/coverage/testgrid/testsuiteXmlWriter.go
Labels: approved, lgtm, size/L

#734 Install Istio from Addon
  scripts/README.md
  scripts/e2e-tests.sh
  scripts/library.sh
Labels: approved, lgtm, size/S

#719 Also display username during e2e init
  scripts/e2e-tests.sh
Labels: approved, lgtm, size/XS

#728 add coverage completion marker regardless of unit test failure
  tools/coverage/artifacts/profiling.go
Labels: approved, lgtm, size/XS

#737 Update prow and testgrid for knative/observability
  ci/prow/config.yaml
  ci/prow/config_knative.yaml
  ci/testgrid/config.yaml
Labels: approved, lgtm, size/L

#738 Update fortio imports to istio.io
  Gopkg.lock
  shared/loadgenerator/loadgenerator.go
  vendor/fortio.org/fortio/debian/copyright
  vendor/fortio.org/fortio/fhttp/http_client.go
  vendor/fortio.org/fortio/fhttp/http_server.go
  vendor/fortio.org/fortio/fhttp/http_utils.go
  vendor/fortio.org/fortio/fnet/network.go
  vendor/fortio.org/fortio/version/version.go
  vendor/istio.io/fortio/LICENSE
  vendor/istio.io/fortio/fhttp/http.go
  vendor/istio.io/fortio/fhttp/httprunner.go
  vendor/istio.io/fortio/fnet/network.go
  vendor/istio.io/fortio/log/logger.go
  vendor/istio.io/fortio/periodic/periodic.go
  vendor/istio.io/fortio/stats/stats.go
Labels: approved, lgtm, size/XXL

#732 Group all repos under the same dashboard for released projects
  ci/prow/make_config.go
  ci/testgrid/config.yaml
Labels: approved, lgtm, size/M

#739 rename skip-istio flag to skip-istio-addon to make it more obvious
  scripts/README.md
  scripts/e2e-tests.sh
Labels: approved, lgtm, size/XS

#740 Add crier and pubsub reporter to prow config
  ci/prow/cluster.yaml
  ci/prow/config_start.yaml
Labels: approved, lgtm, size/M

#741 Update WORKSPACE file to latest versions
  WORKSPACE
Labels: approved, lgtm, size/S

#744 Wait until all containers in pods are running too.
  scripts/library.sh
Labels: approved, lgtm, size/XS

#731 Also add coverage job/tab if no periodic job defined
  ci/prow/config.yaml
  ci/prow/config_knative.yaml
  ci/prow/make_config.go
  ci/testgrid/config.yaml
Labels: approved, lgtm, size/L

#747 Remove apicoverage tool
  tools/apicoverage/README.md
  tools/apicoverage/apicoverage.go
Labels: approved, lgtm, size/L

#748 Remove istio yaml vars since they do not exist anymore
  scripts/library.sh
Labels: approved, lgtm, size/XS

#750 Add knative/community to tide
  ci/prow/config.yaml
  ci/prow/make_config.go
Labels: approved, lgtm, size/XS

#743 Do not generate dashboard groups for versioned projects in testgrid
  ci/prow/make_config.go
  ci/testgrid/config.yaml
Labels: approved, lgtm, size/S

#751 CI flows on branches use stable releases
  scripts/library.sh
Labels: approved, lgtm, size/S

#767 fix typo
  ci/prow/make_config.go
Labels: approved, lgtm, size/XS

#768 Automate permissions when adding a new boskos project
  ci/prow/boskos/permissions.sh
  ci/prow_setup.md
Labels: approved, lgtm, size/M

#769 Add CI flow for serving 0.6 branch
  ci/prow/config.yaml
  ci/prow/config_knative.yaml
  ci/testgrid/config.yaml
Labels: approved, lgtm, size/M

#752 added basic kubernetes app skeleton for infra monitoring
  images/monitoring/Dockerfile
  images/monitoring/Makefile
  tools/monitoring/Makefile
  tools/monitoring/gke_deployment/monitoring_service.yaml
  tools/monitoring/main.go
Labels: approved, lgtm, size/L

#771 A few updates to permissions.sh
  ci/prow/boskos/README.md
  ci/prow/boskos/permissions.sh
  ci/prow_setup.md
Labels: approved, lgtm, size/M

#772 Tool for updating test-infra in other repos
  hack/update-test-infra.sh
Labels: approved, lgtm, size/M

#777 Install the correct version of component for all prow jobs
  ci/prow/config.yaml
  ci/prow/make_config.go
  scripts/library.sh
Labels: approved, lgtm, size/S

#782 Jessie is moving, remove her from OWNERS
  OWNERS
Labels: approved, lgtm, size/XS

#773 Add CI flow and testgrid dashboards for eventing, eventing-sources and build 0.6 release
  ci/prow/config.yaml
  ci/prow/config_knative.yaml
  ci/testgrid/config.yaml
Labels: approved, lgtm, size/L

#781 Allow releasing any kind of artifact, not only YAML files
  scripts/README.md
  scripts/release.sh
Labels: approved, lgtm, size/M

#783 Fix the tag name in some situation
  scripts/library.sh
Labels: approved, lgtm, size/XS

#784 update cluster creation retry logic for 2 different error messages
  scripts/e2e-tests.sh
Labels: approved, lgtm, size/XS

#786 Create the automated release jobs for Knative Client
  ci/prow/config.yaml
  ci/prow/config_knative.yaml
  ci/testgrid/config.yaml
Labels: approved, lgtm, size/L

#776 Add a config parser for knative monitoring
  tools/monitoring/config.go
  tools/monitoring/main.go
  tools/monitoring/sample.yaml
Labels: approved, lgtm, size/L

#789 bug fix on monitoring config
  tools/monitoring/config.go
Labels: approved, lgtm, size/XS

#788 Don't fail auto-releases if no tags exist in the repo
  scripts/release.sh
Labels: approved, lgtm, size/S

#792 Fix detection of "documentation only" PRs
  scripts/presubmit-tests.sh
  test/unit/presubmit-tests.sh
Labels: approved, lgtm, size/S

#791 Update test-infra OWNERS
  OWNERS
  OWNERS_ALIASES
Labels: approved, lgtm, size/S

#793 Determine the OS we're running on
  scripts/library.sh
Labels: approved, lgtm, size/S

#787 update-test-infra script handles repos with no Gopkg.lock file
  hack/update-test-infra.sh
Labels: approved, lgtm, size/S

#785 Export build date, tag and hash properties for release
  scripts/README.md
  scripts/release.sh
Labels: approved, lgtm, size/M

#794 Also handle single quotes in make_banner()
  scripts/library.sh
Labels: approved, lgtm, size/XS

#779 Make using profiler optional when using loadgenerator
  shared/loadgenerator/loadgenerator.go
  test/e2e/load_generator_test.go
Labels: approved, lgtm, size/M

#795 Remove pointer to JobConfig in RepoData struct to fix memory bug
  tools/flaky-test-reporter/github_issue_test.go
  tools/flaky-test-reporter/main.go
  tools/flaky-test-reporter/result.go
Labels: approved, lgtm, ok-to-test, size/XS

#797 Create a CI flow for Knative Client
  ci/prow/config.yaml
  ci/prow/config_knative.yaml
  ci/testgrid/config.yaml
Labels: approved, lgtm, size/M

#802 update prow componenets to v20190517-bb7028b16
  ci/prow/cluster.yaml
  ci/prow/config.yaml
  ci/prow/make_config.go
Labels: approved, lgtm, size/M

#798 Don't assume PULL_BASE_REF exists in get_knative_base_yaml_source()
  scripts/library.sh
Labels: approved, lgtm, size/S

#808 Prevents e2e test from running on prow cluster
  scripts/e2e-tests.sh
  scripts/library.sh
  test/unit/library-tests.sh
Labels: approved, lgtm, size/M

#796 Adds unit tests for config yaml parser
  tools/monitoring/config.go
  tools/monitoring/config_test.go
Labels: approved, lgtm, size/L

#809 Add flaky test reporting for various istio/mesh combinations
  tools/flaky-test-reporter/config.go
  tools/flaky-test-reporter/github_issue.go
  tools/flaky-test-reporter/main.go
  tools/flaky-test-reporter/result.go
  tools/flaky-test-reporter/slack_notification.go
Labels: approved, lgtm, ok-to-test, size/L

#814 Fix gcr locations for devstats images
  tools/devstats/Kubernetes/batch-job-backfill.yaml
  tools/devstats/Kubernetes/cli-home.yaml
  tools/devstats/Kubernetes/cron-updates.yaml
  tools/devstats/Kubernetes/postgres-service.yaml
Labels: approved, lgtm, size/XS

#811 Build Log Parser
  tools/monitoring/logs.go
  tools/monitoring/logs_test.go
Labels: approved, lgtm, size/L

#813 flaky-test-reporter: refactor logging to better support new job/repo mapping format
  tools/flaky-test-reporter/config.go
  tools/flaky-test-reporter/github_issue.go
  tools/flaky-test-reporter/result.go
  tools/flaky-test-reporter/slack_notification.go
Labels: approved, lgtm, ok-to-test, size/M

#817 use UnmarshalStrict for monitoring config parsing
  tools/monitoring/config.go
Labels: approved, lgtm, size/XS

#816 flaky-test-reporter: add unit tests for GitHub issue flag
  tools/flaky-test-reporter/github_issue_test.go
Labels: approved, lgtm, needs-ok-to-test, size/S

#822 Update url for deploying Prow
  ci/prow_setup.md
Labels: approved, lgtm, size/XS

#818 Unify alias name for productivity approvers/reviewers in OWNERS
  OWNERS
  OWNERS_ALIASES
Labels: approved, lgtm, size/XS

#823 Add a more flexible flaky reporting threshold for jobs with less tests
  tools/flaky-test-reporter/README.md
  tools/flaky-test-reporter/config.go
  tools/flaky-test-reporter/github_issue.go
  tools/flaky-test-reporter/github_issue_test.go
  tools/flaky-test-reporter/result.go
  tools/flaky-test-reporter/slack_notification.go
Labels: approved, lgtm, needs-ok-to-test, size/M

#824 set defaults for missing entries in monitoring config file
  tools/monitoring/config.go
Labels: approved, lgtm, size/S

#820 monitoring config validator
  tools/monitoring/config.go
  tools/monitoring/config_test.go
Labels: approved, lgtm, size/L

#827 Also retry test cluster creation during GKE updates
  scripts/e2e-tests.sh
Labels: approved, lgtm, size/S

#825 change monitoring config receiver's name
  tools/monitoring/config.go
Labels: approved, lgtm, size/XS

#832 Move ghutil to under shared
  shared/ghutil/fakeghutil/fakeghutil.go
  shared/ghutil/ghutil.go
  tools/flaky-test-reporter/github_issue.go
  tools/flaky-test-reporter/github_issue_test.go
Labels: approved, lgtm, size/XS

#834 Fixes flaky knative serving install
  scripts/e2e-tests.sh
  scripts/library.sh
Labels: approved, lgtm, size/S

#839 Add a new performance-mesh job to run perf tests with mesh config
  ci/prow/config.yaml
  ci/prow/config_knative.yaml
  ci/prow/make_config.go
  ci/testgrid/config.yaml
Labels: approved, lgtm, size/M

#838 Split shared/ghutil based on functionalities, add pullrequest support
  shared/ghutil/client.go
  shared/ghutil/fakeghutil/fakeghutil.go
  shared/ghutil/issue.go
  shared/ghutil/pullrequest.go
  tools/flaky-test-reporter/github_issue.go
Labels: approved, lgtm, size/L

#828 Fix the logic to find the latest release build for the given repo
  scripts/library.sh
Labels: approved, lgtm, size/M

#840 install knative serving in two steps
  scripts/library.sh
Labels: approved, lgtm, size/S

#842 Add mock functions for ghutil pullrequest related functions
  shared/ghutil/client.go
  shared/ghutil/fakeghutil/fakeghutil.go
Labels: approved, lgtm, size/L

#843 Fix depagination in ghutil package
  shared/ghutil/issue.go
  shared/ghutil/pullrequest.go
Labels: approved, lgtm, size/S

#845 Check for forbidden GCR during cluster setup
  scripts/e2e-tests.sh
Labels: approved, lgtm, size/XS

#836 Create the tables specified in monitoring design doc
  tools/monitoring/mysql/tables.sql
Labels: approved, lgtm, size/M
