Repository knative/test-infra, pull requests merged in 2019-12, with the labels that each got.

#1562 Add prow config for knative/sample-source
  ci/prow/config.yaml
  ci/prow/config_knative.yaml
  ci/prow/plugins.yaml
  ci/prow/testgrid.yaml
Labels: approved, lgtm, size/L

#1563 Fail build tests if `go list` fails
  scripts/presubmit-tests.sh
Labels: approved, lgtm, size/XS

#1567 Add job for running knative-serving e2e against kourier stable
  ci/prow/config.yaml
  ci/prow/config_knative.yaml
  ci/prow/testgrid.yaml
  shared/testgrid/testgrid.go
Labels: approved, lgtm, ok-to-test, size/L

#1571 Add start_knative_eventing to library
  scripts/library.sh
Labels: approved, lgtm, size/S

#1576 Flaky test reporter notify slack for gloo and kourier
  tools/flaky-test-reporter/config/config.yaml
Labels: approved, lgtm, size/S

#1579 Remove emit-metrics flag support and update jobs
  ci/prow/config.yaml
  ci/prow/make_config.go
  scripts/README.md
  scripts/e2e-tests.sh
  scripts/presubmit-tests.sh
  test/e2e/flag.go
Labels: approved, lgtm, size/M

#1577 Increase cpu request so that we don't overscheduling
  ci/prow/deployments/cpu_limitrange.yaml
Labels: approved, lgtm, size/XS

#1558 Use prow-tests image with go1.13 for all eventing repos
  ci/prow/config.yaml
  ci/prow/config_knative.yaml
Labels: approved, lgtm, size/XXL

#1582 Update Boskos images from 20190723 to 20191204
  ci/prow/deployments/boskos_janitor.yaml
  ci/prow/deployments/boskos_metrics.yaml
  ci/prow/deployments/boskos_reaper.yaml
  ci/prow/deployments/boskos_statefulset.yaml
Labels: approved, lgtm, size/XS

#1584 Switching Boskos to deployment, as well as removing persistent volume
  ci/prow/deployments/boskos_deployment.yaml
  ci/prow/deployments/boskos_volumes.yaml
Labels: approved, lgtm, size/M

#1589 Fixing boskos deployment by deleting wrong field
  ci/prow/deployments/boskos_deployment.yaml
Labels: approved, lgtm, size/XS

#1585 Change all Prow jobs running on master to Go 1.13
  ci/prow/config.yaml
  ci/prow/config_knative.yaml
Labels: approved, lgtm, size/XXL

#1590 Make chizhg a member of productivity-approvers
  OWNERS_ALIASES
Labels: approved, lgtm, size/XS

#1594 Add labels "proposal/0.[11-19]" to Prow's /label plugin
  ci/prow/plugins.yaml
  ci/prow/templates/prow_plugins.yaml
Labels: approved, lgtm, size/S

#1595 Add nightly Tekton tests for knative/client
  ci/prow/config.yaml
  ci/prow/config_knative.yaml
  ci/prow/testgrid.yaml
Labels: approved, lgtm, size/M

#1597 Update folder for newly created boskos projects
  ci/prow/create_boskos_projects.sh
Labels: approved, lgtm, size/XS

#1602 Highlight Knative setup errors in Spyglass logs
  ci/prow/config.yaml
  ci/prow/templates/prow_config_header.yaml
Labels: approved, lgtm, size/XS
