Repository knative/test-infra, pull requests merged in 2019-02, with the labels that each got.

#434 Move fileHandle Close() invocation after error checking
  shared/gcs/gcs.go
  shared/prow/prow.go
Labels: approved, lgtm, size/XS

#436 Check existence of GCS path should also work for directory path
  shared/gcs/gcs.go
  shared/prow/prow.go
Labels: approved, lgtm, size/M

#443 Make productivity oncall schedule visible to community
  tools/oncall/oncall.html
Labels: approved, lgtm, size/M

#446 Fix spacing
  ci/testgrid/config.yaml
Labels: approved, lgtm, size/XS

#435 Precompute start and finish time of prow builds
  shared/prow/prow.go
Labels: approved, lgtm, size/M

#447 Ignore links starting with '/' or './' for lint
  scripts/markdown-link-check-config.json
Labels: approved, lgtm, size/XS

#449 Don't lint links starting with /, ./, or ../
  scripts/markdown-link-check-config.json
Labels: approved, lgtm, size/XS

#454 Replace markdown-link-check with liche
  images/prow-tests/Dockerfile
  images/prow-tests/Makefile
  scripts/library.sh
  scripts/markdown-link-check-config.json
  scripts/markdown-link-check-config.rc
  scripts/presubmit-tests.sh
Labels: approved, lgtm, size/M

#456 Group performance tests by target in TestGrid
  ci/testgrid/config.yaml
Labels: approved, lgtm, size/XS

#457 Ensure continuous and release tests sorted consistently in TestGrid
  ci/testgrid/config.yaml
Labels: approved, lgtm, size/S

#461 Bash script unit tests don't print output if passed
  test/unit/test-helper.sh
Labels: approved, lgtm, size/XS

#462 Clearly state when the config files tests start
  test/presubmit-tests.sh
Labels: approved, lgtm, size/XS

#455 Don't run post_unit_tests or post_build_tests if failed in pre/build
  scripts/presubmit-tests.sh
Labels: approved, lgtm, size/XS

#460 Create xml output from testcases for testgrid
  shared/loadgenerator/loadgenerator.go
  shared/testgrid/testgrid.go
  shared/testgrid/testgrid_test.go
  tools/apicoverage/apicoverage.go
Labels: approved, lgtm, size/M

#467 Bump plank version from 20180709-7109caeb1 to 20190109-716fe27
  ci/prow/cluster.yaml
Labels: approved, lgtm, size/XS

#468 Add some defaults to non mandatory values for loadgenerator
  shared/loadgenerator/loadgenerator.go
  shared/loadgenerator/loadgenerator_test.go
Labels: approved, lgtm, size/S

#469 Fixes for Release script to correctly detect branches
  scripts/release.sh
Labels: approved, lgtm, size/XS

#470 update release yaml path from build
  scripts/library.sh
Labels: approved, lgtm, size/XS

#474 Default build test skips checking license if there is no go code
  scripts/presubmit-tests.sh
Labels: approved, lgtm, size/XS

#464 Setting up auto-release jobs for build, eventing and serving
  ci/prow/config.yaml
Labels: approved, lgtm, size/L

#473 Remove unnecessary bundling: serving and build, and build and istio.
  scripts/library.sh
Labels: approved, lgtm, size/XS

#463 webhook-apicoverage: apicovareage-recorder
  tools/webhook-apicoverage/resourcetree/resourceforest.go
  tools/webhook-apicoverage/webhook/README.md
  tools/webhook-apicoverage/webhook/apicoverage_recorder.go
  tools/webhook-apicoverage/webhook/webhook.go
Labels: approved, lgtm, size/L

#477 Make --run-test skip unnecessary testing on presubmit
  scripts/presubmit-tests.sh
Labels: approved, lgtm, size/XS

#480 webhook-apicoverage: API Coverage recorder fix
  tools/webhook-apicoverage/webhook/apicoverage_recorder.go
Labels: approved, lgtm, size/S

#466 Flaky test reporting(part #3) Add ghutil package for supporting Github issues tracking
  tools/flaky-test-reporter/ghutil/ghutil.go
Labels: approved, lgtm, size/L

#465 Flaky test reporting(part #2): define data structure and data collection
  shared/prow/prow.go
  tools/flaky-test-reporter/config.go
  tools/flaky-test-reporter/main.go
  tools/flaky-test-reporter/result.go
Labels: approved, lgtm, size/L

#482 Initial version of the Prow config generator
  ci/prow/Makefile
  ci/prow/README.md
  ci/prow/config.yaml
  ci/prow/config_knative.yaml
  ci/prow/make_config.go
Labels: approved, lgtm, size/XXL

#476 let 0 statement go file pass coverage threshold
  tools/coverage/calc/base.go
  tools/coverage/calc/delta.go
Labels: approved, lgtm, size/XS

#485 Update go version to 1.12rc1 in prow-tests docker image
  images/prow-tests/Dockerfile
Labels: approved, lgtm, size/XS

#489 Fix log in library script.
  scripts/library.sh
Labels: approved, lgtm, size/XS

#490 Adding the missing .0 at the end of release number
  scripts/release.sh
Labels: approved, lgtm, size/XS

#487 gather directories for testgrid without relying on go test output
  tools/coverage/artifacts/profiling.go
  tools/coverage/calc/group.go
  tools/coverage/testgrid/folder.go
  tools/coverage/testgrid/testsuiteXmlWriter.go
Labels: approved, lgtm, size/M

#481 Replace DOCKER_REPO_OVERRIDE by KO_DOCKER_REPO and delete the K8S_* vars
  scripts/README.md
  scripts/e2e-tests.sh
Labels: approved, lgtm, size/M

#492 Updates to the Prow config generator
  ci/prow/config.yaml
  ci/prow/make_config.go
Labels: approved, lgtm, size/XXL

#493 Webhook-APICoverage: tools support
  Gopkg.lock
  tools/webhook-apicoverage/coveragecalculator/coveragedata.go
  tools/webhook-apicoverage/resourcetree/arraykindnode.go
  tools/webhook-apicoverage/resourcetree/basictypekindnode.go
  tools/webhook-apicoverage/resourcetree/node.go
  tools/webhook-apicoverage/resourcetree/otherkindnode.go
  tools/webhook-apicoverage/resourcetree/ptrkindnode.go
  tools/webhook-apicoverage/resourcetree/resourceforest.go
  tools/webhook-apicoverage/resourcetree/structkindnode.go
  tools/webhook-apicoverage/resourcetree/timetypenode.go
  tools/webhook-apicoverage/tools/README.md
  tools/webhook-apicoverage/tools/tools.go
  tools/webhook-apicoverage/view/jsontype_display.go
  tools/webhook-apicoverage/webhook/apicoverage_recorder.go
  vendor/github.com/knative/pkg/signals/signal.go
  vendor/github.com/knative/pkg/signals/signal_posix.go
  vendor/github.com/knative/pkg/signals/signal_windows.go
  vendor/github.com/knative/serving/pkg/system/clock.go
  vendor/github.com/knative/serving/pkg/system/names.go
  vendor/k8s.io/client-go/plugin/pkg/client/auth/gcp/gcp.go
  vendor/k8s.io/client-go/third_party/forked/golang/template/exec.go
  vendor/k8s.io/client-go/third_party/forked/golang/template/funcs.go
  vendor/k8s.io/client-go/util/jsonpath/doc.go
  vendor/k8s.io/client-go/util/jsonpath/jsonpath.go
  vendor/k8s.io/client-go/util/jsonpath/node.go
  vendor/k8s.io/client-go/util/jsonpath/parser.go
Labels: approved, lgtm, size/XXL

#494 Setting the test grid config for monitoring auto-release
  ci/testgrid/config.yaml
Labels: approved, lgtm, size/S

#497 Allow setting custom environment variables when generating Prow config
  ci/prow/make_config.go
Labels: approved, lgtm, size/M

#495 Remove usage of K8S_CLUSTER_OVERRIDE
  tools/webhook-apicoverage/tools/README.md
  tools/webhook-apicoverage/tools/tools.go
Labels: approved, lgtm, size/S

#502 Create CI flows for knative/serving 0.3 and 0.4
  ci/prow/config.yaml
  ci/prow/config_knative.yaml
  ci/testgrid/config.yaml
Labels: approved, lgtm, size/L

#504 webhook-apicoverage: Add support for total coverage API and display
  tools/webhook-apicoverage/tools/README.md
  tools/webhook-apicoverage/tools/tools.go
  tools/webhook-apicoverage/view/README.md
  tools/webhook-apicoverage/view/coverage_display.go
  tools/webhook-apicoverage/view/jsontype_display.go
  tools/webhook-apicoverage/webhook/apicoverage_recorder.go
Labels: approved, lgtm, size/L

#505 Remove the logger from prometheus teardown.
  shared/prometheus/prometheus.go
Labels: approved, lgtm, size/S

#503 Run serving tests hourly
  ci/prow/config.yaml
  ci/prow/config_knative.yaml
Labels: approved, lgtm, size/XS

#507 Allow listing prow builds in gcs without precompute start/finish time
  shared/prow/prow.go
  tools/flaky-test-reporter/result.go
Labels: approved, lgtm, size/M

#510 Enable tide for knative/website repo
  ci/prow/config.yaml
  ci/prow/make_config.go
Labels: approved, lgtm, size/XS

#509 Add a tab for serving "dot" releases in Testgrid
  ci/testgrid/config.yaml
Labels: approved, lgtm, size/XS

#511 Add a screenshot of the GitHub branch check setting for clarity.
  ci/prow/branch_checks.png
  ci/prow/prow_setup.md
Labels: approved, lgtm, size/M

#512 More flexibility for running E2E tests
  scripts/README.md
  scripts/e2e-tests.sh
  scripts/library.sh
Labels: approved, lgtm, size/L

#514 Fix failing release when `build_release` fails.
  scripts/release.sh
Labels: approved, lgtm, size/XS

#524 Update instructions about setting Prow jobs for a new repo
  ci/prow/prow_setup.md
Labels: approved, lgtm, size/S

#525 Update e2e-tests.sh
  test/e2e-tests.sh
Labels: approved, lgtm, size/XS

#523 Add function for displaying pod logs.
  scripts/library.sh
  scripts/release.sh
  test/unit/library-tests.sh
  test/unit/release-tests.sh
  test/unit/test-helper.sh
Labels: approved, lgtm, size/M

#528 Always store the logs in `go_test_e2e`
  scripts/e2e-tests.sh
  scripts/library.sh
Labels: approved, lgtm, size/S

#526 Use stable GO version 1.12 instead of 1.12rc1
  images/prow-tests/Dockerfile
Labels: approved, lgtm, size/S

#531 Adding webhook API Coverage prow job
  ci/prow/config.yaml
  ci/prow/config_knative.yaml
  ci/prow/make_config.go
Labels: approved, lgtm, size/M

#534 Use FormatLogger instead of BaseLogger in prometheus wrapper
  Gopkg.lock
  shared/prometheus/prometheus.go
  shared/prometheus/prometheus_test.go
  vendor/github.com/knative/pkg/apis/duck/v1alpha1/condition_set.go
  vendor/github.com/knative/pkg/apis/duck/v1alpha1/generational_types.go
  vendor/github.com/knative/pkg/apis/duck/v1alpha1/register.go
  vendor/github.com/knative/pkg/apis/duck/v1alpha1/zz_generated.deepcopy.go
  vendor/github.com/knative/pkg/apis/interfaces.go
  vendor/github.com/knative/pkg/test/logging/logging.go
  vendor/github.com/knative/pkg/webhook/webhook.go
  vendor/github.com/pkg/errors/LICENSE
  vendor/github.com/pkg/errors/errors.go
  vendor/github.com/pkg/errors/stack.go
Labels: approved, lgtm, size/XXL

#533 Simplify defining a continuous build for previous releases
  ci/prow/config.yaml
  ci/prow/config_knative.yaml
  ci/prow/make_config.go
Labels: approved, lgtm, size/M

#529 Follow ListFiles Pagination
  .gitignore
  tools/coverage/githubUtil/githubFakes/fake.go
  tools/coverage/githubUtil/githubFiles.go
  tools/githubhelper/githubhelper.go
Labels: approved, lgtm, size/M
