Repository knative/test-infra, pull requests merged in 2019-04, with the labels that each got.

#651 Initial commit of the latency metrics aggregation tool
  tools/latency/Dockerfile
  tools/latency/Makefile
  tools/latency/main.go
Labels: approved, lgtm, size/L

#653 Show Go path, repo dir and gcloud user when building release
  scripts/release.sh
Labels: approved, lgtm, size/XS

#655 Let boskos handle test cluster teardown
  scripts/e2e-tests.sh
Labels: approved, lgtm, size/M

#657 expand boskos pool by adding 11 more projects
  ci/prow/boskos/resources.yaml
Labels: approved, lgtm, size/S

#658 update boskos flags
  ci/prow/boskos/config.yaml
Labels: approved, lgtm, size/XS

#663 During release, only remove the latest dir if it exists
  scripts/release.sh
Labels: approved, lgtm, size/XS

#664 fix wrong variable name in cleanup tool
  tools/cleanup/cleanup-functions.sh
Labels: approved, lgtm, size/XS

#665 Document GeneratorOptions in loadgenerator.
  shared/loadgenerator/loadgenerator.go
Labels: approved, lgtm, size/S

#672 Update Istio installation
  scripts/library.sh
Labels: approved, lgtm, size/S

#670 Increase timeout of branch CI tests
  ci/prow/config.yaml
  ci/prow/make_config.go
Labels: approved, lgtm, size/XS

#673 Remove start_latest_knative_build from library.sh
  scripts/library.sh
Labels: approved, lgtm, size/XS

#667 Allow running a setup function before starting the test cluster
  scripts/README.md
  scripts/e2e-tests.sh
Labels: approved, lgtm, size/S

#677 refactor mkdir into a common function
  shared/common/common.go
  shared/loadgenerator/loadgenerator.go
  shared/testgrid/testgrid.go
  tools/flaky-test-reporter/main.go
Labels: approved, lgtm, size/M

#662 Add instructions on how to release Knative via Prow
  ci/README.md
  ci/branch_checks.png
  ci/prow_setup.md
  ci/release.md
Labels: approved, lgtm, size/L

#681 Fix batch job wait logic.
  scripts/library.sh
Labels: approved, lgtm, size/S

#684 Use 6 janitors for Boskos cleanup
  ci/prow/boskos/config.yaml
Labels: approved, lgtm, size/XS

#683 Increase Boskos pool to a total of 40
  ci/prow/boskos/resources.yaml
Labels: approved, lgtm, size/XS

#671 E2E clusters creation retry different regions/zones
  scripts/README.md
  scripts/e2e-tests.sh
Labels: approved, lgtm, size/M

#668 Create the CI flows for knative 0.5
  ci/prow/config.yaml
  ci/prow/config_knative.yaml
  ci/testgrid/config.yaml
Labels: approved, lgtm, size/L

#685 Add a way to run multiple runs of load test
  shared/loadgenerator/loadgenerator.go
  shared/loadgenerator/loadgenerator_test.go
  test/e2e-tests.sh
  test/e2e/load_generator_test.go
  test/e2e/simple_e2e_test.go
Labels: approved, lgtm, size/L

#687 update plank versions
  ci/prow/cluster.yaml
  ci/prow/config.yaml
  ci/prow/make_config.go
Labels: approved, lgtm, size/S

#688 update all Prow components to latest version
  ci/prow/cluster.yaml
Labels: approved, lgtm, size/S

#693 Add defaults before using the values
  shared/loadgenerator/loadgenerator.go
  shared/loadgenerator/loadgenerator_test.go
Labels: approved, lgtm, size/M

#692 make E2E_CLUSTER_PROJECT globally available
  scripts/README.md
  scripts/e2e-tests.sh
Labels: approved, lgtm, size/S

#696 Find some duplicate words for "the" and delete them
  scripts/e2e-tests.sh
Labels: approved, lgtm, ok-to-test, size/XS

#699 Increase timeout for perf job to 2 hrs
  ci/prow/config.yaml
  ci/prow/make_config.go
Labels: approved, lgtm, size/XS

#703 Don't tear down test environment on boskos
  scripts/e2e-tests.sh
Labels: approved, lgtm, size/XS

#700 Fix some spelling mistakes
  shared/prow/prow.go
  test/unit/cleanup-tests.sh
  tools/apicoverage/README.md
Labels: approved, lgtm, ok-to-test, size/S

#708 Fix detecting presubmit-exempt PRs
  scripts/presubmit-tests.sh
  test/unit/presubmit-tests.sh
Labels: approved, lgtm, size/M

#705 Add CI support for istio version and istio mesh
  ci/prow/config.yaml
  ci/prow/config_knative.yaml
  ci/prow/make_config.go
  ci/testgrid/config.yaml
Labels: approved, lgtm, size/L

#712 Add some missing labels to Prow config
  ci/prow/config.yaml
  ci/prow/make_config.go
Labels: approved, lgtm, size/S

#707 Fix latency aggregation tool for E2E tests
  tools/latency/main.go
Labels: approved, lgtm, size/XS

#720 Document how to create nightlies on demand
  ci/release.md
Labels: approved, lgtm, size/S

#701 Add ability to add cpu and memory profile with loadgenerator
  shared/loadgenerator/loadgenerator.go
  shared/loadgenerator/loadgenerator_test.go
  test/e2e/load_generator_test.go
Labels: approved, lgtm, size/M

#725 fix coverage error message format
  tools/coverage/artifacts/profiling.go
Labels: approved, lgtm, size/XS
