Repository knative/test-infra, pull requests merged in 2020-04, with the labels that each got.

#1881 Enable API for boskos projects to support Workload Identity testing
  config/prow/boskos/set_up_boskos_project.sh
Labels: approved, cla: yes, lgtm, size/XS

#1879 Minor fixes to prow config updater
  tools/prow-config-updater/pullrequest.go
Labels: approved, cla: yes, lgtm, size/M

#1885 [master] Auto-update dependencies
  Gopkg.lock
  vendor/knative.dev/pkg/test/helpers/dir.go
Labels: approved, cla: yes, lgtm, size/M

#1886 Remove stale dummy.go
  dummy.go
Labels: approved, cla: yes, lgtm, size/S

#1887 Ignore build tags under hack.
  scripts/presubmit-tests.sh
Labels: approved, cla: yes, lgtm, size/XS

#1849 Update vendor to use pkg test
  Gopkg.lock
  pkg/common/common.go
  pkg/gcs/gcs.go
  pkg/gcs/gcs_test.go
  pkg/junit/junit_test.go
  pkg/performance/performance.go
  pkg/prow/prow.go
  pkg/prow/prow_test.go
  pkg/testgrid/testgrid.go
  pkg/testgrid/yaml.go
  pkg/testgrid/yaml_test.go
  tools/coverage/testgrid/testsuiteXmlWriter.go
  tools/flaky-test-reporter/github_issue.go
  tools/flaky-test-reporter/jsonreport/jsonreport.go
  tools/flaky-test-reporter/main.go
  tools/flaky-test-reporter/result.go
  tools/flaky-test-retryer/log_parser.go
  tools/monitoring/alert/alert.go
  tools/monitoring/main.go
  tools/prow-auto-bumper/file.go
  tools/prow-config-updater/config/config_test.go
  vendor/knative.dev/pkg/test/junit/junit.go
Labels: approved, cla: yes, lgtm, size/XXL

#1888 Move github.com/knative-sandbox/operator to knative.dev/operator
  config/prow/config_knative.yaml
  config/prow/jobs/config.yaml
Labels: approved, cla: yes, lgtm, size/S

#1891 Add the upgrade test job into knative-sandbox/operator
  config/prow/config_knative.yaml
  config/prow/jobs/config.yaml
Labels: approved, cla: yes, lgtm, size/M

#1892 dep collector works with Go modules
  tools/dep-collector/gobuild.go
  tools/dep-collector/imports.go
  tools/dep-collector/licenses.go
Labels: approved, cla: yes, lgtm, size/L

#1895 [master] Auto-update dependencies
  Gopkg.lock
  vendor/knative.dev/pkg/test/cmd/command.go
  vendor/knative.dev/pkg/test/e2e_flags.go
  vendor/knative.dev/pkg/test/logging/sugar.go
  vendor/knative.dev/pkg/test/logging/tlogger.go
  vendor/knative.dev/pkg/testutils/clustermanager/e2e-tests/config.go
  vendor/knative.dev/pkg/testutils/clustermanager/e2e-tests/gke.go
  vendor/knative.dev/pkg/testutils/clustermanager/e2e-tests/setup.go
  vendor/knative.dev/pkg/testutils/clustermanager/e2e-tests/util.go
  vendor/knative.dev/pkg/testutils/clustermanager/prow-cluster-operation/actions/create.go
  vendor/knative.dev/pkg/testutils/clustermanager/prow-cluster-operation/actions/delete.go
  vendor/knative.dev/pkg/testutils/clustermanager/prow-cluster-operation/options/options.go
  vendor/knative.dev/pkg/testutils/metahelper/client/client.go
  vendor/knative.dev/pkg/testutils/metahelper/main.go
Labels: approved, cla: yes, lgtm, size/XL

#1897 fix dep collector by not using pkg
  tools/dep-collector/gobuild.go
Labels: approved, cla: yes, lgtm, size/S

#1884 Add presubmit tests job for knative-gcp workload identity tests
  config/prow/config_knative.yaml
  config/prow/jobs/config.yaml
Labels: approved, cla: yes, lgtm, size/M

#1898 Require a static `.md` suffix, rather than {any character} followed by `md`
  scripts/presubmit-tests.sh
Labels: approved, cla: yes, lgtm, size/XS

#1901 set merge method to squash for knative-sandbox
  config/prow-staging/core/config.yaml
  tools/config-generator/templates/prow-staging/prow_config.yaml
Labels: approved, cla: yes, lgtm, size/XS

#1908 Add setup for https://github.com/knative-sandbox/eventing-kafka
  config/prow/config_knative.yaml
  config/prow/core/config.yaml
  config/prow/core/plugins.yaml
  config/prow/jobs/config.yaml
  config/prow/testgrid/testgrid.yaml
Labels: approved, cla: yes, lgtm, size/L

#1909 [master] Auto-update dependencies
  Gopkg.lock
  third_party/VENDOR-LICENSE
  vendor/github.com/hashicorp/golang-lru/2q.go
  vendor/github.com/hashicorp/golang-lru/LICENSE
  vendor/github.com/hashicorp/golang-lru/arc.go
  vendor/github.com/hashicorp/golang-lru/doc.go
  vendor/github.com/hashicorp/golang-lru/lru.go
  vendor/github.com/hashicorp/golang-lru/simplelru/lru.go
  vendor/github.com/hashicorp/golang-lru/simplelru/lru_interface.go
  vendor/k8s.io/apimachinery/pkg/apis/meta/internalversion/doc.go
  vendor/k8s.io/apimachinery/pkg/apis/meta/internalversion/register.go
  vendor/k8s.io/apimachinery/pkg/apis/meta/internalversion/types.go
  vendor/k8s.io/apimachinery/pkg/apis/meta/internalversion/zz_generated.conversion.go
  vendor/k8s.io/apimachinery/pkg/apis/meta/internalversion/zz_generated.deepcopy.go
  vendor/k8s.io/apimachinery/pkg/apis/meta/v1beta1/conversion.go
  vendor/k8s.io/apimachinery/pkg/apis/meta/v1beta1/deepcopy.go
  vendor/k8s.io/apimachinery/pkg/apis/meta/v1beta1/doc.go
  vendor/k8s.io/apimachinery/pkg/apis/meta/v1beta1/generated.pb.go
  vendor/k8s.io/apimachinery/pkg/apis/meta/v1beta1/register.go
  vendor/k8s.io/apimachinery/pkg/apis/meta/v1beta1/types.go
  vendor/k8s.io/apimachinery/pkg/apis/meta/v1beta1/types_swagger_doc_generated.go
  vendor/k8s.io/apimachinery/pkg/apis/meta/v1beta1/zz_generated.deepcopy.go
  vendor/k8s.io/apimachinery/pkg/apis/meta/v1beta1/zz_generated.defaults.go
  vendor/k8s.io/apimachinery/pkg/util/cache/cache.go
  vendor/k8s.io/apimachinery/pkg/util/cache/lruexpirecache.go
  vendor/k8s.io/apimachinery/pkg/util/diff/diff.go
  vendor/k8s.io/client-go/tools/cache/controller.go
  vendor/k8s.io/client-go/tools/cache/delta_fifo.go
  vendor/k8s.io/client-go/tools/cache/doc.go
  vendor/k8s.io/client-go/tools/cache/expiration_cache.go
  vendor/k8s.io/client-go/tools/cache/expiration_cache_fakes.go
  vendor/k8s.io/client-go/tools/cache/fake_custom_store.go
  vendor/k8s.io/client-go/tools/cache/fifo.go
  vendor/k8s.io/client-go/tools/cache/heap.go
  vendor/k8s.io/client-go/tools/cache/index.go
  vendor/k8s.io/client-go/tools/cache/listers.go
  vendor/k8s.io/client-go/tools/cache/listwatch.go
  vendor/k8s.io/client-go/tools/cache/mutation_cache.go
  vendor/k8s.io/client-go/tools/cache/mutation_detector.go
  vendor/k8s.io/client-go/tools/cache/reflector.go
  vendor/k8s.io/client-go/tools/cache/reflector_metrics.go
  vendor/k8s.io/client-go/tools/cache/shared_informer.go
  vendor/k8s.io/client-go/tools/cache/store.go
  vendor/k8s.io/client-go/tools/cache/thread_safe_store.go
  vendor/k8s.io/client-go/tools/cache/undelta_store.go
  vendor/k8s.io/client-go/tools/pager/pager.go
  vendor/k8s.io/client-go/util/retry/util.go
  vendor/k8s.io/utils/buffer/ring_growing.go
  vendor/k8s.io/utils/trace/trace.go
  vendor/knative.dev/pkg/kmeta/accessor.go
  vendor/knative.dev/pkg/kmeta/doc.go
  vendor/knative.dev/pkg/kmeta/labels.go
  vendor/knative.dev/pkg/kmeta/map.go
  vendor/knative.dev/pkg/kmeta/names.go
  vendor/knative.dev/pkg/kmeta/owner_references.go
  vendor/knative.dev/pkg/kmeta/ownerrefable_accessor.go
  vendor/knative.dev/pkg/test/helpers/name.go
Labels: approved, cla: yes, lgtm, size/XXL

#1915 Remove unnecesary full-command key for config generator
  config/prow/config_knative.yaml
  tools/config-generator/main.go
Labels: approved, cla: yes, lgtm, size/XS

#1910 Add instruction for creating Prow build cluster
  config/prow/build-cluster/README.md
  config/prow/build-cluster/add-secrets.sh
  config/prow/build-cluster/create-build-cluster.sh
Labels: approved, cla: yes, lgtm, size/L

#1911 Add Boskos for build cluster
  config/build-cluster/Makefile
  config/build-cluster/boskos/boskos_resources.yaml
  config/build-cluster/cluster/400-boskos-deployment.yaml
  config/build-cluster/cluster/400-boskos-janitor.yaml
  config/build-cluster/cluster/400-boskos-metrics.yaml
  config/build-cluster/cluster/400-boskos-reaper.yaml
  config/build-cluster/cluster/400-boskos.yaml
  config/prow/boskos/boskos_resources.yaml
Labels: approved, cla: yes, lgtm, size/L

#1916 Enable integration test job for net-certmanager
  config/prow/config_knative.yaml
  config/prow/jobs/config.yaml
Labels: approved, cla: yes, lgtm, size/M

#1919 Improve Prow setup documents
  config/prow-staging/core/config.yaml
  config/prow-staging/jobs/config.yaml
  config/prow/config_knative.yaml
  config/prow/core/config.yaml
  config/prow/jobs/config.yaml
  config/prow/testgrid/testgrid.yaml
  guides/README.md
  guides/prow_knative_setup.md
  guides/prow_setup.md
  guides/release_setup.md
  tools/config-generator/postsubmit_config.go
  tools/config-generator/templates/common_header.yaml
Labels: approved, cla: yes, lgtm, size/L

#1918 Support having multiple Prow job config files
  config/gubernator/Makefile
  config/prow-staging/config_staging.yaml
  config/prow-staging/jobs/config.yaml
  config/prow_common.mk
  scripts/presubmit-tests.sh
Labels: approved, cla: yes, lgtm, size/L

#1921 Small fixes to the Prow config updater tool
  tools/prow-config-updater/config/config.go
  tools/prow-config-updater/config/config_test.go
  tools/prow-config-updater/presubmit-checker/main.go
  tools/prow-config-updater/updater.go
Labels: approved, cla: yes, lgtm, size/M

#1922 Operator release at 12PM instead of 2AM
  config/prow/jobs/config.yaml
  tools/config-generator/periodic_config.go
Labels: approved, cla: yes, lgtm, size/S

#1924 Add service accounts for Boskos in build cluster
  config/build-cluster/cluster/200-cpu-limitrange.yaml
  config/build-cluster/cluster/200-memory-limitrange.yaml
  config/build-cluster/cluster/301-rbac.yaml
Labels: approved, cla: yes, lgtm, size/L

#1926 Move 20 Boskos over to build cluster
  config/build-cluster/boskos/boskos_resources.yaml
  config/prow/boskos/boskos_resources.yaml
Labels: approved, cla: yes, lgtm, size/M

#1927 Migrate less active repo jobs to build cluster
  config/prow/jobs/config.yaml
  tools/config-generator/main.go
  tools/config-generator/templates/prow_periodic_custom_job.yaml
  tools/config-generator/templates/prow_periodic_test_job.yaml
  tools/config-generator/templates/prow_postsubmit_custom_job.yaml
  tools/config-generator/templates/prow_postsubmit_gocoverage_job.yaml
  tools/config-generator/templates/prow_postsubmit_perf_job.yaml
  tools/config-generator/templates/prow_presubmit_gocoverate_job.yaml
  tools/config-generator/templates/prow_presubmit_job.yaml
Labels: approved, cla: yes, lgtm, size/M

#1929 Move more repos to use build cluster
  config/prow/jobs/config.yaml
  tools/config-generator/main.go
Labels: approved, cla: yes, lgtm, size/M

#1930 Enable dind for eventing-kafka repo
  config/prow/config_knative.yaml
  config/prow/jobs/config.yaml
Labels: approved, cla: yes, lgtm, size/M

#1928 Move another 20 Boskos projects to build cluster
  config/build-cluster/boskos/boskos_resources.yaml
  config/prow/boskos/boskos_resources.yaml
Labels: approved, cla: yes, lgtm, size/M

#1931 Move third wave of repos to use build cluster
  config/prow/jobs/config.yaml
  tools/config-generator/main.go
Labels: approved, cla: yes, lgtm, size/M

#1932 Move all repos other than serving to build cluster
  config/prow-staging/jobs/config.yaml
  config/prow/jobs/config.yaml
  tools/config-generator/main.go
Labels: approved, cla: yes, lgtm, size/L

#1933 Move another 20 Boskos to build cluster
  config/build-cluster/boskos/boskos_resources.yaml
  config/prow/boskos/boskos_resources.yaml
Labels: approved, cla: yes, lgtm, size/M

#1937 Do not generate most of the maintenance jobs with config-generator
  config/prow/jobs/config.yaml
  config/prow/jobs/custom-jobs.yaml
  tools/config-generator/main.go
  tools/config-generator/periodic_config.go
  tools/config-generator/postsubmit_config.go
Labels: approved, cla: yes, lgtm, size/XL

#1940 Fix run_job.sh and pj-on-kind.sh
  config/prow/pj-on-kind.sh
  config/prow/run_job.sh
Labels: approved, cla: yes, lgtm, size/XS

#1938 Add checkconfig jobs for prow and prow-staging
  config/prow/jobs/custom-jobs.yaml
  test/presubmit-config-check.sh
Labels: approved, cla: yes, lgtm, size/M

#1943 Fix cleanup job by using go1.13
  config/prow/jobs/custom-jobs.yaml
Labels: approved, cla: yes, lgtm, size/XS

#1939 Update Prow config per the deprecation notice
  config/prow-staging/core/config.yaml
  tools/config-generator/templates/prow-staging/prow_config.yaml
Labels: approved, cla: yes, lgtm, size/M

#1942 Improve presubmit config check
  config/prow/config_knative.yaml
  config/prow/jobs/config.yaml
  config/prow/jobs/custom-jobs.yaml
  test/presubmit-config-check.sh
  tools/prow-config-updater/presubmit-checker/main.go
Labels: approved, cla: yes, lgtm, size/M

#1946 Clean up tool supports multiple yaml locations
  tools/cleanup/cleanup.go
  tools/cleanup/cleanup_test.go
  tools/cleanup/options/options.go
  tools/cleanup/testdata/resources_01.yaml
  tools/cleanup/testdata/resources_02.yaml
Labels: approved, cla: yes, lgtm, size/L

#1949 Add ci jobs for release-0.14
  config/prow/config_knative.yaml
  config/prow/jobs/config.yaml
  config/prow/testgrid/testgrid.yaml
Labels: approved, cla: yes, lgtm, size/XXL

#1952 Fix some custom jobs
  config/prow/jobs/custom-jobs.yaml
Labels: approved, cla: yes, lgtm, size/S

#1954 Send net-* flaky tests to #net-* channels instead of #networking.
  tools/flaky-test-reporter/config/config.yaml
Labels: approved, cla: yes, lgtm, size/M

#1944 Prow jobs explicitly set it's own resources requests/limit
  config/build-cluster/cluster/200-memory-limitrange.yaml
  config/build-cluster/cluster/400-boskos-janitor.yaml
  config/prow-staging/cluster/200-memory-limitrange.yaml
  config/prow-staging/core/config.yaml
  tools/config-generator/main.go
  tools/config-generator/templates/prow-staging/prow_config.yaml
  tools/config-generator/templates/prow_periodic_custom_job.yaml
  tools/config-generator/templates/prow_postsubmit_custom_job.yaml
  tools/config-generator/templates/prow_postsubmit_gocoverage_job.yaml
  tools/config-generator/templates/prow_postsubmit_perf_job.yaml
  tools/config-generator/templates/prow_presubmit_gocoverate_job.yaml
Labels: approved, cla: yes, lgtm, size/M

#1957 Fixing job names for go114
  config/prow/jobs/config.yaml
  tools/config-generator/main.go
Labels: approved, cla: yes, lgtm, size/XS

#1956 Fixing staging Prow: don't use build cluster
  config/prow-staging/jobs/config.yaml
  tools/config-generator/main.go
Labels: approved, cla: yes, lgtm, size/XS

#1958 Set memory limit for janitor also so they don't really request much r…
  config/build-cluster/cluster/400-boskos-janitor.yaml
  config/prow-staging/cluster/400-boskos-janitor.yaml
Labels: approved, cla: yes, lgtm, size/XS

#1962 Fix flaky tool config
  tools/flaky-test-reporter/config/config.yaml
Labels: approved, cla: yes, lgtm, size/XS

#1934 Move everything to build cluster
  config/prow/jobs/config.yaml
  tools/config-generator/main.go
Labels: approved, cla: yes, lgtm, size/M

#1966 GOFLAGS='' before go get
  scripts/library.sh
Labels: approved, cla: yes, lgtm, size/XS

#1968 Disable go coverage job for eventing-kafka
  config/prow/config_knative.yaml
  config/prow/jobs/config.yaml
  config/prow/testgrid/testgrid.yaml
Labels: approved, cla: yes, lgtm, size/M

#1969 Simpler list_changed_files in PR using plain git command
  scripts/presubmit-tests.sh
Labels: approved, cla: yes, lgtm, size/XS

#1972 Remove all Boskos projects from prow cluster
  config/prow/boskos/boskos_resources.yaml
Labels: approved, cla: yes, lgtm, size/M

#1973 Correctly install go1.14 in docker image
  images/prow-tests-go112/Dockerfile
  images/prow-tests-go114/Dockerfile
Labels: approved, cla: yes, lgtm, size/M

#1976 run_go_tool always install/update the go tool
  images/backups/Dockerfile
  images/coverage-go112/Dockerfile
  images/coverage/Dockerfile
  images/flaky-test-reporter/Dockerfile
  images/flaky-test-retryer/Dockerfile
  images/prow-auto-bumper/Dockerfile
  images/prow-config-updater/Dockerfile
  images/prow-tests-go112/Dockerfile
  images/prow-tests-go114/Dockerfile
  images/prow-tests/Dockerfile
  scripts/library.sh
Labels: approved, cla: yes, lgtm, size/M

#1953 Use go114 in knative-gcp continuous and nightly
  config/prow/config_knative.yaml
  config/prow/jobs/config.yaml
Labels: approved, cla: yes, lgtm, size/XS

#1964 More boskos related pods use less resources
  config/build-cluster/cluster/400-boskos-metrics.yaml
  config/build-cluster/cluster/400-boskos-reaper.yaml
  config/prow-staging/cluster/400-boskos-metrics.yaml
  config/prow-staging/cluster/400-boskos-reaper.yaml
Labels: approved, cla: yes, lgtm, size/S

#1981 Run Prow job ad hoc using docker command instead of bazel
  config/prow/run_job.sh
Labels: approved, cla: yes, lgtm, size/S

#1985 [master] Auto-update dependencies
  Gopkg.lock
  vendor/knative.dev/pkg/test/ghutil/client.go
  vendor/knative.dev/pkg/test/helpers/dir.go
  vendor/knative.dev/pkg/test/monitoring/monitoring.go
  vendor/knative.dev/pkg/test/spoof/spoof.go
  vendor/knative.dev/pkg/test/zipkin/util.go
  vendor/knative.dev/pkg/testutils/clustermanager/e2e-tests/boskos/boskos.go
  vendor/knative.dev/pkg/testutils/clustermanager/e2e-tests/gke.go
  vendor/knative.dev/pkg/testutils/clustermanager/perf-tests/pkg/benchmark.go
  vendor/knative.dev/pkg/testutils/clustermanager/perf-tests/pkg/cluster.go
Labels: approved, cla: yes, lgtm, size/M

#1984 Avoid git diff renames limit
  scripts/presubmit-tests.sh
Labels: approved, cla: yes, lgtm, size/XS

#1965 Move build cluster instruction to correct place and add a missing piece
  config/build-cluster/README.md
  config/build-cluster/add-secrets.sh
  config/build-cluster/create-build-cluster.sh
Labels: approved, cla: yes, lgtm, size/XS

#1979 Add shellcheck and others to prow-tests image
  images/prow-tests/Dockerfile
Labels: approved, cla: yes, lgtm, size/XS

#1980 Cleanup image Makefiles and add security check.
  common.mk
  config/prow_common.mk
  images/README.md
  images/backups/Makefile
  images/clear-test-infra-alerts/Makefile
  images/coverage-go112/Makefile
  images/coverage/Makefile
  images/flaky-test-reporter/Makefile
  images/flaky-test-retryer/Makefile
  images/monitoring/Makefile
  images/prow-auto-bumper/Makefile
  images/prow-config-updater/Makefile
  images/prow-tests-go112/Makefile
  images/prow-tests-go114/Makefile
  images/prow-tests/Makefile
  images/prow-tests/README.md
  images/simple-image.mk
Labels: approved, cla: yes, lgtm, size/L

#1990 add go-licenses tool in the image
  images/prow-tests/Dockerfile
Labels: approved, cla: yes, lgtm, size/XS

#1993 replace kubectl with version 1.17.4
  images/prow-tests/Dockerfile
Labels: approved, cla: yes, lgtm, size/XS

#1994 Add some badges on the frontpage
  README.md
Labels: approved, cla: yes, lgtm, size/XS

#1992 add ghproxy deployment
  config/prow-staging/cluster/302-gce-ssd-retain_storageclass.yaml
  config/prow-staging/cluster/400-crier.yaml
  config/prow-staging/cluster/400-deck.yaml
  config/prow-staging/cluster/400-ghproxy.yaml
  config/prow-staging/cluster/400-hook.yaml
Labels: approved, cla: yes, lgtm, size/L

#1991 use go-licenses to check forbidden licenses
  scripts/library.sh
  scripts/presubmit-tests.sh
Labels: approved, cla: yes, lgtm, size/S

#1996 use go-licenses to update licenses
  hack/update-deps.sh
  scripts/library.sh
Labels: approved, cla: yes, lgtm, size/S

#1998 revert the changes in function run_go_tool
  scripts/library.sh
Labels: approved, cla: yes, lgtm, size/S
