Repository knative/test-infra, pull requests merged in 2020-11, with the labels that each got.

#2548 Also set eventing continuous tests timeout to be 180m
  config/prod/prow/config_knative.yaml
  config/prod/prow/jobs/config.yaml
Labels: approved, cla: yes, lgtm, size/XS

#2549 Various cleanups to the codebase
  pkg/git/commit.go
  pkg/gomod/float.go
  pkg/gomod/float_test.go
  pkg/gomod/modules.go
  tools/cleanup/cleanup.go
  tools/dkcm/mainservice/mainservice.go
  tools/flaky-test-reporter/github_issue.go
  tools/flaky-test-reporter/main.go
  tools/flaky-test-reporter/result.go
  tools/githubhelper/githubhelper.go
  tools/prow-jobs-syncer/pullrequest.go
Labels: approved, cla: yes, lgtm, size/M

#2550 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  scripts/library.sh
  scripts/performance-tests.sh
  vendor/knative.dev/hack/library.sh
  vendor/knative.dev/hack/performance-tests.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/S

#2551 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  scripts/library.sh
  vendor/knative.dev/hack/library.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/S

#2541 Set up Prow jobs for hack repo
  config/prod/prow/config_knative.yaml
  config/prod/prow/jobs/config.yaml
Labels: approved, cla: yes, lgtm, size/L

#2553 Clean up some tests since we have moved them to knative.dev/hack
  test/e2e-kind.sh
  test/e2e-tests.sh
  test/e2e/simple_e2e_test.go
  test/library_test.go
  test/presubmit-tests.sh
  test/unit/e2e-custom-flag-tests.sh
  test/unit/library-tests.sh
  test/unit/presubmit-tests.sh
  test/unit/release-tests.sh
  test/unit/test-helper.sh
Labels: approved, cla: yes, lgtm, size/XL

#2554 Remove dep-collector since we now use go-licenses
  go.mod
  go.sum
  third_party/VENDOR-LICENSE/github.com/google/licenseclassifier/LICENSE
  third_party/VENDOR-LICENSE/github.com/google/licenseclassifier/stringclassifier/LICENSE
  tools/dep-collector/README.md
  tools/dep-collector/gobuild.go
  tools/dep-collector/imports.go
  tools/dep-collector/licenses.go
  tools/dep-collector/main.go
  vendor/github.com/google/licenseclassifier/.travis.yml
  vendor/github.com/google/licenseclassifier/CHANGELOG
  vendor/github.com/google/licenseclassifier/CONTRIBUTING.md
  vendor/github.com/google/licenseclassifier/LICENSE
  vendor/github.com/google/licenseclassifier/README.md
  vendor/github.com/google/licenseclassifier/classifier.go
  vendor/github.com/google/licenseclassifier/file_system_resources.go
  vendor/github.com/google/licenseclassifier/forbidden.go
  vendor/github.com/google/licenseclassifier/go.mod
  vendor/github.com/google/licenseclassifier/go.sum
  vendor/github.com/google/licenseclassifier/internal/sets/sets.go
  vendor/github.com/google/licenseclassifier/internal/sets/stringset.go
  vendor/github.com/google/licenseclassifier/license_type.go
  vendor/github.com/google/licenseclassifier/stringclassifier/CONTRIBUTING.md
  vendor/github.com/google/licenseclassifier/stringclassifier/LICENSE
  vendor/github.com/google/licenseclassifier/stringclassifier/README.md
  vendor/github.com/google/licenseclassifier/stringclassifier/classifier.go
  vendor/github.com/google/licenseclassifier/stringclassifier/internal/pq/priority.go
  vendor/github.com/google/licenseclassifier/stringclassifier/searchset/searchset.go
  vendor/github.com/google/licenseclassifier/stringclassifier/searchset/tokenizer/tokenizer.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XXL

#2552 Added integration-test-channel-consolidated and distributed
  config/prod/prow/config_knative.yaml
  config/prod/prow/jobs/config.yaml
Labels: approved, cla: yes, lgtm, ok-to-test, size/M

#2557 [Automated] Update actions
  .github/workflows/knative-releasability.yaml
  .github/workflows/knative-release-notes.yaml
  .github/workflows/knative-style.yaml
Labels: approved, cla: yes, lgtm, size/L

#2556 Autogenerate k8s testgrid YAML
  config/prod/prow/k8s-testgrid/k8s-testgrid.yaml
  hack/generate-configs.sh
  tools/config-generator/k8s_testgrid_config.go
  tools/config-generator/main.go
  tools/config-generator/templates/k8s_testgrid.yaml
  tools/config-generator/templates/k8s_testgrid_testgroup.yaml
  tools/config-generator/utils.go
  tools/config-generator/utils_test.go
Labels: approved, cla: yes, do-not-merge/hold, lgtm, size/L

#2561 Add Prow for knative-sandbox kperf
  config/prod/prow/config_knative.yaml
  config/prod/prow/jobs/config.yaml
  config/prod/prow/k8s-testgrid/k8s-testgrid.yaml
  config/prod/prow/testgrid/testgrid.yaml
Labels: approved, cla: yes, lgtm, ok-to-test, size/L

#2564 Seed dot releases for GitLab source
  config/prod/prow/config_knative.yaml
  config/prod/prow/jobs/config.yaml
  config/prod/prow/testgrid/testgrid.yaml
Labels: approved, cla: yes, lgtm, size/L

#2565 Ensure generated k8s-testgrid config have deterministic order
  config/prod/prow/k8s-testgrid/k8s-testgrid.yaml
  tools/config-generator/k8s_testgrid_config.go
Labels: approved, cla: yes, lgtm, size/S

#2568 adding labels to allow more kind labels for PRs.
  config/label_sync/labels.yaml
Labels: approved, cla: yes, lgtm, size/M

#2570 Fix a few more occurrences of divisive language
  pkg/gcs/mock/mock_test.go
  pkg/junit/junit_test.go
  scripts/placeholder.go
  tools/cleanup/cleanup.go
  tools/config-generator/main.go
Labels: approved, cla: yes, lgtm, size/S

#2555 Run branch-protector Prow job for Knative org
  config/branch_protector/rules.yaml
  config/prod/prow/jobs/custom/branchprotector.yaml
Labels: approved, cla: yes, lgtm, size/M

#2571 Testgrid prowjobs
  config/prod/prow/jobs/custom/test-infra.yaml
Labels: approved, cla: yes, lgtm, size/M

#2575 Optionally run validate k8s testgrid
  config/prod/prow/jobs/custom/test-infra.yaml
Labels: approved, cla: yes, lgtm, size/XS

#2558 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  scripts/library.sh
  vendor/knative.dev/hack/README.md
  vendor/knative.dev/hack/library.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/S

#2577 bump go patch versions
  images/prow-tests/Dockerfile
Labels: approved, cla: yes, lgtm, size/XS

#2580 Disable validate k8s testgrid yaml job for now
  config/prod/prow/jobs/custom/test-infra.yaml
Labels: approved, cla: yes, lgtm, size/XS

#2562 Add Prow for kn-plugin-diag
  config/prod/prow/config_knative.yaml
  config/prod/prow/jobs/config.yaml
  config/prod/prow/k8s-testgrid/k8s-testgrid.yaml
  config/prod/prow/testgrid/testgrid.yaml
Labels: approved, cla: yes, lgtm, ok-to-test, size/L

#2569 [Automated] Update actions
  .github/workflows/knative-style.yaml
Labels: approved, cla: yes, lgtm, size/XS

#2579 Require Kourier tests to pass, if they are run
  config/prod/prow/config_knative.yaml
  config/prod/prow/jobs/config.yaml
Labels: approved, cla: yes, lgtm, size/XS

#2581 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  scripts/e2e-tests.sh
  scripts/library.sh
  vendor/knative.dev/hack/e2e-tests.sh
  vendor/knative.dev/hack/library.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#2583 Adding two different jobs for eventing-kafka repo
  config/prod/prow/config_knative.yaml
  config/prod/prow/jobs/config.yaml
Labels: approved, cla: yes, lgtm, size/M

#2584 Change upgrade test to required as PR presubmit in knative-gcp
  config/prod/prow/config_knative.yaml
  config/prod/prow/jobs/config.yaml
Labels: approved, cla: yes, lgtm, size/XS

#2587 Add prow jobs for knative-sandbox/kn-plugin-source-kafka
  config/prod/prow/config_knative.yaml
  config/prod/prow/jobs/config.yaml
  config/prod/prow/k8s-testgrid/k8s-testgrid.yaml
  config/prod/prow/testgrid/testgrid.yaml
Labels: approved, cla: yes, lgtm, size/L

#2588 Link the guides from landing readme
  README.md
Labels: approved, cla: yes, lgtm, size/XS

#2589 [Automated] Format markdown
  README.md
Labels: approved, cla: yes, lgtm, size/XS

#2586 Disable coverage job for kperf repo
  config/prod/prow/config_knative.yaml
  config/prod/prow/jobs/config.yaml
  config/prod/prow/testgrid/testgrid.yaml
Labels: approved, cla: yes, lgtm, size/L

#2592 Disable go-coverage job for kn-plugin-source-kafka
  config/prod/prow/config_knative.yaml
  config/prod/prow/jobs/config.yaml
  config/prod/prow/testgrid/testgrid.yaml
Labels: approved, cla: yes, lgtm, size/L

#2585 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  scripts/microbenchmarks.sh
  scripts/release.sh
  vendor/knative.dev/hack/microbenchmarks.sh
  vendor/knative.dev/hack/release.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#2590 A few improvements and cleanups to the image auto-push process
  config/prod/prow/jobs/custom/test-infra.yaml
  images/backups/Makefile
  images/flaky-test-reporter/Makefile
  images/flaky-test-retryer/Makefile
  images/prow-tests/Dockerfile
  images/prow-tests/Makefile
  images/simple-image.mk
Labels: approved, cla: yes, lgtm, size/M
