Repository knative/test-infra, pull requests merged in 2020-05, with the labels that each got.

#1999 Switch the master branches for all repos to run with Go 1.14
  config/prow/config_knative.yaml
  config/prow/jobs/config.yaml
  config/prow/testgrid/testgrid.yaml
  images/coverage-go114/Dockerfile
  images/coverage-go114/Makefile
  tools/config-generator/main.go
  tools/config-generator/perf_config.go
  tools/config-generator/periodic_config.go
  tools/config-generator/postsubmit_config.go
  tools/config-generator/templates/prow_postsubmit_custom_job.yaml
Labels: approved, cla: yes, lgtm, size/XXL

#1997 Mirror copy from staging to prod configs while auto update
  tools/prow-config-updater/updater.go
Labels: approved, cla: yes, lgtm, size/S

#2002 fix rebase error
  config/staging/prow/cluster/302-gce-ssd-retain_storageclass.yaml
  config/staging/prow/cluster/400-ghproxy.yaml
Labels: approved, cla: yes, lgtm, size/XS

#2001 only filter testgrid file for prod Prow
  config/staging/prow/config_staging.yaml
  config/staging/prow/jobs/config.yaml
  tools/prow-config-updater/updater.go
Labels: approved, cla: yes, lgtm, size/M

#2006 [master] Format markdown
  guides/prow_knative_setup.md
  guides/prow_setup.md
Labels: approved, cla: yes, lgtm, size/S

#2008 Update build cluster instructions, and move Boskos
  config/prod/build-cluster/README.md
  config/staging/build-cluster/add-secrets.sh
  config/staging/build-cluster/boskos/boskos_resources.yaml
  config/staging/build-cluster/create-build-cluster.sh
  config/staging/prow/boskos/boskos_resources.yaml
Labels: approved, cla: yes, lgtm, size/XS

#2010 Add a new wait function that also confirms HTTP connection.
  scripts/library.sh
Labels: approved, cla: yes, lgtm, size/M

#2013 Fix github.com/knative/test-infra/pull/2010#discussion_r419820466
  scripts/library.sh
Labels: approved, cla: yes, lgtm, size/XS

#2014 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/test/helpers/name.go
  vendor/knative.dev/pkg/testutils/metahelper/client/client.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/S

#2016 Fixing project name for staging build cluster Makefile
  config/staging/build-cluster/Makefile
Labels: approved, cla: yes, lgtm, size/XS

#2007 Move all Boskos to build clsuter
  config/prod/build-cluster/boskos/boskos_resources.yaml
Labels: approved, cla: yes, lgtm, size/M

#2015 Fix auto bumper
  config/prod/prow/jobs/custom-jobs.yaml
  config/prod/prow/run_job.sh
  tools/prow-auto-bumper/file.go
Labels: approved, cla: yes, lgtm, size/S

#2009 All jobs use build cluster
  config/staging/prow/jobs/config.yaml
  tools/config-generator/main.go
Labels: approved, cla: yes, lgtm, size/S

#2018 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/testutils/metahelper/client/client.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#2019 remove yt3liu from productivity reviewers
  OWNERS_ALIASES
Labels: approved, cla: yes, lgtm, size/XS

#2004 Add junit and metadata subcommands to kntest
  go.sum
  kntest/cmd/kntest/main.go
  kntest/pkg/cluster/commands.go
  kntest/pkg/cluster/gke/README.md
  kntest/pkg/cluster/gke/commands.go
  kntest/pkg/cluster/gke/ops/create.go
  kntest/pkg/cluster/gke/ops/delete.go
  kntest/pkg/cluster/gke/ops/get.go
  kntest/pkg/cluster/gke/ops/request.go
  kntest/pkg/cluster/gke/options.go
  kntest/pkg/junit/README.md
  kntest/pkg/junit/command.go
  kntest/pkg/metadata/README.md
  kntest/pkg/metadata/command.go
  scripts/library.sh
Labels: approved, cla: yes, lgtm, size/L

#2022 Use the correct GKE cluster version
  scripts/e2e-tests.sh
Labels: approved, cla: yes, lgtm, size/XS

#2023 Updates to prow-tests image
  images/prow-tests-go112/Dockerfile
  images/prow-tests-go112/Makefile
  images/prow-tests-go112/README.md
  images/prow-tests/Dockerfile
Labels: approved, cla: yes, lgtm, size/M

#2020 Full support build cluster: auto config update also covers build cluster
  config/prod/Makefile
  config/prod/build-cluster/Makefile
  config/prod/build-cluster/README.md
  config/prod/gubernator/Makefile
  config/prod/prow/build-cluster/README.md
  config/prod/prow/build-cluster/add-secrets.sh
  config/prod/prow/build-cluster/create-build-cluster.sh
  config/prod/prow/jobs/custom-jobs.yaml
  config/prod/prow/run_job.sh
  config/prow_common.mk
  config/staging/Makefile
  config/staging/build-cluster/Makefile
  tools/prow-config-updater/config/config.go
Labels: approved, cla: yes, lgtm, size/L

#2024 Add cleanup jobs for perf tests
  config/prod/prow/jobs/custom-jobs.yaml
  tools/cleanup/cleanup.go
  tools/cleanup/cleanup_test.go
  tools/cleanup/options/options.go
Labels: approved, cla: yes, lgtm, size/M

#2025 No op update to Prow job
  config/prod/prow/jobs/custom-jobs.yaml
Labels: approved, cla: yes, lgtm, size/XS

#2027 Fix config updater
  config/prod/prow/jobs/custom-jobs.yaml
  config/staging/build-cluster/cluster/200-cpu-limitrange.yaml
Labels: approved, cla: yes, lgtm, size/XS

#2028 Revert "No op update to Prow job"
  config/prod/prow/jobs/custom-jobs.yaml
Labels: approved, cla: yes, lgtm, size/XS

#2029 prow config updater Prow job uses go run instead of a custom image
  config/prod/prow/jobs/custom-jobs.yaml
  config/prod/prow/run_job.sh
Labels: approved, cla: yes, lgtm, size/S

#2033 Revert some changes to kntest
  scripts/library.sh
Labels: approved, cla: yes, lgtm, size/M

#2034 Partially revert 2029: Prow config updater use image instead of go run
  config/prod/prow/jobs/custom-jobs.yaml
Labels: approved, cla: yes, lgtm, size/XS

#2035 One small fix and some cleanups
  config/prod/prow/jobs/custom-jobs.yaml
  images/prow-auto-bumper/Dockerfile
  images/prow-auto-bumper/Makefile
  images/prow-auto-bumper/README.md
  images/prow-config-updater/Dockerfile
  images/prow-config-updater/Makefile
  images/prow-config-updater/README.md
  scripts/library.sh
Labels: approved, cla: yes, lgtm, size/L

#2036 Update prow-tests-go114 image
  images/prow-tests-go114/Dockerfile
Labels: approved, cla: yes, lgtm, size/XS

#2038 add knative-sandbox/eventing-rabbitmq
  config/prod/prow/config_knative.yaml
  config/prod/prow/core/config.yaml
  config/prod/prow/core/plugins.yaml
  config/prod/prow/jobs/config.yaml
Labels: approved, cla: yes, lgtm, size/L

#2039 Staging Prow jobs using the same prow-tests image
  config/staging/prow/jobs/config.yaml
  hack/generate-configs.sh
Labels: approved, cla: yes, lgtm, size/S

#2043 Update ko to v0.5.1
  images/prow-tests-go114/Dockerfile
  images/prow-tests/Dockerfile
Labels: approved, cla: yes, lgtm, size/XS

#2041 Update prow-tests to use gvm
  images/prow-tests/Dockerfile
  images/prow-tests/my-gvm.sh
  images/prow-tests/runner.sh
Labels: approved, cla: yes, lgtm, size/M

#2048 Update cluster config
  config/staging/prow/cluster/400-crier.yaml
  config/staging/prow/cluster/400-ghproxy.yaml
  config/staging/prow/cluster/400-plank.yaml
Labels: approved, cla: yes, lgtm, size/XS

#2049 Tide usess ghproxy
  config/staging/prow/cluster/400-tide.yaml
Labels: approved, cla: yes, lgtm, size/XS

#2051 Update Prow jobs to include GO_VERSION env var
  config/prod/prow/jobs/config.yaml
  config/staging/prow/jobs/config.yaml
  tools/config-generator/main.go
  tools/config-generator/perf_config.go
  tools/config-generator/periodic_config.go
  tools/config-generator/presubmit_config.go
Labels: approved, cla: yes, lgtm, size/L

#2052 Remove Prow jobs for observability
  config/prod/prow/config_knative.yaml
  config/prod/prow/core/config.yaml
  config/prod/prow/core/plugins.yaml
  config/prod/prow/jobs/config.yaml
  config/prod/prow/testgrid/testgrid.yaml
Labels: approved, cla: yes, lgtm, size/L

#2053 Fix the path of testgrid config file
  config/prod/Makefile
Labels: approved, cla: yes, lgtm, size/XS

#2045 Print out "go env" in the test flows
  scripts/presubmit-tests.sh
Labels: approved, cla: yes, lgtm, size/XS

#2054 Add --github-token-path config for crier and hook
  config/staging/prow/cluster/400-crier.yaml
  config/staging/prow/cluster/400-hook.yaml
Labels: approved, cla: yes, lgtm, size/XS

#2057 Attempt fixing dep-collector
  tools/dep-collector/README.md
  tools/dep-collector/licenses.go
  tools/dep-collector/main.go
Labels: approved, cla: yes, lgtm, size/L

#2058 Fix CI/CD flows on release branches
  config/prod/prow/config_knative.yaml
  config/prod/prow/jobs/config.yaml
  config/prod/prow/testgrid/testgrid.yaml
  images/prow-tests-go113/Dockerfile
  images/prow-tests-go113/Makefile
  images/prow-tests-go113/README.md
  tools/config-generator/main.go
Labels: approved, cla: yes, lgtm, size/XL

#2044 Add beta prow-tests CI flows and cleanup code
  config/prod/prow/jobs/config.yaml
  config/prod/prow/testgrid/testgrid.yaml
  tools/config-generator/main.go
  tools/config-generator/periodic_config.go
  tools/config-generator/presubmit_config.go
  tools/config-generator/testgrid_config.go
  tools/config-generator/types.go
  tools/config-generator/types_test.go
Labels: approved, cla: yes, lgtm, size/XXL

#2061 Add last good dep-collector to the prow-tests image
  images/prow-tests/Dockerfile
Labels: approved, cla: yes, lgtm, size/XS

#2062 Fix GOPATH in gvm-based prow-tests image
  images/prow-tests/Dockerfile
  images/prow-tests/runner.sh
Labels: approved, cla: yes, lgtm, size/S

#2066 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/test/e2e_flags.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XS

#2067 Fix missing copyright and warn on silent go-license failure
  scripts/library.sh
  scripts/shellcheck-presubmit.sh
Labels: approved, cla: yes, lgtm, size/S

#2065 Prow tests alpha jobs fix image name
  config/prod/prow/jobs/config.yaml
  tools/config-generator/main.go
  tools/config-generator/periodic_config.go
Labels: approved, cla: yes, lgtm, size/M

#2072 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/test/kube_checks.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#2073 Add missing RBAC for hook
  config/staging/prow/cluster/301-rbac.yaml
Labels: approved, cla: yes, lgtm, size/XS

#2070 Enable flaky test retryer for knative-gcp
  config/prod/prow/config_knative.yaml
  config/prod/prow/jobs/config.yaml
  tools/flaky-test-reporter/config/config.go
  tools/flaky-test-reporter/config/config.yaml
  tools/flaky-test-reporter/constants.go
  tools/flaky-test-reporter/github_issue.go
  tools/flaky-test-reporter/github_issue_test.go
Labels: approved, cla: yes, lgtm, size/L

#2075 Remove deprecation warnings from Prow
  config/staging/prow/core/config.yaml
  tools/config-generator/templates/prow-staging/prow_config.yaml
Labels: approved, cla: yes, lgtm, size/S

#2080 Kick config updater
  config/staging/prow/core/config.yaml
  tools/config-generator/templates/prow-staging/prow_config.yaml
Labels: approved, cla: yes, lgtm, size/XS

#2086 Fixing flaky test reporter failure
  images/flaky-test-reporter/Dockerfile
  tools/flaky-test-reporter/github_issue.go
Labels: approved, cla: yes, lgtm, size/S

#2082 Spyglass highlights 'Metrics logs'.
  config/staging/prow/core/config.yaml
  tools/config-generator/templates/prow-staging/prow_config.yaml
Labels: approved, cla: yes, lgtm, size/XS

#2083 Move all boskos to staging build cluster
  config/staging/build-cluster/boskos/boskos_resources.yaml
  config/staging/prow/boskos/boskos_resources.yaml
Labels: approved, cla: yes, lgtm, size/XS

#2093 Pin pkg to 0.15
  go.mod
  go.sum
  hack/update-deps.sh
  tools/flaky-test-reporter/jsonreport/jsonreport.go
  tools/flaky-test-reporter/result.go
  tools/flaky-test-retryer/log_parser.go
  vendor/knative.dev/pkg/test/prow/prow.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/S

#2094 Update deps
  go.mod
  go.sum
  hack/update-codegen.sh
  tools/flaky-test-reporter/jsonreport/jsonreport.go
  tools/flaky-test-reporter/result.go
  tools/flaky-test-retryer/log_parser.go
  vendor/knative.dev/pkg/test/prow/prow.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/S

#2095 update flaky test retryer to the latest image
  tools/flaky-test-retryer/gke_deployment/retryer_service.yaml
Labels: approved, cla: yes, lgtm, size/XS

#2077 Unify images to reduce burden and add testing
  images/clear-test-infra-alerts/Dockerfile
  images/clear-test-infra-alerts/Makefile
  images/flaky-test-reporter/Makefile
  images/flaky-test-retryer/Dockerfile
  images/flaky-test-retryer/Makefile
  images/monitoring/Dockerfile
  images/monitoring/Makefile
  images/prow-tests/Dockerfile
  images/simple-image.mk
  images/tool/Dockerfile
  images/tool/README.md
Labels: approved, cla: yes, lgtm, size/L

#2097 Cleanup coverage prior to deprecating
  images/coverage-go114/Dockerfile
  images/coverage/Dockerfile
Labels: approved, cla: yes, lgtm, size/S

#2096 Consolidate prow-tests images
  config/prod/prow/jobs/config.yaml
  config/staging/prow/jobs/config.yaml
  tools/config-generator/main.go
  tools/config-generator/perf_config.go
  tools/config-generator/periodic_config.go
  tools/config-generator/postsubmit_config.go
  tools/config-generator/presubmit_config.go
  tools/config-generator/types.go
Labels: approved, cla: yes, lgtm, size/XL

#2100 Move 'operator' from knative-sandbox to knative.
  config/prod/prow/config_knative.yaml
  config/prod/prow/core/config.yaml
  config/prod/prow/core/plugins.yaml
  config/prod/prow/jobs/config.yaml
  config/prod/prow/testgrid/testgrid.yaml
Labels: approved, cla: yes, lgtm, size/L

#2101 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/test/spoof/spoof.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/S

#2099 Add github-token-path for needs-rebase
  config/staging/prow/cluster/500-needs-rebase.yaml
Labels: approved, cla: yes, lgtm, size/XS

#2000 Configurator use docker run
  config/prow_common.mk
Labels: approved, cla: yes, lgtm, size/S

#2098 Prepare for coverage in prow-tests
  config/prod/prow/jobs/config.yaml
  config/prod/prow/testgrid/testgrid.yaml
  images/prow-tests/Dockerfile
  images/prow-tests/coverage.sh
  images/prow-tests/in-gvm-env.sh
  images/prow-tests/runner.sh
  images/prow-tests/source-gvm-and-run.sh
  tools/config-generator/main.go
  tools/config-generator/periodic_config.go
  tools/config-generator/postsubmit_config.go
  tools/config-generator/templates/prow_postsubmit_gocoverage_job.yaml
  tools/config-generator/testgrid_config.go
  tools/config-generator/types.go
Labels: approved, cla: yes, lgtm, size/XL

#2106 Document prow-tests:beta flow and how to use it
  images/prow-tests/Makefile
  images/prow-tests/README.md
  images/simple-image.mk
Labels: approved, cla: yes, lgtm, size/M

#2110 Add coverage job for eventing-kafka
  config/prod/prow/config_knative.yaml
  config/prod/prow/jobs/config.yaml
  config/prod/prow/testgrid/testgrid.yaml
Labels: approved, cla: yes, lgtm, size/L

#2111 Fixing testgrid config updater by passing GOOGLE_APPLICATION_CREDENTIALS
  config/prod/prow/jobs/custom-jobs.yaml
  config/prow_common.mk
Labels: approved, cla: yes, lgtm, size/S

#2068 Create script to "vendor" test-infra/scripts
  scripts/update-test-infra.sh
Labels: approved, cla: yes, lgtm, size/M

#2112 Cleanup images
  config/prod/prow/jobs/config.yaml
  images/coverage-go114/Dockerfile
  images/coverage-go114/Makefile
  images/coverage/Dockerfile
  images/coverage/Makefile
  images/prow-tests-go113/Dockerfile
  images/prow-tests-go113/Makefile
  images/prow-tests-go113/README.md
  images/prow-tests-go114/Dockerfile
  images/prow-tests-go114/Makefile
  images/prow-tests-go114/README.md
  images/prow-tests/Makefile
  tools/config-generator/main.go
  tools/config-generator/periodic_config.go
  tools/config-generator/postsubmit_config.go
  tools/config-generator/presubmit_config.go
  tools/config-generator/templates/prow_postsubmit_gocoverage_job.yaml
  tools/config-generator/templates/prow_presubmit_gocoverage_job.yaml
  tools/coverage/README.md
Labels: approved, cla: yes, lgtm, size/XL

#2121 Revert "Revert "Cleanup images (#2112)" (#2117)"
  config/prod/prow/jobs/config.yaml
  images/coverage-go114/Dockerfile
  images/coverage-go114/Makefile
  images/coverage/Dockerfile
  images/coverage/Makefile
  images/prow-tests-go113/Dockerfile
  images/prow-tests-go113/Makefile
  images/prow-tests-go113/README.md
  images/prow-tests-go114/Dockerfile
  images/prow-tests-go114/Makefile
  images/prow-tests-go114/README.md
  images/prow-tests/Makefile
  tools/config-generator/main.go
  tools/config-generator/periodic_config.go
  tools/config-generator/postsubmit_config.go
  tools/config-generator/presubmit_config.go
  tools/config-generator/templates/prow_postsubmit_gocoverage_job.yaml
  tools/config-generator/templates/prow_presubmit_gocoverage_job.yaml
  tools/coverage/README.md
Labels: approved, cla: yes, lgtm, size/XL

#2108 Simplify prow configs by defining on org level
  tools/config-generator/main.go
  tools/config-generator/templates/prow-staging/prow_config.yaml
  tools/config-generator/templates/prow-staging/prow_plugins.yaml
Labels: approved, cla: yes, lgtm, size/M

#2124 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/kmeta/map.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/S

#2126 Increase knative-gcp build memory limits to match knative/serving
  config/prod/prow/config_knative.yaml
  config/prod/prow/jobs/config.yaml
Labels: approved, cla: yes, lgtm, size/S

#2125 Fixing run_job.sh
  config/prod/prow/run_job.sh
Labels: approved, cla: yes, lgtm, size/M

#2128 Update prow to v20200528-4abea382ef
  config/staging/prow/core/config.yaml
  tools/config-generator/templates/prow-staging/prow_config.yaml
Labels: approved, cla: yes, lgtm, size/S

#2130 Add comment for run_job.sh
  config/prod/prow/run_job.sh
Labels: approved, cla: yes, lgtm, size/XS

#2131 Update go.mod to specify the module is go1.14
  go.mod
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/S
