Repository knative/test-infra, pull requests merged in 2020-10, with the labels that each got.

#2472 looks like I missed an update for camel, and duped discovery
  config/prod/prow/config_knative.yaml
Labels: approved, cla: yes, lgtm, size/XS

#2476 Remove markdown checks from the bash scripts
  scripts/library.sh
  scripts/markdown-link-check-config.rc
  scripts/markdown-lint-config.rc
  scripts/presubmit-tests.sh
Labels: approved, cla: yes, lgtm, size/M

#2475 Removed failed unit tests when it's run with GitHub Actions
  tools/cleanup/cleanup_test.go
  tools/coverage/calc/calcTestExports/covList_test.go
  tools/coverage/calc/calc_test.go
  tools/coverage/githubUtil/github_test.go
  tools/coverage/presubmit_test.go
  tools/coverage/test/env.go
  tools/coverage/testgrid/folder_test.go
  tools/coverage/testgrid/testsuiteXmlWriter_test.go
Labels: approved, cla: yes, lgtm, size/L

#2479 Remove optional markdown checks from docs pre-submit test
  config/prod/prow/config_knative.yaml
  config/prod/prow/jobs/config.yaml
Labels: approved, cla: yes, lgtm, size/M

#2473 Increase unit test coverage from 46% to 82% for config-generator tool
  tools/config-generator/customjobs_test.go
  tools/config-generator/getlivebranch_test.go
  tools/config-generator/main_test.go
  tools/config-generator/perf_config_test.go
  tools/config-generator/periodic_config_test.go
  tools/config-generator/postsubmit_config_test.go
  tools/config-generator/presubmit_config_test.go
  tools/config-generator/testgrid_config_test.go
Labels: approved, cla: yes, lgtm, size/XL

#2482 nromalize owners to include WG leads and TOC
  OWNERS
  OWNERS_ALIASES
Labels: approved, cla: yes, lgtm, size/S

#2483 Enable fetching of go-import headers
  pkg/golang/goimport.go
  pkg/golang/goimport_test.go
  vendor/golang.org/x/net/html/atom/atom.go
  vendor/golang.org/x/net/html/atom/table.go
  vendor/golang.org/x/net/html/const.go
  vendor/golang.org/x/net/html/doc.go
  vendor/golang.org/x/net/html/doctype.go
  vendor/golang.org/x/net/html/entity.go
  vendor/golang.org/x/net/html/escape.go
  vendor/golang.org/x/net/html/foreign.go
  vendor/golang.org/x/net/html/node.go
  vendor/golang.org/x/net/html/parse.go
  vendor/golang.org/x/net/html/render.go
  vendor/golang.org/x/net/html/token.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XXL

#2461 [Automated] Update actions
  .github/workflows/knative-boilerplate.yaml
  .github/workflows/knative-style.yaml
  .github/workflows/knative-verify.yaml
Labels: approved, cla: yes, lgtm, size/L

#2485 [Automated] Update actions
  .github/workflows/knative-boilerplate.yaml
  .github/workflows/knative-go-test.yaml
  .github/workflows/knative-security.yaml
  .github/workflows/knative-style.yaml
Labels: approved, cla: yes, lgtm, size/M

#2486 Add --platform=all to our default KO_FLAGS.
  scripts/release.sh
Labels: approved, cla: yes, lgtm, size/XS

#2487 Adding go module parsing to understand which deps are needed.
  go.mod
  pkg/gomod/modules.go
  pkg/gomod/modules_test.go
  pkg/gomod/testdata/bad.example
  pkg/gomod/testdata/gomod.example1
  pkg/gomod/testdata/gomod.example2
  third_party/VENDOR-LICENSE/golang.org/x/mod/LICENSE
  third_party/VENDOR-LICENSE/golang.org/x/xerrors/LICENSE
  vendor/golang.org/x/mod/internal/lazyregexp/lazyre.go
  vendor/golang.org/x/mod/modfile/print.go
  vendor/golang.org/x/mod/modfile/read.go
  vendor/golang.org/x/mod/modfile/rule.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XXL

#2488 This adds functions that check and calculate refs for best deps based on a release.
  pkg/gomod/check.go
  pkg/gomod/check_test.go
  pkg/gomod/float.go
  pkg/gomod/float_test.go
  pkg/gomod/modules.go
Labels: approved, cla: yes, lgtm, size/L

#2489 adding buoy cli
  buoy/README.md
  buoy/buoy.go
  buoy/commands/check.go
  buoy/commands/commands.go
  buoy/commands/float.go
  buoy/commands/needs.go
  pkg/git/git.go
  pkg/git/git_test.go
  pkg/golang/goimport.go
  pkg/gomod/check.go
  pkg/gomod/check_test.go
  pkg/gomod/float.go
  pkg/gomod/float_test.go
  pkg/gomod/modules.go
  pkg/gomod/testdata/gomod.check1
  pkg/gomod/testdata/gomod.float1
Labels: approved, cla: yes, lgtm, size/XL

#2492 introduce a bash entry point for update deps
  hack/update-deps.sh
  scripts/library.sh
Labels: approved, cla: yes, lgtm, size/M

#2494 delete anything we know about that should not be vendored
  scripts/library.sh
  vendor/k8s.io/test-infra/prow/config/secret/BUILD.bazel
  vendor/k8s.io/test-infra/prow/logrusutil/BUILD.bazel
  vendor/k8s.io/test-infra/prow/version/BUILD.bazel
Labels: approved, cla: yes, lgtm, size/L

#2501 Bumping dependeny
  go.mod
  go.sum
  vendor/github.com/google/go-containerregistry/pkg/name/tag.go
  vendor/github.com/google/go-containerregistry/pkg/v1/partial/README.md
  vendor/github.com/google/go-containerregistry/pkg/v1/remote/README.md
  vendor/github.com/google/go-containerregistry/pkg/v1/remote/catalog.go
  vendor/github.com/google/go-containerregistry/pkg/v1/remote/check.go
  vendor/github.com/google/go-containerregistry/pkg/v1/remote/delete.go
  vendor/github.com/google/go-containerregistry/pkg/v1/remote/descriptor.go
  vendor/github.com/google/go-containerregistry/pkg/v1/remote/image.go
  vendor/github.com/google/go-containerregistry/pkg/v1/remote/index.go
  vendor/github.com/google/go-containerregistry/pkg/v1/remote/list.go
  vendor/github.com/google/go-containerregistry/pkg/v1/remote/options.go
  vendor/github.com/google/go-containerregistry/pkg/v1/remote/transport/bearer.go
  vendor/github.com/google/go-containerregistry/pkg/v1/remote/transport/error.go
  vendor/github.com/google/go-containerregistry/pkg/v1/remote/write.go
  vendor/golang.org/x/net/http2/transport.go
  vendor/golang.org/x/tools/internal/gopathwalk/walk.go
  vendor/golang.org/x/tools/internal/imports/fix.go
  vendor/golang.org/x/tools/internal/imports/mod.go
  vendor/golang.org/x/tools/internal/imports/zstdlib.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#2502 Forcing go-containerregistry
  go.mod
  go.sum
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#2505 Revert "Forcing go-containerregistry"
  go.mod
  go.sum
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#2506 Add redis to nightly and auto-release
  config/prod/prow/config_knative.yaml
  config/prod/prow/jobs/config.yaml
  config/prod/prow/testgrid/testgrid.yaml
Labels: approved, cla: yes, lgtm, size/L

#2500 adding `exists` command for buoy
  buoy/README.md
  buoy/commands/check.go
  buoy/commands/commands.go
  buoy/commands/exists.go
  buoy/commands/float.go
  buoy/commands/needs.go
  pkg/git/git.go
  pkg/git/git_test.go
  pkg/gomod/release_meta.go
  pkg/gomod/release_meta_test.go
  pkg/gomod/testdata/gomod.next1
Labels: approved, cla: yes, lgtm, size/L

#2508 Clean up prow-tests image a bit
  images/prow-tests/Dockerfile
Labels: approved, cla: yes, lgtm, size/XS

#2496 Configure branch protector for Knative
  config/branch_protector/README.md
  config/branch_protector/rules.yaml
  config/label_sync/README.md
  config/label_sync/labels.yaml
  config/prod/prow/jobs/custom/branchprotector.yaml
  config/prod/prow/jobs/custom/label-sync.yaml
Labels: approved, cla: yes, lgtm, size/L

#2509 Add Sample Source to release/nightlies
  config/prod/prow/config_knative.yaml
  config/prod/prow/jobs/config.yaml
  config/prod/prow/testgrid/testgrid.yaml
Labels: approved, cla: yes, lgtm, size/L

#2510 [Automated] Format markdown
  config/branch_protector/README.md
  config/label_sync/README.md
Labels: approved, cla: yes, lgtm, size/S

#2513 Add test and release label
  config/label_sync/labels.yaml
Labels: approved, cla: yes, lgtm, size/XS

#2515 Update Go versions to the latest and some cleanups
  config/prod/prow/jobs/custom/experimental.yaml
  images/prow-tests/Dockerfile
Labels: approved, cla: yes, lgtm, size/M

#2512 Fix shellcheck file search
  scripts/library.sh
  scripts/shellcheck-presubmit.sh
Labels: approved, cla: yes, lgtm, size/XS

#2516 Add prow job for knative-gcp conformance tests
  config/prod/prow/config_knative.yaml
  config/prod/prow/jobs/config.yaml
Labels: approved, cla: yes, lgtm, size/M

#2521 bypass the golang proxy for upgrades if GOPROXY is not set
  scripts/library.sh
Labels: approved, cla: yes, lgtm, size/S

#2511 Add ProwJobs annotations field
  config/prod/prow/jobs/config.yaml
  tools/config-generator/main.go
  tools/config-generator/periodic_config.go
  tools/config-generator/templates/prow_periodic_test_job.yaml
  tools/config-generator/testgrid_config.go
  tools/config-generator/testgrid_config_test.go
Labels: approved, cla: yes, lgtm, size/XXL

#2522 Specify resource requirements in knative-gcp conformance tests
  config/prod/prow/config_knative.yaml
  config/prod/prow/jobs/config.yaml
Labels: approved, cla: yes, lgtm, size/S

#2520 drop monitoring helpers in the bash lib
  scripts/library.sh
Labels: approved, cla: yes, lgtm, size/S

#2519 Clean up prow-tests image
  images/prow-tests/Dockerfile
Labels: approved, cla: yes, lgtm, size/M

#2523 Rename short text metric
  tools/config-generator/testgrid_config.go
  tools/config-generator/testgrid_config_test.go
Labels: approved, cla: yes, lgtm, size/XS

#2524 Use random cluster name for e2e tests and another nit update
  kntest/pkg/kubetest2/gke/options.go
  pkg/clustermanager/kubetest2/gke.go
Labels: approved, cla: yes, lgtm, size/S

#2527 Fix config generator to generate the correct value for field 'optional'
  config/prod/prow/config_knative.yaml
  config/prod/prow/jobs/config.yaml
  tools/config-generator/main.go
  tools/config-generator/main_test.go
  tools/config-generator/templates/prow_presubmit_job.yaml
Labels: approved, cla: yes, lgtm, size/L

#2528 pin to code-generator 18.8
  go.mod
  go.sum
  vendor/github.com/google/go-containerregistry/pkg/v1/google/auth.go
  vendor/github.com/google/go-containerregistry/pkg/v1/google/list.go
  vendor/github.com/google/go-containerregistry/pkg/v1/google/options.go
  vendor/github.com/google/go-containerregistry/pkg/v1/progress.go
  vendor/github.com/google/go-containerregistry/pkg/v1/remote/index.go
  vendor/github.com/google/go-containerregistry/pkg/v1/remote/transport/error.go
  vendor/golang.org/x/crypto/ssh/kex.go
  vendor/k8s.io/apimachinery/pkg/util/errors/errors.go
  vendor/k8s.io/apimachinery/pkg/util/validation/validation.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#2529 feat: Add upgrade test for knative-gcp in CI job
  config/prod/prow/config_knative.yaml
  config/prod/prow/jobs/config.yaml
Labels: approved, cla: yes, lgtm, size/M

#2532 Optimize unwanted file removal a bit
  scripts/library.sh
Labels: approved, cla: yes, lgtm, size/XS

#2530 [Automated] Update actions
  .github/workflows/knative-boilerplate.yaml
  .github/workflows/knative-donotsubmit.yaml
  .github/workflows/knative-go-build.yaml
  .github/workflows/knative-go-test.yaml
  .github/workflows/knative-releasability.yaml
  .github/workflows/knative-security.yaml
  .github/workflows/knative-stale.yaml
  .github/workflows/knative-style.yaml
  .github/workflows/knative-verify.yaml
Labels: approved, cla: yes, lgtm, ok-to-test, size/L

#2535 Increase Pod timeout for continuous periodic jobs
  config/prod/prow/jobs/config.yaml
  tools/config-generator/periodic_config.go
  tools/config-generator/templates/prow_periodic_test_job.yaml
Labels: approved, cla: yes, lgtm, size/L

#2537 Build stripped binaries to reduce sizes
  scripts/release.sh
Labels: approved, cla: yes, lgtm, size/XS

#2538 fix prow-tests image; go-licenses is a terrible tool
  images/prow-tests/Dockerfile
Labels: approved, cla: yes, lgtm, size/XS

#2539 Increase the timeout for release jobs and cleanups
  config/prod/prow/config_knative.yaml
  config/prod/prow/jobs/config.yaml
  config/prod/prow/testgrid/testgrid.yaml
  tools/config-generator/periodic_config.go
  tools/config-generator/periodic_config_test.go
  tools/config-generator/testgrid_config.go
  tools/config-generator/testgrid_config_test.go
Labels: approved, cla: yes, lgtm, size/XL

#2544 [Automated] Update actions
  .github/workflows/knative-releasability.yaml
  .github/workflows/knative-style.yaml
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#2545 Add a heartbeat job
  config/prod/prow/jobs/custom/test-infra.yaml
Labels: approved, cla: yes, lgtm, size/S

#2546 Heartbeat job requests only 0.1CPU
  config/prod/prow/jobs/custom/test-infra.yaml
Labels: approved, cla: yes, lgtm, size/XS
