Repository knative/test-infra, pull requests merged in 2020-01, with the labels that each got.

#1606 Updated prow and testgrid config licenses for 2020
  ci/prow/config.yaml
  ci/prow/testgrid.yaml
Labels: approved, lgtm, size/XS

#1608 Add CI jobs for new Knative releases
  ci/prow/config.yaml
  ci/prow/config_knative.yaml
  ci/prow/testgrid.yaml
Labels: approved, lgtm, size/XL

#1612 Add dot-dev for all Serving jobs
  ci/prow/config.yaml
  ci/prow/config_knative.yaml
Labels: approved, lgtm, size/M

#1610 Ignore copyright year in config file when testing it
  ci/prow/Makefile
Labels: approved, lgtm, size/XS

#1605 Update Boskos Projects Permission
  ci/prow/README.md
  ci/prow/set_boskos_permissions.sh
  ci/prow/update_all_boskos_permissions.sh
Labels: approved, lgtm, size/M

#1613 Format markdown
  ci/prow/README.md
Labels: approved, lgtm, size/XS

#1616 Add CI jobs for Contour.
  ci/prow/config.yaml
  ci/prow/config_knative.yaml
  ci/prow/testgrid.yaml
  shared/testgrid/testgrid.go
  tools/flaky-test-reporter/config/config.yaml
Labels: approved, lgtm, size/L

#1618 Enable cloudscheduler API for boskos projects
  ci/prow/set_boskos_permissions.sh
Labels: approved, lgtm, size/XS

#1619 Add Scheduler admin role to Prow test service account
  ci/prow/set_boskos_permissions.sh
Labels: approved, lgtm, size/XS

#1621 Create App Engine app for boskos projects
  ci/prow/README.md
  ci/prow/set_up_boskos_project.sh
  ci/prow/update_all_boskos_projects.sh
Labels: approved, lgtm, size/S

#1620 Change eventing release file name to eventing.yaml
  scripts/library.sh
Labels: approved, lgtm, size/XS

#1625 update the boskos janitor
  ci/prow/deployments/boskos_janitor.yaml
Labels: approved, lgtm, size/XS

#1598 Prow job to run serving e2e against ambassador
  ci/prow/config.yaml
  ci/prow/config_knative.yaml
  ci/prow/testgrid.yaml
  shared/testgrid/testgrid.go
  tools/flaky-test-reporter/config/config.yaml
Labels: approved, lgtm, ok-to-test, size/L

#1628 ProwAutoBumper also updates images for boskos
  tools/prow-auto-bumper/config.go
  tools/prow-auto-bumper/file.go
  tools/prow-auto-bumper/parser.go
Labels: approved, lgtm, size/S

#1634 Remove CI jobs for release-0.8
  ci/prow/config.yaml
  ci/prow/config_knative.yaml
  ci/prow/testgrid.yaml
Labels: approved, lgtm, size/XL

#1630 Add CI jobs for release-0.12
  ci/prow/config.yaml
  ci/prow/config_knative.yaml
  ci/prow/testgrid.yaml
Labels: approved, lgtm, size/L

#1635 Also highlight error message when Prow job is killed
  ci/prow/config.yaml
  ci/prow/templates/prow_config_header.yaml
Labels: approved, lgtm, size/XS

#1636 Deal with missing tags/manifests in get_latest_knative_yaml_source
  scripts/library.sh
Labels: approved, lgtm, size/M

#1639 Add knative/net-contour CI jobs
  ci/prow/config.yaml
  ci/prow/config_knative.yaml
  ci/prow/plugins.yaml
  ci/prow/testgrid.yaml
Labels: approved, lgtm, size/L

#1641 Prow jobs for net-contour repo use go1.13
  ci/prow/config.yaml
  ci/prow/config_knative.yaml
  ci/prow/testgrid.yaml
Labels: approved, lgtm, size/L

#1643 dotdev for net-contour CI jobs
  ci/prow/config.yaml
  ci/prow/config_knative.yaml
Labels: approved, lgtm, size/XS

#1646 golang format tools
  ci/prow/periodic_config.go
  tools/cleanup/cleanup.go
  tools/cleanup/cleanup_test.go
Labels: approved, lgtm, ok-to-test, size/M

#1649 Use e2 VMs instead of n1 for test clusters
  scripts/README.md
  scripts/e2e-tests.sh
Labels: approved, lgtm, size/XS

#1648 Fix spelling errors
  tools/cleanup/cleanup.go
Labels: approved, lgtm, size/XS

#1642 Update OWNERS_ALIASES for Productivity WG
  OWNERS_ALIASES
Labels: approved, lgtm, size/XS

#1650 Fix eventing release file name
  scripts/library.sh
Labels: approved, lgtm, size/XS

#1651 Enable welcome plugin
  ci/prow/plugins.yaml
  ci/prow/templates/prow_plugins.yaml
Labels: approved, lgtm, size/M
