Repository knative/test-infra, pull requests merged in 2020-12, with the labels that each got.

#2594 Add prow jobs for knative-sandbox/kn-plugin-admin
  config/prod/prow/config_knative.yaml
  config/prod/prow/jobs/config.yaml
  config/prod/prow/k8s-testgrid/k8s-testgrid.yaml
  config/prod/prow/testgrid/testgrid.yaml
Labels: approved, cla: yes, lgtm, size/L

#2574 Unique dashboard group, dashboard, and tab names in k8s testgrid
  config/prod/prow/jobs/config.yaml
  config/prod/prow/k8s-testgrid/k8s-testgrid.yaml
  tools/config-generator/k8s_testgrid_config.go
  tools/config-generator/main.go
  tools/config-generator/perf_config.go
  tools/config-generator/periodic_config.go
  tools/config-generator/templates/prow_periodic_custom_job.yaml
  tools/config-generator/templates/prow_postsubmit_gocoverage_job.yaml
  tools/config-generator/templates/prow_postsubmit_perf_job.yaml
  tools/config-generator/testgrid_config.go
  tools/config-generator/utils.go
  tools/config-generator/utils_test.go
Labels: approved, cla: yes, lgtm, size/XXL

#2596 Update prow configs for kn-plugin-admin
  config/prod/prow/config_knative.yaml
  config/prod/prow/jobs/config.yaml
  config/prod/prow/k8s-testgrid/k8s-testgrid.yaml
  config/prod/prow/testgrid/testgrid.yaml
Labels: approved, cla: yes, lgtm, size/L

#2595 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  scripts/codegen-library.sh
  scripts/library.sh
  scripts/microbenchmarks.sh
  vendor/knative.dev/hack/codegen-library.sh
  vendor/knative.dev/hack/library.sh
  vendor/knative.dev/hack/microbenchmarks.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#2597 Add other branches to do dot-release for operator
  config/prod/prow/config_knative.yaml
  config/prod/prow/jobs/config.yaml
  config/prod/prow/testgrid/testgrid.yaml
Labels: approved, cla: yes, lgtm, size/L

#2599 add arg to specify fork
  config/prod/prow/jobs/custom/test-infra.yaml
Labels: approved, cla: yes, lgtm, size/XS

#2600 remove arg
  config/prod/prow/jobs/custom/test-infra.yaml
Labels: approved, cla: yes, lgtm, size/XS

#2601 Do not protect knative/.github repo
  config/branch_protector/rules.yaml
Labels: approved, cla: yes, lgtm, size/XS

#2603 Fix git url for a couple of plugin repos
  config/prod/prow/config_knative.yaml
  config/prod/prow/jobs/config.yaml
  config/prod/prow/k8s-testgrid/k8s-testgrid.yaml
  config/prod/prow/testgrid/testgrid.yaml
Labels: approved, cla: yes, lgtm, size/L

#2604 Add release config for kn-plugin-source-kafka
  config/prod/prow/config_knative.yaml
  config/prod/prow/jobs/config.yaml
  config/prod/prow/testgrid/testgrid.yaml
Labels: approved, cla: yes, lgtm, size/L

#2605 move beta-prow-tests to their own dashboard
  config/prod/prow/jobs/config.yaml
  config/prod/prow/k8s-testgrid/k8s-testgrid.yaml
  tools/config-generator/main.go
  tools/config-generator/periodic_config.go
  tools/config-generator/testgrid_config.go
  tools/config-generator/testgrid_config_test.go
Labels: approved, cla: yes, lgtm, size/L

#2606 beta prow tests for go coverage jobs need to go in knative-prow-tests dashboard
  config/prod/prow/jobs/config.yaml
  tools/config-generator/periodic_config.go
Labels: approved, cla: yes, lgtm, size/M

#2531 Add a rundk tool to help reproduce the same test flows as run in CI
  go.mod
  pkg/interactive/docker.go
  rundk/README.md
  rundk/main.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#2602 [Automated] Update actions
  .github/workflows/knative-boilerplate.yaml
  .github/workflows/knative-donotsubmit.yaml
  .github/workflows/knative-go-build.yaml
  .github/workflows/knative-go-test.yaml
  .github/workflows/knative-releasability.yaml
  .github/workflows/knative-security.yaml
  .github/workflows/knative-style.yaml
  .github/workflows/knative-verify.yaml
Labels: approved, cla: yes, lgtm, size/S

#2607 [Automated] Format markdown
  rundk/README.md
Labels: approved, cla: yes, lgtm, size/XS

#2608 Fixes and improvements to the rundk tool
  rundk/README.md
  rundk/main.go
Labels: approved, cla: yes, lgtm, size/M

#2611 disable go-coverage for kn-plugin-diag
  config/prod/prow/config_knative.yaml
  config/prod/prow/jobs/config.yaml
  config/prod/prow/testgrid/testgrid.yaml
Labels: approved, cla: yes, lgtm, ok-to-test, size/L

#2610 Define rundk tool as a submodule
  go.mod
  go.sum
  rundk/go.mod
  rundk/go.sum
  rundk/interactive/command.go
  rundk/interactive/command_test.go
  rundk/interactive/docker.go
  rundk/interactive/docker_test.go
  rundk/main.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#2612 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  scripts/library.sh
  vendor/knative.dev/hack/library.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/S

#2613 Separate the upgrade tests in operator
  config/prod/prow/config_knative.yaml
  config/prod/prow/jobs/config.yaml
Labels: approved, cla: yes, lgtm, size/M

#2614 [Automated] Update actions
  .github/workflows/knative-style.yaml
Labels: approved, cla: yes, lgtm, size/M

#2615 Add prow jobs for knative-sandbox/net-ingressv2
  config/prod/prow/config_knative.yaml
  config/prod/prow/jobs/config.yaml
  config/prod/prow/k8s-testgrid/k8s-testgrid.yaml
  config/prod/prow/testgrid/testgrid.yaml
Labels: approved, cla: yes, kind/enhancement, lgtm, size/XL
