Repository knative/test-infra, pull requests merged in 2020-07, with the labels that each got.

#2259 Stop pushing prow-test image from prow so that other images can be pushed
  images/push-all.sh
Labels: approved, cla: yes, lgtm, size/XS

#2263 Bump mem for serving upgrade test
  config/prod/prow/config_knative.yaml
  config/prod/prow/jobs/config.yaml
Labels: approved, cla: yes, lgtm, size/S

#2265 Move interactive to test-infra and some refactor
  kntest/pkg/cluster/gke/commands.go
  kntest/pkg/cluster/gke/options.go
  pkg/clustermanager/boskos/boskos.go
  pkg/clustermanager/boskos/boskos_test.go
  pkg/clustermanager/boskos/fake/fake.go
  pkg/clustermanager/common/common.go
  pkg/clustermanager/common/common_test.go
  pkg/clustermanager/create.go
  pkg/clustermanager/delete.go
  pkg/clustermanager/get.go
  pkg/clustermanager/gke/client.go
  pkg/clustermanager/gke/config.go
  pkg/clustermanager/gke/doc.go
  pkg/clustermanager/gke/example_test.go
  pkg/clustermanager/gke/gke.go
  pkg/clustermanager/gke/gke_test.go
  pkg/clustermanager/gke/setup.go
  pkg/clustermanager/gke/setup_test.go
  pkg/clustermanager/gke/util.go
  pkg/clustermanager/gke/util_test.go
  pkg/clustermanager/request.go
  pkg/interactive/command.go
  pkg/interactive/command_test.go
  pkg/interactive/docker.go
  pkg/interactive/docker_test.go
Labels: approved, cla: yes, lgtm, size/L

#2266 More moving from knative.dev/pkg
  go.sum
  images/prow-tests/Dockerfile
  kntest/pkg/cluster/gke/commands.go
  kntest/pkg/cluster/gke/options.go
  pkg/clustermanager/e2e-tests/boskos/boskos.go
  pkg/clustermanager/e2e-tests/boskos/boskos_test.go
  pkg/clustermanager/e2e-tests/boskos/fake/fake.go
  pkg/clustermanager/e2e-tests/common/common.go
  pkg/clustermanager/e2e-tests/common/common_test.go
  pkg/clustermanager/e2e-tests/create.go
  pkg/clustermanager/e2e-tests/delete.go
  pkg/clustermanager/e2e-tests/get.go
  pkg/clustermanager/e2e-tests/gke/client.go
  pkg/clustermanager/e2e-tests/gke/config.go
  pkg/clustermanager/e2e-tests/gke/doc.go
  pkg/clustermanager/e2e-tests/gke/example_test.go
  pkg/clustermanager/e2e-tests/gke/gke.go
  pkg/clustermanager/e2e-tests/gke/gke_test.go
  pkg/clustermanager/e2e-tests/gke/setup.go
  pkg/clustermanager/e2e-tests/gke/setup_test.go
  pkg/clustermanager/e2e-tests/gke/util.go
  pkg/clustermanager/e2e-tests/gke/util_test.go
  pkg/clustermanager/e2e-tests/request.go
  pkg/clustermanager/perf-tests/main.go
  pkg/clustermanager/perf-tests/pkg/benchmark.go
  pkg/clustermanager/perf-tests/pkg/benchmark_test.go
  pkg/clustermanager/perf-tests/pkg/cluster.go
  pkg/clustermanager/perf-tests/pkg/cluster_test.go
  pkg/clustermanager/perf-tests/pkg/testdir/test-benchmark
  pkg/clustermanager/perf-tests/pkg/testdir/test-benchmark1/cluster.yaml
  pkg/clustermanager/perf-tests/pkg/testdir/test-benchmark2/cluster.yaml
  pkg/clustermanager/perf-tests/pkg/testdir/test-benchmark3/cluster.yaml
  pkg/clustermanager/perf-tests/pkg/testdir/test-benchmark4/noop.yaml
  pkg/gcs/client.go
  pkg/gcs/gcs.go
  pkg/gcs/mock/mock.go
  pkg/gcs/mock/mock_example_test.go
  pkg/prow/prow.go
Labels: approved, cla: yes, lgtm, size/XXL

#2256 Cleanup post prow config migration
  config/prod/prow/cluster/100-namespace.yaml
  config/prod/prow/cluster/200-cpu-limitrange.yaml
  config/prod/prow/cluster/200-memory-limitrange.yaml
  config/prod/prow/cluster/300-crds.yaml
  config/prod/prow/cluster/301-rbac.yaml
  config/prod/prow/cluster/302-gce-ssd-retain_storageclass.yaml
  config/prod/prow/cluster/400-crier.yaml
  config/prod/prow/cluster/400-deck.yaml
  config/prod/prow/cluster/400-ghproxy.yaml
  config/prod/prow/cluster/400-hook.yaml
  config/prod/prow/cluster/400-horologium.yaml
  config/prod/prow/cluster/400-ingress.yaml
  config/prod/prow/cluster/400-plank.yaml
  config/prod/prow/cluster/400-sinker.yaml
  config/prod/prow/cluster/400-tide.yaml
  config/prod/prow/cluster/500-needs-rebase.yaml
  config/prod/prow/cluster/500-status-reconciler.yaml
  config/prod/prow/core/config.yaml
  config/prod/prow/core/plugins.yaml
  config/prod/prow/jobs/custom/test-infra.yaml
  config/prow_common.mk
  tools/config-generator/main.go
  tools/prow-config-updater/config/config_test.go
Labels: approved, cla: yes, lgtm, size/XXL

#2272 Enable cloudbuild.googleapis.com APIs during Boskos project setup
  config/prod/build-cluster/boskos/set_up_boskos_project.sh
Labels: approved, cla: yes, lgtm, size/XS

#2267 Add DEVELOPMENT guide
  DEVELOPMENT.md
  README.md
Labels: approved, cla: yes, lgtm, size/M

#2270 Remove auto-bumper and config-updater
  third_party/VENDOR-LICENSE/k8s.io/klog/LICENSE
  tools/prow-auto-bumper/Makefile
  tools/prow-auto-bumper/README.md
  tools/prow-auto-bumper/config.go
  tools/prow-auto-bumper/file.go
  tools/prow-auto-bumper/getversion_test.go
  tools/prow-auto-bumper/main.go
  tools/prow-auto-bumper/parser.go
  tools/prow-auto-bumper/pullrequest.go
  tools/prow-config-updater/Makefile
  tools/prow-config-updater/README.md
  tools/prow-config-updater/config/config.go
  tools/prow-config-updater/config/config_test.go
  tools/prow-config-updater/github_commenter.go
  tools/prow-config-updater/github_commenter_test.go
  tools/prow-config-updater/main.go
  tools/prow-config-updater/presubmit-checker/README.md
  tools/prow-config-updater/presubmit-checker/main.go
  tools/prow-config-updater/pullrequest.go
  tools/prow-config-updater/slack_notification.go
  tools/prow-config-updater/updater.go
  vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go
  vendor/k8s.io/apimachinery/pkg/util/wait/doc.go
  vendor/k8s.io/apimachinery/pkg/util/wait/wait.go
  vendor/k8s.io/klog/.travis.yml
  vendor/k8s.io/klog/CONTRIBUTING.md
  vendor/k8s.io/klog/LICENSE
  vendor/k8s.io/klog/README.md
  vendor/k8s.io/klog/RELEASE.md
  vendor/k8s.io/klog/SECURITY_CONTACTS
  vendor/k8s.io/klog/code-of-conduct.md
  vendor/k8s.io/klog/go.mod
  vendor/k8s.io/klog/go.sum
  vendor/k8s.io/klog/klog.go
  vendor/k8s.io/klog/klog_file.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XXL

#2271 Delete staging prow configs
  config/staging/Makefile
  config/staging/build-cluster/README.md
  config/staging/build-cluster/add-secrets.sh
  config/staging/build-cluster/boskos/boskos_resources.yaml
  config/staging/build-cluster/cluster/200-cpu-limitrange.yaml
  config/staging/build-cluster/cluster/200-memory-limitrange.yaml
  config/staging/build-cluster/cluster/301-rbac.yaml
  config/staging/build-cluster/cluster/400-boskos-deployment.yaml
  config/staging/build-cluster/cluster/400-boskos-janitor.yaml
  config/staging/build-cluster/cluster/400-boskos-metrics.yaml
  config/staging/build-cluster/cluster/400-boskos-reaper.yaml
  config/staging/build-cluster/cluster/400-boskos.yaml
  config/staging/build-cluster/create-build-cluster.sh
  config/staging/prow/README.md
  config/staging/prow/boskos/boskos_resources.yaml
  config/staging/prow/cluster/100-namespace.yaml
  config/staging/prow/cluster/200-cpu-limitrange.yaml
  config/staging/prow/cluster/200-memory-limitrange.yaml
  config/staging/prow/cluster/300-crds.yaml
  config/staging/prow/cluster/301-rbac.yaml
  config/staging/prow/cluster/302-gce-ssd-retain_storageclass.yaml
  config/staging/prow/cluster/400-boskos-deployment.yaml
  config/staging/prow/cluster/400-boskos-janitor.yaml
  config/staging/prow/cluster/400-boskos-metrics.yaml
  config/staging/prow/cluster/400-boskos-reaper.yaml
  config/staging/prow/cluster/400-boskos.yaml
  config/staging/prow/cluster/400-crier.yaml
  config/staging/prow/cluster/400-deck.yaml
  config/staging/prow/cluster/400-ghproxy.yaml
  config/staging/prow/cluster/400-hook.yaml
  config/staging/prow/cluster/400-horologium.yaml
  config/staging/prow/cluster/400-ingress.yaml
  config/staging/prow/cluster/400-plank.yaml
  config/staging/prow/cluster/400-sinker.yaml
  config/staging/prow/cluster/400-tide.yaml
  config/staging/prow/cluster/500-needs-rebase.yaml
  config/staging/prow/cluster/500-status-reconciler.yaml
  config/staging/prow/config_staging.yaml
  config/staging/prow/core/config.yaml
  config/staging/prow/core/plugins.yaml
  config/staging/prow/jobs/config.yaml
Labels: approved, cla: yes, lgtm, size/XXL

#2274 Fix git command
  pkg/git/commit.go
Labels: approved, cla: yes, lgtm, size/XS

#2276 Fix git command in job syncer
  pkg/git/commit.go
Labels: approved, cla: yes, lgtm, size/XS

#2268 Add timestamp into Jobdata for more informative display by commenter
  tools/flaky-test-retryer/github_commenter.go
  tools/flaky-test-retryer/github_commenter_test.go
  tools/flaky-test-retryer/handler.go
  tools/flaky-test-retryer/log_parser.go
  tools/flaky-test-retryer/log_parser_test.go
  tools/flaky-test-retryer/subscriber/subscriber.go
  tools/flaky-test-retryer/subscriber/subscriber_test.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/M

#2282 Retryer use latest iamge
  tools/flaky-test-retryer/gke_deployment/retryer_service.yaml
Labels: approved, cla: yes, lgtm, size/XS

#2281 Fix run_job and pj_on_kind by downloading prow core config
  config/prod/prow/pj-on-kind.sh
  config/prod/prow/run_job.sh
Labels: approved, cla: yes, lgtm, size/S

#2283 Move net-http01 to knative-sandbox repo
  config/prod/prow/config_knative.yaml
  config/prod/prow/jobs/config.yaml
  config/prod/prow/testgrid/testgrid.yaml
Labels: approved, cla: yes, lgtm, size/L

#2284 Some improvements to the kntest cluster gke related commands.
  kntest/pkg/cluster/gke/README.md
  kntest/pkg/cluster/gke/options.go
  pkg/clustermanager/e2e-tests/create.go
  pkg/clustermanager/e2e-tests/gke/gke.go
  pkg/clustermanager/e2e-tests/gke/setup.go
  pkg/gke/request.go
  test/e2e-tests.sh
Labels: approved, cla: yes, lgtm, size/M

#2040 run shellcheck
  hack/generate-configs.sh
  hack/update-codegen.sh
  hack/update-deps.sh
  hack/verify-codegen.sh
  scripts/e2e-tests.sh
  scripts/library.sh
  scripts/performance-tests.sh
  scripts/presubmit-tests.sh
  scripts/release.sh
  test/e2e-tests.sh
  test/presubmit-tests.sh
  test/unit/release-tests.sh
Labels: approved, cla: yes, lgtm, size/L

#2280 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/cloud.google.com/go/pubsub/CHANGES.md
  vendor/cloud.google.com/go/pubsub/apiv1/doc.go
  vendor/cloud.google.com/go/pubsub/go.mod
  vendor/cloud.google.com/go/pubsub/go.sum
  vendor/cloud.google.com/go/pubsub/iterator.go
  vendor/cloud.google.com/go/pubsub/pullstream.go
  vendor/cloud.google.com/go/pubsub/subscription.go
  vendor/cloud.google.com/go/pubsub/topic.go
  vendor/golang.org/x/tools/cmd/goimports/goimports.go
  vendor/golang.org/x/tools/internal/imports/fix.go
  vendor/golang.org/x/tools/internal/imports/imports.go
  vendor/golang.org/x/tools/internal/imports/sortimports.go
  vendor/google.golang.org/api/container/v1beta1/container-api.json
  vendor/google.golang.org/api/container/v1beta1/container-gen.go
  vendor/google.golang.org/api/internal/settings.go
  vendor/google.golang.org/api/option/internaloption/internaloption.go
  vendor/google.golang.org/api/storage/v1/storage-api.json
  vendor/google.golang.org/api/storage/v1/storage-gen.go
  vendor/google.golang.org/api/transport/grpc/dial.go
  vendor/google.golang.org/api/transport/http/dial.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XXL

#2286 Auto deploy tools
  config/prod/prow/jobs/custom/test-infra.yaml
  config/prod/prow/testgrid/testgrid.yaml
  tools/config-generator/customjobs.go
  tools/flaky-test-retryer/gke_deployment/Makefile
Labels: approved, cla: yes, lgtm, size/M

#2285 Added labels for knative-sandbox/eventing-kafka-broker
  label_sync/labels.yaml
Labels: approved, cla: yes, lgtm, size/M

#2290 Fix peribolos Prow jobs by disabling --fix-team-repos and setting --tokens as a larger value
  config/prod/prow/jobs/custom/peribolos.yaml
Labels: approved, cla: yes, lgtm, size/S

#2288 Fix run_job.sh by exporting the Prow config file to a mountable path
  config/prod/prow/pj-on-kind.sh
  config/prod/prow/run_job.sh
Labels: approved, cla: yes, lgtm, size/S

#2279 Add sugar-controller extension setup
  scripts/library.sh
Labels: approved, cla: yes, lgtm, size/S

#2291 Improvements to the peribolos and label_sync Prow jobs
  config/prod/prow/jobs/custom/label-sync.yaml
  config/prod/prow/jobs/custom/peribolos.yaml
  label_sync/labels.yaml
Labels: approved, cla: yes, lgtm, size/L

#2292 Productivity oncalls owns custom jobs configs
  OWNERS_ALIASES
  config/prod/prow/jobs/custom/OWNERS
Labels: approved, cla: yes, lgtm, size/XS

#2294 Make Serving e2e resources uniform
  config/prod/prow/config_knative.yaml
  config/prod/prow/jobs/config.yaml
Labels: approved, cla: yes, lgtm, size/S

#2296 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/cloud.google.com/go/CHANGES.md
  vendor/cloud.google.com/go/go.mod
  vendor/cloud.google.com/go/go.sum
  vendor/cloud.google.com/go/internal/.repo-metadata-full.json
  vendor/cloud.google.com/go/internal/version/version.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#2298 Move net-{contour,certmanager} to knative-sandbox
  config/prod/prow/config_knative.yaml
  config/prod/prow/jobs/config.yaml
  config/prod/prow/testgrid/testgrid.yaml
Labels: approved, cla: yes, lgtm, size/L

#2300 Missed config from https://github.com/knative/test-infra/pull/2298
  config/prod/prow/config_knative.yaml
  config/prod/prow/jobs/config.yaml
  config/prod/prow/testgrid/testgrid.yaml
Labels: approved, cla: yes, lgtm, size/L

#2301 Move knative/net-{istio,kourier} to knative-sandbox org.
  config/prod/prow/config_knative.yaml
  config/prod/prow/jobs/config.yaml
  config/prod/prow/testgrid/testgrid.yaml
Labels: approved, cla: yes, lgtm, size/XL

#2299 Replace issue tracker job for test-infra with github action
  .github/workflows/stale.yaml
  config/prod/prow/jobs/custom/issue-tracker.yaml
Labels: approved, cla: yes, lgtm, size/M

#2302 Ignore 'Terminating' pods when waiting for all pods running.
  scripts/library.sh
Labels: approved, cla: yes, lgtm, size/XS

#2303 Stale action ignores lifecycle/frozen
  .github/workflows/stale.yaml
Labels: approved, cla: yes, lgtm, size/XS

#2304 dump metrics to artifacts directory
  scripts/e2e-tests.sh
Labels: approved, cla: yes, lgtm, size/S

#2305 Redirect the metrics to the actual file. zomg. sorry
  scripts/e2e-tests.sh
Labels: approved, cla: yes, lgtm, size/XS

#2310 Auto generated config header uses fixed copyright year.
  tools/config-generator/templates/common_header.yaml
Labels: approved, cla: yes, lgtm, needs-ok-to-test, size/XS

#2314 Update Go to 1.14.6 to fix the test logging issue
  images/prow-tests/Dockerfile
Labels: approved, cla: yes, lgtm, size/XS

#2315 Install kubetest2 in prow-tests image
  images/prow-tests/Dockerfile
Labels: approved, cla: yes, lgtm, size/XS

#2316 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/golang.org/x/sys/unix/syscall_linux.go
  vendor/golang.org/x/sys/unix/zsyscall_linux.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#2317 Docs repo stop using prow job managing stale issues/PRs
  config/prod/prow/jobs/custom/issue-tracker.yaml
Labels: approved, cla: yes, lgtm, size/XS

#2318 Delete issue tracker prow job entirely in favor of github actions
  config/prod/prow/jobs/custom/issue-tracker.yaml
Labels: approved, cla: yes, lgtm, size/L

#2321 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/github.com/google/go-cmp/cmp/report_reflect.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#2324 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/cloud.google.com/go/pubsub/CHANGES.md
  vendor/cloud.google.com/go/pubsub/apiv1/doc.go
  vendor/cloud.google.com/go/pubsub/go.mod
  vendor/cloud.google.com/go/pubsub/go.sum
  vendor/cloud.google.com/go/pubsub/pubsub.go
  vendor/golang.org/x/sys/unix/mkerrors.sh
  vendor/golang.org/x/sys/unix/syscall_bsd.go
  vendor/golang.org/x/sys/unix/zerrors_openbsd_386.go
  vendor/golang.org/x/sys/unix/zerrors_openbsd_amd64.go
  vendor/golang.org/x/sys/unix/zerrors_openbsd_arm.go
  vendor/golang.org/x/sys/unix/zerrors_openbsd_arm64.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#2307 Remove a few labels in the label-sync.yaml file for now to get the job pass
  label_sync/labels.yaml
Labels: approved, cla: yes, lgtm, size/S

#2308 Add --help option for presubmit-tests.sh and fix more shellcheck warnings
  scripts/presubmit-tests.sh
  test/unit/presubmit-tests.sh
Labels: approved, cla: yes, lgtm, size/M

#2325 This fixes the return value of the default integration test runner
  scripts/presubmit-tests.sh
Labels: approved, cla: yes, lgtm, size/XS

#2326 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/golang.org/x/sys/unix/zerrors_freebsd_386.go
  vendor/golang.org/x/sys/unix/zerrors_freebsd_amd64.go
  vendor/golang.org/x/sys/unix/zerrors_freebsd_arm.go
  vendor/golang.org/x/sys/unix/zerrors_freebsd_arm64.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#2328 Test-infra oncalls own prow files for approving release branch jobs auto updates PRs
  config/prod/prow/OWNERS
Labels: approved, cla: yes, lgtm, size/XS

#2329 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/cloud.google.com/go/pubsub/CHANGES.md
  vendor/cloud.google.com/go/pubsub/apiv1/doc.go
  vendor/cloud.google.com/go/pubsub/go.mod
  vendor/cloud.google.com/go/pubsub/go.sum
  vendor/cloud.google.com/go/pubsub/subscription.go
  vendor/golang.org/x/sys/unix/mkerrors.sh
  vendor/golang.org/x/sys/unix/zerrors_netbsd_386.go
  vendor/golang.org/x/sys/unix/zerrors_netbsd_amd64.go
  vendor/golang.org/x/sys/unix/zerrors_netbsd_arm.go
  vendor/golang.org/x/sys/unix/zerrors_netbsd_arm64.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#2327 Run eventing conformance tests in a separate Prow job
  config/prod/prow/config_knative.yaml
  config/prod/prow/jobs/config.yaml
Labels: approved, cla: yes, lgtm, size/M

#2330 Fix test-infra continuous tests
  test/unit/presubmit-tests.sh
Labels: approved, cla: yes, lgtm, size/XS

#2332 Report on Slack if eventing nightly release job fails
  config/prod/prow/config_knative.yaml
  config/prod/prow/jobs/config.yaml
  tools/config-generator/main.go
  tools/config-generator/periodic_config.go
  tools/config-generator/templates/prow_periodic_test_job.yaml
Labels: approved, cla: yes, lgtm, size/XL

#2334 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/cloud.google.com/go/CHANGES.md
  vendor/cloud.google.com/go/CONTRIBUTING.md
  vendor/cloud.google.com/go/go.mod
  vendor/cloud.google.com/go/go.sum
  vendor/cloud.google.com/go/internal/.repo-metadata-full.json
  vendor/cloud.google.com/go/internal/version/version.go
  vendor/google.golang.org/genproto/googleapis/pubsub/v1/pubsub.pb.go
  vendor/google.golang.org/grpc/README.md
  vendor/google.golang.org/grpc/balancer/balancer.go
  vendor/google.golang.org/grpc/balancer/base/balancer.go
  vendor/google.golang.org/grpc/balancer/base/base.go
  vendor/google.golang.org/grpc/balancer/grpclb/grpclb.go
  vendor/google.golang.org/grpc/balancer/grpclb/grpclb_remote_balancer.go
  vendor/google.golang.org/grpc/balancer/roundrobin/roundrobin.go
  vendor/google.golang.org/grpc/balancer_conn_wrappers.go
  vendor/google.golang.org/grpc/clientconn.go
  vendor/google.golang.org/grpc/codes/codes.go
  vendor/google.golang.org/grpc/credentials/alts/alts.go
  vendor/google.golang.org/grpc/credentials/alts/internal/authinfo/authinfo.go
  vendor/google.golang.org/grpc/credentials/alts/internal/handshaker/service/service.go
  vendor/google.golang.org/grpc/credentials/tls.go
  vendor/google.golang.org/grpc/dialoptions.go
  vendor/google.golang.org/grpc/grpclog/component.go
  vendor/google.golang.org/grpc/grpclog/loggerv2.go
  vendor/google.golang.org/grpc/internal/binarylog/binarylog.go
  vendor/google.golang.org/grpc/internal/binarylog/env_config.go
  vendor/google.golang.org/grpc/internal/binarylog/method_logger.go
  vendor/google.golang.org/grpc/internal/binarylog/sink.go
  vendor/google.golang.org/grpc/internal/channelz/funcs.go
  vendor/google.golang.org/grpc/internal/channelz/logging.go
  vendor/google.golang.org/grpc/internal/channelz/types.go
  vendor/google.golang.org/grpc/internal/channelz/types_nonlinux.go
  vendor/google.golang.org/grpc/internal/credentials/go110.go
  vendor/google.golang.org/grpc/internal/credentials/gobefore110.go
  vendor/google.golang.org/grpc/internal/grpclog/grpclog.go
  vendor/google.golang.org/grpc/internal/grpclog/prefixLogger.go
  vendor/google.golang.org/grpc/internal/grpcutil/encode_duration.go
  vendor/google.golang.org/grpc/internal/grpcutil/metadata.go
  vendor/google.golang.org/grpc/internal/grpcutil/method.go
  vendor/google.golang.org/grpc/internal/resolver/dns/dns_resolver.go
  vendor/google.golang.org/grpc/internal/syscall/syscall_linux.go
  vendor/google.golang.org/grpc/internal/syscall/syscall_nonlinux.go
  vendor/google.golang.org/grpc/internal/transport/controlbuf.go
  vendor/google.golang.org/grpc/internal/transport/handler_server.go
  vendor/google.golang.org/grpc/internal/transport/http2_client.go
  vendor/google.golang.org/grpc/internal/transport/http2_server.go
  vendor/google.golang.org/grpc/internal/transport/http_util.go
  vendor/google.golang.org/grpc/internal/transport/log.go
  vendor/google.golang.org/grpc/internal/transport/transport.go
  vendor/google.golang.org/grpc/picker_wrapper.go
  vendor/google.golang.org/grpc/pickfirst.go
  vendor/google.golang.org/grpc/resolver_conn_wrapper.go
  vendor/google.golang.org/grpc/server.go
  vendor/google.golang.org/grpc/service_config.go
  vendor/google.golang.org/grpc/stream.go
  vendor/google.golang.org/grpc/vet.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XXL
