Repository knative/test-infra, pull requests merged in 2020-09, with the labels that each got.

#2407 generate-config.sh don't import library.sh
  hack/generate-configs.sh
Labels: approved, cla: yes, lgtm, size/XS

#2405 adding ci-knative-serving-contour-latest to beta-prow-tests
  config/prod/prow/jobs/custom/experimental.yaml
Labels: approved, cla: yes, lgtm, size/M

#2408 Make coryrc a member of productivity-approvers
  OWNERS_ALIASES
Labels: approved, cla: yes, lgtm, size/XS

#2409 Fix the experimental Prow job
  config/prod/prow/check_config.sh
  config/prod/prow/jobs/custom/experimental.yaml
Labels: approved, cla: yes, lgtm, size/S

#2413 Fix check prow job config script
  config/prod/prow/check_config.sh
Labels: approved, cla: yes, lgtm, size/XS

#2404 functions implementation
  tools/dkcm/clerk/clerk.go
  tools/dkcm/clerk/clerk_foptions.go
  tools/dkcm/clerk/clerk_newstructs.go
  tools/dkcm/clerk/schema.sql
Labels: approved, cla: yes, lgtm, size/L

#2417 [master] Format markdown
  kntest/pkg/kubetest2/gke/README.md
  scripts/README.md
Labels: approved, cla: yes, lgtm, size/S

#2415 Remove boskos deployment files
  config/prod/build-cluster/cluster/200-cpu-limitrange.yaml
  config/prod/build-cluster/cluster/200-memory-limitrange.yaml
  config/prod/build-cluster/cluster/301-rbac.yaml
  config/prod/build-cluster/cluster/400-boskos-deployment.yaml
  config/prod/build-cluster/cluster/400-boskos-janitor.yaml
  config/prod/build-cluster/cluster/400-boskos-metrics.yaml
  config/prod/build-cluster/cluster/400-boskos-reaper.yaml
  config/prod/build-cluster/cluster/400-boskos.yaml
Labels: approved, cla: yes, lgtm, size/L

#2420 Add unit test for outputConfig
  .gitignore
  tools/config-generator/main.go
  tools/config-generator/main_test.go
  tools/config-generator/testutils_test.go
Labels: approved, cla: yes, lgtm, needs-ok-to-test, size/M

#2422 [master] golang format tools
  tools/config-generator/main_test.go
Labels: approved, cla: yes, lgtm, size/XS

#2421 kntest kubetest2 supports more flags and bug fix
  kntest/pkg/kubetest2/gke/options.go
  pkg/clustermanager/kubetest2/gke.go
  test/e2e-tests.sh
Labels: approved, cla: yes, lgtm, size/M

#2426 configure knative-sandbox/eventing-github
  config/prod/prow/config_knative.yaml
  config/prod/prow/jobs/config.yaml
  config/prod/prow/testgrid/testgrid.yaml
Labels: approved, cla: yes, lgtm, size/L

#2428 Make output a struct to reduce global var confusion.
  tools/config-generator/main.go
  tools/config-generator/main_test.go
  tools/config-generator/testgrid_config.go
  tools/config-generator/testutils_test.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/M

#2429 adding natss and rabbitmq to the nightly release scripts
  config/prod/prow/config_knative.yaml
  config/prod/prow/jobs/config.yaml
  config/prod/prow/testgrid/testgrid.yaml
Labels: approved, cla: yes, lgtm, size/L

#2427 Prow jobs support running integration tests with kind
  config/prod/prow/config_knative.yaml
  config/prod/prow/jobs/config.yaml
  images/prow-tests/Dockerfile
  scripts/e2e-tests.sh
  scripts/infra-library.sh
  test/e2e-kind.sh
  tools/config-generator/main.go
  tools/config-generator/perf_config.go
  tools/config-generator/periodic_config.go
  tools/config-generator/presubmit_config.go
Labels: approved, cla: yes, lgtm, size/XL

#2433 Add eventing-gitlab/couchdb sandbox repo for continuous testing/release
  config/prod/prow/config_knative.yaml
  config/prod/prow/jobs/config.yaml
  config/prod/prow/testgrid/testgrid.yaml
Labels: approved, cla: yes, lgtm, size/L

#2432 Add eventing-awssqs sandbox repo for continuous testing/release
  config/prod/prow/config_knative.yaml
  config/prod/prow/jobs/config.yaml
  config/prod/prow/testgrid/testgrid.yaml
Labels: approved, cla: yes, lgtm, size/L

#2435 Add prometheus & ceph sources
  config/prod/prow/config_knative.yaml
  config/prod/prow/jobs/config.yaml
  config/prod/prow/testgrid/testgrid.yaml
Labels: approved, cla: yes, lgtm, size/L

#2437 Mock log.Fatalf calls and add test suite
  tools/config-generator/main.go
  tools/config-generator/main_test.go
  tools/config-generator/periodic_config.go
  tools/config-generator/testutils_test.go
  tools/config-generator/udpaterelease.go
  tools/config-generator/utils.go
  tools/config-generator/utils_test.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/L

#2439 Add devel Go to prow test image
  images/prow-tests/Dockerfile
Labels: approved, cla: yes, lgtm, size/XS

#2440 Simplify the wait_for_xx bash functions
  scripts/library.sh
Labels: approved, cla: yes, lgtm, size/M

#2442 update prow-tests Dockerfile
  images/prow-tests/Dockerfile
Labels: approved, cla: yes, lgtm, size/S

#2443 Partially revert https://github.com/knative/test-infra/pull/2440
  scripts/library.sh
Labels: approved, cla: yes, lgtm, size/M

#2445 Permissions for Eventing's new service account
  config/prod/build-cluster/boskos/set_up_boskos_project.sh
Labels: approved, cla: yes, lgtm, size/S

#2444 kntest kubetest2 supports --extra-gcloud-flags
  kntest/pkg/kubetest2/gke/options.go
  pkg/clustermanager/kubetest2/gke.go
  test/e2e-tests.sh
Labels: approved, cla: yes, lgtm, size/S

#2451 [Automated] Update actions
  .github/workflows/knative-donotsubmit.yaml
  .github/workflows/knative-go-build.yaml
  .github/workflows/knative-go-test.yaml
  .github/workflows/knative-stale.yaml
  .github/workflows/knative-style.yaml
  .github/workflows/knative-verify.yaml
Labels: approved, cla: yes, lgtm, size/XL

#2454 This adjusts a number of the presubmits.
  config/prod/prow/config_knative.yaml
  config/prod/prow/jobs/config.yaml
Labels: approved, cla: yes, lgtm, size/L

#2455 Switch to istio-stable as our presubmit check.
  config/prod/prow/config_knative.yaml
  config/prod/prow/jobs/config.yaml
Labels: approved, cla: yes, lgtm, size/L

#2460 Fix permissions for cloud-run-events-source
  config/prod/build-cluster/boskos/set_up_boskos_project.sh
Labels: approved, cla: yes, lgtm, size/XS

#2453 enable prow to send slack messages for nightly discovery failures
  config/prod/prow/config_knative.yaml
  config/prod/prow/jobs/config.yaml
Labels: approved, cla: yes, lgtm, size/S

#2450 Fix a small issue in infra-library.sh
  scripts/infra-library.sh
Labels: approved, cla: yes, lgtm, size/XS

#2463 fix to kntest kubetest2 wrapper
  pkg/clustermanager/kubetest2/gke.go
Labels: approved, cla: yes, lgtm, size/XS

#2459 Add unit tests for main.go. Increases coverage from 20% to 46%.
  tools/config-generator/main.go
  tools/config-generator/main_test.go
  tools/config-generator/testutils_test.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/XL

#2462 Disable the bespoke coverage job for a few repos.
  config/prod/prow/config_knative.yaml
  config/prod/prow/jobs/config.yaml
  config/prod/prow/testgrid/testgrid.yaml
Labels: approved, cla: yes, lgtm, size/XL

#2464 add tests for dkcm
  tools/dkcm/clerk/clerk_test.go
Labels: approved, cla: yes, lgtm, size/L

#2465 [Automated] Fix misspellings
  config/prod/build-cluster/create-build-cluster.sh
  config/prod/prow/pj-on-kind.sh
  tools/flaky-test-reporter/README.md
Labels: approved, cla: yes, lgtm, size/XS

#2467 Add eventing-ceph nightlies and auto-releases
  config/prod/prow/config_knative.yaml
  config/prod/prow/jobs/config.yaml
  config/prod/prow/testgrid/testgrid.yaml
Labels: approved, cla: yes, lgtm, size/L

#2469 adding camel to the nightly builds
  config/prod/prow/config_knative.yaml
  config/prod/prow/jobs/config.yaml
  config/prod/prow/testgrid/testgrid.yaml
Labels: approved, cla: yes, lgtm, size/L

#2470 Add cloudrun-run-events@knative-releases service account to boskos
  config/prod/build-cluster/boskos/set_up_boskos_project.sh
Labels: approved, cla: yes, lgtm, size/XS

#2471 Pick up multi-arch support in ko
  images/prow-tests/Dockerfile
Labels: approved, cla: yes, lgtm, size/XS
