Repository knative/test-infra, pull requests merged in 2020-02, with the labels that each got.

#1655 Fix flag values when running cleanup tool
  ci/prow/config.yaml
  ci/prow/periodic_config.go
Labels: approved, lgtm, size/S

#1647 Fix how coverage tool reads git attributes
  tools/coverage/git/git.go
Labels: approved, lgtm, size/S

#1661 Prow auto bumper /assigns oncall instead of /cc
  tools/prow-auto-bumper/pullrequest.go
Labels: approved, lgtm, size/XS

#1663 Fixes to prow-auto-bumper
  images/prow-auto-bumper/Dockerfile
  tools/prow-auto-bumper/config.go
  tools/prow-auto-bumper/file.go
Labels: approved, lgtm, size/XS

#1659 added optional presubmits for go 1.14
  ci/prow/config.yaml
  ci/prow/config_knative.yaml
  ci/prow/make_config.go
  ci/prow/testgrid.yaml
Labels: approved, lgtm, size/L

#1664 added prow-test go114 image
  images/prow-tests-go114/Dockerfile
  images/prow-tests-go114/Makefile
  images/prow-tests-go114/README.md
Labels: approved, lgtm, size/M

#1667 Code coverage prow tool uses ARTIFACTS env var
  CONTRIBUTING.md
  tools/coverage/main.go
Labels: approved, lgtm, size/XS

#1668 enable cgo in prow-test-go114 image
  images/prow-tests-go114/Dockerfile
Labels: approved, lgtm, size/XS

#1671 Format markdown
  CONTRIBUTING.md
Labels: approved, lgtm, size/XS

#1672 Rename var auther so grammar bot doesn't complain
  tools/cleanup/cleanup.go
Labels: approved, lgtm, size/XS

#1669 Testgroup Failure Alert Modification (PR#1609):
  ci/prow/templates/testgrid_config_header.yaml
  ci/prow/testgrid.yaml
  ci/prow/testgrid_config.go
Labels: approved, lgtm, size/L

#1673 Create a new prow job for upgrade tests in operators
  ci/prow/config.yaml
  ci/prow/config_knative.yaml
Labels: approved, lgtm, size/M

#1674 Remove the prow job integration-tests-on-latest-serving for serving operator
  ci/prow/config.yaml
  ci/prow/config_knative.yaml
  ci/prow/testgrid.yaml
Labels: approved, lgtm, size/L

#1554 Allow publishing manifests to a local dir
  ci/manual_release.md
  scripts/README.md
  scripts/release.sh
  test/unit/release-tests.sh
Labels: approved, lgtm, size/M

#1675 Set always_run to false for go114 presubmit job in serving
  ci/prow/config.yaml
  ci/prow/config_knative.yaml
Labels: approved, lgtm, size/S

#1677 Format markdown
  scripts/README.md
Labels: approved, lgtm, size/XS

#1676 Add the upgrade tests for eventing-operator and remove integration tests on latest
  ci/prow/config.yaml
  ci/prow/config_knative.yaml
  ci/prow/testgrid.yaml
Labels: approved, lgtm, size/M

#1678 Allow pods to retry on image pull errors
  scripts/library.sh
Labels: approved, lgtm, size/XS

#1679 Make smoke tests in serving optional
  ci/prow/config.yaml
  ci/prow/config_knative.yaml
Labels: approved, lgtm, size/XS

#1687 e2e-tests.sh supports --skip-teardowns
  scripts/README.md
  scripts/e2e-tests.sh
Labels: approved, lgtm, size/XS

#1688 Format markdown
  scripts/README.md
Labels: approved, lgtm, size/XS

#1691 Serving presubmit tests all using default instead of hard coded 1.13
  ci/prow/config.yaml
  ci/prow/config_knative.yaml
Labels: approved, lgtm, size/S

#1690 Revert "Update prow to v20200204-7e8cd997a"
  ci/prow/config.yaml
  ci/prow/deployments/boskos_deployment.yaml
  ci/prow/deployments/boskos_janitor.yaml
  ci/prow/deployments/boskos_metrics.yaml
  ci/prow/deployments/boskos_reaper.yaml
  ci/prow/deployments/crier.yaml
  ci/prow/deployments/deck.yaml
  ci/prow/deployments/hook.yaml
  ci/prow/deployments/horologium.yaml
  ci/prow/deployments/plank.yaml
  ci/prow/deployments/sinker.yaml
  ci/prow/deployments/tide.yaml
  ci/prow/staging/config.yaml
  ci/prow/templates/prow_config_header.yaml
Labels: approved, lgtm, size/M

#1692 Also skip cluster teardown if --skip-teardowns
  scripts/e2e-tests.sh
Labels: approved, lgtm, size/XS

#1697 additional labels for eventing-contrib
  config/prow/plugins.yaml
  config/prow/templates/prow_plugins.yaml
Labels: approved, lgtm, size/S

#1699 Update prow images and deployments
  config/prow/config.yaml
  config/prow/deployments/boskos_deployment.yaml
  config/prow/deployments/boskos_janitor.yaml
  config/prow/deployments/boskos_reaper.yaml
  config/prow/deployments/crier.yaml
  config/prow/deployments/deck.yaml
  config/prow/deployments/hook.yaml
  config/prow/deployments/horologium.yaml
  config/prow/deployments/plank.yaml
  config/prow/deployments/sinker.yaml
  config/prow/deployments/tide.yaml
  config/prow/staging/config.yaml
  config/prow/templates/prow_config.yaml
Labels: approved, lgtm, size/M

#1694 Add missing Prow configs so that we can update to latest images
  config/prow/config_start.yaml
  config/prow/deployments/deck.yaml
Labels: approved, lgtm, size/S

#1703 Fix the issue tracker jobs and improve doc
  config/prow/issue_tracker_config.go
  config/prow/jobs/config.yaml
  config/prow_setup.md
Labels: approved, lgtm, size/S

#1705 Format markdown
  config/prow_setup.md
  config/release_setup.md
  tools/cleanup/README.md
Labels: approved, lgtm, size/S

#1698 chore: Add "client-contrib" as new repo
  config/prow/config.yaml
  config/prow/config_knative.yaml
  config/prow/issue_tracker_config.go
  config/prow/jobs/config.yaml
  config/prow/plugins.yaml
  config/prow/testgrid.yaml
  config/prow_setup.md
Labels: approved, lgtm, size/L

#1702 Reorganize a bunch of prow config files
  config/prow/Makefile
  config/prow/cluster/100-namespace.yaml
  config/prow/cluster/200-cpu-limitrange.yaml
  config/prow/cluster/200-memory-limitrange.yaml
  config/prow/cluster/300-crds.yaml
  config/prow/cluster/301-rbac.yaml
  config/prow/cluster/400-boskos-deployment.yaml
  config/prow/cluster/400-boskos-janitor.yaml
  config/prow/cluster/400-boskos-metrics.yaml
  config/prow/cluster/400-boskos-reaper.yaml
  config/prow/cluster/400-boskos.yaml
  config/prow/cluster/400-crier.yaml
  config/prow/cluster/400-deck.yaml
  config/prow/cluster/400-hook.yaml
  config/prow/cluster/400-horologium.yaml
  config/prow/cluster/400-ingress.yaml
  config/prow/cluster/400-plank.yaml
  config/prow/cluster/400-sinker.yaml
  config/prow/cluster/400-tide.yaml
  config/prow_setup.md
Labels: approved, lgtm, size/M

#1706 We have to use kubectl replace for job-config configmap
  config/prow/Makefile
Labels: approved, lgtm, size/XS

#1701 Move config generator code to tools
  config/prow/Makefile
  config/prow/README.md
  tools/config-generator/README.md
  tools/config-generator/issue_tracker_config.go
  tools/config-generator/main.go
  tools/config-generator/perf_config.go
  tools/config-generator/periodic_config.go
  tools/config-generator/postsubmit_config.go
  tools/config-generator/presubmit_config.go
  tools/config-generator/templates/common_header.yaml
  tools/config-generator/templates/prow_config.yaml
  tools/config-generator/templates/prow_periodic_custom_job.yaml
  tools/config-generator/templates/prow_periodic_test_job.yaml
  tools/config-generator/templates/prow_plugins.yaml
  tools/config-generator/templates/prow_postsubmit_gocoverage_job.yaml
  tools/config-generator/templates/prow_postsubmit_perf_job.yaml
  tools/config-generator/templates/prow_presubmit_gocoverate_job.yaml
  tools/config-generator/templates/prow_presubmit_job.yaml
  tools/config-generator/templates/testgrid_config_header.yaml
  tools/config-generator/templates/testgrid_dashboardgroup.yaml
  tools/config-generator/templates/testgrid_dashboardtab.yaml
  tools/config-generator/templates/testgrid_testgroup.yaml
  tools/config-generator/testgrid_config.go
Labels: approved, lgtm, size/M

#1710 golang format tools
  tools/config-generator/issue_tracker_config.go
  tools/config-generator/perf_config.go
  tools/config-generator/periodic_config.go
  tools/config-generator/postsubmit_config.go
  tools/config-generator/presubmit_config.go
  tools/config-generator/testgrid_config.go
Labels: approved, lgtm, size/S

#1708 Move boskos and core config files to separate folders
  config/prow/Makefile
  config/prow/README.md
  config/prow/boskos/README.md
  config/prow/boskos/boskos_resources.yaml
  config/prow/boskos/create_boskos_projects.sh
  config/prow/boskos/set_up_boskos_project.sh
  config/prow/boskos/update_all_boskos_projects.sh
  config/prow/config_knative.yaml
  config/prow/core/config.yaml
  config/prow/core/plugins.yaml
  config/prow_setup.md
  config/release_setup.md
  tools/cleanup/README.md
  tools/coverage/design.md
Labels: approved, lgtm, size/M

#1715 Format markdown
  config/prow/README.md
  config/prow_setup.md
  config/release_setup.md
  tools/cleanup/README.md
  tools/config-generator/README.md
Labels: approved, lgtm, size/M

#1711 Do not generate testgrid config for prow-staging
  config/prow/Makefile
  config/prow/staging/Makefile
  config/prow/staging/README.md
  config/prow/staging/config.yaml
  config/prow/staging/jobs/config.yaml
  config/prow/staging/plugins.yaml
  config/prow/staging/testgrid.yaml
Labels: approved, lgtm, size/M

#1718 Revert "Update prow to v20200212-1f7b8ac1d"
  config/prow/cluster/400-boskos-deployment.yaml
  config/prow/cluster/400-boskos-janitor.yaml
  config/prow/cluster/400-boskos-metrics.yaml
  config/prow/cluster/400-boskos-reaper.yaml
  config/prow/cluster/400-crier.yaml
  config/prow/cluster/400-deck.yaml
  config/prow/cluster/400-hook.yaml
  config/prow/cluster/400-horologium.yaml
  config/prow/cluster/400-plank.yaml
  config/prow/cluster/400-sinker.yaml
  config/prow/cluster/400-tide.yaml
  config/prow/core/config.yaml
  config/prow/staging/config.yaml
  tools/config-generator/templates/prow_config.yaml
Labels: approved, lgtm, size/M

#1712 Move testgrid config file to a separate folder
  config/prow/Makefile
  config/prow/README.md
  config/prow/testgrid/testgrid.yaml
  shared/testgrid/yaml.go
Labels: approved, lgtm, size/S

#1717 prow-auto-bumper also scans templates folder
  config/prow/pj-on-kind.sh
  config/prow/run_job.sh
  tools/prow-auto-bumper/config.go
  tools/prow-auto-bumper/file.go
Labels: approved, lgtm, size/M

#1713 Move config docs to guides
  config/README.md
  docs/README.md
  guides/REAME.md
  guides/branch_checks.png
  guides/manual_release.md
  guides/prow_setup.md
  guides/release_setup.md
  scripts/README.md
Labels: approved, lgtm, size/M

#1720 Update images to latest and fix boskos
  config/prow/cluster/400-boskos-deployment.yaml
  config/prow/cluster/400-boskos-janitor.yaml
  config/prow/cluster/400-boskos-metrics.yaml
  config/prow/cluster/400-boskos-reaper.yaml
  config/prow/cluster/400-boskos.yaml
  config/prow/cluster/400-crier.yaml
  config/prow/cluster/400-deck.yaml
  config/prow/cluster/400-hook.yaml
  config/prow/cluster/400-horologium.yaml
  config/prow/cluster/400-plank.yaml
  config/prow/cluster/400-sinker.yaml
  config/prow/cluster/400-tide.yaml
  config/prow/core/config.yaml
  config/prow/staging/config.yaml
  guides/README.md
  tools/config-generator/templates/prow_config.yaml
Labels: approved, lgtm, size/M

#1722 Format markdown
  config/prow/README.md
Labels: approved, lgtm, size/XS

#1726 Ignore github templates when linting markdown
  scripts/presubmit-tests.sh
Labels: approved, lgtm, size/XS

#1725 Fix testgrid tab name for coverage and comments for coverage-dev job
  config/prow/testgrid/testgrid.yaml
  tools/config-generator/postsubmit_config.go
  tools/config-generator/testgrid_config.go
Labels: approved, lgtm, size/M

#1724 Add https tests to testgrid
  config/prow/config_knative.yaml
  config/prow/jobs/config.yaml
  config/prow/testgrid/testgrid.yaml
Labels: approved, lgtm, size/M

#1727 Update ko in prow-tests image
  images/prow-tests/Dockerfile
Labels: approved, lgtm, size/XS

#1729 Update to latest pkg
  Gopkg.lock
  vendor/github.com/go-logr/logr/LICENSE
  vendor/github.com/go-logr/logr/logr.go
  vendor/github.com/golang/glog/LICENSE
  vendor/github.com/golang/glog/glog.go
  vendor/github.com/golang/glog/glog_file.go
  vendor/knative.dev/pkg/changeset/commit.go
  vendor/knative.dev/pkg/changeset/doc.go
  vendor/knative.dev/pkg/logging/config.go
  vendor/knative.dev/pkg/logging/logger.go
  vendor/knative.dev/pkg/logging/logkey/constants.go
  vendor/knative.dev/pkg/logging/zz_generated.deepcopy.go
  vendor/knative.dev/pkg/test/e2e_flags.go
  vendor/knative.dev/pkg/test/gke/request.go
  vendor/knative.dev/pkg/test/logging/doc.go
  vendor/knative.dev/pkg/test/logging/error.go
  vendor/knative.dev/pkg/test/logging/logger.go
  vendor/knative.dev/pkg/test/logging/logging.go
  vendor/knative.dev/pkg/test/logging/memory_encoder.go
  vendor/knative.dev/pkg/test/logging/spew_encoder.go
  vendor/knative.dev/pkg/test/logging/sugar.go
  vendor/knative.dev/pkg/test/logging/tlogger.go
  vendor/knative.dev/pkg/test/logging/zapr.go
  vendor/knative.dev/pkg/test/slackutil/message_read.go
  vendor/knative.dev/pkg/testutils/clustermanager/e2e-tests/boskos/boskos.go
  vendor/knative.dev/pkg/testutils/clustermanager/e2e-tests/gke.go
  vendor/knative.dev/pkg/testutils/clustermanager/perf-tests/pkg/benchmark.go
  vendor/knative.dev/pkg/testutils/clustermanager/perf-tests/pkg/cluster.go
  vendor/knative.dev/pkg/testutils/clustermanager/prow-cluster-operation/main.go
Labels: approved, lgtm, size/XXL

#1732 Enable needs-rebase plugin
  config/prow/cluster/500-needs-rebase.yaml
  config/prow/core/plugins.yaml
  config/prow/staging/plugins.yaml
  tools/config-generator/templates/prow_plugins.yaml
Labels: approved, lgtm, size/L

#1736 Add needs-rebase to missingLabels
  config/prow/core/config.yaml
  config/prow/staging/config.yaml
  tools/config-generator/templates/prow_config.yaml
Labels: approved, lgtm, size/XS

#1730 Add autotls test as a separate presubmit test for serving
  config/prow/config_knative.yaml
  config/prow/jobs/config.yaml
Labels: approved, lgtm, size/M

#1731 Flaky test retryer skip PR that's not open
  tools/flaky-test-retryer/handler.go
Labels: approved, lgtm, size/S

#1739 Prow auto bumper won't bother anyone but oncall
  tools/prow-auto-bumper/pullrequest.go
Labels: approved, lgtm, size/XS

#1740 Update to janitor with cleanup fix
  config/prow/cluster/400-boskos-deployment.yaml
  config/prow/cluster/400-boskos-janitor.yaml
  config/prow/cluster/400-boskos-metrics.yaml
  config/prow/cluster/400-boskos-reaper.yaml
Labels: approved, lgtm, size/XS

#1738 Make auto tls test a required leg for serving
  config/prow/config_knative.yaml
  config/prow/jobs/config.yaml
Labels: approved, lgtm, size/XS

#1743 Explicitly enable pubsub in Prow job generator
  config/prow/config_knative.yaml
  config/prow/jobs/config.yaml
  tools/config-generator/main.go
  tools/config-generator/presubmit_config.go
Labels: approved, lgtm, size/L

#1745 Rename auto tls test script
  config/prow/config_knative.yaml
  config/prow/jobs/config.yaml
Labels: approved, lgtm, size/XS

#1747 Collect eventing flakes report
  tools/flaky-test-reporter/config/config.yaml
Labels: approved, lgtm, size/XS

#1748 Prow jobs send pubsub for eventing
  config/prow/config_knative.yaml
  config/prow/jobs/config.yaml
Labels: approved, lgtm, size/S

#1751 Update flaky test reporter Dockerfile to use go1.13
  images/flaky-test-reporter/Dockerfile
Labels: approved, lgtm, size/XS

#1752 Revoke flakes retry for eventing and enable alerting
  config/prow/config_knative.yaml
  config/prow/jobs/config.yaml
  tools/flaky-test-reporter/config/config.yaml
Labels: approved, lgtm, size/S

#1749 Highlight "code is outdated" error
  config/prow/core/config.yaml
  config/prow/staging/config.yaml
  config/prow/staging/jobs/config.yaml
  tools/config-generator/templates/prow_config.yaml
Labels: approved, lgtm, size/M

#1753 Set up CI for the net-istio repo
  config/prow/config_knative.yaml
  config/prow/core/config.yaml
  config/prow/core/plugins.yaml
  config/prow/jobs/config.yaml
  config/prow/testgrid/testgrid.yaml
Labels: approved, lgtm, size/XL

#1754 Add reviewers for test-infra
  OWNERS_ALIASES
Labels: approved, lgtm, size/XS

#1755 Report flakes for eventing-contrib in Github and Slack
  tools/flaky-test-reporter/config/config.yaml
Labels: approved, lgtm, size/XS

#1756 Remove serving smoke tests
  config/prow/config_knative.yaml
  config/prow/jobs/config.yaml
Labels: approved, lgtm, size/M

#1757 Enable showing pod info on spyglass
  config/prow/cluster/400-crier.yaml
  config/prow/core/config.yaml
  config/prow/staging/config.yaml
  tools/config-generator/templates/prow_config.yaml
Labels: approved, lgtm, size/S

#1741 Fix Prow Makefile
  config/prow-staging/Makefile
  config/prow-staging/README.md
  config/prow-staging/boskos/boskos_resources.yaml
  config/prow-staging/config_staging.yaml
  config/prow-staging/core/config.yaml
  config/prow-staging/core/plugins.yaml
  config/prow-staging/jobs/config.yaml
  config/prow/Makefile
  config/prow/README.md
  config/prow/core/config.yaml
  config/prow/jobs/config.yaml
  config/prow/testgrid/testgrid.yaml
  config/prow_common.mk
  guides/prow_setup.md
  guides/release_setup.md
  test/presubmit-tests.sh
  tools/config-generator/templates/common_header.yaml
Labels: approved, lgtm, size/L

#1760 update-testgrid-config should confirm master branch
  config/prow_common.mk
Labels: approved, lgtm, size/XS

#1764 Update liche in prow-tests image to pick up the fix
  images/prow-tests/Dockerfile
Labels: approved, lgtm, size/XS
