Repository knative/test-infra, pull requests merged in 2020-03, with the labels that each got.

#1768 Format markdown
  config/prow/README.md
  guides/prow_setup.md
Labels: approved, lgtm, size/XS

#1767 Use Go 1.13 for staging test-infra presubmit tests
  config/prow-staging/config_staging.yaml
  config/prow-staging/core/config.yaml
  config/prow-staging/jobs/config.yaml
Labels: approved, lgtm, size/L

#1771 Fix the check-config presubmit job
  config/prow/config_knative.yaml
  config/prow/jobs/config.yaml
Labels: approved, lgtm, size/XS

#1772 Reduce Boskos Janitor count
  config/prow/cluster/400-boskos-janitor.yaml
Labels: approved, lgtm, size/XS

#1775 Add `--upgrade` to `./hack/update-deps.sh`
  hack/update-deps.sh
Labels: approved, lgtm, size/S

#1776 Auto-update dependencies
  Gopkg.lock
  vendor/knative.dev/pkg/test/logging/logging.go
Labels: approved, lgtm, size/S

#1781 Add permissions for release service accounts
  config/prow/boskos/set_up_boskos_project.sh
Labels: approved, lgtm, size/XS

#1774 Update the prow-tests image
  images/prow-tests/Dockerfile
Labels: approved, lgtm, size/XS

#1785 disable templated (containing {{ chars) link check
  scripts/markdown-link-check-config.rc
Labels: approved, lgtm, size/XS

#1780 Allow presubmit run multiple sctips
  config/prow-staging/core/config.yaml
  config/prow/core/config.yaml
  scripts/README.md
  scripts/library.sh
  scripts/presubmit-tests.sh
  tools/config-generator/templates/prow_config.yaml
Labels: approved, lgtm, size/M

#1786 Dop the Istio add on
  scripts/README.md
  scripts/e2e-tests.sh
  test/e2e-tests.sh
Labels: approved, lgtm, size/S

#1788 Revert "Dop the Istio add on"
  scripts/README.md
  scripts/e2e-tests.sh
  test/e2e-tests.sh
Labels: approved, lgtm, size/S

#1789 Fix for incorrect folder in manual release process
  guides/manual_release.md
Labels: approved, lgtm, size/XS

#1790 Revert "Allow presubmit run multiple sctips"
  config/prow-staging/core/config.yaml
  config/prow/core/config.yaml
  scripts/README.md
  scripts/library.sh
  scripts/presubmit-tests.sh
  tools/config-generator/templates/prow_config.yaml
Labels: approved, lgtm, size/M

#1791 Add integration test for net-istio
  config/prow/config_knative.yaml
  config/prow/jobs/config.yaml
Labels: approved, lgtm, size/M

#1796 Allows PRs in test-infra to be automatically merged
  config/prow-staging/core/config.yaml
  config/prow/core/config.yaml
  tools/config-generator/main.go
  tools/config-generator/templates/prow_config.yaml
Labels: approved, lgtm, size/M

#1794 Add config for build cluster(s) to run postsubmit jobs for Prow auto-update
  config/prow/cluster/400-deck.yaml
  config/prow/cluster/400-plank.yaml
  config/prow/cluster/400-sinker.yaml
Labels: approved, lgtm, size/S

#1800 Auto-update dependencies
  Gopkg.lock
  vendor/knative.dev/pkg/test/clients.go
  vendor/knative.dev/pkg/test/e2e_flags.go
  vendor/knative.dev/pkg/test/request.go
  vendor/knative.dev/pkg/test/spoof/spoof.go
Labels: approved, cla: yes, lgtm, size/M

#1802 Run ./hack/release.sh from the release branch
  scripts/release.sh
Labels: approved, cla: yes, lgtm, size/S

#1806 Fix recursive call to `hack/release.sh`
  scripts/release.sh
Labels: approved, cla: yes, lgtm, size/XS

#1808 Hotfix release: Prow and local use different checkout
  scripts/release.sh
Labels: approved, cla: yes, lgtm, size/XS

#1809 Run Istio 1.5 tests instead of Istio 1.3 (deprecated).
  config/prow/config_knative.yaml
  config/prow/jobs/config.yaml
  config/prow/testgrid/testgrid.yaml
  shared/testgrid/testgrid.go
  tools/flaky-test-reporter/config/config.yaml
Labels: approved, cla: yes, lgtm, size/M

#1719 Disable default failure alert
  config/prow/testgrid/testgrid.yaml
  tools/config-generator/templates/testgrid_config_header.yaml
  tools/config-generator/templates/testgrid_dashboardtab.yaml
  tools/config-generator/testgrid_config.go
Labels: approved, cla: yes, lgtm, size/L

#1814 Enable rerun button on Prow
  config/prow-staging/core/config.yaml
  config/prow/cluster/301-rbac.yaml
  config/prow/cluster/400-deck.yaml
  config/prow/core/config.yaml
  tools/config-generator/templates/prow_config.yaml
Labels: approved, cla: yes, lgtm, size/S

#1817 Auto-update dependencies
  Gopkg.lock
  vendor/github.com/kelseyhightower/envconfig/LICENSE
  vendor/github.com/kelseyhightower/envconfig/doc.go
  vendor/github.com/kelseyhightower/envconfig/env_os.go
  vendor/github.com/kelseyhightower/envconfig/env_syscall.go
  vendor/github.com/kelseyhightower/envconfig/envconfig.go
  vendor/github.com/kelseyhightower/envconfig/usage.go
  vendor/knative.dev/pkg/test/prow/env.go
  vendor/knative.dev/pkg/test/prow/prow.go
  vendor/knative.dev/pkg/test/zipkin/util.go
Labels: approved, cla: yes, lgtm, size/XL

#1818 Add Rerun instructions
  guides/manual_release.md
  guides/rerun_button.png
Labels: approved, cla: yes, lgtm, size/S

#1820 Fix istio-1.5 tests for serving
  config/prow/config_knative.yaml
  config/prow/jobs/config.yaml
Labels: approved, cla: yes, lgtm, size/S

#1816 Run verify-codegen for docs only PRs
  scripts/presubmit-tests.sh
Labels: approved, cla: yes, lgtm, size/S

#1822 Minor improvements to the config-generator
  config/prow/config_knative.yaml
  config/prow/jobs/config.yaml
  config/prow/testgrid/testgrid.yaml
  tools/config-generator/main.go
  tools/config-generator/presubmit_config.go
Labels: approved, cla: yes, lgtm, size/XXL

#1819 Adds net-kourier
  config/prow/config_knative.yaml
  config/prow/core/config.yaml
  config/prow/core/plugins.yaml
  config/prow/jobs/config.yaml
  config/prow/testgrid/testgrid.yaml
Labels: approved, cla: yes, lgtm, ok-to-test, size/L

#1824 Move git package from prow-auto-bumper to shared
  shared/git/commit.go
  shared/git/info.go
  tools/prow-auto-bumper/config.go
  tools/prow-auto-bumper/file.go
  tools/prow-auto-bumper/getversion_test.go
  tools/prow-auto-bumper/main.go
  tools/prow-auto-bumper/parser.go
  tools/prow-auto-bumper/pullrequest.go
  tools/prow-auto-bumper/run.go
Labels: approved, cla: yes, lgtm, size/L

#1828 Creating dot-release jobs for old release branches
  config/prow/config_knative.yaml
  config/prow/jobs/config.yaml
  config/prow/testgrid/testgrid.yaml
  tools/config-generator/periodic_config.go
Labels: approved, cla: yes, lgtm, size/XXL

#1821 Remove Prow jobs for 0.9 and add jobs for 0.13
  config/prow-staging/core/config.yaml
  config/prow/config_knative.yaml
  config/prow/core/config.yaml
  config/prow/jobs/config.yaml
  config/prow/testgrid/testgrid.yaml
  tools/config-generator/main.go
Labels: approved, cla: yes, lgtm, size/XL

#1829 Update readme with instructions for releasing old release branches
  guides/manual_release.md
Labels: approved, cla: yes, lgtm, size/S

#1830 Restore presubmit run multiple scripts functionality (#1811)
  config/prow-staging/core/config.yaml
  config/prow/core/config.yaml
  scripts/README.md
  scripts/library.sh
  scripts/presubmit-tests.sh
  test/unit/presubmit-tests.sh
  tools/config-generator/templates/prow_config.yaml
Labels: approved, cla: yes, lgtm, size/M

#1835 Add net-contour e2e testing
  config/prow/config_knative.yaml
  config/prow/jobs/config.yaml
Labels: approved, cla: yes, lgtm, size/M

#1832 Add testgrid tabs for dot release jobs
  config/prow/testgrid/testgrid.yaml
  tools/config-generator/testgrid_config.go
Labels: approved, cla: yes, lgtm, size/L

#1834 Duplicate prow cluster and core config files for staging and production
  config/prow-staging/Makefile
  config/prow-staging/cluster/100-namespace.yaml
  config/prow-staging/cluster/200-cpu-limitrange.yaml
  config/prow-staging/cluster/200-memory-limitrange.yaml
  config/prow-staging/cluster/300-crds.yaml
  config/prow-staging/cluster/301-rbac.yaml
  config/prow-staging/cluster/400-boskos-deployment.yaml
  config/prow-staging/cluster/400-boskos-janitor.yaml
  config/prow-staging/cluster/400-boskos-metrics.yaml
  config/prow-staging/cluster/400-boskos-reaper.yaml
  config/prow-staging/cluster/400-boskos.yaml
  config/prow-staging/cluster/400-crier.yaml
  config/prow-staging/cluster/400-deck.yaml
  config/prow-staging/cluster/400-hook.yaml
  config/prow-staging/cluster/400-horologium.yaml
  config/prow-staging/cluster/400-ingress.yaml
  config/prow-staging/cluster/400-plank.yaml
  config/prow-staging/cluster/400-sinker.yaml
  config/prow-staging/cluster/400-tide.yaml
  config/prow-staging/cluster/500-needs-rebase.yaml
  config/prow_common.mk
  tools/config-generator/main.go
  tools/config-generator/templates/prow-staging/prow_config.yaml
  tools/config-generator/templates/prow-staging/prow_plugins.yaml
  tools/config-generator/templates/prow/prow_config.yaml
  tools/config-generator/templates/prow/prow_plugins.yaml
Labels: approved, cla: yes, lgtm, size/XXL

#1836 Testgrid alerting new email
  config/prow/testgrid/testgrid.yaml
  tools/config-generator/testgrid_config.go
  tools/monitoring/alert/alert.go
Labels: approved, cla: yes, lgtm, size/L

#1815 Move Prow/Testgrid config generation to update-codegen.sh
  config/prow-staging/Makefile
  config/prow_common.mk
  guides/prow_setup.md
  hack/generate-configs.sh
  hack/update-codegen.sh
  hack/verify-codegen.sh
  test/presubmit-config-check.sh
Labels: approved, cla: yes, lgtm, size/L

#1783 All networking jobs run both e2e and auto tls
  config/prow/config_knative.yaml
  config/prow/jobs/config.yaml
Labels: approved, cla: yes, lgtm, size/L

#1838 [master] Format markdown
  guides/prow_setup.md
Labels: approved, cla: yes, lgtm, size/S

#1795 Prow config updater tool
  Gopkg.lock
  Gopkg.toml
  config/prow-staging/Makefile
  config/prow_common.mk
  hack/generate-configs.sh
  tools/githubhelper/githubhelper.go
  tools/prow-config-updater/config/config.go
  tools/prow-config-updater/config/config_test.go
  tools/prow-config-updater/github_commenter.go
  tools/prow-config-updater/github_commenter_test.go
  tools/prow-config-updater/main.go
  tools/prow-config-updater/presubmit-checker/README.md
  tools/prow-config-updater/presubmit-checker/main.go
  tools/prow-config-updater/pullrequest.go
  tools/prow-config-updater/slack_notification.go
  tools/prow-config-updater/updater.go
  tools/prow-config-updater/updater_test.go
Labels: approved, cla: yes, lgtm, size/XXL

#1831 Rename package shared to pkg
  images/Makefile.simple-image
  images/backups/Makefile
  images/clear-test-infra-alerts/Makefile
  images/coverage-go112/Makefile
  images/coverage/Makefile
  images/flaky-test-reporter/Makefile
  images/flaky-test-retryer/Makefile
  images/monitoring/Makefile
  images/prow-auto-bumper/Makefile
  images/prow-tests-go112/Makefile
  images/prow-tests-go114/Makefile
  images/prow-tests/Makefile
  pkg/README.md
  pkg/common/common.go
  pkg/gcs/gcs.go
  pkg/gcs/gcs_test.go
  pkg/git/commit.go
  pkg/git/info.go
  pkg/junit/junit.go
  pkg/junit/junit_test.go
  pkg/mysql/client.go
  pkg/performance/performance.go
  pkg/prow/prow.go
  pkg/prow/prow_test.go
  pkg/testgrid/testgrid.go
  pkg/testgrid/testgrid_test.go
  pkg/testgrid/yaml.go
  shared/README.md
  tools/coverage/testgrid/testsuiteXmlWriter.go
  tools/flaky-test-reporter/github_issue.go
  tools/flaky-test-reporter/jsonreport/jsonreport.go
  tools/flaky-test-reporter/main.go
  tools/flaky-test-reporter/result.go
  tools/flaky-test-reporter/slack_notification.go
  tools/flaky-test-retryer/log_parser.go
  tools/monitoring/alert/alert.go
  tools/monitoring/clearalerts/main.go
  tools/monitoring/main.go
  tools/monitoring/mysql/database.go
  tools/prow-auto-bumper/file.go
  tools/prow-auto-bumper/getversion_test.go
  tools/prow-auto-bumper/main.go
  tools/prow-auto-bumper/parser.go
  tools/prow-auto-bumper/pullrequest.go
  tools/prow-config-updater/config/config_test.go
  tools/prow-config-updater/main.go
  tools/prow-config-updater/pullrequest.go
Labels: approved, cla: yes, lgtm, size/M

#1840 Add net-http01 to meta config
  config/prow/config_knative.yaml
  config/prow/core/config.yaml
  config/prow/core/plugins.yaml
  config/prow/jobs/config.yaml
  config/prow/testgrid/testgrid.yaml
Labels: approved, cla: yes, lgtm, size/L

#1843 Add postsubmit job for Prow config updater
  config/prow/config_knative.yaml
  config/prow/jobs/config.yaml
  config/prow/testgrid/testgrid.yaml
  tools/config-generator/main.go
  tools/config-generator/postsubmit_config.go
  tools/config-generator/templates/prow_postsubmit_custom_job.yaml
Labels: approved, cla: yes, lgtm, size/L

#1844 Add restrictions for Prow staging process
  Gopkg.lock
  images/prow-config-updater/Dockerfile
  test/presubmit-config-check.sh
  tools/prow-auto-bumper/config.go
  tools/prow-config-updater/Makefile
  tools/prow-config-updater/config/config.go
  tools/prow-config-updater/config/config_test.go
  tools/prow-config-updater/presubmit-checker/main.go
  tools/prow-config-updater/updater.go
  tools/prow-config-updater/updater_test.go
  vendor/knative.dev/pkg/test/cmd/command.go
  vendor/knative.dev/pkg/testutils/clustermanager/e2e-tests/gke.go
Labels: approved, cla: yes, lgtm, size/L

#1846 Add another presubmit job for knative/net-istio using istio-latest
  config/prow/config_knative.yaml
  config/prow/jobs/config.yaml
Labels: approved, cla: yes, lgtm, size/M

#1850 Avoid running go get from the repo root dir
  scripts/library.sh
Labels: approved, cla: yes, lgtm, size/S

#1848 Bug fixes for prow-config-updater
  config/prow/jobs/config.yaml
  tools/cleanup/cleanup_test.go
  tools/config-generator/postsubmit_config.go
  tools/prow-config-updater/config/config.go
  tools/prow-config-updater/github_commenter.go
  tools/prow-config-updater/pullrequest.go
  tools/prow-config-updater/updater.go
Labels: approved, cla: yes, lgtm, size/M

#1841 Enable net-http01 e2e tests
  config/prow/config_knative.yaml
  config/prow/jobs/config.yaml
Labels: approved, cla: yes, lgtm, size/M

#1853 Fix issue in run_go_tool
  hack/update-deps.sh
  scripts/library.sh
  third_party/VENDOR-LICENSE
Labels: approved, cla: yes, lgtm, size/XXL

#1851 Set up https://github.com/knative-sandbox/operator
  config/prow/config_knative.yaml
  config/prow/core/config.yaml
  config/prow/core/plugins.yaml
  config/prow/jobs/config.yaml
  config/prow/testgrid/testgrid.yaml
Labels: approved, cla: yes, lgtm, size/L

#1857 Update prow-tests image to use latest kubekins-e2e
  images/prow-tests/Dockerfile
Labels: approved, cla: yes, lgtm, size/XS

#1854 Add net-kourier e2e testing
  config/prow/config_knative.yaml
  config/prow/jobs/config.yaml
Labels: approved, cla: yes, lgtm, size/M

#1861 Update janitor to make it wokr
  config/prow-staging/cluster/400-boskos-deployment.yaml
  config/prow-staging/cluster/400-boskos-janitor.yaml
  config/prow-staging/cluster/400-boskos-metrics.yaml
  config/prow-staging/cluster/400-boskos-reaper.yaml
Labels: approved, cla: yes, lgtm, size/XS

#1860 Add net-certmanager to mega config
  config/prow/config_knative.yaml
  config/prow/core/config.yaml
  config/prow/core/plugins.yaml
  config/prow/jobs/config.yaml
  config/prow/testgrid/testgrid.yaml
Labels: approved, cla: yes, lgtm, size/L

#1867 Flaky test reporter skip Slack notification on weekends
  tools/flaky-test-reporter/main.go
Labels: approved, cla: yes, lgtm, size/S

#1868 fix two shell syntax issues
  scripts/presubmit-tests.sh
Labels: approved, cla: yes, lgtm, size/XS

#1870 Highlight datarace errors in spyglass logs
  config/prow-staging/core/config.yaml
  tools/config-generator/templates/prow-staging/prow_config.yaml
Labels: approved, cla: yes, lgtm, size/XS

#1869 chore: Remove gocoverage for client-contrib
  config/prow/config_knative.yaml
  config/prow/jobs/config.yaml
  config/prow/testgrid/testgrid.yaml
Labels: approved, cla: yes, lgtm, size/M

#1880 Append script name to k8s.dump.txt
  scripts/e2e-tests.sh
Labels: approved, cla: yes, lgtm, size/XS
