Repository knative/test-infra, pull requests merged in 2020-08, with the labels that each got.

#2336 [master] Auto-update dependencies
  go.mod
  go.sum
  third_party/VENDOR-LICENSE/github.com/docker/cli/cli/config/NOTICE
  vendor/github.com/docker/cli/AUTHORS
  vendor/github.com/docker/cli/NOTICE
  vendor/github.com/docker/cli/cli/config/config.go
  vendor/github.com/docker/cli/cli/config/configfile/file.go
  vendor/github.com/docker/cli/cli/config/configfile/file_unix.go
  vendor/github.com/docker/cli/cli/config/configfile/file_windows.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#2335 Replace go-junit-report with gotestsum
  images/prow-tests/Dockerfile
  scripts/e2e-tests.sh
  scripts/library.sh
  test/e2e-tests.sh
  tools/coverage/presubmit_test.go
Labels: approved, cla: yes, lgtm, size/M

#2339 Omit property in testcase if empty
  pkg/junit/junit.go
  pkg/junit/junit_test.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/S

#2340 Bump the resources for all serving e2e test legs
  config/prod/prow/config_knative.yaml
  config/prod/prow/jobs/config.yaml
Labels: approved, cla: yes, lgtm, size/M

#2347 Add flaky test reporter config for eventing-kafka-broker
  tools/flaky-test-reporter/config/config.yaml
Labels: approved, cla: yes, lgtm, size/XS

#2344 Config generator supports run_if_changed config
  config/prod/prow/config_knative.yaml
  config/prod/prow/jobs/config.yaml
  tools/config-generator/main.go
  tools/config-generator/presubmit_config.go
  tools/config-generator/templates/prow_presubmit_job.yaml
Labels: approved, cla: yes, lgtm, size/M

#2348 gotestsum outputs a json file, for debugging an error
  scripts/library.sh
Labels: approved, cla: yes, lgtm, size/XS

#2349 Post nightly failures to respective channels.
  config/prod/prow/config_knative.yaml
  config/prod/prow/jobs/config.yaml
Labels: approved, cla: yes, lgtm, size/M

#2342 e2e-tests.sh switches to kubetest2
  images/prow-tests/Dockerfile
  scripts/e2e-tests.sh
  scripts/library.sh
  test/e2e-tests.sh
Labels: approved, cla: yes, lgtm, size/L

#2351 Change time schema from float64 to string to preserve precision
  pkg/junit/junit.go
  pkg/junit/junit_test.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#2352 Add Kong test jobs
  config/prod/prow/config_knative.yaml
  config/prod/prow/jobs/config.yaml
  config/prod/prow/testgrid/testgrid.yaml
  pkg/testgrid/testgrid.go
  tools/flaky-test-reporter/config/config.yaml
Labels: approved, cla: yes, lgtm, size/L

#2354 GKE cluster creation creates network plus firewall rules
  scripts/e2e-tests.sh
Labels: approved, cla: yes, lgtm, size/XS

#2353 GKE cluster creation creates network plus firewall rules
  scripts/e2e-tests.sh
Labels: approved, cla: yes, size/XS

#2341 Replace Istio versions by stable/latest channels
  config/prod/prow/config_knative.yaml
  config/prod/prow/jobs/config.yaml
  config/prod/prow/testgrid/testgrid.yaml
  pkg/testgrid/testgrid.go
  tools/flaky-test-reporter/config/config.yaml
Labels: approved, cla: yes, lgtm, size/L

#2356 Keep in-gvm-env.sh to use different Go version to install tools
  images/prow-tests/Dockerfile
Labels: approved, cla: yes, lgtm, size/XS

#2358 Support passing kubetest2-flag for the e2e-tests.sh
  scripts/e2e-tests.sh
Labels: approved, cla: yes, lgtm, size/XS

#2357 Support passing kubetest2-flag for the e2e-tests.sh
  scripts/e2e-tests.sh
Labels: approved, cla: yes, size/XS

#2359 Require contour-latest, when contour changes
  config/prod/prow/config_knative.yaml
  config/prod/prow/jobs/config.yaml
Labels: approved, cla: yes, lgtm, size/XS

#2360 Enable NodeLocalDNS GKE addon in test setup.
  scripts/e2e-tests.sh
Labels: approved, cla: yes, lgtm, size/XS

#2361 [RELEASE-0.17] Cherry-pick "Enable NodeLocalDNS GKE addon in test setup. (#2360)"
  scripts/e2e-tests.sh
Labels: approved, cla: yes, lgtm, size/XS

#2362 Make gotestsum verbosity configurable
  scripts/library.sh
Labels: approved, cla: yes, lgtm, size/XS

#2363 [release 0.17] Make gotestsum verbosity configurable (#2362)
  scripts/library.sh
Labels: cla: yes, size/XS

#2364 Abstract the infra related code out to a separate script and some cleanups
  scripts/README.md
  scripts/e2e-tests.sh
  scripts/infra-library.sh
  scripts/library.sh
  scripts/presubmit-tests.sh
Labels: approved, cla: yes, lgtm, size/XL

#2366 Add a post-submit job for knative-sandbox/net-istio to run with latest Istio version.
  config/prod/prow/config_knative.yaml
  config/prod/prow/jobs/config.yaml
  config/prod/prow/testgrid/testgrid.yaml
Labels: approved, cla: yes, lgtm, size/M

#2367 Fix wrong repo in #2366, should have been net-istio.
  config/prod/prow/config_knative.yaml
  config/prod/prow/jobs/config.yaml
  config/prod/prow/testgrid/testgrid.yaml
Labels: approved, cla: yes, lgtm, size/M

#2372 Fix release jobs for a few knative-sandbox repos
  config/prod/prow/config_knative.yaml
  config/prod/prow/jobs/config.yaml
Labels: approved, cla: yes, lgtm, size/M

#2370 Run more Istio tests when net-istio.yaml changes.
  config/prod/prow/config_knative.yaml
  config/prod/prow/jobs/config.yaml
Labels: approved, cla: yes, lgtm, size/XS

#2375 Revert "[Auto] Update prow jobs for release branches"
  config/prod/prow/config_knative.yaml
  config/prod/prow/jobs/config.yaml
  config/prod/prow/testgrid/testgrid.yaml
Labels: approved, cla: yes, lgtm, size/L

#2376 Restore from revert "[Auto] Update prow jobs for release branches""
  config/prod/prow/config_knative.yaml
  config/prod/prow/jobs/config.yaml
  config/prod/prow/testgrid/testgrid.yaml
Labels: approved, cla: yes, lgtm, size/L

#2368 [master] Format markdown
  scripts/README.md
Labels: approved, cla: yes, lgtm, size/S

#2385 Make E2E_SCRIPT value global
  scripts/e2e-tests.sh
Labels: approved, cla: yes, lgtm, size/XS

#2383 Fix Peribolos Prow jobs by using a different GitHub token and running it in the build cluster
  config/prod/prow/jobs/custom/peribolos.yaml
Labels: approved, cla: yes, lgtm, size/M

#2386 Use dependabot to update go deps
  .github/dependabot.yml
Labels: approved, cla: yes, lgtm, size/S

#2382 Remove dot-dev and ORG_NAME env var from meta job config
  config/prod/prow/config_knative.yaml
  config/prod/prow/jobs/config.yaml
  config/prod/prow/jobs/custom/test-infra.yaml
  tools/config-generator/main.go
  tools/config-generator/perf_config.go
  tools/config-generator/periodic_config.go
  tools/config-generator/postsubmit_config.go
Labels: approved, cla: yes, lgtm, size/XL

#2388 Install Go 1.15 in the prow-tests image
  images/prow-tests/Dockerfile
Labels: approved, cla: yes, lgtm, size/XS

#2390 Revert "Use dependabot to update go deps"
  .github/dependabot.yml
Labels: approved, cla: yes, lgtm, size/S

#2391 add clerk interface
  go.sum
  third_party/VENDOR-LICENSE/k8s.io/apimachinery/pkg/LICENSE
  tools/dkcm/README.md
  tools/dkcm/clerk/clerk.go
  vendor/k8s.io/apimachinery/pkg/types/doc.go
  vendor/k8s.io/apimachinery/pkg/types/namespacedname.go
  vendor/k8s.io/apimachinery/pkg/types/nodename.go
  vendor/k8s.io/apimachinery/pkg/types/patch.go
  vendor/k8s.io/apimachinery/pkg/types/uid.go
  vendor/k8s.io/apimachinery/pkg/util/uuid/uuid.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#2394 Grant container admin role to the Prow tests service account
  config/prod/build-cluster/boskos/set_up_boskos_project.sh
Labels: approved, cla: yes, lgtm, size/XS

#2397 Split apart the net-contour jobs
  config/prod/prow/config_knative.yaml
  config/prod/prow/jobs/config.yaml
Labels: approved, cla: yes, lgtm, size/M

#2393 More improvements to the bash scripts
  scripts/e2e-tests.sh
  scripts/infra-library.sh
  scripts/library.sh
Labels: approved, cla: yes, lgtm, size/L

#2396 update config_knative with new async repo
  config/prod/prow/config_knative.yaml
  config/prod/prow/jobs/config.yaml
  config/prod/prow/testgrid/testgrid.yaml
Labels: approved, cla: yes, lgtm, ok-to-test, size/L

#2399 Fix flaky test reporter by removing over cautious check
  tools/flaky-test-reporter/result.go
Labels: approved, cla: yes, lgtm, size/XS

#2400 Cleanup prow-tests Dockerfile
  images/prow-tests/Dockerfile
Labels: approved, cla: yes, lgtm, size/S

#2403 No prow tests in eventing rabbitmq
  config/prod/prow/config_knative.yaml
  config/prod/prow/jobs/config.yaml
Labels: approved, cla: yes, lgtm, size/L
