Repository knative/test-infra, pull requests merged in 2020-06, with the labels that each got.

#2127 Use updateconfig plugin for updating prow job configs
  config/staging/prow/core/plugins.yaml
  tools/config-generator/main.go
  tools/config-generator/templates/prow-staging/prow_plugins.yaml
Labels: approved, cla: yes, lgtm, size/M

#2135 Auto config updater only monitors master branch
  config/prod/prow/jobs/custom-jobs.yaml
Labels: approved, cla: yes, lgtm, size/XS

#2138 Revert "Use updateconfig plugin for updating prow job configs"
  config/staging/prow/core/plugins.yaml
  tools/config-generator/main.go
  tools/config-generator/templates/prow-staging/prow_plugins.yaml
Labels: approved, cla: yes, lgtm, size/M

#2140 Update knative.dev/pkg for test-infra.
  go.mod
  go.sum
  tools/monitoring/alert/alert.go
  tools/monitoring/main.go
  vendor/knative.dev/pkg/test/gcs/client.go
  vendor/knative.dev/pkg/test/gcs/gcs.go
  vendor/knative.dev/pkg/test/gcs/helpers.go
  vendor/knative.dev/pkg/test/prow/prow.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#2139 Use configupdater
  config/staging/prow/core/config.yaml
  config/staging/prow/core/plugins.yaml
  tools/config-generator/main.go
  tools/config-generator/templates/prow-staging/prow_plugins.yaml
Labels: approved, cla: yes, lgtm, size/M

#2123 Fix #2120
  tools/flaky-test-reporter/result.go
  tools/flaky-test-reporter/result_test.go
Labels: approved, cla: yes, lgtm, size/L

#2146 added mem limit for knative-gcp release
  config/prod/prow/config_knative.yaml
  config/prod/prow/jobs/config.yaml
Labels: approved, cla: yes, lgtm, size/L

#2150 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/test/junit/junit.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#2151 Add 0.15 dot release jobs
  config/prod/prow/config_knative.yaml
  config/prod/prow/jobs/config.yaml
  config/prod/prow/testgrid/testgrid.yaml
Labels: approved, cla: yes, lgtm, size/XXL

#2144 Also update prow core/plugin using configupdater
  config/staging/prow/core/plugins.yaml
  tools/config-generator/main.go
  tools/config-generator/templates/prow-staging/prow_plugins.yaml
Labels: approved, cla: yes, lgtm, size/S

#2147 Use go version defined in go.mod to run Prow jobs
  images/prow-tests/Dockerfile
  images/prow-tests/runner.sh
Labels: approved, cla: yes, lgtm, size/S

#2155 Add status-reconciler deployment
  config/staging/prow/cluster/301-rbac.yaml
  config/staging/prow/cluster/500-status-reconciler.yaml
Labels: approved, cla: yes, lgtm, size/L

#2157 Update mkpj image to the latest
  config/prod/prow/run_job.sh
Labels: approved, cla: yes, lgtm, size/XS

#2145 Updating prow configs straight in postsubmit jobs instead of auto con…
  config/prod/prow/jobs/custom-jobs.yaml
  config/prow_common.mk
Labels: approved, cla: yes, lgtm, size/M

#2158 Update custom jobs to use prow-tests image
  config/prod/prow/jobs/custom-jobs.yaml
Labels: approved, cla: yes, lgtm, size/XS

#2159 Fix makefile
  config/prow_common.mk
Labels: approved, cla: yes, lgtm, size/XS

#2160 Update copyright year of plugin config
  config/prod/prow/core/plugins.yaml
  config/staging/prow/core/plugins.yaml
  tools/config-generator/templates/prow-staging/prow_plugins.yaml
  tools/config-generator/templates/prow/prow_plugins.yaml
Labels: approved, cla: yes, lgtm, size/XS

#2161 Update prow image version
  config/prod/prow/core/config.yaml
  tools/config-generator/templates/prow/prow_config.yaml
Labels: approved, cla: yes, lgtm, size/S

#2162 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/test/gcs/gcs.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/S

#2164 Update hook to latest with better debugging message on updateconfig p…
  config/prod/prow/cluster/400-hook.yaml
Labels: approved, cla: yes, lgtm, size/XS

#2165 Switch prow image bumper to update prod configs
  config/prod/prow/core/plugins.yaml
  config/staging/prow/core/plugins.yaml
  tools/config-generator/templates/prow-staging/prow_plugins.yaml
  tools/config-generator/templates/prow/prow_plugins.yaml
  tools/prow-auto-bumper/config.go
Labels: approved, cla: yes, lgtm, size/S

#2148 Remove the logic to set go version via Prow jobs
  config/prod/prow/config_knative.yaml
  config/prod/prow/jobs/config.yaml
  config/staging/prow/config_staging.yaml
  config/staging/prow/jobs/config.yaml
  tools/config-generator/main.go
  tools/config-generator/perf_config.go
  tools/config-generator/periodic_config.go
  tools/config-generator/postsubmit_config.go
  tools/config-generator/presubmit_config.go
Labels: approved, cla: yes, lgtm, size/XXL

#2166 increase the memory limit when running e2e tests of knative gcp
  config/prod/prow/config_knative.yaml
  config/prod/prow/jobs/config.yaml
Labels: approved, cla: yes, lgtm, size/S

#2167 Taking a hook bug fix
  config/prod/prow/cluster/400-hook.yaml
Labels: approved, cla: yes, lgtm, size/XS

#2168 Stop using serving.yaml
  scripts/library.sh
Labels: approved, cla: yes, lgtm, size/S

#2169 No op plugin updates
  config/prod/prow/core/plugins.yaml
  tools/config-generator/templates/prow/prow_plugins.yaml
Labels: approved, cla: yes, lgtm, size/XS

#2170 Add missing rbac for hook, this should fix updateconfig plugin
  config/prod/prow/cluster/301-rbac.yaml
  config/prod/prow/core/plugins.yaml
  tools/config-generator/templates/prow/prow_plugins.yaml
Labels: approved, cla: yes, lgtm, size/XS

#2172 Fix start_serving by installing net-istio
  scripts/library.sh
Labels: approved, cla: yes, lgtm, size/XS

#2173 Use runner.sh for the config-updater job
  config/prod/prow/jobs/custom-jobs.yaml
Labels: approved, cla: yes, lgtm, size/XS

#2176 Cleaning up Prow jobs and fixing some issues
  config/prod/prow/config_knative.yaml
  config/prod/prow/jobs/config.yaml
  config/prod/prow/testgrid/testgrid.yaml
Labels: approved, cla: yes, lgtm, size/XXL

#2163 Deprecating monitoring tool
  images/clear-test-infra-alerts/Makefile
  images/monitoring/Makefile
  tools/flaky-test-retryer/github_commenter_test.go
  tools/flaky-test-retryer/handler.go
  tools/flaky-test-retryer/log_parser.go
  tools/flaky-test-retryer/log_parser_test.go
  tools/flaky-test-retryer/prowapi/types.go
  tools/flaky-test-retryer/subscriber/subscriber.go
  tools/flaky-test-retryer/subscriber/subscriber_test.go
  tools/monitoring/Makefile
  tools/monitoring/README.md
  tools/monitoring/alert/alert.go
  tools/monitoring/alert/report.go
  tools/monitoring/alert/report_test.go
  tools/monitoring/clearalerts/Makefile
  tools/monitoring/clearalerts/main.go
  tools/monitoring/clearalerts/run_clear_alerts.sh
  tools/monitoring/config/config.go
  tools/monitoring/config/config.yaml
  tools/monitoring/config/config_test.go
  tools/monitoring/config/sample.yaml
  tools/monitoring/gke_deployment/monitoring_service.yaml
  tools/monitoring/log_parser/log_parser.go
  tools/monitoring/log_parser/log_parser_test.go
  tools/monitoring/mail/mail.go
  tools/monitoring/mail/mail_test.go
  tools/monitoring/main.go
  tools/monitoring/mysql/README.md
  tools/monitoring/mysql/database.go
  tools/monitoring/mysql/schema.sql
  tools/monitoring/systems.png
Labels: approved, cla: yes, lgtm, size/XXL

#2178 Configure test-infra for knative/networking repository
  config/prod/prow/config_knative.yaml
  config/prod/prow/jobs/config.yaml
  config/prod/prow/testgrid/testgrid.yaml
Labels: approved, cla: yes, lgtm, size/L

#2181 Update deck image to fix spamming errors, restore updateconfig plugin
  config/prod/prow/cluster/400-deck.yaml
  config/prod/prow/cluster/400-hook.yaml
Labels: approved, cla: yes, lgtm, size/XS

#2182 Configure dot release for net-istio 0.14
  config/prod/prow/config_knative.yaml
  config/prod/prow/jobs/config.yaml
  config/prod/prow/testgrid/testgrid.yaml
Labels: approved, cla: yes, lgtm, size/M

#2184 Taking in deck patch for removing noises
  config/prod/prow/cluster/400-deck.yaml
Labels: approved, cla: yes, lgtm, size/XS

#2141 Define scripts/ as a submodule
  scripts/dummy.go
  scripts/go.mod
  scripts/presubmit-tests.sh
Labels: approved, cla: yes, lgtm, size/S

#2185 Revert "Define scripts/ as a submodule"
  scripts/dummy.go
  scripts/go.mod
  scripts/presubmit-tests.sh
Labels: approved, cla: yes, lgtm, size/S

#2188 Update release jobs
  config/prod/prow/config_knative.yaml
  config/prod/prow/jobs/config.yaml
  config/prod/prow/testgrid/testgrid.yaml
  tools/config-generator/main.go
  tools/config-generator/udpaterelease.go
  tools/config-generator/updaterelease_test.go
Labels: approved, cla: yes, lgtm, size/XXL

#2190 updateConcernedFiles returns the stored value, not always true.
  tools/coverage/calc/base.go
Labels: approved, cla: yes, lgtm, size/XS

#2193 Auto push images
  config/prod/prow/jobs/custom-jobs.yaml
  images/push-all.sh
Labels: approved, cla: yes, lgtm, size/M

#2195 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/test/ghutil/client.go
  vendor/knative.dev/pkg/test/ghutil/fakeghutil/fakeghutil.go
  vendor/knative.dev/pkg/test/ghutil/repo.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#2196 Update crier and prow-staging
  config/prod/prow/cluster/400-crier.yaml
  config/staging/prow/cluster/400-crier.yaml
  config/staging/prow/cluster/400-deck.yaml
  config/staging/prow/cluster/400-ghproxy.yaml
  config/staging/prow/cluster/400-hook.yaml
  config/staging/prow/cluster/400-horologium.yaml
  config/staging/prow/cluster/400-plank.yaml
  config/staging/prow/cluster/400-sinker.yaml
  config/staging/prow/cluster/400-tide.yaml
  config/staging/prow/cluster/500-needs-rebase.yaml
  config/staging/prow/core/config.yaml
  tools/config-generator/templates/prow-staging/prow_config.yaml
Labels: approved, cla: yes, lgtm, size/M

#2191 Add a package for syncing prow jobs based on release branch
  tools/prow-jobs-syncer/config.go
  tools/prow-jobs-syncer/main.go
  tools/prow-jobs-syncer/pullrequest.go
Labels: approved, cla: yes, lgtm, size/L

#2198 Remove boskos from prow default cluster and move entirely to build cluster
  config/prod/build-cluster/boskos/README.md
  config/prod/build-cluster/boskos/create_boskos_projects.sh
  config/prod/build-cluster/boskos/set_up_boskos_project.sh
  config/prod/build-cluster/boskos/update_all_boskos_projects.sh
  config/prod/prow/boskos/boskos_resources.yaml
  config/prod/prow/cluster/301-rbac.yaml
  config/prod/prow/cluster/400-boskos-deployment.yaml
  config/prod/prow/cluster/400-boskos-janitor.yaml
  config/prod/prow/cluster/400-boskos-metrics.yaml
  config/prod/prow/cluster/400-boskos-reaper.yaml
  config/prod/prow/cluster/400-boskos.yaml
  tools/prow-config-updater/config/config.go
Labels: approved, cla: yes, lgtm, size/L

#2179 Install kntest in Dockerfile and use it to create junit xml file
  images/prow-tests/Dockerfile
  scripts/library.sh
Labels: approved, cla: yes, lgtm, size/M

#2201 Enable DIND in image pushing job
  config/prod/prow/jobs/custom-jobs.yaml
Labels: approved, cla: yes, lgtm, size/XS

#2202 Add testgrid tabs for all in house tools
  config/prod/prow/testgrid/testgrid.yaml
  tools/config-generator/customjobs.go
  tools/config-generator/customjobs_test.go
  tools/config-generator/main.go
  tools/config-generator/testgrid_config.go
Labels: approved, cla: yes, lgtm, size/XL

#2203 Skip collecting event log with -o yaml
  scripts/e2e-tests.sh
Labels: approved, cla: yes, lgtm, size/XS

#2206 Revert "Add testgrid tabs for all in house tools"
  config/prod/prow/testgrid/testgrid.yaml
  tools/config-generator/customjobs.go
  tools/config-generator/customjobs_test.go
  tools/config-generator/main.go
  tools/config-generator/testgrid_config.go
Labels: approved, cla: yes, lgtm, size/XL

#2207 Readd testgrid custom job
  config/prod/prow/testgrid/testgrid.yaml
  tools/config-generator/customjobs.go
  tools/config-generator/customjobs_test.go
  tools/config-generator/main.go
  tools/config-generator/testgrid_config.go
Labels: approved, cla: yes, lgtm, size/XL

#2208 Fixing testgrid config, by the way add verify testgrid config make ta…
  config/prod/prow/jobs/custom-jobs.yaml
  config/prod/prow/testgrid/testgrid.yaml
  config/prow_common.mk
  tools/config-generator/customjobs.go
Labels: approved, cla: yes, lgtm, size/M

#2192 Add a job for updating release branch jobs
  config/prod/prow/jobs/custom-jobs.yaml
  config/prod/prow/testgrid/testgrid.yaml
  tools/config-generator/customjobs.go
Labels: approved, cla: yes, lgtm, size/M

#2212 Check for git status before git commiting
  pkg/git/commit.go
  tools/prow-auto-bumper/pullrequest.go
  tools/prow-config-updater/pullrequest.go
  tools/prow-jobs-syncer/pullrequest.go
Labels: approved, cla: yes, lgtm, size/M

#2210 Set up label_sync for knative and knative-sandbox org
  config/prod/prow/jobs/custom-jobs.yaml
  label_sync/README.md
  label_sync/labels.yaml
Labels: approved, cla: yes, lgtm, size/L

#2213 Increase frequency and concurrency count for the cleanup job
  config/prod/prow/jobs/custom-jobs.yaml
Labels: approved, cla: yes, lgtm, size/S

#2204 Stop updating prow deployments from knative/test-infra
  config/prod/prow/jobs/custom-jobs.yaml
  config/prow_common.mk
Labels: approved, cla: yes, lgtm, size/S

#2214 [master] Fix spelling errors
  tools/prow-auto-bumper/pullrequest.go
  tools/prow-config-updater/pullrequest.go
  tools/prow-jobs-syncer/pullrequest.go
Labels: approved, cla: yes, lgtm, size/XS

#2215 [master] Format markdown
  label_sync/README.md
Labels: approved, cla: yes, lgtm, size/XS

#2216 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/test/spoof/spoof.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XS

#2060 Add peribolos job for updating knative-sandbox
  config/prod/prow/jobs/custom/peribolos.yaml
  config/prod/prow/jobs/custom/test-infra.yaml
  config/prod/prow/testgrid/testgrid.yaml
  tools/config-generator/customjobs.go
  tools/config-generator/customjobs_test.go
Labels: approved, cla: yes, lgtm, size/L

#2220 Fix job config path for updateconfig plugin
  config/prod/prow/core/plugins.yaml
  tools/config-generator/main.go
Labels: approved, cla: yes, lgtm, size/XS

#2219 Fixing image push job
  config/prod/prow/jobs/custom/test-infra.yaml
Labels: approved, cla: yes, lgtm, size/XS

#2224 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/go.opencensus.io/Makefile
  vendor/go.opencensus.io/plugin/ocgrpc/client.go
  vendor/go.opencensus.io/plugin/ocgrpc/server.go
  vendor/go.opencensus.io/plugin/ocgrpc/trace_common.go
  vendor/go.opencensus.io/plugin/ochttp/propagation/b3/b3.go
  vendor/go.opencensus.io/stats/record.go
  vendor/go.opencensus.io/stats/view/export.go
  vendor/go.opencensus.io/stats/view/view_to_metric.go
  vendor/go.opencensus.io/stats/view/worker.go
  vendor/go.opencensus.io/stats/view/worker_commands.go
  vendor/go.opencensus.io/trace/lrumap.go
  vendor/go.opencensus.io/trace/trace.go
  vendor/knative.dev/pkg/test/presubmit-tests.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#2223 Exclude long-job-names warning for checkconfig and clean up code
  config/prod/prow/jobs/custom/test-infra.yaml
  tools/config-generator/main.go
  tools/config-generator/udpaterelease.go
  tools/config-generator/utils.go
Labels: approved, cla: yes, lgtm, size/L

#2218 prow config check using a script
  config/prod/prow/check_config.sh
  config/prod/prow/jobs/custom/test-infra.yaml
  config/prow_common.mk
Labels: approved, cla: yes, lgtm, size/M

#2227 Fixing config check job error by adding missing volumeMounts
  config/prod/prow/jobs/custom/test-infra.yaml
Labels: approved, cla: yes, lgtm, size/XS

#2228 Enable override plugin
  config/prod/prow/core/plugins.yaml
  tools/config-generator/templates/prow/prow_plugins.yaml
Labels: approved, cla: yes, lgtm, size/XS

#2226 Try moving the sample-controller
  config/prod/prow/config_knative.yaml
  config/prod/prow/jobs/config.yaml
  config/prod/prow/testgrid/testgrid.yaml
Labels: approved, cla: yes, lgtm, size/L

#2222 Add eventing-kafka-broker prow jobs
  config/prod/prow/config_knative.yaml
  config/prod/prow/jobs/config.yaml
  config/prod/prow/testgrid/testgrid.yaml
Labels: approved, cla: yes, lgtm, size/L

#2229 Enable more options for the peribolos job
  config/prod/prow/jobs/custom/peribolos.yaml
Labels: approved, cla: yes, lgtm, size/XS

#2230 Add periodic peribolos job
  config/prod/prow/jobs/custom/peribolos.yaml
Labels: approved, cla: yes, lgtm, size/M

#2231 Add needs-dind to eventing-kafka-broker
  config/prod/prow/config_knative.yaml
  config/prod/prow/jobs/config.yaml
Labels: approved, cla: yes, lgtm, size/M

#2232 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/test/gcs/gcs.go
  vendor/knative.dev/pkg/testutils/clustermanager/prow-cluster-operation/README.md
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/S

#2233 Add tooling to generate protobufs to test Dockerfile.
  images/prow-tests/Dockerfile
Labels: approved, cla: yes, lgtm, size/XS

#2234 Increase image push job memory limit to 16Gb
  config/prod/prow/jobs/custom/test-infra.yaml
Labels: approved, cla: yes, lgtm, size/XS

#2237 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/go.opencensus.io/plugin/ochttp/propagation/tracecontext/propagation.go
  vendor/knative.dev/pkg/test/spoof/spoof.go
  vendor/knative.dev/pkg/tracing/propagation/http_format_sequence.go
  vendor/knative.dev/pkg/tracing/propagation/tracecontextb3/http_format.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#2238 Add periodic Prow job for label_sync
  config/prod/prow/jobs/custom/label-sync.yaml
  config/prod/prow/jobs/custom/test-infra.yaml
Labels: approved, cla: yes, lgtm, size/L

#2236 Increase image push job memory limit to 32 Gb
  config/prod/prow/jobs/custom/test-infra.yaml
Labels: approved, cla: yes, lgtm, size/XS

#2240 Update peribolos image to the latest
  config/prod/prow/jobs/custom/label-sync.yaml
  config/prod/prow/jobs/custom/peribolos.yaml
Labels: approved, cla: yes, lgtm, size/XS

#2242 Add peribolos Prow jobs for Knative
  config/prod/prow/jobs/custom/peribolos.yaml
Labels: approved, cla: yes, lgtm, size/M

#2243 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/test/ghutil/fakeghutil/fakeghutil.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/S

#2244 Move sample-source to knative-sandbox
  config/prod/prow/config_knative.yaml
  config/prod/prow/jobs/config.yaml
  config/prod/prow/testgrid/testgrid.yaml
Labels: approved, cla: yes, lgtm, size/M

#2245 Add discovery repo configs
  config/prod/prow/config_knative.yaml
  config/prod/prow/jobs/config.yaml
  config/prod/prow/testgrid/testgrid.yaml
Labels: approved, cla: yes, lgtm, size/L

#2247 Bump prow versions using k8s auto bumper
  config/prod/prow/jobs/custom/test-infra.yaml
Labels: approved, cla: yes, lgtm, size/M

#2246 Fix some name errors for knative-sandbox in testgrid config file
  config/prod/prow/testgrid/testgrid.yaml
  tools/config-generator/main.go
  tools/config-generator/types.go
Labels: approved, cla: yes, lgtm, size/L

#2250 Fix autobump
  config/prod/prow/jobs/custom/test-infra.yaml
Labels: approved, cla: yes, lgtm, size/XS

#2225 Update instructions post oss-test-infra migration, as well as stop ge…
  guides/manual_release.md
  guides/prow_setup.md
  hack/generate-configs.sh
  tools/config-generator/main.go
  tools/config-generator/templates/prow-staging/prow_config.yaml
  tools/config-generator/templates/prow-staging/prow_plugins.yaml
  tools/config-generator/templates/prow/prow_config.yaml
  tools/config-generator/templates/prow/prow_plugins.yaml
  tools/prow-config-updater/config/config.go
  tools/prow-config-updater/config/config_test.go
  tools/prow-jobs-syncer/main.go
Labels: approved, cla: yes, lgtm, size/XL

#2253 Do not generate issue tracker Prow jobs
  config/prod/prow/jobs/config.yaml
  config/prod/prow/jobs/custom/issue-tracker.yaml
  guides/prow_knative_setup.md
  hack/generate-configs.sh
  tools/config-generator/issue_tracker_config.go
  tools/config-generator/main.go
Labels: approved, cla: yes, lgtm, size/XL

#2254 Add stdout option to exec.Command
  pkg/cmd/command.go
Labels: approved, cla: yes, lgtm, size/S

#2255 Stop updating core and plugins config from knative prow
  config/prod/prow/core/plugins.yaml
Labels: approved, cla: yes, lgtm, size/XS

#2257 [master] Format markdown
  guides/prow_setup.md
Labels: approved, cla: yes, lgtm, size/S
