Repository knative/test-infra, pull requests merged in 2021-01, with the labels that each got.

#2616 [Automated] Update actions
  .github/workflows/knative-releasability.yaml
  .github/workflows/knative-verify.yaml
Labels: approved, cla: yes, lgtm, size/XS

#2618 [Automated] Update actions
  .github/workflows/knative-releasability.yaml
Labels: approved, cla: yes, lgtm, size/XS

#2619 Change knative-gcp upgrade test to optional
  config/prod/prow/config_knative.yaml
  config/prod/prow/jobs/config.yaml
Labels: approved, cla: yes, lgtm, size/XS

#2620 Add a script for enabling rbe in knative-tests project
  config/prod/build-cluster/rbe.sh
Labels: approved, cla: yes, lgtm, size/M

#2621 Patch rbe.sh script to make it work`
  config/prod/build-cluster/rbe.sh
Labels: approved, cla: yes, lgtm, size/XS

#2623 Manually regen deps
  go.mod
  go.sum
  scripts/library.sh
  vendor/knative.dev/hack/library.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#2624 Fix the test name and the test
  tools/dkcm/clerk/clerk.go
  tools/dkcm/clerk/clerk_test.go
Labels: approved, cla: yes, lgtm, size/S

#2626 Drop in replacement using uber/sync
  go.mod
  go.sum
  third_party/VENDOR-LICENSE/go.uber.org/atomic/LICENSE.txt
  tools/cleanup/cleanup.go
  vendor/go.uber.org/atomic/.codecov.yml
  vendor/go.uber.org/atomic/.gitignore
  vendor/go.uber.org/atomic/.travis.yml
  vendor/go.uber.org/atomic/CHANGELOG.md
  vendor/go.uber.org/atomic/LICENSE.txt
  vendor/go.uber.org/atomic/Makefile
  vendor/go.uber.org/atomic/README.md
  vendor/go.uber.org/atomic/atomic.go
  vendor/go.uber.org/atomic/error.go
  vendor/go.uber.org/atomic/go.mod
  vendor/go.uber.org/atomic/go.sum
  vendor/go.uber.org/atomic/string.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XL

#2627 Added eventing-autoscaler-keda
  config/prod/prow/config_knative.yaml
  config/prod/prow/jobs/config.yaml
  config/prod/prow/k8s-testgrid/k8s-testgrid.yaml
  config/prod/prow/testgrid/testgrid.yaml
Labels: approved, cla: yes, lgtm, size/L

#2628 Revert "Change knative-gcp upgrade test to optional"
  config/prod/prow/config_knative.yaml
  config/prod/prow/jobs/config.yaml
Labels: approved, cla: yes, lgtm, size/XS

#2629 bump autobumper to working image
  config/prod/prow/jobs/custom/test-infra.yaml
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#2636 [Automated] Update actions
  .github/workflows/knative-style.yaml
Labels: approved, cla: yes, lgtm, size/S

#2637 Add an extra-env to knative-gcp workflows
  config/prod/prow/config_knative.yaml
  config/prod/prow/jobs/config.yaml
Labels: approved, cla: yes, lgtm, size/XS

#2609 Remove eventing performance tests Prow jobs
  config/prod/prow/config_knative.yaml
  config/prod/prow/jobs/config.yaml
Labels: approved, cla: yes, lgtm, size/L

#2638 change default gke region to us-east1
  kntest/pkg/kubetest2/gke/options.go
Labels: approved, cla: yes, lgtm, size/XS

#2639 Change env value in knative-gcp workflows
  config/prod/prow/config_knative.yaml
  config/prod/prow/jobs/config.yaml
Labels: approved, cla: yes, lgtm, size/XS

#2640 Update kubekins-e2e and kubetest2 versions for prow-tests image
  images/prow-tests/Dockerfile
Labels: approved, cla: yes, lgtm, size/XS

#2641 Run conformance tests in mesh mode in net-istio
  config/prod/prow/config_knative.yaml
  config/prod/prow/jobs/config.yaml
Labels: approved, cla: yes, lgtm, size/M

#2644 Add an update_config script to update Prow job config
  config/prod/prow/update_config.sh
Labels: approved, cla: yes, lgtm, size/M
