Repository knative/test-infra, pull requests merged in 2021-11, with the labels that each got.

#2934 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  scripts/release.sh
  vendor/knative.dev/hack/release.sh
  vendor/modules.txt
Labels: approved, size/L, lgtm, cla: yes

#2936 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  scripts/library.sh
  scripts/release.sh
  vendor/knative.dev/hack/library.sh
  vendor/knative.dev/hack/release.sh
  vendor/modules.txt
Labels: approved, size/L, lgtm, cla: yes

#2937 Remove the Prow jobs for performance testing
  config/prod/prow/check_config.sh
  config/prod/prow/config_knative.yaml
  config/prod/prow/jobs/config.yaml
  config/prod/prow/run_job.sh
Labels: approved, size/L, lgtm, cla: yes

#2938 [main] Update community files
  OWNERS_ALIASES
Labels: approved, lgtm, size/XS, cla: yes

#2939 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  scripts/library.sh
  vendor/knative.dev/hack/library.sh
  vendor/modules.txt
Labels: approved, size/L, lgtm, cla: yes

#2941 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  scripts/release.sh
  vendor/knative.dev/hack/release.sh
  vendor/modules.txt
Labels: approved, lgtm, size/S, cla: yes

#2940 [main] Update actions
  .github/workflows/knative-boilerplate.yaml
  .github/workflows/knative-releasability.yaml
  .github/workflows/knative-release-notes.yaml
  .github/workflows/knative-style.yaml
  .github/workflows/knative-verify.yaml
Labels: approved, size/M, lgtm, cla: yes

#2944 drop Kong and Ambassador from CI
  config/prod/prow/config_knative.yaml
  config/prod/prow/jobs/config.yaml
  config/prod/prow/testgrid/testgrid.yaml
  pkg/testgrid/testgrid.go
  tools/flaky-test-reporter/config/config.yaml
Labels: approved, size/L, lgtm, cla: yes

#2947 Add upgrade test Prow job for eventing-kafka-broker
  config/prod/prow/config_knative.yaml
  config/prod/prow/jobs/config.yaml
Labels: approved, size/M, lgtm, cla: yes

#2945 [main] Update community files
  OWNERS_ALIASES
Labels: approved, lgtm, size/XS, cla: yes

#2949 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  scripts/release.sh
  vendor/knative.dev/hack/release.sh
  vendor/modules.txt
Labels: approved, lgtm, size/S, cla: yes

#2950 Add prow job for performance tests
  config/prod/prow/config_knative.yaml
  config/prod/prow/jobs/config.yaml
Labels: approved, size/M, lgtm, cla: yes

#2952 Add continuous, nigthly, auto-released and test-grid for net-gateway-api
  config/prod/prow/config_knative.yaml
  config/prod/prow/jobs/config.yaml
  config/prod/prow/k8s-testgrid/k8s-testgrid.yaml
  config/prod/prow/testgrid/testgrid.yaml
Labels: approved, size/L, lgtm, cla: yes

#2953 Add net-gateway-api job to serving CI
  config/prod/prow/config_knative.yaml
  config/prod/prow/jobs/config.yaml
  config/prod/prow/testgrid/testgrid.yaml
  pkg/testgrid/testgrid.go
Labels: approved, size/L, lgtm, cla: yes
