Repository knative/test-infra, pull requests merged in 2021-05, with the labels that each got.

#2761 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  scripts/codegen-library.sh
  scripts/presubmit-tests.sh
  scripts/release.sh
  vendor/knative.dev/hack/codegen-library.sh
  vendor/knative.dev/hack/presubmit-tests.sh
  vendor/knative.dev/hack/release.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#2776 Add go 1.16 and bump prior versions
  images/prow-tests/Dockerfile
Labels: approved, cla: yes, lgtm, size/XS

#2774 [Automated] Format markdown
  images/prow-tests/README.md
Labels: approved, cla: yes, lgtm, size/S

#2779 Disable knative-gcp performance test jobs
  config/prod/prow/config_knative.yaml
  config/prod/prow/jobs/config.yaml
Labels: approved, cla: yes, lgtm, size/L

#2778 [main] Update actions
  .github/workflows/knative-boilerplate.yaml
  .github/workflows/knative-go-build.yaml
  .github/workflows/knative-go-test.yaml
  .github/workflows/knative-releasability.yaml
  .github/workflows/knative-style.yaml
  .github/workflows/knative-verify.yaml
Labels: approved, cla: yes, lgtm, size/M

#2788 Adding self to OWNERS_ALIASES
  OWNERS_ALIASES
Labels: approved, cla: yes, lgtm, size/XS

#2782 Add guide for SLACK_WEBHOOK
  guides/README.md
  guides/slack/README.md
  guides/slack/configuration.png
  guides/slack/webhook-url.png
Labels: approved, cla: yes, lgtm, size/S

#2783 Bump the protobuf version
  images/prow-tests/Dockerfile
Labels: approved, cla: yes, lgtm, size/XS

#2789 Add productivity-reviewers as the approver for images and config dir
  OWNERS_ALIASES
  config/OWNERS
  config/prod/prow/OWNERS
  images/OWNERS
Labels: approved, cla: yes, lgtm, size/S

#2780 [main] Update actions
  .github/workflows/knative-go-build.yaml
Labels: approved, cla: yes, lgtm, size/XS

#2777 README cleanup
  README.md
Labels: approved, cla: yes, lgtm, size/M

#2792 Switch to OWNERS from CODEOWNERS in knative-sandbox
  config/branch_protector/rules.yaml
Labels: approved, cla: yes, lgtm, size/XS

#2795 [main] Update actions
  .github/workflows/knative-style.yaml
Labels: approved, cla: yes, lgtm, size/XS
