Repository knative/test-infra, pull requests merged in 2021-03, with the labels that each got.

#2677 Add configurator jobs for creating proto consumed by testgrid
  config/prod/prow/jobs/custom/test-infra.yaml
  config/prod/prow/k8s-testgrid/testgrid-common-settings.yaml
Labels: approved, cla: yes, lgtm, size/M

#2683 Add all current 'main' based repos to the respective list
  config/prod/prow/jobs/config.yaml
  tools/config-generator/main.go
Labels: approved, cla: yes, lgtm, size/M

#2685 Allow 'main' to act as the correct branch as well
  common.mk
  config/prow_common.mk
  images/prow-tests/Makefile
  images/simple-image.mk
  tools/flaky-test-retryer/gke_deployment/Makefile
Labels: approved, cla: yes, lgtm, size/S

#2684 Automate filling in the main exception list
  tools/config-generator/main.go
Labels: approved, cla: yes, lgtm, size/M

#2686 Renamed the default branch of Kourier to main
  config/prod/prow/jobs/config.yaml
Labels: approved, cla: yes, lgtm, size/S

#2682 Make validate testgrid config job required
  config/prod/prow/jobs/custom/test-infra.yaml
  config/prow_common.mk
Labels: approved, cla: yes, lgtm, size/M

#2687 Update knative autobump job to new generic autobump image
  config/prod/prow/jobs/custom/test-infra.yaml
  config/prod/prow/knative-autobump-config.yaml
Labels: approved, cla: yes, lgtm, needs-ok-to-test, size/M

#2688 Fix incorrect autobump config
  config/prod/prow/knative-autobump-config.yaml
Labels: approved, cla: yes, lgtm, needs-ok-to-test, size/XS

#2689 Fix job command for generic autobump
  config/prod/prow/jobs/custom/test-infra.yaml
Labels: approved, cla: yes, lgtm, needs-ok-to-test, size/XS

#2690 Fix config path for autobump job
  config/prod/prow/jobs/custom/test-infra.yaml
Labels: approved, cla: yes, lgtm, needs-ok-to-test, size/XS

#2691 Changed all sandbox repos to have main as default branch
  config/prod/prow/jobs/config.yaml
Labels: approved, cla: yes, lgtm, size/L

#2693 Add ssh key for generic autobump job
  config/prod/prow/jobs/custom/test-infra.yaml
  config/prod/prow/knative-autobump-config.yaml
Labels: approved, cla: yes, lgtm, needs-ok-to-test, size/XS

#2667 Add kn-plugin-sample to prow configuration
  config/prod/prow/config_knative.yaml
  config/prod/prow/jobs/config.yaml
  config/prod/prow/k8s-testgrid/k8s-testgrid.yaml
  config/prod/prow/testgrid/testgrid.yaml
  go.sum
Labels: approved, cla: yes, lgtm, size/L

#2696 Move google release artifacts outside knative-releases/nightly
  config/prod/prow/config_knative.yaml
  config/prod/prow/jobs/config.yaml
Labels: approved, cla: yes, lgtm, size/M

#2699 Switch all repos in knative to have main as the default branch
  config/prod/prow/jobs/config.yaml
  config/prod/prow/jobs/custom/branchprotector.yaml
  config/prod/prow/jobs/custom/label-sync.yaml
  config/prod/prow/jobs/custom/peribolos.yaml
  config/prod/prow/jobs/custom/test-infra.yaml
Labels: approved, cla: yes, lgtm, size/L

#2700 Remove Github API calls and default generator to main
  tools/config-generator/main.go
Labels: approved, cla: yes, lgtm, size/M

#2698 eventing is breaking apart e2e and rekt tests
  config/prod/prow/config_knative.yaml
  config/prod/prow/jobs/config.yaml
Labels: approved, cla: yes, lgtm, size/M

#2702 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/README.md
  vendor/knative.dev/hack/go.sum
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/S

#2701 [Automated] Update actions
  .github/workflows/knative-releasability.yaml
  .github/workflows/knative-release-notes.yaml
Labels: approved, cla: yes, lgtm, size/XS

#2705 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  scripts/library.sh
  scripts/microbenchmarks.sh
  vendor/knative.dev/hack/README.md
  vendor/knative.dev/hack/library.sh
  vendor/knative.dev/hack/microbenchmarks.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#2703 Drop unnecessary occurrences of master
  README.md
  config/prod/prow/jobs/config.yaml
  config/prow_common.mk
  guides/manual_release.md
  guides/prow_knative_setup.md
  guides/release_setup.md
  images/README.md
  images/prow-tests/README.md
  pkg/ghutil/fakeghutil/fakeghutil.go
  pkg/ghutil/pullrequest.go
  scripts/update-test-infra.sh
  tools/config-generator/periodic_config.go
  tools/coverage/design.md
  tools/coverage/gcs/gcsPostsubmit.go
  tools/flaky-test-retryer/README.md
  tools/flaky-test-retryer/subscriber/subscriber_test.go
  tools/prow-jobs-syncer/config.go
Labels: approved, cla: yes, lgtm, size/L

#2707 Add knative/specs to prow config
  config/prod/prow/config_knative.yaml
  config/prod/prow/jobs/config.yaml
Labels: approved, cla: yes, lgtm, size/M

#2709 [Automated] Update actions
  .github/workflows/knative-style.yaml
Labels: approved, cla: yes, lgtm, size/XS

#2711 Replace /k8s-testimages/generic_autobumper with /k8s-prow/generic-auto-bumper
  config/prod/prow/jobs/custom/test-infra.yaml
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#2713 Add triaging labels
  config/label_sync/labels.yaml
Labels: approved, cla: yes, lgtm, size/S

#2716 Fix check config tool version to unblock PRs
  config/prod/prow/check_config.sh
Labels: approved, cla: yes, lgtm, size/XS

#2704 Remove knative- prefix from testgrid dashboard names
  config/prod/prow/jobs/config.yaml
  config/prod/prow/k8s-testgrid/k8s-testgrid.yaml
  tools/config-generator/k8s_testgrid_config.go
  tools/config-generator/periodic_config.go
Labels: approved, cla: yes, lgtm, size/XXL

#2715 Images autobump tool: update to use branch main and update to image v…
  config/prod/prow/jobs/custom/test-infra.yaml
  config/prod/prow/knative-autobump-config.yaml
Labels: approved, cla: yes, lgtm, size/XS

#2720 Add labels for ux repo
  config/label_sync/labels.yaml
Labels: approved, cla: yes, lgtm, size/S

#2725 Remove nightly release job and disable go-coverage for net-ingressv2
  config/prod/prow/config_knative.yaml
  config/prod/prow/jobs/config.yaml
  config/prod/prow/k8s-testgrid/k8s-testgrid.yaml
  config/prod/prow/testgrid/testgrid.yaml
Labels: approved, cla: yes, lgtm, size/L

#2727 Remove CI job for Gloo
  config/prod/prow/config_knative.yaml
  config/prod/prow/jobs/config.yaml
  config/prod/prow/testgrid/testgrid.yaml
  pkg/testgrid/testgrid.go
  tools/flaky-test-reporter/config/config.yaml
Labels: approved, cla: yes, lgtm, size/L

#2717 Add eventing e2e tests on s390x architecture
  config/prod/prow/config_knative.yaml
  config/prod/prow/jobs/config.yaml
  config/prod/prow/testgrid/testgrid.yaml
  tools/config-generator/main.go
  tools/config-generator/main_test.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/L

#2721 [Automated] Update actions
  .github/workflows/knative-security.yaml
  .github/workflows/knative-style.yaml
Labels: approved, cla: yes, lgtm, size/XS

#2712 chore: Add kn-plugin-event prow jobs
  config/prod/prow/config_knative.yaml
  config/prod/prow/jobs/config.yaml
  config/prod/prow/k8s-testgrid/k8s-testgrid.yaml
  config/prod/prow/testgrid/testgrid.yaml
Labels: approved, cla: yes, lgtm, size/L

#2722 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  scripts/e2e-tests.sh
  scripts/library.sh
  scripts/presubmit-tests.sh
  vendor/knative.dev/hack/e2e-tests.sh
  vendor/knative.dev/hack/library.sh
  vendor/knative.dev/hack/presubmit-tests.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#2724 Fix flaky-test-reporter by matching the issue owner
  pkg/ghutil/fakeghutil/fakeghutil.go
  tools/flaky-test-reporter/github_issue.go
Labels: approved, cla: yes, lgtm, size/S

#2732 Enable eventing autoscaler keda custom e2e tests
  config/prod/prow/config_knative.yaml
  config/prod/prow/jobs/config.yaml
Labels: approved, cla: yes, lgtm, size/M

#2730 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  scripts/library.sh
  vendor/knative.dev/hack/library.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/S

#2733 Fix the image push check that was broken by https://github.com/knative/test-infra/pull/2685
  common.mk
Labels: approved, cla: yes, lgtm, size/S

#2734 [Automated] Update actions
  .github/workflows/knative-releasability.yaml
Labels: approved, cla: yes, lgtm, size/XS
