Repository knative/test-infra, pull requests merged in 2021-04, with the labels that each got.

#2736 Update OWNERS_ALIASES to match autogen in community
  OWNERS
  OWNERS_ALIASES
Labels: approved, cla: yes, lgtm, size/M

#2738 Regroup generated k8s testgrid config to make it look the same as knative testgrid config
  config/prod/prow/jobs/config.yaml
  config/prod/prow/k8s-testgrid/k8s-testgrid.yaml
  tools/config-generator/k8s_testgrid_config.go
  tools/config-generator/main.go
  tools/config-generator/periodic_config.go
Labels: approved, cla: yes, lgtm, size/XL

#2739 K8s testgrid config: add all utilites tabs and rename google-knative …
  config/prod/prow/jobs/custom/test-infra.yaml
  config/prod/prow/k8s-testgrid/k8s-testgrid.yaml
  tools/config-generator/k8s_testgrid_config.go
Labels: approved, cla: yes, lgtm, size/M

#2740 k8s testgrid: generate based on all jobs
  config/prod/prow/jobs/custom/test-infra.yaml
Labels: approved, cla: yes, lgtm, size/XS

#2741 k8s testgrid: add all missing tabs
  config/prod/prow/jobs/custom/branchprotector.yaml
  config/prod/prow/jobs/custom/label-sync.yaml
  config/prod/prow/jobs/custom/peribolos.yaml
Labels: approved, cla: yes, lgtm, size/M

#2743 K8s testgrid: presubmit test matching postsubmit
  config/prod/prow/jobs/custom/test-infra.yaml
Labels: approved, cla: yes, lgtm, size/XS

#2735 Eventing Kafka upgrade tests
  config/prod/prow/config_knative.yaml
  config/prod/prow/jobs/config.yaml
  hack/generate-configs.sh
Labels: approved, cla: yes, lgtm, size/M

#2742 Update kubectl version in the prow-tests image to v1.18.0
  images/prow-tests/Dockerfile
Labels: approved, cla: yes, lgtm, size/XS

#2745 Update release branch job syncer with latest testgrid code gen changes
  tools/prow-jobs-syncer/config.go
  tools/prow-jobs-syncer/main.go
Labels: approved, cla: yes, lgtm, size/XS

#2747 remove eventing-contrib
  config/prod/gubernator/config.yaml
  config/prod/prow/config_knative.yaml
  config/prod/prow/jobs/config.yaml
  config/prod/prow/k8s-testgrid/k8s-testgrid.yaml
  config/prod/prow/testgrid/testgrid.yaml
  pkg/clustermanager/perf-tests/pkg/benchmark_test.go
  tools/flaky-test-reporter/config/config.yaml
Labels: approved, cla: yes, lgtm, size/XXL

#2746 Configure skip-review label to enable auto-merge a few trusted PRs
  config/label_sync/labels.yaml
  config/prod/prow/jobs/custom/test-infra.yaml
  pkg/ghutil/client.go
  pkg/ghutil/fakeghutil/fakeghutil.go
  pkg/ghutil/pullrequest.go
  tools/prow-jobs-syncer/main.go
  tools/prow-jobs-syncer/pullrequest.go
Labels: approved, cla: yes, lgtm, size/L

#2749 Fix run_if_changed to istio-latest/net-istio.yaml
  config/prod/prow/config_knative.yaml
  config/prod/prow/jobs/config.yaml
Labels: approved, cla: yes, lgtm, size/XS

#2750 bump kubetest2 to latest
  images/prow-tests/Dockerfile
Labels: approved, cla: yes, lgtm, size/XS

#2694 Fix kubetest2 installation in prow-tests image by removing -u option from go get
  images/prow-tests/Dockerfile
Labels: approved, cla: yes, lgtm, size/S

#2756 Added proper dot releases for eventing-kafka and eventing-kafka-broker
  config/prod/prow/config_knative.yaml
  config/prod/prow/jobs/config.yaml
  config/prod/prow/testgrid/testgrid.yaml
Labels: approved, cla: yes, lgtm, size/L

#2753 Setup JDK and Maven
  images/prow-tests/Dockerfile
Labels: approved, cla: yes, lgtm, size/S

#2754 Update protoc version
  images/prow-tests/Dockerfile
Labels: approved, cla: yes, lgtm, size/XS

#2755 Update ko
  images/prow-tests/Dockerfile
Labels: approved, cla: yes, lgtm, size/XS

#2758 Remove deprecated param from autobumper job to make it pass
  config/prod/prow/knative-autobump-config.yaml
Labels: approved, cla: yes, lgtm, size/XS

#2757 Simplify the go get installs
  images/prow-tests/Dockerfile
Labels: approved, cla: yes, lgtm, size/M

#2762 Add protobuf go
  images/prow-tests/Dockerfile
Labels: approved, cla: yes, lgtm, size/XS

#2763 Remove old stuff
  images/prow-tests/Dockerfile
Labels: approved, cla: yes, lgtm, size/S

#2767 Update prow-tests image generation instructions
  images/prow-tests/README.md
Labels: approved, cla: yes, lgtm, size/S
