Repository knative/test-infra, pull requests merged in 2021-06, with the labels that each got.

#2791 [main] Update community files
  OWNERS_ALIASES
Labels: approved, cla: yes, lgtm, size/L

#2781 Add knative-release-leads to OWNERS
  OWNERS
Labels: approved, cla: yes, lgtm, size/XS

#2796 [main] Update community files
  OWNERS_ALIASES
Labels: approved, cla: yes, lgtm, size/XS

#2797 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  scripts/release.sh
  vendor/knative.dev/hack/release.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/S

#2799 [main] Update actions
  .github/workflows/knative-boilerplate.yaml
  .github/workflows/knative-donotsubmit.yaml
  .github/workflows/knative-go-build.yaml
  .github/workflows/knative-go-test.yaml
  .github/workflows/knative-releasability.yaml
  .github/workflows/knative-security.yaml
  .github/workflows/knative-style.yaml
  .github/workflows/knative-verify.yaml
Labels: approved, cla: yes, lgtm, size/S

#2800 Update dependency for release-0.23
  go.mod
  go.sum
  scripts/release.sh
  vendor/knative.dev/hack/release.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/S

#2798 Add prow config for kn-plugin-quickstart
  config/prod/prow/config_knative.yaml
  config/prod/prow/jobs/config.yaml
  config/prod/prow/k8s-testgrid/k8s-testgrid.yaml
  config/prod/prow/testgrid/testgrid.yaml
Labels: approved, cla: yes, lgtm, size/L

#2794 Add custom jobs for s390x
  config/prod/prow/config_knative.yaml
  config/prod/prow/jobs/config.yaml
  config/prod/prow/testgrid/testgrid.yaml
Labels: approved, cla: yes, lgtm, ok-to-test, size/L

#2804 Specify volume permission for s390x tests
  config/prod/prow/jobs/config.yaml
  tools/config-generator/main.go
  tools/config-generator/main_test.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#2805 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  scripts/codegen-library.sh
  scripts/library.sh
  vendor/knative.dev/hack/codegen-library.sh
  vendor/knative.dev/hack/library.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/S

#2806 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  scripts/codegen-library.sh
  vendor/knative.dev/hack/codegen-library.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/S

#2807 [main] Update actions
  .github/workflows/knative-releasability.yaml
  .github/workflows/knative-vulnerability.yaml
Labels: approved, cla: yes, lgtm, size/M

#2808 Run https test when net-certmanager was updated
  config/prod/prow/config_knative.yaml
  config/prod/prow/jobs/config.yaml
Labels: approved, cla: yes, lgtm, size/XS

#2809 Remove dead things and deprecate obsolete libs
  images/dkcm/README.md
  pkg/clustermanager/kubetest2/gke.go
  pkg/cmd/command.go
  pkg/junit/junit.go
  third_party/VENDOR-LICENSE/k8s.io/apimachinery/pkg/util/LICENSE
  tools/dkcm/README.md
  tools/dkcm/clerk/clerk.go
  tools/dkcm/clerk/clerk_test.go
  tools/dkcm/clerk/cluster.go
  tools/dkcm/clerk/cluster_params.go
  tools/dkcm/clerk/constants.go
  tools/dkcm/clerk/request.go
  tools/dkcm/clerk/response.go
  tools/dkcm/clerk/schema.sql
  tools/dkcm/clerk/sql_params.go
  tools/dkcm/main.go
  tools/dkcm/mainservice/constants.go
  tools/dkcm/mainservice/mainservice.go
  tools/prow-jobs-syncer/README.md
  vendor/k8s.io/apimachinery/pkg/types/doc.go
  vendor/k8s.io/apimachinery/pkg/types/namespacedname.go
  vendor/k8s.io/apimachinery/pkg/types/nodename.go
  vendor/k8s.io/apimachinery/pkg/types/patch.go
  vendor/k8s.io/apimachinery/pkg/types/uid.go
  vendor/k8s.io/apimachinery/pkg/util/uuid/uuid.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XXL

#2810 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  scripts/library.sh
  scripts/release.sh
  vendor/knative.dev/hack/library.sh
  vendor/knative.dev/hack/release.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#2812 Add serving-s390x-kourier-test
  config/prod/prow/config_knative.yaml
  config/prod/prow/jobs/config.yaml
  config/prod/prow/testgrid/testgrid.yaml
  third_party/VENDOR-LICENSE/github.com/go-sql-driver/mysql/.gitignore
  third_party/VENDOR-LICENSE/github.com/go-sql-driver/mysql/.travis.yml
  third_party/VENDOR-LICENSE/github.com/go-sql-driver/mysql/AUTHORS
  third_party/VENDOR-LICENSE/github.com/go-sql-driver/mysql/CHANGELOG.md
  third_party/VENDOR-LICENSE/github.com/go-sql-driver/mysql/LICENSE
  third_party/VENDOR-LICENSE/github.com/go-sql-driver/mysql/README.md
  third_party/VENDOR-LICENSE/github.com/go-sql-driver/mysql/auth.go
  third_party/VENDOR-LICENSE/github.com/go-sql-driver/mysql/buffer.go
  third_party/VENDOR-LICENSE/github.com/go-sql-driver/mysql/collations.go
  third_party/VENDOR-LICENSE/github.com/go-sql-driver/mysql/conncheck.go
  third_party/VENDOR-LICENSE/github.com/go-sql-driver/mysql/conncheck_dummy.go
  third_party/VENDOR-LICENSE/github.com/go-sql-driver/mysql/connection.go
  third_party/VENDOR-LICENSE/github.com/go-sql-driver/mysql/connector.go
  third_party/VENDOR-LICENSE/github.com/go-sql-driver/mysql/const.go
  third_party/VENDOR-LICENSE/github.com/go-sql-driver/mysql/driver.go
  third_party/VENDOR-LICENSE/github.com/go-sql-driver/mysql/dsn.go
  third_party/VENDOR-LICENSE/github.com/go-sql-driver/mysql/errors.go
  third_party/VENDOR-LICENSE/github.com/go-sql-driver/mysql/fields.go
  third_party/VENDOR-LICENSE/github.com/go-sql-driver/mysql/go.mod
  third_party/VENDOR-LICENSE/github.com/go-sql-driver/mysql/infile.go
  third_party/VENDOR-LICENSE/github.com/go-sql-driver/mysql/nulltime.go
  third_party/VENDOR-LICENSE/github.com/go-sql-driver/mysql/nulltime_go113.go
  third_party/VENDOR-LICENSE/github.com/go-sql-driver/mysql/nulltime_legacy.go
  third_party/VENDOR-LICENSE/github.com/go-sql-driver/mysql/packets.go
  third_party/VENDOR-LICENSE/github.com/go-sql-driver/mysql/result.go
  third_party/VENDOR-LICENSE/github.com/go-sql-driver/mysql/rows.go
  third_party/VENDOR-LICENSE/github.com/go-sql-driver/mysql/statement.go
  third_party/VENDOR-LICENSE/github.com/go-sql-driver/mysql/transaction.go
  third_party/VENDOR-LICENSE/github.com/go-sql-driver/mysql/utils.go
  third_party/VENDOR-LICENSE/github.com/hashicorp/errwrap/LICENSE
  third_party/VENDOR-LICENSE/github.com/hashicorp/errwrap/README.md
  third_party/VENDOR-LICENSE/github.com/hashicorp/errwrap/errwrap.go
  third_party/VENDOR-LICENSE/github.com/hashicorp/errwrap/go.mod
  third_party/VENDOR-LICENSE/github.com/hashicorp/go-multierror/.travis.yml
  third_party/VENDOR-LICENSE/github.com/hashicorp/go-multierror/LICENSE
  third_party/VENDOR-LICENSE/github.com/hashicorp/go-multierror/Makefile
  third_party/VENDOR-LICENSE/github.com/hashicorp/go-multierror/README.md
  third_party/VENDOR-LICENSE/github.com/hashicorp/go-multierror/append.go
  third_party/VENDOR-LICENSE/github.com/hashicorp/go-multierror/flatten.go
  third_party/VENDOR-LICENSE/github.com/hashicorp/go-multierror/format.go
  third_party/VENDOR-LICENSE/github.com/hashicorp/go-multierror/go.mod
  third_party/VENDOR-LICENSE/github.com/hashicorp/go-multierror/go.sum
  third_party/VENDOR-LICENSE/github.com/hashicorp/go-multierror/multierror.go
  third_party/VENDOR-LICENSE/github.com/hashicorp/go-multierror/prefix.go
  third_party/VENDOR-LICENSE/github.com/hashicorp/go-multierror/sort.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/L

#2815 Update branchprotector Prow job config to also config status contexts for the presubmit Prow jobs
  config/branch_protector/rules.yaml
  config/prod/prow/jobs/custom/branchprotector.yaml
Labels: approved, cla: yes, lgtm, size/XS

#2813 [main] Update community files
  OWNERS_ALIASES
Labels: approved, cla: yes, lgtm, size/XS

#2811 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  scripts/library.sh
  vendor/knative.dev/hack/library.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/S

#2818 Don't protect dependabot branches on knative-sandbox
  config/branch_protector/rules.yaml
Labels: approved, cla: yes, lgtm, size/XS

#2817 Add new job trigger for mesh test with short option
  config/prod/prow/config_knative.yaml
  config/prod/prow/jobs/config.yaml
Labels: approved, cla: yes, lgtm, size/L

#2819 [main] Update community files
  OWNERS_ALIASES
Labels: approved, cla: yes, lgtm, size/XS

#2820 [main] Upgrade to latest dependencies
  third_party/VENDOR-LICENSE/github.com/go-sql-driver/mysql/.gitignore
  third_party/VENDOR-LICENSE/github.com/go-sql-driver/mysql/.travis.yml
  third_party/VENDOR-LICENSE/github.com/go-sql-driver/mysql/AUTHORS
  third_party/VENDOR-LICENSE/github.com/go-sql-driver/mysql/CHANGELOG.md
  third_party/VENDOR-LICENSE/github.com/go-sql-driver/mysql/LICENSE
  third_party/VENDOR-LICENSE/github.com/go-sql-driver/mysql/README.md
  third_party/VENDOR-LICENSE/github.com/go-sql-driver/mysql/auth.go
  third_party/VENDOR-LICENSE/github.com/go-sql-driver/mysql/buffer.go
  third_party/VENDOR-LICENSE/github.com/go-sql-driver/mysql/collations.go
  third_party/VENDOR-LICENSE/github.com/go-sql-driver/mysql/conncheck.go
  third_party/VENDOR-LICENSE/github.com/go-sql-driver/mysql/conncheck_dummy.go
  third_party/VENDOR-LICENSE/github.com/go-sql-driver/mysql/connection.go
  third_party/VENDOR-LICENSE/github.com/go-sql-driver/mysql/connector.go
  third_party/VENDOR-LICENSE/github.com/go-sql-driver/mysql/const.go
  third_party/VENDOR-LICENSE/github.com/go-sql-driver/mysql/driver.go
  third_party/VENDOR-LICENSE/github.com/go-sql-driver/mysql/dsn.go
  third_party/VENDOR-LICENSE/github.com/go-sql-driver/mysql/errors.go
  third_party/VENDOR-LICENSE/github.com/go-sql-driver/mysql/fields.go
  third_party/VENDOR-LICENSE/github.com/go-sql-driver/mysql/go.mod
  third_party/VENDOR-LICENSE/github.com/go-sql-driver/mysql/infile.go
  third_party/VENDOR-LICENSE/github.com/go-sql-driver/mysql/nulltime.go
  third_party/VENDOR-LICENSE/github.com/go-sql-driver/mysql/nulltime_go113.go
  third_party/VENDOR-LICENSE/github.com/go-sql-driver/mysql/nulltime_legacy.go
  third_party/VENDOR-LICENSE/github.com/go-sql-driver/mysql/packets.go
  third_party/VENDOR-LICENSE/github.com/go-sql-driver/mysql/result.go
  third_party/VENDOR-LICENSE/github.com/go-sql-driver/mysql/rows.go
  third_party/VENDOR-LICENSE/github.com/go-sql-driver/mysql/statement.go
  third_party/VENDOR-LICENSE/github.com/go-sql-driver/mysql/transaction.go
  third_party/VENDOR-LICENSE/github.com/go-sql-driver/mysql/utils.go
  third_party/VENDOR-LICENSE/github.com/hashicorp/errwrap/LICENSE
  third_party/VENDOR-LICENSE/github.com/hashicorp/errwrap/README.md
  third_party/VENDOR-LICENSE/github.com/hashicorp/errwrap/errwrap.go
  third_party/VENDOR-LICENSE/github.com/hashicorp/errwrap/go.mod
  third_party/VENDOR-LICENSE/github.com/hashicorp/go-multierror/.travis.yml
  third_party/VENDOR-LICENSE/github.com/hashicorp/go-multierror/LICENSE
  third_party/VENDOR-LICENSE/github.com/hashicorp/go-multierror/Makefile
  third_party/VENDOR-LICENSE/github.com/hashicorp/go-multierror/README.md
  third_party/VENDOR-LICENSE/github.com/hashicorp/go-multierror/append.go
  third_party/VENDOR-LICENSE/github.com/hashicorp/go-multierror/flatten.go
  third_party/VENDOR-LICENSE/github.com/hashicorp/go-multierror/format.go
  third_party/VENDOR-LICENSE/github.com/hashicorp/go-multierror/go.mod
  third_party/VENDOR-LICENSE/github.com/hashicorp/go-multierror/go.sum
  third_party/VENDOR-LICENSE/github.com/hashicorp/go-multierror/multierror.go
  third_party/VENDOR-LICENSE/github.com/hashicorp/go-multierror/prefix.go
  third_party/VENDOR-LICENSE/github.com/hashicorp/go-multierror/sort.go
Labels: approved, cla: yes, lgtm, size/XS
