Repository knative/test-infra, pull requests merged in 2021-07, with the labels that each got.

#2835 Add links to repos
  README.md
Labels: approved, cla: yes, lgtm, size/S

#2836 setup sample-controller for autorelease & nightlies
  config/prod/prow/config_knative.yaml
  config/prod/prow/jobs/config.yaml
  config/prod/prow/testgrid/testgrid.yaml
Labels: approved, cla: yes, lgtm, size/L

#2834 [main] Update actions
  .github/workflows/knative-go-test.yaml
  .github/workflows/knative-stale.yaml
Labels: approved, cla: yes, lgtm, size/S

#2821 Add istio labels per dr. max
  config/label_sync/labels.yaml
Labels: approved, cla: yes, lgtm, size/S

#2839 [main] Update community files
  OWNERS_ALIASES
Labels: approved, cla: yes, lgtm, size/XS

#2838 Add items for s390x to flaky-test-reporter
  tools/flaky-test-reporter/config/config.yaml
Labels: approved, cla: yes, lgtm, ok-to-test, size/M

#2844 Add s390x custom-jobs for release-0.23
  config/prod/prow/config_knative.yaml
  config/prod/prow/jobs/config.yaml
  config/prod/prow/testgrid/testgrid.yaml
Labels: approved, cla: yes, lgtm, ok-to-test, size/XL
