Repository knative/test-infra, pull requests merged in 2021-12, with the labels that each got.

#2951 Drop istio stable from test
  config/prod/prow/config_knative.yaml
  config/prod/prow/jobs/config.yaml
  config/prod/prow/testgrid/testgrid.yaml
  pkg/testgrid/testgrid.go
  tools/flaky-test-reporter/config/config.yaml
Labels: approved, lgtm, size/XL, cla: yes

#2954 [main] Update community files
  OWNERS_ALIASES
Labels: approved, lgtm, size/XS, cla: yes

#2955 [main] Update actions
  .github/workflows/knative-releasability.yaml
Labels: approved, lgtm, size/XS, cla: yes

#2956 [main] Update community files
  OWNERS_ALIASES
Labels: approved, lgtm, size/XS, cla: yes

#2958 [main] Update community files
  OWNERS_ALIASES
Labels: approved, lgtm, size/XS

#2964 [main] Update community files
  OWNERS_ALIASES
Labels: approved, lgtm, size/S

#2966 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/modules.txt
Labels: approved, lgtm, size/XS

#2979 [main] Update actions
  .github/workflows/knative-style.yaml
Labels: approved, lgtm, size/XS
