Repository knative/test-infra, pull requests merged in 2021-02, with the labels that each got.

#2646 Enable reviewer protections for net-contour
  config/branch_protector/rules.yaml
Labels: approved, cla: yes, lgtm, size/S

#2649 Add explicit timeout and move to latest branchprotector
  config/prod/prow/jobs/custom/branchprotector.yaml
Labels: approved, cla: yes, lgtm, size/XS

#2651 Fix branch protector config file
  config/branch_protector/rules.yaml
Labels: approved, cla: yes, lgtm, size/XS

#2658 Switch knative-gcp jobs from master to main
  config/prod/prow/config_knative.yaml
  config/prod/prow/jobs/config.yaml
  config/prod/prow/testgrid/testgrid.yaml
  tools/config-generator/periodic_config.go
Labels: approved, cla: yes, lgtm, size/L

#2659 Delete unused shellcheck filtering
  scripts/library.sh
Labels: approved, cla: yes, lgtm, size/S

#2661 Fix the net-contour config
  config/branch_protector/rules.yaml
  scripts/library.sh
Labels: approved, cla: yes, lgtm, size/S

#2653 run with same flags as in post except confirm stays as false
  config/prod/prow/jobs/custom/peribolos.yaml
Labels: approved, cla: yes, lgtm, size/S

#2654 add dot releases for .19 .20 for rqbbitmq/natss
  config/prod/prow/config_knative.yaml
  config/prod/prow/jobs/config.yaml
  config/prod/prow/testgrid/testgrid.yaml
Labels: approved, cla: yes, lgtm, size/L

#2663 Add daily prow jobs running istio-head
  config/prod/prow/config_knative.yaml
  config/prod/prow/jobs/config.yaml
  config/prod/prow/testgrid/testgrid.yaml
Labels: approved, cla: yes, lgtm, size/L

#2657 Add multi-tenant Kafka Source e2e tests in Prow Jobs
  config/prod/prow/config_knative.yaml
  config/prod/prow/jobs/config.yaml
Labels: approved, cla: yes, lgtm, size/M

#2656 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  scripts/library.sh
  vendor/knative.dev/hack/library.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#2655 [Automated] Update actions
  .github/workflows/knative-style.yaml
Labels: approved, cla: yes, lgtm, size/XS

#2665 [Automated] Update actions
  .github/workflows/knative-releasability.yaml
Labels: approved, cla: yes, lgtm, size/XS

#2666 mt-source test job is optional in eventing-kafka
  config/prod/prow/config_knative.yaml
  config/prod/prow/jobs/config.yaml
Labels: approved, cla: yes, lgtm, size/XS

#2668 [Automated] Update actions
  .github/workflows/knative-releasability.yaml
  .github/workflows/knative-style.yaml
Labels: approved, cla: yes, lgtm, ok-to-test, size/S

#2669 Dismiss stale reviews net-contour
  config/branch_protector/rules.yaml
Labels: approved, cla: yes, lgtm, size/XS

#2672 Send Slack alert to productivity channel if the peribolos jobs fail
  config/prod/prow/check_config.sh
  config/prod/prow/jobs/custom/peribolos.yaml
Labels: approved, cla: yes, lgtm, size/M

#2671 Expand the CODEOWNERS canary to net-*
  config/branch_protector/rules.yaml
Labels: approved, cla: yes, lgtm, size/S

#2673 Switch the sample and productivity repos over to CODEOWNERS
  config/branch_protector/rules.yaml
Labels: approved, cla: yes, lgtm, size/S

#2674 Move the knative-sandbox org to CODEOWNERS
  config/branch_protector/rules.yaml
Labels: approved, cla: yes, lgtm, size/M

#2676 chore: Add kn-plugin-admin releases
  config/prod/prow/config_knative.yaml
  config/prod/prow/jobs/config.yaml
  config/prod/prow/k8s-testgrid/k8s-testgrid.yaml
  config/prod/prow/testgrid/testgrid.yaml
Labels: approved, cla: yes, lgtm, size/L

#2678 Enable HTTP01 tests for Istio no mesh continuous tests
  config/prod/prow/config_knative.yaml
  config/prod/prow/jobs/config.yaml
Labels: approved, cla: yes, lgtm, size/XS

#2679 Enable http01 tests for contour and kourier
  config/prod/prow/config_knative.yaml
  config/prod/prow/jobs/config.yaml
Labels: approved, cla: yes, lgtm, size/XS

#2680 Add a optional presubmit workflow to test http01 challenge
  config/prod/prow/config_knative.yaml
  config/prod/prow/jobs/config.yaml
Labels: approved, cla: yes, lgtm, size/M
