Repository knative/test-infra, pull requests merged in 2021-09, with the labels that each got.

#2865 Generate dot release jobs for net-contour repo correctly
  config/prod/prow/config_knative.yaml
  config/prod/prow/jobs/config.yaml
  config/prod/prow/testgrid/testgrid.yaml
Labels: approved, size/L, lgtm, cla: yes

#2860 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  scripts/release.sh
  vendor/knative.dev/hack/release.sh
  vendor/modules.txt
Labels: approved, lgtm, size/S, cla: yes

#2861 [main] Update community files
  OWNERS_ALIASES
Labels: approved, lgtm, size/S, cla: yes

#2863 [main] Update actions
  .github/workflows/knative-style.yaml
Labels: approved, lgtm, size/XS, cla: yes

#2864 Setting up Prow for eventing-kogito
  config/prod/prow/config_knative.yaml
  config/prod/prow/jobs/config.yaml
  config/prod/prow/k8s-testgrid/k8s-testgrid.yaml
  config/prod/prow/testgrid/testgrid.yaml
Labels: approved, size/L, lgtm, cla: yes

#2867 drop extra stale issue workflow
  .github/workflows/stale.yaml
Labels: approved, size/M, lgtm, cla: yes

#2869 Generate dot release jobs for net-certmanager repo correctly
  config/prod/prow/config_knative.yaml
  config/prod/prow/jobs/config.yaml
  config/prod/prow/testgrid/testgrid.yaml
Labels: approved, size/L, lgtm, cla: yes

#2870 Update kubectl to 1.21.4
  images/prow-tests/Dockerfile
Labels: approved, lgtm, size/XS, cla: yes

#2872 Add CI confing for client-pkg repository
  config/prod/prow/config_knative.yaml
  config/prod/prow/jobs/config.yaml
  config/prod/prow/k8s-testgrid/k8s-testgrid.yaml
  config/prod/prow/testgrid/testgrid.yaml
Labels: approved, size/L, lgtm, cla: yes

#2871 Enable dot releases for some sources repos
  config/prod/prow/config_knative.yaml
  config/prod/prow/jobs/config.yaml
  config/prod/prow/testgrid/testgrid.yaml
Labels: approved, lgtm, size/XXL, cla: yes

#2874 Add kn-plugin-source-kamelet for autorelease
  config/prod/prow/config_knative.yaml
  config/prod/prow/jobs/config.yaml
  config/prod/prow/testgrid/testgrid.yaml
Labels: approved, size/L, lgtm, cla: yes

#2877 Add kn-plugin-service-log release builds
  config/prod/prow/config_knative.yaml
  config/prod/prow/jobs/config.yaml
  config/prod/prow/testgrid/testgrid.yaml
Labels: approved, size/L, lgtm, cla: yes

#2873 [main] Update community files
  OWNERS_ALIASES
Labels: approved, size/M, lgtm, cla: yes

#2875 Update prow members for manual jobs
  guides/manual_release.md
Labels: approved, lgtm, size/XS, cla: yes

#2876 [main] Update actions
  .github/workflows/knative-boilerplate.yaml
  .github/workflows/knative-donotsubmit.yaml
  .github/workflows/knative-go-build.yaml
  .github/workflows/knative-go-test.yaml
  .github/workflows/knative-security.yaml
  .github/workflows/knative-style.yaml
  .github/workflows/knative-verify.yaml
Labels: approved, lgtm, size/S, cla: yes

#2878 Add s390x custom-jobs for release-0.24
  config/prod/prow/config_knative.yaml
  config/prod/prow/jobs/config.yaml
  config/prod/prow/testgrid/testgrid.yaml
Labels: approved, lgtm, size/XL, needs-ok-to-test, cla: yes

#2885 [main] Update community files
  OWNERS_ALIASES
Labels: approved, lgtm, size/XS, cla: yes

#2886 [main] Update actions
  .github/workflows/knative-releasability.yaml
  .github/workflows/knative-style.yaml
Labels: approved, lgtm, size/S, cla: yes

#2887 Add release config for kn-plugin-event
  config/prod/prow/config_knative.yaml
  config/prod/prow/jobs/config.yaml
  config/prod/prow/testgrid/testgrid.yaml
Labels: approved, size/L, lgtm, cla: yes

#2889 Workaround Prow CI failures with iptables change
  images/prow-tests/runner.sh
Labels: approved, lgtm, size/XS, cla: yes

#2879 Add prow config for container-freezer
  config/prod/prow/config_knative.yaml
  config/prod/prow/jobs/config.yaml
  config/prod/prow/k8s-testgrid/k8s-testgrid.yaml
  config/prod/prow/testgrid/testgrid.yaml
Labels: approved, lgtm, size/XL, cla: yes

#2891 Remove Knative Docs integration jobs, since the tests have had low value
  config/prod/prow/config_knative.yaml
  config/prod/prow/jobs/config.yaml
Labels: approved, size/M, lgtm, cla: yes

#2892 [main] Update community files
  CODE-OF-CONDUCT.md
Labels: approved, size/M, lgtm, cla: yes
