Repository knative/test-infra, pull requests merged in 2021-10, with the labels that each got.

#2893 Reverting coc changes
  CODE-OF-CONDUCT.md
Labels: approved, lgtm, size/S, cla: yes

#2894 Fix the Prow config file path for the branchprotector Prow job
  config/prod/prow/jobs/custom/branchprotector.yaml
  config/prod/prow/jobs/custom/test-infra.yaml
Labels: approved, lgtm, size/S, cla: yes

#2896 Fix the Prow config path for testgrid validate jobs
  config/prod/prow/jobs/custom/test-infra.yaml
Labels: approved, lgtm, size/XS, cla: yes

#2895 Rename net-ingressv2 to net-gateway-api
  config/prod/prow/config_knative.yaml
  config/prod/prow/jobs/config.yaml
Labels: approved, size/M, lgtm, cla: yes

#2901 use go1.17.2 by default
  images/prow-tests/runner.sh
Labels: approved, lgtm, size/S, cla: yes

#2909 Remove GKE networking workaround
  images/prow-tests/runner.sh
Labels: approved, lgtm, size/XS, cla: yes

#2915 Remove transfigure jobs
  config/prod/prow/jobs/custom/test-infra.yaml
Labels: approved, size/M, lgtm, cla: yes

#2906 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  scripts/infra-library.sh
  scripts/library.sh
  scripts/presubmit-tests.sh
  vendor/knative.dev/hack/hack.go
  vendor/knative.dev/hack/infra-library.sh
  vendor/knative.dev/hack/library.sh
  vendor/knative.dev/hack/presubmit-tests.sh
  vendor/modules.txt
Labels: approved, size/M, lgtm, cla: yes

#2913 Fix code coverage
  images/prow-tests/runner.sh
Labels: approved, lgtm, size/S, cla: yes

#2917 Fix go coverage tool by using the correct GOPATH
  images/prow-tests/runner.sh
Labels: approved, lgtm, size/XS, cla: yes
