Repository knative/test-infra, pull requests merged in 2022-08, with the labels that each got.

#3462 Fix k8s manifest typos
  prow/cluster/control-plane/gcsweb.yaml
  prow/cluster/trusted/serviceaccounts.yaml
Labels: approved, lgtm, size/XS

#3463 github actions are optional in knative.dev/pkg
  prow/config.yaml
Labels: approved, lgtm, size/XS

#3464 Optional GH actions for knative.dev/reconciler-test
  prow/config.yaml
Labels: approved, lgtm, size/XS

#3465 [main] Update actions
  .github/workflows/knative-releasability.yaml
Labels: approved, size/M, skip-review

#3466 Add new jobs for namespaced broker and adjust existing jobs
  prow/jobs/generated/knative-sandbox/eventing-kafka-broker-main.gen.yaml
  prow/jobs_config/knative-sandbox/eventing-kafka-broker.yaml
Labels: approved, size/L, lgtm

#3467 GH actions optional for knative.dev/eventing
  prow/config.yaml
Labels: approved, lgtm, size/XS

#3470 add secret for perf tests
  prow/cluster/build/600-kubernetes_external_secrets.yaml
  prow/jobs/generated/knative/serving-main.gen.yaml
  prow/jobs_config/.base.yaml
  prow/jobs_config/knative/serving.yaml
Labels: approved, size/L, lgtm

#3469 adding security-guard
  config/prow/k8s-testgrid/k8s-testgrid.yaml
  prow/jobs/generated/knative-sandbox/security-guard-main.gen.yaml
  prow/jobs_config/knative-sandbox/security-guard.yaml
Labels: approved, size/L, lgtm

#3472 update influx secret name in config
  prow/cluster/build/600-kubernetes_external_secrets.yaml
Labels: approved, lgtm, size/S

#3480 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#3478 update influx external secrets
  prow/cluster/build/600-kubernetes_external_secrets.yaml
  prow/jobs/generated/knative/serving-main.gen.yaml
  prow/jobs_config/.base.yaml
Labels: approved, size/M, lgtm

#3482 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#3485 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/modules.txt
Labels: approved, lgtm, size/XS

#3488 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#3496 [s390x] add release 1.7 jobs
  prow/jobs/generated/knative-sandbox/eventing-kafka-broker-release-1.7.gen.yaml
  prow/jobs/generated/knative-sandbox/eventing-kafka-release-1.7.gen.yaml
  prow/jobs/generated/knative/client-release-1.7.gen.yaml
  prow/jobs/generated/knative/eventing-release-1.7.gen.yaml
  prow/jobs/generated/knative/serving-release-1.7.gen.yaml
  prow/jobs_config/knative-sandbox/eventing-kafka-broker-release-1.7.yaml
  prow/jobs_config/knative-sandbox/eventing-kafka-release-1.7.yaml
  prow/jobs_config/knative/client-release-1.7.yaml
  prow/jobs_config/knative/eventing-release-1.7.yaml
  prow/jobs_config/knative/serving-release-1.7.yaml
Labels: approved, size/L, lgtm

#3490 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/release.sh
  vendor/modules.txt
Labels: approved, lgtm, size/S

#3501 [s390x] add operator release 1.7 jobs
  prow/jobs/generated/knative/operator-release-1.7.gen.yaml
  prow/jobs_config/knative/operator-release-1.7.yaml
Labels: approved, lgtm, size/XS

#3500 Deploy Grafana
  infra/gcp/.terraform.lock.hcl
  infra/gcp/boskos/main.tf
  infra/gcp/dns/dns.tf
  infra/gcp/provider.tf
  infra/gcp/tests/addresses.tf
  infra/gcp/tests/buckets.tf
  infra/gcp/tests/iam.tf
  infra/gcp/tests/main.tf
  infra/gcp/tests/prow.tf
  infra/gcp/tests/tls.tf
  prow/cluster/control-plane/gateway.yaml
  prow/cluster/gitops/apps/monitoring.yaml
  prow/cluster/monitoring/chart/Chart.lock
  prow/cluster/monitoring/chart/Chart.yaml
  prow/cluster/monitoring/chart/templates/backend.yaml
  prow/cluster/monitoring/chart/templates/monitoring.yaml
  prow/cluster/monitoring/chart/templates/namespace.yaml
  prow/cluster/monitoring/chart/templates/proxy.yaml
  prow/cluster/monitoring/chart/templates/route.yaml
  prow/cluster/monitoring/chart/templates/secret.yaml
  prow/cluster/monitoring/chart/values.yaml
  prow/cluster/monitoring/mixins/.gitignore
  prow/cluster/monitoring/mixins/Makefile
  prow/cluster/monitoring/mixins/dashboards.yaml
  prow/cluster/monitoring/mixins/grafana_dashboards/boskos.jsonnet
  prow/cluster/monitoring/mixins/lib/config.libsonnet
  prow/cluster/monitoring/prometheus-operator-crds/README.md
  prow/cluster/monitoring/prometheus-operator-crds/monitoring.coreos.com_alertmanagerconfigs.yaml
  prow/cluster/monitoring/prometheus-operator-crds/monitoring.coreos.com_alertmanagers.yaml
  prow/cluster/monitoring/prometheus-operator-crds/monitoring.coreos.com_podmonitors.yaml
  prow/cluster/monitoring/prometheus-operator-crds/monitoring.coreos.com_probes.yaml
  prow/cluster/monitoring/prometheus-operator-crds/monitoring.coreos.com_prometheuses.yaml
  prow/cluster/monitoring/prometheus-operator-crds/monitoring.coreos.com_prometheusrules.yaml
  prow/cluster/monitoring/prometheus-operator-crds/monitoring.coreos.com_servicemonitors.yaml
  prow/cluster/monitoring/prometheus-operator-crds/monitoring.coreos.com_thanosrulers.yaml
  prow/cluster/monitoring/secrets/alertmanager-prow_secret.yaml
  prow/cluster/monitoring/secrets/replace-secrets-from-gcp.sh
Labels: approved, lgtm, size/XXL, area/gcp

#3503 Remove some projects from boskos pool for testing
  prow/cluster/boskos/README.md
  prow/cluster/boskos/boskos_resources.yaml
  prow/cluster/build/boskos-deployment.yaml
Labels: approved, size/L, lgtm
