Repository knative/test-infra, pull requests merged in 2022-02, with the labels that each got.

#3058 [main] Update community files
  OWNERS_ALIASES
Labels: approved, lgtm, size/XS

#3059 [main] Update actions
  .github/workflows/knative-security.yaml
Labels: approved, lgtm, size/XS

#3061 [main] Update actions
  .github/workflows/knative-release-notes.yaml
Labels: approved, size/M, lgtm

#3062 Additional jobs to run KafkaChannel tests with auth cases
  config/prow/config_knative.yaml
  config/prow/jobs/config.yaml
Labels: approved, size/L, lgtm

#3066 Fix KafkaChannel jobs for eventing-kafka-broker
  config/prow/config_knative.yaml
  config/prow/jobs/config.yaml
Labels: approved, size/M, lgtm

#3065 [main] Update community files
  OWNERS_ALIASES
Labels: approved, lgtm, size/XS

#3067 Update s390x custom-jobs to release-1.2
  config/prow/config_knative.yaml
  config/prow/jobs/config.yaml
  config/prow/testgrid/testgrid.yaml
Labels: approved, size/L, lgtm, ok-to-test

#3074 Don't set SOURCE_DATE_EPOCH
  images/prow-tests/runner.sh
Labels: approved, lgtm, size/XS

#3078 Wrap `runner.sh` for k8s groups sync jobs
  config/prow/check_config.sh
  config/prow/jobs/custom/test-infra.yaml
Labels: approved, lgtm, size/S

#3079 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/release.sh
  vendor/modules.txt
Labels: approved, lgtm, size/S

#3082 Some fixes to the Prow config files after the move
  config/prow/testgrid/testgrid.yaml
  prow/README.md
  prow/config.sh
  prow/jobs/custom/autobump-prow.yaml
  prow/jobs/custom/autodeploy-prow.yaml
  prow/jobs/custom/autodeply-prow.yaml
  prow/jobs/custom/branchprotector.yaml
  prow/jobs/custom/prow-autobump.yaml
  prow/jobs/custom/test-infra.yaml
  tools/config-generator/customjobs.go
Labels: approved, size/L, lgtm

#3083 More fixes to the Prow config files
  config/Makefile
  config/prow/testgrid/testgrid.yaml
  prow/Makefile
  prow/jobs/custom/autodeploy-prow.yaml
  prow/jobs/custom/test-infra.yaml
  prow/jobs/run_job.sh
  prow/knative-autobump-config.yaml
  tools/config-generator/customjobs.go
Labels: approved, size/M, lgtm

#3084 Temporarily mark pull-knativeteam-groups-test job as optional
  prow/jobs/custom/test-infra.yaml
Labels: approved, lgtm, size/XS

#3085 Fix the config check Prow job
  prow/jobs/custom/test-infra.yaml
Labels: approved, lgtm, size/XS

#3088 Clean up some Prow jobs for knative-gcp
  config/prow/k8s-testgrid/k8s-testgrid.yaml
  config/prow/testgrid/testgrid.yaml
  prow/config_knative.yaml
  prow/jobs/config.yaml
Labels: approved, lgtm, size/XXL

#3087 Move kntest and rundk to the tools folder
  images/prow-tests/Dockerfile
  prow/config.sh
  prow/jobs/custom/test-infra.yaml
  tools/kntest/README.md
  tools/kntest/cmd/kntest/main.go
  tools/kntest/pkg/cluster/commands.go
  tools/kntest/pkg/cluster/gke/README.md
  tools/kntest/pkg/cluster/gke/commands.go
  tools/kntest/pkg/cluster/gke/options.go
  tools/kntest/pkg/junit/README.md
  tools/kntest/pkg/junit/command.go
  tools/kntest/pkg/kubetest2/commands.go
  tools/kntest/pkg/kubetest2/gke/README.md
  tools/kntest/pkg/kubetest2/gke/commands.go
  tools/kntest/pkg/kubetest2/gke/options.go
  tools/kntest/pkg/kubetest2/options.go
  tools/kntest/pkg/metadata/README.md
  tools/kntest/pkg/metadata/command.go
  tools/rundk/README.md
  tools/rundk/go.mod
  tools/rundk/go.sum
  tools/rundk/interactive/command.go
  tools/rundk/interactive/command_test.go
  tools/rundk/interactive/docker.go
  tools/rundk/interactive/docker_test.go
  tools/rundk/main.go
Labels: approved, lgtm, size/S

#3092 [main] Update community files
  OWNERS_ALIASES
Labels: approved, lgtm, size/XS

#3093 Update knative-autobump-config.yaml to include more paths
  prow/knative-autobump-config.yaml
Labels: approved, lgtm, size/XS

#3097 Add security and cncf-blocked labels
  config/label_sync/labels.yaml
Labels: approved, lgtm, size/S

#3094 [main] Update community files
  OWNERS_ALIASES
Labels: approved, lgtm, size/XS

#3095 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/README.md
  vendor/knative.dev/hack/library.sh
  vendor/modules.txt
Labels: approved, lgtm, size/S

#3099 Simplify PR template
  .github/pull-request-template.md
Labels: approved, lgtm, size/S

#3098 Remove confusing and unused github page
  docs/README.md
  docs/_config.yml
  docs/cors-json-file.json
  docs/index.html
Labels: approved, size/M, lgtm

#3105 Change cncf-blocked to cncf-after
  config/label_sync/labels.yaml
Labels: approved, lgtm, size/XS

#3107 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/presubmit-tests.sh
  vendor/modules.txt
Labels: approved, lgtm, size/S

#3112 Only run auto-bump job once per week
  config/prow/testgrid/testgrid.yaml
  prow/jobs/custom/autobump-prow.yaml
  tools/config-generator/customjobs.go
Labels: approved, size/M, lgtm

#3114 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/presubmit-tests.sh
  vendor/modules.txt
Labels: approved, lgtm, size/S

#3115 Fix the kubetest2 command
  pkg/clustermanager/kubetest2/gke.go
Labels: approved, lgtm, size/XS

#3110 [main] Update actions
  .github/workflows/knative-style.yaml
Labels: approved, lgtm, size/XS

#3116 [main] Update community files
  OWNERS_ALIASES
Labels: approved, lgtm, size/XS

#3118 Run kubetest2 with --down arg
  images/prow-tests/Dockerfile
  pkg/clustermanager/kubetest2/gke.go
  tools/kntest/pkg/cluster/commands.go
Labels: approved, lgtm, size/XS

#3126 Remove --output arg from the validate-own-testgrid job
  prow/jobs/custom/test-infra.yaml
Labels: approved, lgtm, size/XS

#3123 make pull-knative-eventing-reconciler-tests prow job optional
  prow/config_knative.yaml
  prow/jobs/config.yaml
Labels: approved, lgtm, size/XS

#3125 Fix typo and revert #3084
  prow/jobs/custom/test-infra.yaml
Labels: approved, lgtm, size/XS

#3129 Change max_pod_age to 30m and max_prowjob_age to 24h for Prow
  prow/config.yaml
Labels: approved, lgtm, size/XS
