Repository knative/test-infra, pull requests merged in 2022-01, with the labels that each got.

#2989 Add reconciler-tests job for eventing-kafka-broker
  config/prod/prow/config_knative.yaml
  config/prod/prow/jobs/config.yaml
Labels: approved, size/M, lgtm

#2988 Update s390x custom-jobs to release-1.0 and 1.1
  config/prod/prow/config_knative.yaml
  config/prod/prow/jobs/config.yaml
  config/prod/prow/k8s-testgrid/k8s-testgrid.yaml
  config/prod/prow/testgrid/testgrid.yaml
Labels: approved, size/L, lgtm, ok-to-test

#2993 :gift: Adding Prow CI for knative-sandbox/reconciler-test project
  config/prod/prow/config_knative.yaml
  config/prod/prow/jobs/config.yaml
Labels: approved, size/L, lgtm

#3000 Add periodic jobs for knative-sandbox/kn-plugin-func
  config/prod/prow/config_knative.yaml
  config/prod/prow/jobs/config.yaml
  config/prod/prow/k8s-testgrid/k8s-testgrid.yaml
  config/prod/prow/testgrid/testgrid.yaml
Labels: approved, size/L, lgtm

#2998 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  scripts/e2e-tests.sh
  scripts/presubmit-tests.sh
  vendor/knative.dev/hack/e2e-tests.sh
  vendor/knative.dev/hack/presubmit-tests.sh
  vendor/modules.txt
Labels: approved, size/L, lgtm

#3001 [main] Update actions
  .github/workflows/knative-releasability.yaml
Labels: approved, lgtm, size/XS

#3002 chore: add docker to func integration tests
  config/prod/prow/config_knative.yaml
  config/prod/prow/jobs/config.yaml
Labels: approved, size/M, lgtm

#3004 Upgrade gcloud SDK
  images/prow-tests/Dockerfile
Labels: approved, lgtm, size/XS

#3007 Install the cred helper properly
  images/prow-tests/Dockerfile
Labels: approved, lgtm, size/XS

#3009 Install the cred helper properly again
  images/prow-tests/Dockerfile
Labels: approved, lgtm, size/XS

#3010 Bump and download Maven properly
  images/prow-tests/Dockerfile
Labels: approved, lgtm, size/S

#3008 Add presubmit job to build Image
  config/prod/prow/jobs/custom/test-infra.yaml
Labels: approved, size/M, lgtm

#3013 bump go version to the latest patches
  images/prow-tests/Dockerfile
Labels: approved, lgtm, size/XS

#3016 Copy docker config properly
  images/prow-tests/Dockerfile
Labels: approved, lgtm, size/XS

#3020 [main] Update community files
  OWNERS_ALIASES
Labels: approved, lgtm, size/XS

#3022 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/modules.txt
Labels: approved, lgtm, size/XS

#3024 drop scripts as they have been moved to knative.dev/hack
  config/prod/prow/check_config.sh
  config/prod/prow/run_job.sh
  config/prod/prow/update_config.sh
  docs/README.md
  guides/README.md
  guides/release_setup.md
  hack/update-codegen.sh
  hack/update-deps.sh
  hack/update-k8s-deps.sh
  hack/verify-codegen.sh
  kntest/README.md
  scripts/README.md
  scripts/codegen-library.sh
  scripts/e2e-tests.sh
  scripts/infra-library.sh
  scripts/library.sh
  scripts/microbenchmarks.sh
  scripts/performance-tests.sh
  scripts/placeholder.go
  scripts/presubmit-tests.sh
  scripts/release.sh
  scripts/shellcheck-presubmit.sh
  scripts/update-test-infra.sh
  test/presubmit-tests.sh
Labels: approved, lgtm, size/XXL

#3014 Build Prow Image from Scratch
  images/prow-tests/Dockerfile
  images/prow-tests/runner.sh
Labels: approved, size/L, lgtm

#3025 Add Commit Hash to prow-tests images
  common.mk
  images/prow-tests/Dockerfile
  images/prow-tests/Makefile
  images/prow-tests/cloudbuild-test.yaml
  images/prow-tests/cloudbuild.yaml
  images/simple-image.mk
Labels: kind/enhancement, approved, lgtm, size/S

#3028 Install jq in the prow-tests image
  images/prow-tests/Dockerfile
Labels: approved, lgtm, size/XS

#3026 Add the label for cncf-infra migration, so we can use it across all Knative repos
  config/label_sync/labels.yaml
Labels: approved, lgtm, size/XS

#3030 Fix a small typo for the make push command for prow-tests image
  images/prow-tests/Makefile
Labels: approved, lgtm, size/XS

#3032 Run kubetest2 --down directly to save some costs
  images/prow-tests/Dockerfile
  kntest/pkg/cluster/commands.go
  pkg/clustermanager/kubetest2/gke.go
Labels: approved, lgtm, size/XS

#3043 Add image-type flag to kubetest2
  kntest/pkg/kubetest2/gke/options.go
  pkg/clustermanager/kubetest2/gke.go
Labels: approved, lgtm, size/XS

#3044 Remove the legacy 'prod' subfolder from the Prow config path
  DEVELOPMENT.md
  config/Makefile
  config/gubernator/Makefile
  config/gubernator/README.md
  config/gubernator/config.yaml
  config/gubernator/redir_github.py
  config/prod/Makefile
  config/prow/README.md
  config/prow/build-cluster/README.md
  config/prow/build-cluster/add-secrets.sh
  config/prow/build-cluster/boskos/README.md
  config/prow/build-cluster/boskos/boskos_resources.yaml
  config/prow/build-cluster/boskos/create_boskos_projects.sh
  config/prow/build-cluster/boskos/set_up_boskos_project.sh
  config/prow/build-cluster/boskos/update_all_boskos_projects.sh
  config/prow/build-cluster/create-build-cluster.sh
  config/prow/build-cluster/rbe.sh
  config/prow/check_config.sh
  config/prow/config_knative.yaml
  config/prow/jobs/config.yaml
  config/prow/jobs/custom/branchprotector.yaml
  config/prow/jobs/custom/label-sync.yaml
  config/prow/jobs/custom/peribolos.yaml
  config/prow/jobs/custom/test-infra.yaml
  config/prow/k8s-testgrid/k8s-testgrid.yaml
  config/prow/k8s-testgrid/testgrid-common-settings.yaml
  config/prow/knative-autobump-config.yaml
  config/prow/pj-on-kind.sh
  config/prow/run_job.sh
  config/prow/testgrid/testgrid.yaml
  config/prow/update_config.sh
  guides/manual_release.md
  guides/prow_knative_setup.md
  guides/prow_setup.md
  guides/release_setup.md
  hack/generate-configs.sh
  pkg/testgrid/yaml.go
  tools/cleanup/README.md
  tools/config-generator/README.md
  tools/config-generator/customjobs_test.go
  tools/prow-jobs-syncer/config.go
Labels: approved, size/L, lgtm, kind/cleanup

#3045 Add `procps` package
  images/prow-tests/Dockerfile
Labels: approved, lgtm, size/XS

#3047 [main] Update community files
  OWNERS_ALIASES
Labels: approved, lgtm, size/XS

#3049 [main] Update community files
  OWNERS_ALIASES
Labels: approved, lgtm, size/XS

#3051 Revert "Run kubetest2 --down directly to save some costs"
  images/prow-tests/Dockerfile
  kntest/pkg/cluster/commands.go
  pkg/clustermanager/kubetest2/gke.go
Labels: approved, lgtm, size/XS

#3053 Add common label for "Epic"
  config/label_sync/labels.yaml
Labels: approved, lgtm, size/XS

#3055 Update kubetest2 to the latest commit
  images/prow-tests/Dockerfile
Labels: approved, lgtm, size/XS

#3056 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/README.md
  vendor/knative.dev/hack/e2e-tests.sh
  vendor/knative.dev/hack/infra-library.sh
  vendor/knative.dev/hack/presubmit-tests.sh
  vendor/modules.txt
Labels: approved, size/M, lgtm
