Repository knative/test-infra, pull requests merged in 2022-04, with the labels that each got.

#3223 [main] Update community files
  OWNERS_ALIASES
Labels: approved, lgtm, size/S

#3167 Add Terraform Infra for `knative-dns` and `knative-gsuite` projects
  .gitignore
  infra/gcp/.terraform.lock.hcl
  infra/gcp/README.md
  infra/gcp/boskos/README.md
  infra/gcp/boskos/boskos_resources.yaml
  infra/gcp/boskos/create_boskos_projects.sh
  infra/gcp/boskos/main.tf
  infra/gcp/boskos/set_up_boskos_project.sh
  infra/gcp/boskos/update_all_boskos_projects.sh
  infra/gcp/boskos/variables.tf
  infra/gcp/dns/README.md
  infra/gcp/dns/dns.tf
  infra/gcp/dns/main.tf
  infra/gcp/gsuite/README.md
  infra/gcp/gsuite/gsuite.tf
  infra/gcp/gsuite/main.tf
  infra/gcp/iam.tf
  infra/gcp/main.tf
  infra/gcp/provider.tf
  infra/gcp/terraform.tfvars
  infra/gcp/variables.tf
  prow/cluster/boskos/README.md
Labels: approved, size/L, lgtm

#3227 boskos_resources.yaml config file is part of Boskos deployment so moving it back
  prow/cluster/boskos/README.md
  prow/cluster/boskos/boskos_resources.yaml
Labels: approved, lgtm, size/XS

#3228 Remove the failing Prow job that builds flaky-test-reporter
  prow/jobs/custom/test-infra.yaml
Labels: approved, size/M, lgtm

#3219 Delete config.sh and replace with actual Prow jobs
  prow/config.sh
  prow/jobs/custom/test-infra.yaml
Labels: approved, size/L, lgtm

#3224 Add external secret for ppc64le cluster
  prow/cluster/build/600-kubernetes_external_secrets.yaml
Labels: approved, lgtm, size/S, ok-to-test

#3232 Add eventing/reconciler prow jobs for s390x
  prow/jobs/generated/knative/eventing-main.gen.yaml
  prow/jobs/generated/knative/eventing-release-1.0.gen.yaml
  prow/jobs/generated/knative/eventing-release-1.1.gen.yaml
  prow/jobs/generated/knative/eventing-release-1.2.gen.yaml
  prow/jobs/generated/knative/eventing-release-1.3.gen.yaml
  prow/jobs_config/knative/eventing-release-1.0.yaml
  prow/jobs_config/knative/eventing-release-1.1.yaml
  prow/jobs_config/knative/eventing-release-1.2.yaml
  prow/jobs_config/knative/eventing-release-1.3.yaml
  prow/jobs_config/knative/eventing.yaml
  tools/release-jobs-syncer/pkg/jobs_sync.go
Labels: approved, lgtm, size/XL, ok-to-test

#3238 [main] Update actions
  .github/workflows/knative-go-build.yaml
  .github/workflows/knative-go-test.yaml
  .github/workflows/knative-releasability.yaml
  .github/workflows/knative-release-notes.yaml
  .github/workflows/knative-security.yaml
  .github/workflows/knative-stale.yaml
  .github/workflows/knative-style.yaml
  .github/workflows/knative-verify.yaml
Labels: approved, size/L, lgtm

#3237 Add the Prow job to run config-bootstrapper periodically
  prow/jobs/custom/autodeploy-prow.yaml
Labels: approved, size/M, lgtm

#3242 Remove the google group from the owner of the Boskos projects
  infra/gcp/boskos/set_up_boskos_project.sh
Labels: approved, lgtm, size/XS

#3241 Use Slack instead of email to alert on Prow job failures
  prow/jobs/custom/autobump-flaky-test-reporter.yaml
  prow/jobs/custom/autobump-prow-tests.yaml
  prow/jobs/custom/autobump-prow.yaml
  prow/jobs/custom/autodeploy-prow.yaml
  prow/jobs/custom/branchprotector.yaml
  prow/jobs/custom/knativeteam-groups.yaml
  prow/jobs/custom/label-sync.yaml
  prow/jobs/custom/peribolos.yaml
  prow/jobs/custom/test-infra.yaml
Labels: approved, size/M, lgtm

#3243 [main] Update actions
  .github/workflows/knative-releasability.yaml
Labels: approved, lgtm, size/XS

#3246 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#3249 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#3251 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#3252 [main] Update actions
  .github/workflows/knative-releasability.yaml
Labels: approved, lgtm, size/XS

#3254 Update Prow alerts recipient to kn-infra-gcp-org-admins@knative.team
  prow/cluster/monitoring/secrets/alertmanager-prow_secret.yaml
Labels: approved, lgtm, size/XS

#3256 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/modules.txt
Labels: approved, lgtm, size/XS

#3257 Remove defunct gubernator, githubhelper tool, and pj-on-kind.sh
  README.md
  config/gubernator/Makefile
  config/gubernator/README.md
  config/gubernator/config.yaml
  config/gubernator/redir_github.py
  infra/gcp/dns/dns.tf
  prow/cluster/prowjob-crd/prowjob_customresourcedefinition.yaml
  prow/config.yaml
  prow/jobs/pj-on-kind.sh
  tools/githubhelper/README.md
  tools/githubhelper/githubhelper.go
Labels: approved, size/L, lgtm

#3255 Add prow job for e2e eventing-main test on ppc64le
  prow/jobs/generated/knative/eventing-main.gen.yaml
  prow/jobs_config/.base.yaml
  prow/jobs_config/knative/eventing.yaml
  tools/release-jobs-syncer/pkg/jobs_sync.go
Labels: approved, size/L, lgtm, ok-to-test

#3258 Fix the kind-tests job for the hack repo
  prow/jobs/generated/knative/hack-main.gen.yaml
  prow/jobs_config/knative/hack.yaml
Labels: approved, size/M, lgtm

#3259 [main] Update actions
  .github/workflows/knative-go-test.yaml
Labels: approved, lgtm, size/XS

#3260 update prow tests image golang to 1.17.9
  images/prow-tests/Dockerfile
Labels: approved, lgtm, size/XS

#3263 migrate label_sync config to community repo
  config/label_sync/README.md
  config/label_sync/labels.yaml
  prow/jobs/custom/label-sync.yaml
Labels: approved, size/L, lgtm

#3264 Fix autobump-prow job and configure Slack alerts
  prow/autobump-config/knative.yaml
  prow/jobs/custom/autobump-flaky-test-reporter.yaml
  prow/jobs/custom/autobump-prow-tests.yaml
  prow/jobs/custom/autobump-prow.yaml
Labels: approved, lgtm, size/S

#3266 Manage Prow Trusted Cluster in Terraform
  infra/gcp/.terraform.lock.hcl
  infra/gcp/README.md
  infra/gcp/main.tf
  infra/gcp/tests/README.md
  infra/gcp/tests/gke.tf
  infra/gcp/tests/iam.tf
  infra/gcp/tests/main.tf
  infra/gcp/tests/prow-flaky-reporter.tf
Labels: approved, size/L, lgtm

#3267 Fix label-sync presumbit Prow job, when config on community repo
  prow/jobs/custom/label-sync.yaml
Labels: approved, lgtm, size/S

#3274 Fix the rm command in hack/generate-configs.sh
  hack/generate-configs.sh
  prow/jobs/generated/knative-sandbox/eventing-autoscaler-keda-release-1.0.gen.yaml
  prow/jobs/generated/knative-sandbox/eventing-ceph-release-1.0.gen.yaml
  prow/jobs/generated/knative-sandbox/eventing-github-release-1.0.gen.yaml
  prow/jobs/generated/knative-sandbox/eventing-gitlab-release-1.0.gen.yaml
  prow/jobs/generated/knative-sandbox/eventing-kafka-release-1.0.gen.yaml
  prow/jobs/generated/knative-sandbox/eventing-kogito-release-1.0.gen.yaml
  prow/jobs/generated/knative-sandbox/eventing-natss-release-1.0.gen.yaml
  prow/jobs/generated/knative-sandbox/eventing-rabbitmq-release-1.0.gen.yaml
  prow/jobs/generated/knative-sandbox/eventing-redis-release-1.0.gen.yaml
  prow/jobs/generated/knative-sandbox/kn-plugin-admin-release-1.0.gen.yaml
  prow/jobs/generated/knative-sandbox/kn-plugin-event-release-1.0.gen.yaml
  prow/jobs/generated/knative-sandbox/kn-plugin-quickstart-release-1.0.gen.yaml
  prow/jobs/generated/knative-sandbox/kn-plugin-source-kafka-release-1.0.gen.yaml
  prow/jobs/generated/knative-sandbox/kn-plugin-source-kamelet-release-1.0.gen.yaml
  prow/jobs/generated/knative-sandbox/net-certmanager-release-1.0.gen.yaml
  prow/jobs/generated/knative-sandbox/net-contour-release-1.0.gen.yaml
  prow/jobs/generated/knative-sandbox/net-http01-release-1.0.gen.yaml
  prow/jobs/generated/knative-sandbox/net-istio-release-1.0.gen.yaml
  prow/jobs/generated/knative-sandbox/net-kourier-release-1.0.gen.yaml
  prow/jobs/generated/knative-sandbox/sample-controller-release-1.0.gen.yaml
  prow/jobs/generated/knative-sandbox/sample-source-release-1.0.gen.yaml
  prow/jobs/generated/knative/client-release-1.0.gen.yaml
  prow/jobs/generated/knative/eventing-release-1.0.gen.yaml
  prow/jobs/generated/knative/serving-release-1.0.gen.yaml
Labels: approved, lgtm, size/XXL

#3279 Remove WORKSPACE file since bazel is not used for test-infra anymore
  WORKSPACE
Labels: approved, size/M, lgtm

#3280 Remove backups tool since it's not used anymore
  images/backups/Dockerfile
  images/backups/Makefile
  images/backups/README.md
  images/backups/backup.sh
Labels: approved, size/M, lgtm

#3282 Fix prow-jobs-syncer-job by changing ssh key default mode to 0700
  prow/jobs/custom/test-infra.yaml
Labels: approved, lgtm, size/XS

#3283 Bump kind version
  images/prow-tests/Dockerfile
Labels: approved, lgtm, size/XS

#3277 Update s390x custom-jobs to release-1.4
  prow/jobs/generated/knative/client-release-1.4.gen.yaml
  prow/jobs/generated/knative/eventing-release-1.4.gen.yaml
  prow/jobs/generated/knative/operator-release-1.4.gen.yaml
  prow/jobs/generated/knative/serving-release-1.4.gen.yaml
  prow/jobs_config/knative/client-release-1.4.yaml
  prow/jobs_config/knative/eventing-release-1.4.yaml
  prow/jobs_config/knative/operator-release-1.4.yaml
  prow/jobs_config/knative/serving-release-1.4.yaml
Labels: approved, size/M, lgtm, ok-to-test

#3285 Move some Prow Jobs over
  prow/cluster/build/301-rbac.yaml
  prow/cluster/build/600-kubernetes_external_secrets.yaml
  prow/jobs/custom/autobump-flaky-test-reporter.yaml
  prow/jobs/custom/autobump-prow-tests.yaml
  prow/jobs/custom/autobump-prow.yaml
  prow/jobs/custom/test-infra.yaml
Labels: approved, size/L, lgtm

#3286 Bump gcloud SDK
  images/prow-tests/Dockerfile
  prow/cluster/build/200-limitrange.yaml
  prow/cluster/build/200-memory-limitrange.yaml
  prow/cluster/build/400-boskos-deployment.yaml
  prow/cluster/build/400-boskos-janitor.yaml
  prow/cluster/build/400-boskos-reaper.yaml
Labels: approved, size/L, lgtm

#3288 Fix autobump token path
  prow/jobs/custom/autobump-flaky-test-reporter.yaml
  prow/jobs/custom/autobump-prow-tests.yaml
  prow/jobs/custom/autobump-prow.yaml
Labels: approved, lgtm, size/XS

#3287 Move generated Prow Jobs over to new `prow-build` cluster
  prow/config.yaml
  prow/jobs/generated/knative/caching-main.gen.yaml
  prow/jobs/generated/knative/client-main.gen.yaml
  prow/jobs/generated/knative/client-pkg-main.gen.yaml
  prow/jobs/generated/knative/client-release-1.1.gen.yaml
  prow/jobs/generated/knative/client-release-1.2.gen.yaml
  prow/jobs_config/knative/caching.yaml
  prow/jobs_config/knative/client-pkg.yaml
  prow/jobs_config/knative/client-release-1.1.yaml
  prow/jobs_config/knative/client-release-1.2.yaml
  prow/jobs_config/knative/client.yaml
Labels: approved, lgtm, size/XL

#3290 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#3294 Fix autobump jobs
  infra/gcp/tests/iam.tf
  prow/cluster/boskos/README.md
  prow/cluster/boskos/boskos_resources.yaml
  prow/cluster/build/400-boskos-deployment.yaml
  prow/cluster/build/600-kubernetes_external_secrets.yaml
  prow/jobs/custom/autobump-flaky-test-reporter.yaml
  prow/jobs/custom/autobump-prow-tests.yaml
  prow/jobs/custom/autobump-prow.yaml
Labels: approved, size/L, lgtm

#3297 Give Boskos More Resources
  prow/cluster/build/400-boskos-janitor.yaml
Labels: approved, lgtm, size/S

#3298 Updates flag when creating new cluster
  pkg/clustermanager/kubetest2/gke.go
Labels: approved, lgtm, size/XS

#3301 flaky-test-reporter skips creating GitHub issues if flakiness rate is high
  tools/flaky-test-reporter/github_issue.go
  tools/flaky-test-reporter/github_issue_test.go
Labels: approved, size/M, lgtm
