Repository knative/test-infra, pull requests merged in 2022-06, with the labels that each got.

#3355 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#3358 Fix path for kperf performance continuous tests
  prow/jobs/generated/knative/serving-main.gen.yaml
  prow/jobs_config/knative/serving.yaml
Labels: approved, lgtm, size/XS

#3361 [main] Update community files
  OWNERS_ALIASES
Labels: skip-review

#3360 Deploy new monitoring stack
  infra/gcp/tests/main.tf
  infra/gcp/tests/monitoring/boskos.tf
  infra/gcp/tests/monitoring/variables.tf
  prow/Makefile
  prow/Makefile.gcloud.mk
  prow/cluster/200-monitoring.yaml
  prow/cluster/build/200-monitoring.yaml
  prow/cluster/build/400-boskos-deployment.yaml
  prow/cluster/build/400-boskos.yaml
Labels: approved, size/L, lgtm

#3357 Added prow job schedule for release-1.5 for s390x platform
  prow/jobs/generated/knative/client-release-1.5.gen.yaml
  prow/jobs/generated/knative/eventing-release-1.5.gen.yaml
  prow/jobs/generated/knative/operator-release-1.5.gen.yaml
  prow/jobs/generated/knative/serving-release-1.5.gen.yaml
  prow/jobs_config/knative/client-release-1.5.yaml
  prow/jobs_config/knative/eventing-release-1.5.yaml
  prow/jobs_config/knative/operator-release-1.5.yaml
  prow/jobs_config/knative/serving-release-1.5.yaml
Labels: approved, size/M, lgtm, ok-to-test

#3339 Add analytics infrastructure
  experiment/gcs-analytics/benthos.yaml
  infra/gcp/analytics/main.tf
  infra/gcp/main.tf
Labels: approved, size/M, lgtm

#3368 bump tooling versions and include gnuplot
  images/prow-tests/Dockerfile
Labels: approved, lgtm, size/S

#3367 bump go version to 1.18
  images/prow-tests/Dockerfile
Labels: approved, lgtm, size/XS

#3373 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#3369 Clean up Knative.Team mail sending DNS records
  infra/gcp/dns/dns.tf
Labels: approved, lgtm, size/S

#3377 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#3381 Disable Workload Identity for `test-pods/default` service account and update deck notice.
  prow/cluster/build/200-serviceaccounts.yaml
  prow/config.yaml
Labels: approved, lgtm, size/XS

#3387 Add DNS Record to Verify GitHub Organization
  infra/gcp/dns/dns.tf
Labels: approved, lgtm, size/S, area/gcp

#3390 enable-dind for serving prow jobs
  prow/jobs/generated/knative/serving-main.gen.yaml
  prow/jobs_config/knative/serving.yaml
Labels: approved, lgtm, size/XL

#3391 Fix the path for the boskos_resources.yaml file used by the scripts
  infra/gcp/boskos/create_boskos_projects.sh
  infra/gcp/boskos/update_all_boskos_projects.sh
Labels: approved, lgtm, size/XS, area/gcp

#3393 Set presubmit peribolos jobs to optional
  prow/jobs/custom/peribolos.yaml
Labels: approved, lgtm, size/XS

#3394 Move to EasyCLA instead of Google CLA.
  prow/config.yaml
Labels: approved, lgtm, size/XS

#3397 [main] Update actions
  .github/workflows/knative-releasability.yaml
Labels: size/XS, skip-review

#3400 Remove ESO yaml files and autodeploy job
  prow/cluster/build/500-external-secrets_crd.yaml
  prow/cluster/build/500-external-secrets_deployment.yaml
  prow/cluster/control-plane/500-external-secrets_crd.yaml
  prow/cluster/control-plane/500-external-secrets_deployment.yaml
  prow/jobs/custom/autodeploy-prow.yaml
Labels: approved, lgtm, size/XXL

#3401 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#3399 Enable ArgoCD for managing cluster state
  infra/gcp/dns/dns.tf
  infra/gcp/tests/iam.tf
  prow/cluster/gitops/README.md
  prow/cluster/gitops/apps/eso-prow-build.yaml
  prow/cluster/gitops/apps/eso-prow.yaml
  prow/cluster/gitops/apps/eso-trusted.yaml
  prow/cluster/gitops/apps/prow-build.yaml
  prow/cluster/gitops/apps/prow.yaml
  prow/cluster/gitops/bootstrap/apps.yaml
  prow/cluster/gitops/bootstrap/argocd-cm-rbac.yaml
  prow/cluster/gitops/bootstrap/argocd-cm.yaml
  prow/cluster/gitops/bootstrap/argocd-server-service.yaml
  prow/cluster/gitops/bootstrap/extras.yaml
  prow/cluster/gitops/bootstrap/kustomization.yaml
Labels: approved, size/L, lgtm, area/gcp

#3402 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/release.sh
  vendor/modules.txt
Labels: lgtm, size/S, skip-review

#3404 fix dot release notes
  guides/manual_release.md
Labels: approved, lgtm, size/XS
