Repository knative/test-infra, pull requests merged in 2022-09, with the labels that each got.

#3508 Expand boskos pool and enable more logging
  infra/gcp/boskos/.terraform.lock.hcl
  infra/gcp/boskos/create_boskos_projects.sh
  infra/gcp/boskos/iam.tf
  infra/gcp/boskos/main.tf
  infra/gcp/boskos/provider.tf
  infra/gcp/boskos/set_up_boskos_project.sh
  infra/gcp/boskos/update_all_boskos_projects.sh
  infra/gcp/main.tf
  prow/cluster/build/boskos-deployment.yaml
  prow/cluster/build/boskos-janitor.yaml
Labels: approved, size/L, lgtm, area/gcp

#3506 Workload Identity Enablement - Part Four
  infra/gcp/tests/buckets.tf
  infra/gcp/tests/prow.tf
  prow/cluster/build/serviceaccounts.yaml
  prow/jobs/custom/test-infra.yaml
Labels: approved, size/L, lgtm, area/tools, area/gcp

#3514 Fix Prow jobs for knative-sandbox/eventing-kafka-broker
  prow/jobs/generated/knative-sandbox/eventing-kafka-broker-main.gen.yaml
  prow/jobs_config/knative-sandbox/eventing-kafka-broker.yaml
Labels: approved, size/L, lgtm

#3515 Temporarily change out new boskos pool
  prow/cluster/build/boskos-deployment.yaml
Labels: approved, lgtm, size/S

#3517 Stop running docs presubmit tests
  config/prow/k8s-testgrid/k8s-testgrid.yaml
  prow/jobs/generated/knative/docs-main.gen.yaml
  prow/jobs_config/knative/docs.yaml
Labels: approved, size/L, lgtm

#3519 Sign Images and Binaries for net-certmanager and client nightlies
  prow/jobs/generated/knative-sandbox/net-certmanager-main.gen.yaml
  prow/jobs/generated/knative/client-main.gen.yaml
  prow/jobs_config/knative-sandbox/net-certmanager.yaml
  prow/jobs_config/knative/client.yaml
  tools/modscope/README.md
Labels: approved, lgtm, size/S, area/tools

#3524 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/e2e-tests.sh
  vendor/knative.dev/hack/go.work
  vendor/knative.dev/hack/go.work.sum
  vendor/knative.dev/hack/infra-library.sh
  vendor/knative.dev/hack/library.sh
  vendor/knative.dev/hack/presubmit-tests.sh
  vendor/knative.dev/hack/release.sh
  vendor/modules.txt
Labels: approved, size/L, lgtm

#3525 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/e2e-tests.sh
  vendor/modules.txt
Labels: approved, lgtm, size/S

#3527 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/e2e-tests.sh
  vendor/modules.txt
Labels: approved, lgtm, size/S

#3537 Add `rcodesign`, drop `liche`, `gojsontoyaml` and bump some deps
  images/prow-tests/Dockerfile
Labels: kind/enhancement, approved, size/M, lgtm, kind/cleanup, area/tools

#3538 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/release.sh
  vendor/modules.txt
Labels: approved, lgtm, size/S

#3542 Add Apple Notary Secrets to Prow
  images/prow-tests/Dockerfile
  prow/cluster/build/rbac.yaml
  prow/cluster/build/secrets.yaml
Labels: approved, size/M, lgtm, kind/security, area/tools

#3545 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#3546 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review
