Repository knative/test-infra, pull requests merged in 2022-03, with the labels that each got.

#3131 [main] Update actions
  .github/workflows/knative-releasability.yaml
Labels: approved, lgtm, size/XS

#3132 [main] Update community files
  OWNERS_ALIASES
Labels: approved, lgtm, size/XS

#3133 Bump `ko` version
  images/prow-tests/Dockerfile
Labels: approved, lgtm, size/XS

#3137 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/modules.txt
Labels: approved, lgtm, size/XS

#3138 Eventing Kafka and RabbitMQ slack reporter for nightlies
  prow/config_knative.yaml
  prow/jobs/config.yaml
Labels: approved, lgtm, size/S

#3140 Updates rerun auth to use slugs instead of ids
  prow/config.yaml
Labels: approved, lgtm, size/S

#3142 Separate prow rerun teams by org
  prow/config.yaml
Labels: approved, lgtm, size/XS

#3148 Remove beta-prow-tests flows to cut some infra cost
  config/prow/k8s-testgrid/k8s-testgrid.yaml
  config/prow/testgrid/testgrid.yaml
  images/prow-tests/README.md
  prow/jobs/config.yaml
  tools/config-generator/k8s_testgrid_config.go
  tools/config-generator/periodic_config.go
  tools/coverage/README.md
Labels: approved, lgtm, size/XXL

#3149 [main] Update community files
  OWNERS_ALIASES
Labels: approved, lgtm, size/XS

#3150 Increase resources for eventing-kafka auto-release
  prow/config_knative.yaml
  prow/jobs/config.yaml
Labels: approved, lgtm, size/S

#3151 document new actions repo
  README.md
Labels: approved, lgtm, size/XS

#3153 Increase resources for eventing-ceph 1.3 dot release
  prow/config_knative.yaml
  prow/jobs/config.yaml
Labels: approved, size/M, lgtm

#3154 downgrade ko to v0.9.3
  images/prow-tests/Dockerfile
Labels: approved, lgtm, size/XS

#3158 [main] Update community files
  OWNERS_ALIASES
Labels: approved, lgtm, size/XS

#3157 Reduce the frequency for running the continuous Prow jobs
  prow/jobs/config.yaml
  prow/jobs/custom/test-infra.yaml
  tools/config-generator/periodic_config.go
  tools/config-generator/periodic_config_test.go
  tools/flaky-test-reporter/main.go
Labels: approved, size/L, lgtm

#3162 Apply ci-script before e2e-tests for s390x
  prow/config_knative.yaml
  prow/jobs/config.yaml
Labels: approved, size/L, lgtm, ok-to-test

#3164 Update s390x custom-jobs to release-1.3
  config/prow/testgrid/testgrid.yaml
  prow/config_knative.yaml
  prow/jobs/config.yaml
Labels: approved, size/L, lgtm, ok-to-test

#3165 Add 1.2 dot release job for knaitve/eventing
  config/prow/testgrid/testgrid.yaml
  prow/config_knative.yaml
  prow/jobs/config.yaml
Labels: approved, size/L, lgtm

#3168 Fix a bug on missing ingressendpoint for s390x custom job
  prow/config_knative.yaml
  prow/jobs/config.yaml
Labels: approved, size/M, lgtm, needs-ok-to-test

#3169 Add terraform to our prow-tests image
  images/prow-tests/Dockerfile
  images/prow-tests/Makefile
Labels: approved, lgtm, size/S

#3170 [main] Update community files
  OWNERS_ALIASES
Labels: approved, lgtm, size/XS

#3172 Adding code of conduct to reference knative/community's CoC
  CODE-OF-CONDUCT.md
Labels: approved, size/M, lgtm

#3174 Move knativeteam-groups Prow jobs to a separate file and delete unused backup Prow job
  config/prow/testgrid/testgrid.yaml
  prow/jobs/custom/knativeteam-groups.yaml
  prow/jobs/custom/test-infra.yaml
  tools/config-generator/customjobs.go
Labels: approved, size/L, lgtm

#3185 Make secret config for s390x coherent to OSS
  prow/cluster/build/600-kubernetes_external_secrets.yaml
Labels: approved, lgtm, size/XS, ok-to-test

#3188 Update timeout for branchprotector to 5h
  prow/jobs/custom/branchprotector.yaml
Labels: approved, lgtm, size/XS

#3190 Fix some misconfigured knative/serving Prow jobs
  prow/jobs/generated/knative/serving-main.gen.yaml
  prow/jobs_config/knative/serving.yaml
Labels: approved, lgtm, size/XS

#3191 Add back the release-job-syncer tool to sync Prow jobs when there is new release
  pkg/ghutil/repo.go
  prow/jobs/custom/test-infra.yaml
  tools/release-jobs-syncer/README.md
  tools/release-jobs-syncer/go.mod
  tools/release-jobs-syncer/go.sum
  tools/release-jobs-syncer/main.go
  tools/release-jobs-syncer/pkg/helpers.go
  tools/release-jobs-syncer/pkg/jobs_sync.go
  tools/release-jobs-syncer/pkg/pull_request.go
  tools/release-jobs-syncer/pkg/release.go
  tools/release-jobs-syncer/pkg/release_test.go
Labels: approved, lgtm, size/XXL

#3189 Fix one config error for flaky-test-reporter
  tools/flaky-test-reporter/config/config.yaml
Labels: approved, lgtm, size/XS

#3194 Revert custom-job schedules for s390x
  prow/jobs/generated/knative/client-main.gen.yaml
  prow/jobs/generated/knative/client-release-1.0.gen.yaml
  prow/jobs/generated/knative/client-release-1.1.gen.yaml
  prow/jobs/generated/knative/client-release-1.2.gen.yaml
  prow/jobs/generated/knative/client-release-1.3.gen.yaml
  prow/jobs/generated/knative/eventing-main.gen.yaml
  prow/jobs/generated/knative/eventing-release-1.0.gen.yaml
  prow/jobs/generated/knative/eventing-release-1.1.gen.yaml
  prow/jobs/generated/knative/eventing-release-1.2.gen.yaml
  prow/jobs/generated/knative/eventing-release-1.3.gen.yaml
  prow/jobs/generated/knative/operator-main.gen.yaml
  prow/jobs/generated/knative/operator-release-1.0.gen.yaml
  prow/jobs/generated/knative/operator-release-1.1.gen.yaml
  prow/jobs/generated/knative/operator-release-1.2.gen.yaml
  prow/jobs/generated/knative/operator-release-1.3.gen.yaml
  prow/jobs/generated/knative/serving-main.gen.yaml
  prow/jobs/generated/knative/serving-release-1.0.gen.yaml
  prow/jobs/generated/knative/serving-release-1.1.gen.yaml
  prow/jobs/generated/knative/serving-release-1.2.gen.yaml
  prow/jobs/generated/knative/serving-release-1.3.gen.yaml
  prow/jobs_config/knative/client-release-1.0.yaml
  prow/jobs_config/knative/client-release-1.1.yaml
  prow/jobs_config/knative/client-release-1.2.yaml
  prow/jobs_config/knative/client-release-1.3.yaml
  prow/jobs_config/knative/client.yaml
  prow/jobs_config/knative/eventing-release-1.0.yaml
  prow/jobs_config/knative/eventing-release-1.1.yaml
  prow/jobs_config/knative/eventing-release-1.2.yaml
  prow/jobs_config/knative/eventing-release-1.3.yaml
  prow/jobs_config/knative/eventing.yaml
  prow/jobs_config/knative/operator-release-1.0.yaml
  prow/jobs_config/knative/operator-release-1.1.yaml
  prow/jobs_config/knative/operator-release-1.2.yaml
  prow/jobs_config/knative/operator-release-1.3.yaml
  prow/jobs_config/knative/operator.yaml
  prow/jobs_config/knative/serving-release-1.0.yaml
  prow/jobs_config/knative/serving-release-1.1.yaml
  prow/jobs_config/knative/serving-release-1.2.yaml
  prow/jobs_config/knative/serving-release-1.3.yaml
  prow/jobs_config/knative/serving.yaml
Labels: approved, size/M, lgtm, ok-to-test

#3195 Fix commands for s390x custom jobs
  prow/jobs/generated/knative/client-main.gen.yaml
  prow/jobs/generated/knative/client-release-1.0.gen.yaml
  prow/jobs/generated/knative/client-release-1.1.gen.yaml
  prow/jobs/generated/knative/client-release-1.2.gen.yaml
  prow/jobs/generated/knative/client-release-1.3.gen.yaml
  prow/jobs/generated/knative/eventing-release-1.0.gen.yaml
  prow/jobs/generated/knative/eventing-release-1.1.gen.yaml
  prow/jobs/generated/knative/eventing-release-1.2.gen.yaml
  prow/jobs/generated/knative/eventing-release-1.3.gen.yaml
  prow/jobs/generated/knative/operator-release-1.0.gen.yaml
  prow/jobs/generated/knative/operator-release-1.1.gen.yaml
  prow/jobs/generated/knative/operator-release-1.2.gen.yaml
  prow/jobs/generated/knative/operator-release-1.3.gen.yaml
  prow/jobs/generated/knative/serving-release-1.0.gen.yaml
  prow/jobs/generated/knative/serving-release-1.1.gen.yaml
  prow/jobs/generated/knative/serving-release-1.2.gen.yaml
  prow/jobs/generated/knative/serving-release-1.3.gen.yaml
  prow/jobs_config/knative/client-release-1.0.yaml
  prow/jobs_config/knative/client-release-1.1.yaml
  prow/jobs_config/knative/client-release-1.2.yaml
  prow/jobs_config/knative/client-release-1.3.yaml
  prow/jobs_config/knative/client.yaml
  prow/jobs_config/knative/eventing-release-1.0.yaml
  prow/jobs_config/knative/eventing-release-1.1.yaml
  prow/jobs_config/knative/eventing-release-1.2.yaml
  prow/jobs_config/knative/eventing-release-1.3.yaml
  prow/jobs_config/knative/operator-release-1.0.yaml
  prow/jobs_config/knative/operator-release-1.1.yaml
  prow/jobs_config/knative/operator-release-1.2.yaml
  prow/jobs_config/knative/operator-release-1.3.yaml
  prow/jobs_config/knative/serving-release-1.0.yaml
  prow/jobs_config/knative/serving-release-1.1.yaml
  prow/jobs_config/knative/serving-release-1.2.yaml
  prow/jobs_config/knative/serving-release-1.3.yaml
Labels: approved, size/L, lgtm, ok-to-test

#3198 Move the label-sync, branchprotector, peribolos Prow jobs to authenticate as GitHub app
  prow/jobs/custom/branchprotector.yaml
  prow/jobs/custom/label-sync.yaml
  prow/jobs/custom/peribolos.yaml
  prow/jobs/custom/test-infra.yaml
Labels: approved, size/L, lgtm

#3199 Remove knative-gcp config from Knative Prow
  prow/config.yaml
  prow/plugins.yaml
Labels: approved, size/M, lgtm

#3196 Update timeout for eventing continuous and release Prow jobs to 3h
  prow/jobs/generated/knative/eventing-main.gen.yaml
  prow/jobs/generated/knative/eventing-release-1.0.gen.yaml
  prow/jobs/generated/knative/eventing-release-1.1.gen.yaml
  prow/jobs/generated/knative/eventing-release-1.2.gen.yaml
  prow/jobs/generated/knative/eventing-release-1.3.gen.yaml
  prow/jobs_config/knative/eventing-release-1.0.yaml
  prow/jobs_config/knative/eventing-release-1.1.yaml
  prow/jobs_config/knative/eventing-release-1.2.yaml
  prow/jobs_config/knative/eventing-release-1.3.yaml
  prow/jobs_config/knative/eventing.yaml
Labels: approved, size/M, lgtm

#3201 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/CODE-OF-CONDUCT.md
  vendor/knative.dev/hack/CODE_OF_CONDUCT.md
  vendor/modules.txt
Labels: approved, lgtm, size/S

#3202 Move a few Prow jobs to run on the build clusters
  prow/jobs/custom/knativeteam-groups.yaml
  prow/jobs/custom/test-infra.yaml
Labels: approved, lgtm, size/XS

#3200 Fix label-sync and peribolos Prow job config as we migrated Prow to GitHub app
  prow/jobs/custom/branchprotector.yaml
  prow/jobs/custom/label-sync.yaml
  prow/jobs/custom/peribolos.yaml
Labels: approved, lgtm, size/S

#3205 Fix peribolos presubmit Prow jobs
  prow/jobs/custom/peribolos.yaml
Labels: approved, size/M, lgtm

#3206 [main] Update community files
  OWNERS_ALIASES
Labels: approved, lgtm, size/XS

#3210 [main] Update actions
  .github/workflows/knative-go-build.yaml
  .github/workflows/knative-go-test.yaml
  .github/workflows/knative-releasability.yaml
  .github/workflows/knative-release-notes.yaml
  .github/workflows/knative-security.yaml
  .github/workflows/knative-stale.yaml
  .github/workflows/knative-style.yaml
  .github/workflows/knative-verify.yaml
Labels: approved, lgtm, size/XL

#3209 [main] Update community files
  OWNERS_ALIASES
Labels: approved, lgtm, size/XS

#3207 Bump go patches
  images/prow-tests/Dockerfile
Labels: approved, lgtm, size/XS

#3211 Update Knative prow onboarding doc after the recent changes
  guides/branch_checks.png
  guides/prow_knative_setup.md
Labels: approved, lgtm, size/S

#3208 Sync Prow config from oss-test-infra to knative, and enable auto-deploy
  prow/cluster/400-crier.yaml
  prow/cluster/400-deck.yaml
  prow/cluster/400-ghproxy.yaml
  prow/cluster/400-hook.yaml
  prow/cluster/400-horologium.yaml
  prow/cluster/400-ingress.yaml
  prow/cluster/400-prow-controller-manager.yaml
  prow/cluster/400-sinker.yaml
  prow/cluster/400-tide.yaml
  prow/cluster/500-cherrypicker.yaml
  prow/cluster/500-needs-rebase.yaml
  prow/cluster/500-status-reconciler.yaml
  prow/cluster/build/100-namespace.yaml
  prow/cluster/monitoring/secrets/alertmanager-prow_secret.yaml
  prow/jobs/custom/autodeploy-prow.yaml
  prow/plugins.yaml
Labels: approved, size/L, lgtm

#3213 Fix the config path for creating Boskos resources configmap
  prow/Makefile
Labels: approved, lgtm, size/XS
