Repository knative/test-infra, pull requests merged in 2022-05, with the labels that each got.

#3307 Move remaining custom jobs to new cluster
  prow/cluster/build/600-kubernetes_external_secrets.yaml
  prow/jobs/custom/test-infra.yaml
Labels: approved, size/L, lgtm

#3308 Remove the config fields for the previous build cluster
  prow/cluster/boskos/README.md
  prow/cluster/boskos/boskos_resources.yaml
  prow/jobs_config/knative/caching.yaml
  prow/jobs_config/knative/client-pkg.yaml
  prow/jobs_config/knative/client-release-1.1.yaml
  prow/jobs_config/knative/client-release-1.2.yaml
  prow/jobs_config/knative/client.yaml
Labels: approved, size/L, lgtm

#3311 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#3309 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/e2e-tests.sh
  vendor/modules.txt
Labels: approved, lgtm, size/S

#3315 Update max number of nodes for the build cluster to 20
  infra/gcp/tests/gke.tf
Labels: approved, lgtm, size/XS

#3316 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#3319 Allow productivity to rerun jobs
  prow/config.yaml
Labels: approved, lgtm, size/XS

#3317 Add eventing-kafka prow job for s390x
  prow/jobs/generated/knative-sandbox/eventing-kafka-main.gen.yaml
  prow/jobs/generated/knative/client-main.gen.yaml
  prow/jobs/generated/knative/client-release-1.1.gen.yaml
  prow/jobs/generated/knative/client-release-1.2.gen.yaml
  prow/jobs/generated/knative/client-release-1.3.gen.yaml
  prow/jobs/generated/knative/client-release-1.4.gen.yaml
  prow/jobs/generated/knative/operator-main.gen.yaml
  prow/jobs/generated/knative/operator-release-1.1.gen.yaml
  prow/jobs/generated/knative/operator-release-1.2.gen.yaml
  prow/jobs/generated/knative/operator-release-1.3.gen.yaml
  prow/jobs/generated/knative/operator-release-1.4.gen.yaml
  prow/jobs_config/knative-sandbox/eventing-kafka.yaml
  prow/jobs_config/knative/client-release-1.1.yaml
  prow/jobs_config/knative/client-release-1.2.yaml
  prow/jobs_config/knative/client-release-1.3.yaml
  prow/jobs_config/knative/client-release-1.4.yaml
  prow/jobs_config/knative/client.yaml
  prow/jobs_config/knative/operator-release-1.1.yaml
  prow/jobs_config/knative/operator-release-1.2.yaml
  prow/jobs_config/knative/operator-release-1.3.yaml
  prow/jobs_config/knative/operator-release-1.4.yaml
  prow/jobs_config/knative/operator.yaml
Labels: approved, size/L, lgtm, ok-to-test

#3320 Update dot release instructions
  guides/manual_release.md
Labels: approved, lgtm, size/S

#3318 Add migration notice to deck
  prow/config.yaml
Labels: approved, lgtm, size/XS

#3324 install netstat which is used by serving tests
  images/prow-tests/Dockerfile
Labels: approved, lgtm, size/XS

#3327 [main] Update community files
  OWNERS_ALIASES
Labels: size/S, skip-review

#3330 Add zones for `kn.dev` and `kn-e2e.dev` domains
  infra/gcp/dns/dns.tf
  infra/gcp/tests/prow.tf
Labels: approved, size/M, lgtm

#3333 feat: move from Google CLA to CNCF EasyCLA
  prow/config.yaml
Labels: approved, lgtm, size/XS

#3335 chore: use proper casing for EasyCLA
  prow/config.yaml
Labels: approved, lgtm, size/XS

#3336 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/library.sh
  vendor/modules.txt
Labels: approved, lgtm, size/S

#3340 Revert easy cla
  prow/config.yaml
Labels: approved, lgtm, size/XS

#3341 Revert "Revert easy cla (#3340)"
  prow/config.yaml
Labels: approved, lgtm, size/XS

#3343 chore: add knative automation to branches excluded from required checks
  prow/config.yaml
Labels: approved, lgtm, size/XS

#3344 chore: remove easycla (again)
  prow/config.yaml
Labels: approved, lgtm, size/XS

#3342 Bump `ko` and base OS Image
  images/prow-tests/Dockerfile
  infra/gcp/dns/README.md
Labels: approved, lgtm, size/S

#3353 Replace removed peribolos flags
  prow/jobs/custom/peribolos.yaml
Labels: approved, lgtm, size/XS
