Repository knative/test-infra, pull requests merged in 2022-07, with the labels that each got.

#3406 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#3403 Add prow job for client-main e2e test on ppc64le
  prow/jobs/generated/knative/client-main.gen.yaml
  prow/jobs_config/knative/client.yaml
  tools/release-jobs-syncer/pkg/jobs_sync.go
Labels: approved, size/M, lgtm, ok-to-test, area/tools

#3410 Update cron timings for client-main job to avoid conflict with eventi…
  prow/jobs/generated/knative/client-main.gen.yaml
  prow/jobs_config/knative/client.yaml
Labels: approved, lgtm, size/XS, ok-to-test

#3413 Add prow job for operator-main e2e test on ppc64le
  prow/jobs/generated/knative/operator-main.gen.yaml
  prow/jobs_config/knative/operator.yaml
  tools/release-jobs-syncer/pkg/jobs_sync.go
Labels: approved, size/M, lgtm, ok-to-test, area/tools

#3414 Add auto-release config for kn-plugin-operator
  prow/jobs/generated/knative-sandbox/kn-plugin-operator-main.gen.yaml
  prow/jobs_config/knative-sandbox/kn-plugin-operator.yaml
Labels: approved, size/L, lgtm

#3415 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/modules.txt
Labels: approved, lgtm, size/XS

#3420 Added prow job schedule for release-1.6 for s390x platform
  prow/jobs/generated/knative/client-release-1.6.gen.yaml
  prow/jobs/generated/knative/eventing-release-1.6.gen.yaml
  prow/jobs/generated/knative/serving-release-1.6.gen.yaml
  prow/jobs_config/knative/client-release-1.6.yaml
  prow/jobs_config/knative/eventing-release-1.6.yaml
  prow/jobs_config/knative/serving-release-1.6.yaml
Labels: approved, size/M, lgtm, ok-to-test

#3430 Added prow job schedule for release-1.6 on ppc64le
  prow/jobs/generated/knative/client-release-1.6.gen.yaml
  prow/jobs/generated/knative/eventing-release-1.6.gen.yaml
  prow/jobs/generated/knative/operator-release-1.6.gen.yaml
  prow/jobs_config/knative/client-release-1.6.yaml
  prow/jobs_config/knative/eventing-release-1.6.yaml
  prow/jobs_config/knative/operator-release-1.6.yaml
Labels: approved, lgtm, size/S, ok-to-test

#3431 Install a prerelease of `ko`
  images/prow-tests/Dockerfile
Labels: approved, lgtm, size/XS, area/tools

#3438 Fixed eventing-reconciler test job schedule for s390x
  prow/jobs/generated/knative/eventing-release-1.6.gen.yaml
  prow/jobs_config/knative/eventing-release-1.6.yaml
Labels: approved, lgtm, size/XS, ok-to-test

#3439 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/README.md
  vendor/modules.txt
Labels: approved, lgtm, size/S

#3441 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/go.mod
  vendor/knative.dev/hack/infra-library.sh
  vendor/knative.dev/hack/library.sh
  vendor/knative.dev/hack/presubmit-tests.sh
  vendor/knative.dev/hack/release.sh
  vendor/modules.txt
Labels: approved, size/L, lgtm

#3443 Updated s390x prow job schedule
  prow/jobs/generated/knative-sandbox/eventing-kafka-broker-main.gen.yaml
  prow/jobs/generated/knative-sandbox/eventing-kafka-main.gen.yaml
  prow/jobs/generated/knative/client-main.gen.yaml
  prow/jobs/generated/knative/client-release-1.3.gen.yaml
  prow/jobs/generated/knative/client-release-1.4.gen.yaml
  prow/jobs/generated/knative/client-release-1.5.gen.yaml
  prow/jobs/generated/knative/client-release-1.6.gen.yaml
  prow/jobs/generated/knative/eventing-main.gen.yaml
  prow/jobs/generated/knative/eventing-release-1.3.gen.yaml
  prow/jobs/generated/knative/eventing-release-1.4.gen.yaml
  prow/jobs/generated/knative/eventing-release-1.5.gen.yaml
  prow/jobs/generated/knative/eventing-release-1.6.gen.yaml
  prow/jobs/generated/knative/operator-main.gen.yaml
  prow/jobs/generated/knative/operator-release-1.3.gen.yaml
  prow/jobs/generated/knative/operator-release-1.4.gen.yaml
  prow/jobs/generated/knative/operator-release-1.5.gen.yaml
  prow/jobs/generated/knative/operator-release-1.6.gen.yaml
  prow/jobs/generated/knative/serving-main.gen.yaml
  prow/jobs/generated/knative/serving-release-1.3.gen.yaml
  prow/jobs/generated/knative/serving-release-1.4.gen.yaml
  prow/jobs/generated/knative/serving-release-1.5.gen.yaml
  prow/jobs/generated/knative/serving-release-1.6.gen.yaml
  prow/jobs_config/knative-sandbox/eventing-kafka-broker.yaml
  prow/jobs_config/knative-sandbox/eventing-kafka.yaml
  prow/jobs_config/knative/client-release-1.3.yaml
  prow/jobs_config/knative/client-release-1.4.yaml
  prow/jobs_config/knative/client-release-1.5.yaml
  prow/jobs_config/knative/client-release-1.6.yaml
  prow/jobs_config/knative/client.yaml
  prow/jobs_config/knative/eventing-release-1.3.yaml
  prow/jobs_config/knative/eventing-release-1.4.yaml
  prow/jobs_config/knative/eventing-release-1.5.yaml
  prow/jobs_config/knative/eventing-release-1.6.yaml
  prow/jobs_config/knative/eventing.yaml
  prow/jobs_config/knative/operator-release-1.3.yaml
  prow/jobs_config/knative/operator-release-1.4.yaml
  prow/jobs_config/knative/operator-release-1.5.yaml
  prow/jobs_config/knative/operator-release-1.6.yaml
  prow/jobs_config/knative/operator.yaml
  prow/jobs_config/knative/serving-release-1.3.yaml
  prow/jobs_config/knative/serving-release-1.4.yaml
  prow/jobs_config/knative/serving-release-1.5.yaml
  prow/jobs_config/knative/serving-release-1.6.yaml
  prow/jobs_config/knative/serving.yaml
Labels: approved, size/L, lgtm, ok-to-test

#3445 pull in latest knative.dev/hack changes
  go.mod
  go.sum
  vendor/knative.dev/hack/library.sh
  vendor/modules.txt
Labels: approved, lgtm, size/S

#3449 Fixed prow job schedule
  prow/jobs/generated/knative/operator-release-1.6.gen.yaml
  prow/jobs_config/knative/operator-release-1.6.yaml
Labels: approved, lgtm, size/XS, ok-to-test

#3444 Deploy `gcsweb`
  infra/gcp/dns/dns.tf
  infra/gcp/nightly/cosign.tf
  prow/cluster/control-plane/303-prow-knative-dev_managedcertificate.yaml
  prow/cluster/control-plane/400-ingress.yaml
  prow/cluster/control-plane/gcsweb.yaml
Labels: approved, size/L, lgtm, area/gcp

#3451 Fix argocd typos
  prow/cluster/gitops/apps/eso-prow-build.yaml
  prow/cluster/gitops/apps/eso-prow.yaml
  prow/cluster/gitops/apps/eso-trusted.yaml
  prow/cluster/gitops/apps/shared.yaml
Labels: approved, lgtm, size/S

#3450 Add prow job for eventing-reconciler test on ppc64le
  prow/jobs/generated/knative/eventing-main.gen.yaml
  prow/jobs_config/knative/eventing.yaml
  tools/release-jobs-syncer/pkg/jobs_sync.go
Labels: approved, size/M, lgtm, ok-to-test, area/tools

#3448 Workload Identity Enablement - Part Two
  infra/gcp/shared/gke.tf
  infra/gcp/tests/buckets.tf
  infra/gcp/tests/cosign.tf
  infra/gcp/tests/prow.tf
  prow/cluster/build/200-serviceaccounts.yaml
  prow/cluster/control-plane/301-rbac.yaml
  prow/cluster/gitops/apps/prow-trusted.yaml
  prow/cluster/trusted/limitrange.yaml
  prow/cluster/trusted/monitoring.yaml
  prow/cluster/trusted/namespace.yaml
  prow/cluster/trusted/secrets.yaml
  prow/cluster/trusted/serviceaccounts.yaml
  prow/config.yaml
Labels: approved, size/L, lgtm, area/gcp

#3454 Remove dry-run fixing teams
  prow/jobs/custom/peribolos.yaml
Labels: approved, lgtm, size/XS

#3453 Make all contexts required unless set to optional.
  prow/config.yaml
Labels: approved, lgtm, size/S

#3458 Skip unknown contexts for eventing-kafka-broker
  prow/config.yaml
Labels: approved, lgtm, size/XS

#3459 remove markdown linting variable
  prow/jobs/generated/knative-sandbox/eventing-kafka-broker-main.gen.yaml
  prow/jobs/generated/knative-sandbox/eventing-kafka-main.gen.yaml
  prow/jobs/generated/knative/client-main.gen.yaml
  prow/jobs/generated/knative/client-release-1.3.gen.yaml
  prow/jobs/generated/knative/client-release-1.4.gen.yaml
  prow/jobs/generated/knative/client-release-1.5.gen.yaml
  prow/jobs/generated/knative/client-release-1.6.gen.yaml
  prow/jobs/generated/knative/eventing-main.gen.yaml
  prow/jobs/generated/knative/eventing-release-1.3.gen.yaml
  prow/jobs/generated/knative/eventing-release-1.4.gen.yaml
  prow/jobs/generated/knative/eventing-release-1.5.gen.yaml
  prow/jobs/generated/knative/eventing-release-1.6.gen.yaml
  prow/jobs/generated/knative/operator-main.gen.yaml
  prow/jobs/generated/knative/operator-release-1.3.gen.yaml
  prow/jobs/generated/knative/operator-release-1.4.gen.yaml
  prow/jobs/generated/knative/operator-release-1.5.gen.yaml
  prow/jobs/generated/knative/operator-release-1.6.gen.yaml
  prow/jobs/generated/knative/serving-main.gen.yaml
  prow/jobs/generated/knative/serving-release-1.3.gen.yaml
  prow/jobs/generated/knative/serving-release-1.4.gen.yaml
  prow/jobs/generated/knative/serving-release-1.5.gen.yaml
  prow/jobs/generated/knative/serving-release-1.6.gen.yaml
  prow/jobs_config/.base.yaml
Labels: approved, size/M, lgtm
