Repository knative/test-infra, pull requests merged in 2022-12, with the labels that each got.

#3630 update serving channel name
  tools/flaky-test-reporter/config/config.yaml
Labels: approved, lgtm, size/XS, area/tools

#3633 skips unknown contexts for async component
  prow/config.yaml
Labels: approved, lgtm, size/XS

#3634 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/library.sh
  vendor/modules.txt
Labels: size/S, skip-review

#3637 adding scaling-group
  config/prow/k8s-testgrid/k8s-testgrid.yaml
  prow/jobs/generated/knative-sandbox/scaling-group-main.gen.yaml
  prow/jobs_config/knative-sandbox/scaling-group.yaml
Labels: approved, size/L, lgtm

#3639 bump go versions
  images/prow-tests/Dockerfile
Labels: approved, lgtm, size/XS, area/tools

#3641 update PR template
  .github/pull-request-template.md
Labels: approved, lgtm, size/S

#3643 Reduce release branches to 3
  tools/release-jobs-syncer/README.md
  tools/release-jobs-syncer/pkg/release.go
Labels: approved, lgtm, size/XS, area/tools

#3645 [main] Update community files
  OWNERS_ALIASES
Labels: size/S, skip-review

#3647 Check for obsolete releases
  tools/release-jobs-syncer/pkg/release.go
Labels: approved, lgtm, size/S, area/tools

#3653 🔄 Synced file(s) with knative/actions
  .github/workflows/synced-security.yaml
  .github/workflows/synced-stale.yaml
  .github/workflows/synced-style.yaml
  .github/workflows/synced-verify.yaml
Labels: size/M, skip-review
