Repository knative/test-infra, pull requests merged in 2022-10, with the labels that each got.

#3548 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/release.sh
  vendor/modules.txt
Labels: approved, size/M, lgtm

#3550 Fix typo from notarizing `kn-plugin-quickstart`
  prow/jobs/generated/knative-sandbox/kn-plugin-quickstart-main.gen.yaml
  prow/jobs_config/knative-sandbox/kn-plugin-quickstart.yaml
Labels: approved, lgtm, size/S

#3552 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/release.sh
  vendor/modules.txt
Labels: approved, lgtm, size/S

#3554 chore: move kn-plugin-func to knative/func
  config/prow/k8s-testgrid/k8s-testgrid.yaml
  prow/jobs/generated/knative/func-main.gen.yaml
  prow/jobs_config/knative/func.yaml
Labels: approved, size/M, lgtm, kind/cleanup

#3556 [main] Update community files
  OWNERS_ALIASES
Labels: size/S, skip-review

#3559 Notarize all nightlies and release jobs
  prow/jobs/generated/knative-sandbox/kn-plugin-admin-main.gen.yaml
  prow/jobs/generated/knative-sandbox/kn-plugin-event-main.gen.yaml
  prow/jobs/generated/knative-sandbox/kn-plugin-operator-main.gen.yaml
  prow/jobs/generated/knative-sandbox/kn-plugin-quickstart-main.gen.yaml
  prow/jobs/generated/knative-sandbox/kn-plugin-service-log-main.gen.yaml
  prow/jobs/generated/knative-sandbox/kn-plugin-source-kafka-main.gen.yaml
  prow/jobs/generated/knative-sandbox/kn-plugin-source-kamelet-main.gen.yaml
  prow/jobs/generated/knative/client-main.gen.yaml
  prow/jobs/generated/knative/func-main.gen.yaml
  prow/jobs_config/knative-sandbox/.base.yaml
  prow/jobs_config/knative-sandbox/kn-plugin-admin.yaml
  prow/jobs_config/knative-sandbox/kn-plugin-event.yaml
  prow/jobs_config/knative-sandbox/kn-plugin-operator.yaml
  prow/jobs_config/knative-sandbox/kn-plugin-quickstart.yaml
  prow/jobs_config/knative-sandbox/kn-plugin-service-log.yaml
  prow/jobs_config/knative-sandbox/kn-plugin-source-kafka.yaml
  prow/jobs_config/knative-sandbox/kn-plugin-source-kamelet.yaml
  prow/jobs_config/knative/client.yaml
  prow/jobs_config/knative/func.yaml
Labels: approved, lgtm, size/XL

#3562 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/release.sh
  vendor/modules.txt
Labels: size/M, skip-review

#3558 run hey performance test for container-freezer
  prow/jobs/generated/knative-sandbox/container-freezer-main.gen.yaml
  prow/jobs_config/knative-sandbox/container-freezer.yaml
Labels: approved, size/M, lgtm

#3566 Bump `cosign` and other deps in `prow-tests` image
  images/prow-tests/Dockerfile
Labels: approved, lgtm, size/XS, area/tools

#3565 Generate provenance for `net-contour`
  prow/jobs/generated/knative-sandbox/net-contour-main.gen.yaml
  prow/jobs_config/knative-sandbox/net-contour.yaml
Labels: approved, lgtm, size/XS

#3569 Fix TestGrid Permissions
  infra/gcp/tests/iam.tf
  infra/gcp/tests/prow.tf
Labels: approved, lgtm, size/S, area/gcp

#3532 Process stale issues/PRs via Prow
  prow/jobs/custom/stale.yaml
Labels: approved, size/L, lgtm

#3568 Fix a bug in the Provenance Generator
  tools/provenance-generator/pkg/generate.go
  tools/provenance-generator/pkg/generate_test.go
  tools/provenance-generator/pkg/parse.go
  tools/provenance-generator/pkg/testdata/attestation.json
  tools/provenance-generator/pkg/testdata/prowjob.yaml
Labels: approved, size/M, lgtm, area/tools

#3570 Add trigger support in pr
  prow/jobs/generated/knative-sandbox/container-freezer-main.gen.yaml
  prow/jobs_config/knative-sandbox/container-freezer.yaml
Labels: approved, size/M, lgtm

#3571 Add `ghproxy` to trusted cluster
  prow/autobump-config/knative.yaml
  prow/cluster/trusted/ghproxy.yaml
  prow/cluster/trusted/serviceaccounts.yaml
Labels: approved, size/L, lgtm

#3581 [s390x] add release 1.8 jobs
  prow/jobs/generated/knative-sandbox/eventing-kafka-broker-release-1.8.gen.yaml
  prow/jobs/generated/knative-sandbox/eventing-kafka-release-1.8.gen.yaml
  prow/jobs/generated/knative/client-release-1.8.gen.yaml
  prow/jobs/generated/knative/eventing-release-1.8.gen.yaml
  prow/jobs/generated/knative/serving-release-1.8.gen.yaml
  prow/jobs_config/knative-sandbox/eventing-kafka-broker-release-1.8.yaml
  prow/jobs_config/knative-sandbox/eventing-kafka-release-1.8.yaml
  prow/jobs_config/knative/client-release-1.8.yaml
  prow/jobs_config/knative/eventing-release-1.8.yaml
  prow/jobs_config/knative/serving-release-1.8.yaml
Labels: approved, size/L, lgtm

#3583 [s390x] add release 1.8 job for operator
  prow/jobs/generated/knative/operator-release-1.8.gen.yaml
  prow/jobs_config/knative/operator-release-1.8.yaml
Labels: approved, lgtm, size/XS

#3584 add a dns record for perf tests dashboard
  infra/gcp/dns/dns.tf
Labels: approved, lgtm, size/XS, area/gcp

#3586 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review
