Repository knative/test-infra, pull requests merged in 2022-11, with the labels that each got.

#3590 [PPC64LE] Added prow job changes for release 1.8
  prow/jobs/generated/knative/client-release-1.8.gen.yaml
  prow/jobs/generated/knative/eventing-release-1.8.gen.yaml
  prow/jobs/generated/knative/operator-release-1.8.gen.yaml
  prow/jobs_config/knative/client-release-1.8.yaml
  prow/jobs_config/knative/eventing-release-1.8.yaml
  prow/jobs_config/knative/operator-release-1.8.yaml
Labels: approved, size/M, lgtm, ok-to-test

#3591 [main] Update community files
  OWNERS_ALIASES
Labels: approved, lgtm, size/XS, skip-review

#3589 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/presubmit-tests.sh
  vendor/modules.txt
Labels: approved, lgtm, size/S

#3598 bump go to 1.19
  images/prow-tests/Dockerfile
Labels: approved, lgtm, size/XS, area/tools

#3587 Fix release process for eventing-kafka-broker
  prow/jobs/generated/knative-sandbox/eventing-kafka-broker-main.gen.yaml
  prow/jobs/generated/knative-sandbox/eventing-kafka-broker-release-1.8.gen.yaml
  prow/jobs_config/knative-sandbox/eventing-kafka-broker-release-1.8.yaml
  prow/jobs_config/knative-sandbox/eventing-kafka-broker.yaml
Labels: approved, lgtm, size/S

#3602 [main] Format Go code
  pkg/clustermanager/e2e-tests/gke/gke.go
  tools/release-jobs-syncer/pkg/release.go
  tools/rundk/interactive/docker.go
Labels: approved, lgtm, size/S, area/tools

#3605 bump kind, kubetest2 and gotestsum
  images/prow-tests/Dockerfile
Labels: approved, lgtm, size/XS, area/tools

#3600 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#3604 :bug: The `files.ReadLines` func properly reads files
  tools/go-ls-tags/.gotagsignore
  tools/go-ls-tags/cli/app_test.go
  tools/go-ls-tags/files/reader.go
  tools/go-ls-tags/files/reader_test.go
  tools/go-ls-tags/files/testdata/example.txt
  tools/go-ls-tags/main_test.go
  tools/go-ls-tags/tags/index/indexer.go
  tools/go-ls-tags/testdata/tagged.go
Labels: approved, size/M, lgtm, area/tools

#3601 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/README.md
  vendor/knative.dev/hack/e2e-tests.sh
  vendor/modules.txt
Labels: approved, lgtm, size/S

#3609 Use the GKE auth plugin in order to avoid spammy test output
  images/prow-tests/Dockerfile
Labels: approved, lgtm, size/XS, area/tools

#3612 setup net-gateway-api/contour prow jobs
  prow/jobs/generated/knative-sandbox/net-gateway-api-main.gen.yaml
  prow/jobs_config/knative-sandbox/net-gateway-api.yaml
Labels: approved, size/L, lgtm

#3613 Increase eventing nightly/release timeout to 4h
  prow/jobs/generated/knative/eventing-main.gen.yaml
  prow/jobs_config/knative/eventing.yaml
Labels: approved, lgtm, size/S

#3610 Write a Predicate instead of a Statement
  prow/jobs/custom/test-infra.yaml
  tools/provenance-generator/main.go
Labels: approved, lgtm, size/S, area/tools

#3617 remove archived repo links
  README.md
Labels: approved, lgtm, size/S

#3621 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#3622 Remove notarisation flags from func 1.7 jobs
  prow/jobs/generated/knative/func-release-1.7.gen.yaml
  prow/jobs_config/knative/func-release-1.7.yaml
Labels: approved, lgtm, size/S

#3623 :bug: Use the GKE production API instead of beta
  tools/kntest/pkg/kubetest2/gke/options.go
Labels: approved, lgtm, size/XS, area/tools

#3626 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/infra-library.sh
  vendor/modules.txt
Labels: approved, lgtm, size/S

#3629 Enable Blunderbuss for knative
  prow/plugins.yaml
Labels: approved, lgtm, size/S
