Repository knative/test-infra, pull requests merged in 2023-04, with the labels that each got.

#3781 Fix shellcheck warning in run_job.sh
  prow/jobs/run_job.sh
Labels: approved, lgtm, size/XS

#3786 we only care about patch versions
  .github/dependabot.yml
Labels: approved, lgtm, size/XS

#3787 added support for s390x for kn-plugin-event
  prow/jobs/generated/knative-sandbox/kn-plugin-event-main.gen.yaml
  prow/jobs/generated/knative-sandbox/kn-plugin-event-release-1.7.gen.yaml
  prow/jobs/generated/knative-sandbox/kn-plugin-event-release-1.8.gen.yaml
  prow/jobs/generated/knative-sandbox/kn-plugin-event-release-1.9.gen.yaml
  prow/jobs_config/knative-sandbox/kn-plugin-event-release-1.7.yaml
  prow/jobs_config/knative-sandbox/kn-plugin-event-release-1.8.yaml
  prow/jobs_config/knative-sandbox/kn-plugin-event-release-1.9.yaml
  prow/jobs_config/knative-sandbox/kn-plugin-event.yaml
Labels: approved, size/L, lgtm

#3788 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/library.sh
  vendor/knative.dev/hack/presubmit-tests.sh
  vendor/modules.txt
Labels: approved, lgtm, size/S

#3790 [main] Update actions
  .github/workflows/knative-boilerplate.yaml
  .github/workflows/knative-donotsubmit.yaml
  .github/workflows/knative-vulnerability.yaml
Labels: size/L, lgtm, skip-review

#3791 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#3793 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#3795 Remove custom jobs for deprecated KafkaChannel and KafkaSource tests
  prow/jobs/generated/knative-sandbox/eventing-kafka-main.gen.yaml
  prow/jobs_config/knative-sandbox/eventing-kafka.yaml
Labels: approved, size/L, lgtm

#3800 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/release.sh
  vendor/modules.txt
Labels: approved, lgtm, size/S

#3804 Change the billing accounts used by GCP projects
  infra/gcp/.terraform.lock.hcl
  infra/gcp/analytics/main.tf
  infra/gcp/analytics/variables.tf
  infra/gcp/boskos/main.tf
  infra/gcp/boskos/variables.tf
  infra/gcp/dns/main.tf
  infra/gcp/dns/variables.tf
  infra/gcp/gsuite/main.tf
  infra/gcp/gsuite/variables.tf
  infra/gcp/main.tf
  infra/gcp/nightly/main.tf
  infra/gcp/nightly/variables.tf
  infra/gcp/provider.tf
  infra/gcp/releases/main.tf
  infra/gcp/releases/variables.tf
  infra/gcp/shared/gke.tf
  infra/gcp/shared/main.tf
  infra/gcp/shared/variables.tf
  infra/gcp/terraform.tfvars
  infra/gcp/tests/gke.tf
  infra/gcp/tests/main.tf
  infra/gcp/tests/variables.tf
Labels: approved, size/L, lgtm, area/gcp

#3806 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review
