Repository knative/test-infra, pull requests merged in 2023-02, with the labels that each got.

#3697 add release 1.9 jobs for s390x
  prow/jobs/generated/knative-sandbox/eventing-kafka-release-1.9.gen.yaml
  prow/jobs/generated/knative/client-release-1.9.gen.yaml
  prow/jobs/generated/knative/eventing-release-1.9.gen.yaml
  prow/jobs/generated/knative/operator-release-1.9.gen.yaml
  prow/jobs/generated/knative/serving-release-1.9.gen.yaml
  prow/jobs_config/knative-sandbox/eventing-kafka-release-1.9.yaml
  prow/jobs_config/knative/client-release-1.9.yaml
  prow/jobs_config/knative/eventing-release-1.9.yaml
  prow/jobs_config/knative/operator-release-1.9.yaml
  prow/jobs_config/knative/serving-release-1.9.yaml
Labels: approved, size/L, lgtm

#3706 [main] Update community files
  OWNERS_ALIASES
Labels: size/M, skip-review

#3702 Adjust release 1.9 jobs for ppc64le
  prow/jobs/generated/knative/client-release-1.9.gen.yaml
  prow/jobs/generated/knative/eventing-release-1.9.gen.yaml
  prow/jobs/generated/knative/operator-release-1.9.gen.yaml
  prow/jobs/generated/knative/serving-release-1.9.gen.yaml
  prow/jobs_config/knative/client-release-1.9.yaml
  prow/jobs_config/knative/eventing-release-1.9.yaml
  prow/jobs_config/knative/operator-release-1.9.yaml
  prow/jobs_config/knative/serving-release-1.9.yaml
Labels: approved, size/M, lgtm, ok-to-test

#3709 [s390x]: added release1.9 eventing-kafka-broker jobs for s390
  prow/jobs/generated/knative-sandbox/eventing-kafka-broker-release-1.9.gen.yaml
  prow/jobs_config/knative-sandbox/eventing-kafka-broker-release-1.9.yaml
Labels: approved, size/L, lgtm

#3712 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#3713 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/release.sh
  vendor/modules.txt
Labels: approved, size/L, lgtm

#3716 Add eventing istio
  config/prow/k8s-testgrid/k8s-testgrid.yaml
  prow/jobs/generated/knative-sandbox/eventing-istio-main.gen.yaml
  prow/jobs_config/knative-sandbox/eventing-istio.yaml
Labels: approved, size/L, lgtm

#3715 [main] Update community files
  OWNERS_ALIASES
Labels: approved, size/XS, skip-review

#3723 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/release.sh
  vendor/modules.txt
Labels: approved, lgtm, size/S

#3725 Migrate from k8s.gcr.io to registry.k8s.io
  prow/cluster/control-plane/gcsweb.yaml
Labels: approved, lgtm, size/XS, ok-to-test

#3704 Refactor selector with feedback from 3696
  pkg/gomod/check.go
  pkg/gomod/float.go
  pkg/gomod/modules.go
  pkg/gomod/release_meta.go
  pkg/gomod/selector.go
  pkg/gomod/selector_test.go
Labels: approved, size/L, lgtm, area/tools

#3730 Revert "Process stale issues/PRs via Prow (#3532)"
  prow/jobs/custom/stale.yaml
Labels: approved, size/L, lgtm

#3729 Allow release leads to submit prowjobs
  infra/gcp/tests/gke.tf
  infra/gcp/tests/iam.tf
  prow/cluster/control-plane/rbac.yaml
Labels: approved, size/M, lgtm, area/gcp

#3740 bump go versions
  images/prow-tests/Dockerfile
Labels: approved, lgtm, size/XS, area/tools
