Repository knative/test-infra, pull requests merged in 2023-05, with the labels that each got.

#3807 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#3809 Upgrade to ko v0.13.0 in prow Dockerfile
  images/prow-tests/Dockerfile
Labels: approved, lgtm, size/XS, area/tools

#3811 go mod tidy to unblock release-jobs-syncer
  tools/release-jobs-syncer/go.mod
  tools/release-jobs-syncer/go.sum
Labels: approved, lgtm, size/S, area/tools

#3815 Drop the number of supported release branches to 2
  tools/flaky-test-reporter/github_issue.go
  tools/release-jobs-syncer/pkg/release.go
Labels: approved, lgtm, size/XS, area/tools

#3817 Update the slack channels for some eventing jobs
  prow/jobs/generated/knative-sandbox/eventing-kafka-broker-main.gen.yaml
  prow/jobs/generated/knative-sandbox/eventing-kafka-main.gen.yaml
  prow/jobs/generated/knative-sandbox/eventing-kogito-main.gen.yaml
  prow/jobs/generated/knative-sandbox/eventing-natss-main.gen.yaml
  prow/jobs/generated/knative-sandbox/eventing-rabbitmq-main.gen.yaml
  prow/jobs_config/knative-sandbox/eventing-kafka-broker.yaml
  prow/jobs_config/knative-sandbox/eventing-kafka.yaml
  prow/jobs_config/knative-sandbox/eventing-kogito.yaml
  prow/jobs_config/knative-sandbox/eventing-natss.yaml
  prow/jobs_config/knative-sandbox/eventing-rabbitmq.yaml
Labels: approved, size/M, lgtm

#3810 bump go version
  images/prow-tests/Dockerfile
  images/tool/Dockerfile
Labels: approved, lgtm, size/XS, area/tools

#3819 add release 1.10 jobs for s390x
  prow/jobs/generated/knative-sandbox/eventing-kafka-broker-release-1.10.gen.yaml
  prow/jobs/generated/knative-sandbox/eventing-kafka-release-1.10.gen.yaml
  prow/jobs/generated/knative-sandbox/kn-plugin-event-release-1.10.gen.yaml
  prow/jobs/generated/knative/client-release-1.10.gen.yaml
  prow/jobs/generated/knative/eventing-release-1.10.gen.yaml
  prow/jobs/generated/knative/operator-release-1.10.gen.yaml
  prow/jobs/generated/knative/serving-release-1.10.gen.yaml
  prow/jobs_config/knative-sandbox/eventing-kafka-broker-release-1.10.yaml
  prow/jobs_config/knative-sandbox/eventing-kafka-release-1.10.yaml
  prow/jobs_config/knative-sandbox/kn-plugin-event-release-1.10.yaml
  prow/jobs_config/knative/client-release-1.10.yaml
  prow/jobs_config/knative/eventing-release-1.10.yaml
  prow/jobs_config/knative/operator-release-1.10.yaml
  prow/jobs_config/knative/serving-release-1.10.yaml
Labels: approved, lgtm, size/XL, needs-ok-to-test

#3825 Change client-main ppc64le job cron timing
  prow/jobs/generated/knative/client-main.gen.yaml
  prow/jobs_config/knative/client.yaml
Labels: approved, lgtm, size/XS, ok-to-test

#3829 Point to correct slack channels
  tools/flaky-test-reporter/config/config.yaml
Labels: approved, size/M, lgtm, area/tools

#3830 Direct bots to bots channel
  tools/flaky-test-reporter/config/config.yaml
Labels: approved, lgtm, size/S, area/tools

#3832 [s390x]: Adjusted cron schedule for s390x e2e-eventing-reconciler tests
  prow/jobs/generated/knative/eventing-release-1.10.gen.yaml
  prow/jobs_config/knative/eventing-release-1.10.yaml
Labels: approved, lgtm, size/XS

#3833 [peribolos] allow archiving
  prow/jobs/custom/peribolos.yaml
Labels: approved, lgtm, size/XS

#3836 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#3690 Deploy Testgrid API
  infra/gcp/dns/dns.tf
  infra/gcp/tests/prow.tf
  prow/cluster/control-plane/303-prow-knative-dev_managedcertificate.yaml
  prow/cluster/control-plane/ingress.yaml
  prow/cluster/control-plane/testgrid.yaml
Labels: approved, size/M, lgtm, area/gcp
