Repository knative/test-infra, pull requests merged in 2023-01, with the labels that each got.

#3657 Reconcile Infra Changes Q4 2022
  infra/gcp/.terraform.lock.hcl
  infra/gcp/dns/dns.tf
  infra/gcp/iam.tf
  infra/gcp/nightly/main.tf
  infra/gcp/provider.tf
  infra/gcp/releases/main.tf
  infra/gcp/shared/gke.tf
  infra/gcp/shared/iam.tf
  infra/gcp/shared/main.tf
  infra/gcp/shared/vpc.tf
  infra/gcp/tests/gke.tf
  infra/gcp/tests/main.tf
  prow/jobs/custom/test-infra.yaml
  tools/provenance-generator/README.md
Labels: approved, size/L, lgtm, area/tools, area/gcp

#3659 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#3660 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/presubmit-tests.sh
  vendor/knative.dev/hack/release.sh
  vendor/modules.txt
Labels: approved, lgtm, size/S

#3649 add new job to run internal encryption tests for Contour
  prow/jobs/generated/knative/serving-main.gen.yaml
  prow/jobs_config/knative/serving.yaml
Labels: approved, size/M, lgtm

#3663 Revert "🔄 Synced file(s) with knative/actions (#3653)"
  .github/workflows/synced-security.yaml
  .github/workflows/synced-stale.yaml
  .github/workflows/synced-style.yaml
  .github/workflows/synced-verify.yaml
Labels: approved, size/M, lgtm

#3664 Revert "bump peribolos tolerance for deletion so we can purge inactiv…
  prow/jobs/custom/peribolos.yaml
Labels: approved, lgtm, size/XS

#3666 [main] Update community files
  OWNERS_ALIASES
Labels: size/S, skip-review

#3669 bump go versions to latest patch
  images/prow-tests/Dockerfile
Labels: approved, lgtm, size/XS, area/tools

#3672 Fix config-bootstrapper and test-runner RBAC
  prow/cluster/control-plane/301-rbac.yaml
  prow/cluster/control-plane/config-bootstrapper.yaml
  prow/cluster/trusted/secrets.yaml
Labels: approved, size/M, lgtm

#3631 Files needed for deployment of influxdb and grafana used by perf tests
  infra/k8s/shared/grafana-dashboard.json
  infra/k8s/shared/grafana-deployment.yaml
  infra/k8s/shared/influxdb-deployment.yaml
  infra/k8s/shared/influxdb-pvc.yaml
  infra/k8s/shared/influxdb-service.yaml
Labels: approved, lgtm, size/XL

#3673 Create SLSA Provenance for all the images.
  prow/jobs/generated/knative-sandbox/async-component-main.gen.yaml
  prow/jobs/generated/knative-sandbox/container-freezer-main.gen.yaml
  prow/jobs/generated/knative-sandbox/eventing-autoscaler-keda-main.gen.yaml
  prow/jobs/generated/knative-sandbox/eventing-awssqs-main.gen.yaml
  prow/jobs/generated/knative-sandbox/eventing-ceph-main.gen.yaml
  prow/jobs/generated/knative-sandbox/eventing-couchdb-main.gen.yaml
  prow/jobs/generated/knative-sandbox/eventing-github-main.gen.yaml
  prow/jobs/generated/knative-sandbox/eventing-gitlab-main.gen.yaml
  prow/jobs/generated/knative-sandbox/eventing-kafka-broker-main.gen.yaml
  prow/jobs/generated/knative-sandbox/eventing-kafka-main.gen.yaml
  prow/jobs/generated/knative-sandbox/eventing-kogito-main.gen.yaml
  prow/jobs/generated/knative-sandbox/eventing-natss-main.gen.yaml
  prow/jobs/generated/knative-sandbox/eventing-rabbitmq-main.gen.yaml
  prow/jobs/generated/knative-sandbox/eventing-redis-main.gen.yaml
  prow/jobs/generated/knative-sandbox/kn-plugin-admin-main.gen.yaml
  prow/jobs/generated/knative-sandbox/kn-plugin-event-main.gen.yaml
  prow/jobs/generated/knative-sandbox/kn-plugin-operator-main.gen.yaml
  prow/jobs/generated/knative-sandbox/kn-plugin-quickstart-main.gen.yaml
  prow/jobs/generated/knative-sandbox/kn-plugin-service-log-main.gen.yaml
  prow/jobs/generated/knative-sandbox/kn-plugin-source-kafka-main.gen.yaml
  prow/jobs/generated/knative-sandbox/kn-plugin-source-kamelet-main.gen.yaml
  prow/jobs/generated/knative-sandbox/net-certmanager-main.gen.yaml
  prow/jobs/generated/knative-sandbox/net-gateway-api-main.gen.yaml
  prow/jobs/generated/knative-sandbox/net-http01-main.gen.yaml
  prow/jobs/generated/knative-sandbox/net-istio-main.gen.yaml
  prow/jobs/generated/knative-sandbox/net-kourier-main.gen.yaml
  prow/jobs/generated/knative-sandbox/sample-controller-main.gen.yaml
  prow/jobs/generated/knative-sandbox/sample-source-main.gen.yaml
  prow/jobs/generated/knative-sandbox/scaling-group-main.gen.yaml
  prow/jobs/generated/knative-sandbox/security-guard-main.gen.yaml
  prow/jobs/generated/knative/client-main.gen.yaml
  prow/jobs/generated/knative/client-release-1.6.gen.yaml
  prow/jobs/generated/knative/client-release-1.7.gen.yaml
  prow/jobs/generated/knative/client-release-1.8.gen.yaml
  prow/jobs/generated/knative/eventing-main.gen.yaml
  prow/jobs/generated/knative/eventing-release-1.6.gen.yaml
  prow/jobs/generated/knative/eventing-release-1.7.gen.yaml
  prow/jobs/generated/knative/eventing-release-1.8.gen.yaml
  prow/jobs/generated/knative/func-main.gen.yaml
  prow/jobs/generated/knative/func-release-1.7.gen.yaml
  prow/jobs/generated/knative/func-release-1.8.gen.yaml
  prow/jobs/generated/knative/operator-main.gen.yaml
  prow/jobs/generated/knative/operator-release-1.6.gen.yaml
  prow/jobs/generated/knative/operator-release-1.7.gen.yaml
  prow/jobs/generated/knative/operator-release-1.8.gen.yaml
  prow/jobs/generated/knative/serving-release-1.6.gen.yaml
  prow/jobs/generated/knative/serving-release-1.7.gen.yaml
  prow/jobs_config/.base.yaml
Labels: approved, size/L, lgtm

#3679 Make Rekt tests required in eventing
  prow/jobs/generated/knative/eventing-main.gen.yaml
  prow/jobs_config/knative/eventing.yaml
Labels: approved, lgtm, size/XS

#3678 Make eventing-kafka upgrade job optional
  prow/jobs/generated/knative-sandbox/eventing-kafka-main.gen.yaml
  prow/jobs_config/knative-sandbox/eventing-kafka.yaml
Labels: approved, lgtm, size/XS

#3680 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/modules.txt
Labels: approved, lgtm, size/XS

#3684 Redirect `slack.knative.dev` to CNCF Slack
  infra/gcp/dns/redirect/Makefile
Labels: approved, lgtm, size/XS, area/gcp

#3694 Revert "add new job to run internal encryption tests for Contour (#36…
  prow/jobs/generated/knative/serving-main.gen.yaml
  prow/jobs_config/knative/serving.yaml
Labels: approved, size/M, lgtm

#3696 :bug: Buoy will not float current project
  buoy/commands/check.go
  buoy/commands/float.go
  buoy/commands/needs.go
  pkg/gomod/check.go
  pkg/gomod/check_test.go
  pkg/gomod/float.go
  pkg/gomod/float_test.go
  pkg/gomod/modules.go
  pkg/gomod/modules_test.go
  pkg/gomod/release_meta.go
  pkg/gomod/selector.go
  pkg/gomod/selector_test.go
  pkg/gowork/current.go
  pkg/gowork/current_test.go
  pkg/gowork/errors.go
  pkg/gowork/io.go
  pkg/gowork/list.go
  pkg/gowork/list_test.go
  pkg/gowork/module.go
  pkg/gowork/system.go
  pkg/gowork/testdata/data.go
  pkg/gowork/testdata/data_test.go
  pkg/gowork/testdata/env.go
  pkg/gowork/testdata/fs.go
  tools/modscope/cli/current.go
  tools/modscope/cli/list.go
  tools/modscope/cli/list_test.go
  tools/modscope/cli/presenter.go
  tools/modscope/cli/system.go
Labels: approved, size/L, lgtm, area/tools
