Repository knative/test-infra, pull requests merged in 2023-03, with the labels that each got.

#3742 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/release.sh
  vendor/modules.txt
Labels: approved, lgtm, size/S

#3746 Cleanup golang install for prow-tests image
  images/prow-tests/Dockerfile
Labels: approved, size/M, lgtm, area/tools

#3748 Configure Prow URL via flags
  tools/provenance-generator/main.go
  tools/provenance-generator/pkg/parse.go
Labels: approved, lgtm, size/S, area/tools

#3757 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#3758 Remove namespaced broker integration test job for EKB
  prow/jobs/generated/knative-sandbox/eventing-kafka-broker-main.gen.yaml
  prow/jobs_config/knative-sandbox/eventing-kafka-broker.yaml
Labels: approved, size/M, lgtm

#3765 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#3764 [main] Update actions
  .github/workflows/knative-go-build.yaml
  .github/workflows/knative-go-test.yaml
  .github/workflows/knative-release-notes.yaml
  .github/workflows/knative-security.yaml
  .github/workflows/knative-stale.yaml
  .github/workflows/knative-style.yaml
  .github/workflows/knative-verify.yaml
Labels: approved, lgtm, size/S, skip-review

#3768 bump go to 1.20
  images/prow-tests/Dockerfile
  images/tool/Dockerfile
Labels: approved, lgtm, size/S, area/tools

#3777 Update slack channels
  prow/config.yaml
  prow/jobs/custom/autobump-flaky-test-reporter.yaml
  prow/jobs/custom/autobump-prow-tests.yaml
  prow/jobs/custom/autobump-prow.yaml
  prow/jobs/custom/autodeploy-prow.yaml
  prow/jobs/custom/branchprotector.yaml
  prow/jobs/custom/knativeteam-groups.yaml
  prow/jobs/custom/label-sync.yaml
  prow/jobs/custom/peribolos.yaml
  prow/jobs/custom/test-infra.yaml
  prow/jobs/generated/knative-sandbox/net-certmanager-main.gen.yaml
  prow/jobs/generated/knative-sandbox/net-contour-main.gen.yaml
  prow/jobs/generated/knative-sandbox/net-gateway-api-main.gen.yaml
  prow/jobs/generated/knative-sandbox/net-http01-main.gen.yaml
  prow/jobs/generated/knative-sandbox/net-istio-main.gen.yaml
  prow/jobs/generated/knative-sandbox/net-kourier-main.gen.yaml
  prow/jobs/generated/knative/client-main.gen.yaml
  prow/jobs/generated/knative/eventing-main.gen.yaml
  prow/jobs/generated/knative/func-main.gen.yaml
  prow/jobs/generated/knative/operator-main.gen.yaml
  prow/jobs/generated/knative/serving-main.gen.yaml
  prow/jobs_config/knative-sandbox/net-certmanager.yaml
  prow/jobs_config/knative-sandbox/net-contour.yaml
  prow/jobs_config/knative-sandbox/net-gateway-api.yaml
  prow/jobs_config/knative-sandbox/net-http01.yaml
  prow/jobs_config/knative-sandbox/net-istio.yaml
  prow/jobs_config/knative-sandbox/net-kourier.yaml
  prow/jobs_config/knative/client.yaml
  prow/jobs_config/knative/eventing.yaml
  prow/jobs_config/knative/func.yaml
  prow/jobs_config/knative/operator.yaml
  prow/jobs_config/knative/serving.yaml
Labels: approved, size/L, lgtm

#3778 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/library.sh
  vendor/knative.dev/hack/presubmit-tests.sh
  vendor/modules.txt
Labels: approved, lgtm, size/S

#3780 Drop freezer from prow
  config/prow/k8s-testgrid/k8s-testgrid.yaml
  prow/jobs/generated/knative-sandbox/container-freezer-main.gen.yaml
  prow/jobs/generated/knative-sandbox/container-freezer-release-0.1.gen.yaml
  prow/jobs_config/knative-sandbox/container-freezer-release-0.1.yaml
  prow/jobs_config/knative-sandbox/container-freezer.yaml
Labels: approved, lgtm, size/XL
